### ISSUE TITLE
Add CO name to cache off the week/month

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1000]
Is it possible to add the name of the CO to the title of cache of the week/month? This make it more personal for the cacheowner :-)
![selectie_043](https://cloud.githubusercontent.com/assets/1060518/25574095/477a08c4-2e4b-11e7-8e1e-633ca78e9128.jpg)

**Comment by tripper1971** [comment]
I will check it

**Comment by tripper1971** [comment]
Done

**Comment by harrieklomp** [comment]
Thanks :+1:
