### ISSUE TITLE
Replace "Natychmiast" value in mywatches.php settings/properties with something more adequate

### ISSUE THREAD

**Issue by rapotek** [opencaching/opencaching-pl#1002]
Current value in 'interval' select contains setting 'Natychmiast' which incorrectly informs that reports about new logs will be sent immediately after a new log appearance in an observed cache. This value should be replaced with another one more adequate or even more a description explaining the frequency of reports sending and delays risk should be added.

**Comment by harrieklomp** [comment]
@deg-pl Yes, you right. It make no sense. Dutch translation for "Every hour" is "Elk uur".
I will change it in Cron from 4 times a day to every hour too.
