### ISSUE TITLE
Extra text(box) in OpenChecker

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#101]
```
Is it possible to add a own text in the screen when coordinates are correct. 
Example: Make a extra waypoint with final coordinates and select to not show 
this waypoint on cachepage. This waypoint is used for OpenChecker. When correct 
coordinates is filled in on OpenChecker it could read what is written in 
description from this final waypoint and show it on resultpage from OpenChecker.

I hope this is clear. If not, please ask.

Thanks

```

Original issue reported on code.google.com by `henricus...@gmail.com` on 8 Apr 2014 at 11:04

Attachments:
* [Selectie_001.png](https://storage.googleapis.com/google-code-attachments/opencaching-pl/issue-101/comment-0/Selectie_001.png)

**Comment by harrieklomp** [comment]
Is there some one who can implement this?

**Comment by andrixnet** [comment]
https://github.com/opencaching/opencaching-pl/pull/590

**Comment by andrixnet** [comment]
Fixed in https://github.com/opencaching/opencaching-pl/pull/654

**Comment by andrixnet** [comment]
Final waypoint description is shown with proper HTML newlines.
If waypoint description includes HTML code, it is rendered as is.

**Comment by andrixnet** [comment]
Added config option to enable or disable this behaviour.
