### ISSUE TITLE
badges cache founds counting issue?

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1015]
It seems that there is a strange looking difference between founds count at badges and founds statistics accessed from user profile - for example for me:

![image](https://cloud.githubusercontent.com/assets/2961448/26283111/a9b064ee-3e21-11e7-88ba-1d6cc404c382.png)

lubuskie has 41 founds - what is same as result of query:
![image](https://cloud.githubusercontent.com/assets/2961448/26283114/cbc4cfac-3e21-11e7-9b3c-7ad8be95bc87.png)

but on badges page I have 39 founds:
![image](https://cloud.githubusercontent.com/assets/2961448/26283119/e38edf1a-3e21-11e7-98f8-f7bdbda29ebd.png)

**Comment by tripper1971** [comment]
The Badges (Tropiciel group) omits own and mobile caches.

**Comment by kojoty** [comment]
@tripper1971 

jesteś pewien, ze to tak działa?

Zglosił się do mnie kolega aka marchewki i on ma:
badge-warm-maz: 113
staty-warm.-maz: 142
łacznie own+mmobile: 9

https://opencaching.pl/ustatsg2.php?userid=32313
https://opencaching.pl/viewprofile.php?userid=32313


gdzieś musi być jakaś rozbieżność... może staty (userprofile)  mają jakiegoś buga?

**Comment by tripper1971** [comment]
OK, jeśli wchodzimy w szczegóły to:
1. sprawności pomijają owny i mobile
2. kilka keszy mają przypisane złe województwo (ale to raczej odpada w tym przypadku, tu i tu byłaby rozbieżność ze stanem faktycznym)
3. sprawności nie są podbijane jeśli logowanie keszy jest przez aplikacje zewnętrzne (prostują się, jesli zaloguje się w serwisie chociaż jeden kesz z danego woj) 

Jeżeli żaden z powyższych przypadków nie wchodzi w grę, to zrób reopen - przeprowadzę śledztwo
