### ISSUE TITLE
rules confirmation (oc.pl specific)

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1024]
Mamy zaimplementowany mechanizm sprawdzania potwierdzenia akceptacji regulaminu (w common.inc.php). To ma znaczenie jedynie dla kont zarejestrowanych zdaje się przez 2008.11 ponieważ później akceptowało się regulamin w momencie zakładania konta.

Aktualnie strona potwierdzenia jest nieaktualna - zawiera jakąś archaiczna wersję regulaminu.

**Pytanie brzmi: aktualizujemy czy to w ogóle usuwamy, a konta sprzed 2008 niech sobie siedzą jak są...**

**Comment by deg-pl** [comment]
Jestem za usunięciem.
Ewentualnie dla świętego spokoju można zablokować konta, które nie logowały się od 2008 i nie akceptowały regulaminu. Nie sądzę, żeby ktoś się po 9 latach obudził i nagle wrócił na OC. Choć moim zdaniem taka blokada kont to gra nie warta świeczki.

**Comment by kojoty** [comment]
OK, usuwam kod. Konta, które nie potwierdziły regulaminu (cos 3,5k sztuk) zostają jak są.
