### ISSUE TITLE
Add an option to download a custom-tailored GPX file

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#1027]
OKAPI allows OC to create many different versions of a single GPX file. There are [tons of options](https://opencaching.pl/okapi/services/caches/formatters/gpx.html) available. I guess we can allow users to use some of these options directly, without them needed to become a developer and use OKAPI for themselves.

I don't usually do that, but I managed to find some time and prepare a change for OCPL with a "OKAPI GPX Downloader" feature.

Initially, this option will be hidden from the users, until we test it properly among ourselves.

**Comment by wrygiel** [comment]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/2168535/26824720/c2dc828e-4ab2-11e7-9567-4c91aaa6083a.png)

**Comment by wrygiel** [comment]
@opencaching/opencaching-pl-lead-programmers 

Instrukcja jak włączyć:

1. Otwieramy konsolę JavaScript (Ctrl+Shift+J w Chrome).
2. Wpisujemy w niej: `localStorage.betatester = "true";` (i Enter)
3. Odświeżamy stronę (F5).

Powinny pojawić się odnośniki "OKAPI GPX" na stronie wyszukiwania.

![image](https://cloud.githubusercontent.com/assets/2168535/26825533/b558f270-4ab5-11e7-8585-c255c7904714.png)

Na razie nie ma tłumaczeń - wyświetli się tylko po angielsku.
@opencaching/opencaching-pl-lead-programmers 

Instrukcja jak włączyć:

1. Otwieramy konsolę JavaScript (Ctrl+Shift+J w Chrome).
2. Wpisujemy w niej: `localStorage.betatester = "true";` (i Enter)
3. Odświeżamy stronę (F5).

Powinny pojawić się odnośniki "OKAPI GPX" na stronie wyszukiwania.

![image](https://cloud.githubusercontent.com/assets/2168535/26825533/b558f270-4ab5-11e7-8585-c255c7904714.png)

Na razie nie ma tłumaczeń - wyświetli się tylko po angielsku.

**Comment by harrieklomp** [comment]
Looks great :+1: 

BTW: In Firefox you can use Ctrl+Shift+K

**Comment by wrygiel** [comment]
Since there are no comments against it, I think I will reveal it to all users.

**Comment by wrygiel** [comment]
Also created [a thread on OCPL forum](https://forum.opencaching.pl/viewtopic.php?f=9&t=8774).
