### ISSUE TITLE
Disable automatic emoticon translation in TinyMCE

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1036]
Currently the visual editor on cache page (TinyMCE) has the following two functions: 

1. allow emoticon insertion via toolbar
2. automatic translation of :) and other "known" emoticons into their graphic equivalent.

The purpose of this issue is to disable the automatic translation of the text :) into an emoticon image.
If the user wants emoticon image explicitely, use the toolbar.
Otherwise, plain text should not be translated into images this way.
_Note: some puzzles cannot be done because of this text processing._

**Comment by kojoty** [comment]
+1

**Comment by deg-pl** [comment]
@andrixnet could you check it once again? I've upgraded TinyMCE (commit c6feedf862d062af7af2e6977238ec3816558246) and now IMHO TinyMCE doesn't automatically translate smiles into emoticons. See also note on https://www.tinymce.com/docs/plugins/emoticons/

Now I close this issue. Reopen if you think the error still exists.

**Comment by andrixnet** [comment]
I've done a quick test and these are the results: 
**Editor:** 
![emoticons-1](https://user-images.githubusercontent.com/3382777/29765653-babb8ea6-8be4-11e7-83ac-b61376a44652.png)

**Description:**
![emoticons-2](https://user-images.githubusercontent.com/3382777/29765662-c4c0350a-8be4-11e7-9dea-e48cbaf436be.png)

**Comment by andrixnet** [comment]
1. Note the improper line alignment of the editor emoticons inside the editor (this is highly disturbing while editing).

2. note the changed symbols into graphical emoticons.

Sidenote: I have OCRO in sync with github. I have applied all SQL changes up to and including July 19th. (including the one refering to TinyMCE).
I have errors on `2017-07-26_changes_around_powertrails.sql` but that does not refer to this subject.

**Comment by deg-pl** [comment]
Thanks for info. I'll check it and try to fix.
