### ISSUE TITLE
Search page: Cannot select "all regions"

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1038]
From OC UK Team:
There may be a problem with the cache search page, in that once you have selected a region it seems you can't go back and choose "all regions". This even persists if I close the page and reopen it, I can choose other regions but not all.

**Comment by deg-pl** [comment]
@Amberel @digdilem this will be fixed on monday

**Comment by digdilem** [comment]
Ok, thanks deg.
