### ISSUE TITLE
Missing flags on link page

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1041]
Somehow the flags on the link page are gone. This is on nodes PL, UK and NL

![selectie_059](https://user-images.githubusercontent.com/1060518/27251121-41101cac-5340-11e7-849e-dacfd5997018.jpg)

**Comment by kojoty** [comment]
It was my fault - I moved flags from 'images' to 'images/flags' and I missed this usage of these pics.
Now it fixed.

**Comment by harrieklomp** [comment]
:+1:
