### ISSUE TITLE
.htaccess redirection must be moved to Apache configuration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#105]
```
.htaccess file at root of site contains the following: 

RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC]
RewriteRule ^(.*)$ http://%1/$1 [NE,R=301,L]

This is a redirection rule to make http://www.website.XX redirect to this URL: 
http://website.XX

IMO this is a rather dirty way of doing it. It was also the cause of many 
problems with OCRO node that entered a redirection loop which I had a hard time 
figuring out. I commented out these lines, only to get SVN update conflicts 
when .htaccess was recently commited.

Since this affects the behaviour of individual nodes based on their preferred 
URL semantic, I suggest that such redirection be handled gracefully at website 
config level, rather then rewrite rules in htaccess. 

An elegant way to do it is the following: 

<VirtualHost *:80>
    ServerName www.opencaching.ro
[...]
</VirtualHost>

<VirtualHost *:80>
    ServerName opencaching.ro
    ServerAlias oc.opencaching.ro
    Redirect permanent / http://www.opencaching.ro/
</VirtualHost>

```

Original issue reported on code.google.com by `andrixnet` on 10 Apr 2014 at 12:25

**Comment by andrixnet** [comment]
To all node admins: 
Please update Apache configuration such that this redirection can be removed from .htaccess file.

**Comment by harrieklomp** [comment]
OCNL has also moved the config to the server itself.

**Comment by mzylowski** [comment]
#508 reverted. Reopen.

**Comment by wrygiel** [comment]
Summary of what was done (and it broke things):

This was removed from `.htaccess`:

```
RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC]		
RewriteRule ^(.*)$ http://%1/$1 [NE,R=301,L]
```

This was added to Apache:

```
<VirtualHost *:80>
    ServerName www.opencaching.pl
    Redirect / http://opencaching.pl/
</VirtualHost>
```

It seems that the first piece (the one which currently resides in `.htaccess`) doesn't work in `/okapi/` directory. Any idea why?

**Comment by deg-pl** [comment]
We must have "normal" VirtualHost entry with DocumentRoot, Directory, Options etc.
Remove "Redirect / http://opencaching.pl/"
Add:
```
RewriteCond %{REQUEST_URI} !^/okapi/
RewriteRule (.*) http://opencaching.pl$1 [R=302,L]
```

**Comment by andrixnet** [comment]
I think it could also be done using: 
`RedirectMatch permanent /(?!okapi) http://www.opencaching.XX/$1`

Either way, it must go into server config, not .htaccess

**Comment by deg-pl** [comment]
1) This also matches www.opencaching.XX/extra_new_search/okapi
2) This redirects to www.opencaching.XX, not to opencaching.XX

**Comment by andrixnet** [comment]
`RedirectMatch permanent ^/(?!okapi) http://www.opencaching.XX/$1` for those wanting site with www
`RedirectMatch permanent ^/(?!okapi) http://opencaching.XX/$1` for those wanting site without www

**Comment by andrixnet** [comment]
Still, regardless of method used to handle multiple hostnames, this belongs in webserver config, not in .htaccess

**Comment by deg-pl** [comment]
I've checked OC PL, NL and RO after commit and in my opinion - is OK. OAuth in OKAPI works well (PL, NL, RO)
