### ISSUE TITLE
Unwanted "micro" caches back on OCNL

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1053]
After commit https://github.com/opencaching/opencaching-pl/pull/1049 it is possible again to make new caches on OCNL. In settings.inc.php is a rule that should prevent this, but somehow this is not working anymore.

![selectie_066](https://user-images.githubusercontent.com/1060518/27317221-3df7aa48-5585-11e7-88fc-8ba840a2d492.jpg)

![selectie_065](https://user-images.githubusercontent.com/1060518/27317252-5b9f8962-5585-11e7-88f7-c67205607449.jpg)

**Comment by kojoty** [comment]
I think it is fixed now.
