### ISSUE TITLE
Search ->>  

### ISSUE THREAD

**Issue by tripper1971** [opencaching/opencaching-pl#1057]
Please
1. change the column name from technical (cache_code) to more a human readable name
2. add the possibility to hide this column

**Comment by kojoty** [comment]
@tripper1971, could you explain what this issue is about if this is not a mistake that this is assigned to me.  Thanks.

**Comment by deg-pl** [comment]
@kojoty see search results page
![tmp](https://user-images.githubusercontent.com/13884863/27368907-6e3cf0fc-5655-11e7-9355-275639cb491f.png)

**Comment by kojoty** [comment]
@tripper1971, @deg-pl I understand that all bugs are my bugs last days but it seems to be not my change:

https://github.com/opencaching/opencaching-pl/commit/e80844209c38494d410ce901775f8cd52fe4c4a8#diff-9dffbca8d20e0407d3ec9f5584a3e293

:)

**Comment by tripper1971** [comment]
Sorry kojoty :)

**Comment by tripper1971** [comment]
Sorry @kojoty :)

**Comment by wrygiel** [comment]
> add the possibility to hide this column

Jak dodawałem tę "kolumnę" to nie udało mi się jej wyświetlić, więc założyłem, że już jest niewidzialna - jak widać błędnie. :) Jak zrobić, żeby tę kolumnę zobaczyć?

**Comment by wrygiel** [comment]
O, widzę, że u mnie też jest teraz widoczna. :-o

**Comment by wrygiel** [comment]
Ukryłem ją. Ona w ogóle nie miała być pokazywana. Dodałem ją wyłącznie po to, bo potrzebna była do poprawnego działania linka "OKAPI GPX".

**Comment by tripper1971** [comment]
@wrygiel OK, ale może przydałaby się taka kolumna.
@deg, Noc z psychopatą ? :) ciekawy przykład podałeś, ej, nasz kod nie jest taki straszny jak go opisują niektórzy :P

**Comment by deg-pl** [comment]
Szukałem skrzynek najbliżej miejsca mojego zamieszkania ;). Taki mamy klimat.
