### ISSUE TITLE
Crypted log(s)?

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1063]
While do some Dutch translations i notice something about encrypting logs. There are some translations like:
- encrypt_log_info (Line 752)
- encrypt_log_entry (Line 753)

Has this ever being used or will it be used in the code in future?

**Comment by deg-pl** [comment]
I think we don't need encrypted logs. What would be the purpose of the action? In logs anyway there should be no "secret" information - whether or not they are encrypted or not.
(This is of course my point of view)

**Comment by harrieklomp** [comment]
I agree with your opinion. I only did wonder why this is in translation files.
Perhaps it can be removed.

**Comment by andrixnet** [comment]
I find that encrypting (ie ROT13) logs is only a useless hassle.

**Comment by harrieklomp** [comment]
It looks we all agree with this. This issue can be closed.
Thanks.

**Comment by deg-pl** [comment]
... but without removing any OC PL code?

**Comment by harrieklomp** [comment]
There is some very small code i believe. If some one like to remove it :-)

**Comment by deg-pl** [comment]
We have partialy (inconsequent) support for this "feature". For example in user logs:
![tpm](https://user-images.githubusercontent.com/13884863/27841812-a3c9a4d6-6104-11e7-8584-41cd3eef8fdf.png)
(but after you'll click on link, you'll see decrypted log :D )

I'll try to remove all code related to log encryption.

**Comment by andrixnet** [comment]
sql done on OCRO
