### ISSUE TITLE
"Ask for unarchive" button for own, archived caches. 

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1066]
> Witam, po jaką cholerę został zlikwidowany guzik " zgłoś  problem" w skrzynkach swoich.
>  W swojej skrzynce nie mam takiej opcji, która kiedyś była i bardzo ułatwiała sprawę podczas  prośby o odarchiwizowanie skrzynki, która została  reaktywowana. Ja mam takich skrzynek dość dużo i nie zamierzam  z sentymentu  do nich tworzyć nowego kesza w tym samym miejscu. Proszę o przywrócenie  "guzika" na  jego stare miejsce. Pozdrawiam alex22.

**Comment by andrixnet** [comment]
There is also a lengthty discussion on the subject here https://github.com/opencaching/opencaching-pl/issues/574

**Comment by deg-pl** [comment]
PL OC Team requests to restore "report problem".
User can report problem with his cache while (for example) somebody spams logs of this cache. Or of coruse - may ask for unarchive.

**Comment by kojoty** [comment]
"report problem" button reverted.

**Comment by andrixnet** [comment]
Actually showing the "report problem" button is an indirect quick-fix. 

Once ADMIN menu contains a section for unarchival requests (among other things), a proper "unarchive" button is in order :-)
