### ISSUE TITLE
Remove all links to other commercial geocaching sites

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1073]
We allow to add waypoints to other commercial geocaching sites, but... why? We shouldn't promote other sites and encourage users to use them.
- GC doesn't allow any link to OC. They even deny including word "Opencaching" in cache description. Why we promote them???
- Navicache - see #963 
- Terracaching - doesn't work, and... don't allow linking to their caches! We are illegal!
- GPSGames - only 0,1% OC PL caches has their waypoint.

There's no one geocaching service that allow to insert link to competitive service! We are the only one!

Let's make OC as simple as possible!

**Comment by harrieklomp** [comment]
I do agree with this.
Why advertise other sites where we are not welcome.

**Comment by andrixnet** [comment]
This is a slightly bit more comlpex issue. 
It is true that other sites (ie geocaching.com) does not allow any mention of a similar service. 
# 
The following considerations should be taken into account: 
- other sites are "unfriendly" and do not reciprocate linking or mentioning. _This is unlikely to change._
- there is no obligation on part of OC to "promote" other sites
- there is also no legal reason for OC _NOT_ to mention anything about other
- OC is by definition "open". _Now think of it in the terms of Linux: it is open-source, it is an OS alternative, yet [most] distributions contain "samba" package that allow it to properly communicate with file sharing based on Windows_
- I would agree to only show alternate waypoints based on some user performance criteria
- we should also get input from OC UK, where they have most players on OC as experienced geocachers that play/played on other sites before (and possibly still do).
# 
There are the following items under question for removal: 
- mentions of other sites on links page. (I do not agree)
I do not see OC as a commercial service that prohibits such mentions. I rather see it as an open platform similar to wikipedia. See geocaching and opencaching info on Wikipedia: https://en.wikipedia.org/wiki/Geocaching

- search nearby caches on alternate sites - links on bottom of viewcache. (debateble)
As a player with an open mind, who is willing and enjoys playing geocaches and does not mind doing it on several playgrounds (ie sites), I see this as a value added

- alternate waypoints - cache owner - editing. (I do not agree)
As cache owner, with some caches published in several sites, I find it most efficient to manage my caches on OC, and use the waypoint references to the other site(s) and copy/paste the modifications there. 

- alternate waypoints - viewcache. (I disagree with removal) These could/should be hidden based on general site rule, on cacher performance indicator or other criteria, including showing to owner.

- removing alternate waypoints might turn to encourage some users to include such links in their descriptions. Which in turn might lead to more restricted OC terms and conditions, which would lead to more punitive actions from OC Team against cache owners, which would lead to discontent with OC service a.s.o.

**Comment by miklobit** [comment]
Third-party waypoints (without links) can not be considered as advertisements, but as neutral information, useful for people playing in a multisystem. Deleting / hiding existing waypoints and banning users from posting such information in the description is nothing but censorship and does not suit the spirit of opencaching.

**Comment by andrixnet** [comment]
Having such waypoint references in the UI can encourage cache owners who have their cache listed on multiple sites to do their central management of caches on OC, that is be on OC, and then propagate changes as they desire.

**Comment by andrixnet** [comment]
This is beyond personal likes and dislikes of various pro and against GC views. 
There are several geocaching services world wide and some of them do function in more then one country. 
Also, like it or not, geocaching.com is the biggest by any comparison. Yes, they are a commercial venture. 

Does OC desire to become commercial? (by applying commercial like practices) ?

**Comment by andrixnet** [comment]
One more thing, which is (IMO) the best policy development-wise: 

- if OC XX desires not to show waypoint references in the cache listing
- if OC XX desires not to allow editing of waypoint references as separate fields

This is perfectly fine, as long as OC YY is able to show/edit them, if they so desire.

I know, some ifs in the code for it. The essential is that the power of the code is not lessened.

**Comment by Amberel** [comment]
I'm the main admin for OC-UK. I really don't have strong feelings either way, but on balance I think I prefer the links to be removed. The reason is simple - the majority of us see little benefit in cross-listing caches on more than one site. A very small number of my own best caches are cross-listed, but most aren't.
In the UK we don't have anything like enough caches to make it practical for an enthusiastic cacher to use ONLY OC-UK, we all have to use geocaching.com too. I run GSAK and use GPX files to load caches from all the listing sites, and plan my caching using the GSAK database. It serves no purpose for me to see the same cache twice in my database. If it is listed in both places I will log it on both sites, which is unnecessary extra work. So my own practice is to prioritise searching for OC-only caches and not those that are cross-listed.
But for me, the biggest disadvantage of cross-listing is that the cache owner almost always forgets to maintain the listing equally on all sites, so if there is a problem with the cache it may become disabled or even archived on one site while remaining active on the other. This is not an isolated incident, it happens nearly all the time on cross-listed caches in this country.
So having a policy of discouraging cross-listing, while at the same time providing explicit support for it on the cache listing, seems inconsistent. My preference would be to remove the explicit support, but to permit cache owners to mentioning  it in the text of the listing if they wish.
Rgds, Andy

**Comment by digdilem** [comment]
(Secondary admin for OC-UK, and I know Amberel won't mind that I have an alternative view)

My opinion is not to add any restrictions unless absolutely required.  One attracting of OC over GC is that we don't (and should not) add arbitrary and pointless rules. OC, to me, stands for freedom. I'd rather not be told not to do something unless there is a practical and real reason not to. 

I also support cross-listing of caches. 

So what if gc.com don't want to advertise us? They are the dominant caching site so can afford to be more restrictive than us.  We cannot pretend that our users won't know of them.

One additional rule might only prevent one user listing one cache with us. And realistically, we need every one we can.

**Comment by harrieklomp** [comment]
I did mentioned it before that i agree to remove all links to other sites. I do mean it this way, why show a link with nearest caches on other sites? I do not see any reason to show nearest caches on GC.
On the other hand it should be possible to make crosslisted caches with links on a OC cachepage to GC, TC or any cache site. OCNL uses this link to check the easy way if a cache is archived on another site.
In some countries GC does rule. Like in NL GC is the only one and other cachingsites are not worth to mention. OCDE does run good and i believe OCPL is running good also. Like andrixnet mentioned before with the link to the geocaching wikipedia on https://en.wikipedia.org/wiki/Geocaching. Here is all about caching and does show other caching sites. When you select the Dutch version https://nl.wikipedia.org/wiki/Geocaching there is only GC. When another site is added than it will be removed by instantly.
My personal suggestion is to keep the part "Also listed on" and remove all other links.

**Comment by harrieklomp** [comment]
![selectie_089](https://user-images.githubusercontent.com/1060518/28650352-a1279908-727b-11e7-853b-3d992d8f386f.jpg)

This line is on a cache page and does show the nearest caches on different sites.
Perhaps it could be possible to only show all other OC sites?

**Comment by andrixnet** [comment]
IMO it's either leave it or remove it. 
Personally I would definitely keep the reference to a GC code of this cache, but I offering to search nearby caches on GC seems a bit too much. 
It goes two ways. One is much user friendlyness for open-minded geocachers. The other is poor marketing policy for OC by facilitating users leaving OC to search more caches on other sites. 
How many of your cachers are sufficiently open-minded?

On the other hand, if you drop geocaching.com from this line, the others have too little meaning to be worth keeping. Why? 
1. how many caches on terracaching.com are there in Poland, UK or BeNeLux? 
(same question goes for navicache.com and gpsgames.org)
2. OC sites are meant to be national. Ok, there may be 10-20 caches published by travelling cachers, but that's it. (goes for OCPL, OCDE, etc)

Or extend this line and list all caching sites that may be of significance to a cacher.

**Comment by deg-pl** [comment]
We have big discussion here, but my intention was to drop LINK (`<a href=...>`), not waypoint to GC.

Navicache & Terracaching should be removed/disabled because doesn't work or are illegal.

**Comment by andrixnet** [comment]
I agree to drop LINK. 

Personal question: in what way are "illegal" ?

**Comment by deg-pl** [comment]
@andrixnet Some time ago I've read that Terracaching don't allow linking to their service. Now I can't find that regulations. So no I'm not sure about it.
They have very restrictive policy - see point 4.B. http://play.terracaching.com/TermsOfUse/Index . If I understand well - if user first to create cache on TC service, can't copy this cache to OC.

**Comment by andrixnet** [comment]
Indeed, under point 4.B. letter c) they explicitely forbid posting a cache from TC to another site (in laywer talk).
I doubt simply linking to their homepage is forbidden, but such a link belongs under the LINKS page. 
I am uncertain if linking to a search page with certain parameters is allowed, but as we talked before, I also believe this line should go out.

**Comment by andrixnet** [comment]
I agree the best way to deal with this issue is to allow mentioning a waypoint code and keep supporting this, but remove the explicit link, as there are/may be legal or other issues because of it. 

@digdilem :
However, for specific users that do find it useful to actually have it as a link, here is a small user_script (requires GreaseMonkey) for your browser that works client only and will parse the cache page and add the link: 

https://gist.github.com/andrixnet/5dd23af785e5b9f0255f30602047a796
