### ISSUE TITLE
Privacy issue in email_user

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1080]
Before refactoring email system, emails with content was stored in email_user. Mails were sent periodically by cron job. Job sents mail, DELETED content of mail from email_user and set date_sent to current date.

Now we have new (better) mail system, BUT...
emails are stored in email_user with full content. Mail are sent immediately, but content of mail is not deleted from DB and date_sent is not set. I think it is privacy issue - OC Team should not have access to content of mails send between users.

IMHO:
- content of emails should be deleted after mail is successfully sent,
- date_sent should be set to right date or should be removed (as field in table - now is not used)

What do you think about it?

**Comment by kojoty** [comment]
I'll try to fix it soon - I'm going to remove the message text.

**Comment by deg-pl** [comment]
Thanks!
mail_text has no default value, and INSERT without mail_text will generate error in strict mode (which is default in MariaDB 10.x and MySQL 5.7.x)
Please consider sqlAlter - remove mail_text and unused date_send or change default value to NULL (or an empty string)

**Comment by kojoty** [comment]
I think we can close this issue now. User2user messages are no longer stored in DB - but (!) we still save all but message text...
