### ISSUE TITLE
nicki userów nie są unikalne

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#111]
```
Żywcu zgłosił mi telefoniczne takiego buga: system pozwala na istnienie 
kilku takich samych nicków. (np.:
 
http://opencaching.pl/viewprofile.php?userid=1355 
http://opencaching.pl/viewprofile.php?userid=30867


```

Original issue reported on code.google.com by `wloczynutka` on 28 Apr 2014 at 7:16

**Comment by kojoty** [comment]
Query to detect duplicate names:
```
SELECT user_id, username, COUNT( * ) 
FROM user
GROUP BY username
HAVING COUNT( * ) >1
LIMIT 0 , 30
```

Currently it returns result from oc.pl db:
![image](https://cloud.githubusercontent.com/assets/2961448/13784036/fdb8b2ec-eacd-11e5-92de-a47f07ec700f.png)

The question is how to resolve duplicates? Can we just change username for them or what?
@wloczynutka any ideas?

**Comment by wloczynutka** [comment]
"konto_usuniete" we can change name without any other actions.

Could you check last log-in datetime for rest? maybe some of these users
are dead then we change nick of inactive users.

For active doubles we just can contact with them (by email) and polite ask.
If negotiation fail, then we must use force, but I hope we can make
pacefull agreement with everyone.

2016-03-15 16:52 GMT+01:00 kojoty <notifications@github.com>:

> Query to detect duplicate names:
>
> SELECT user_id, username, COUNT( * )
> FROM user
> GROUP BY username
> HAVING COUNT( * ) >1
> LIMIT 0 , 30
>
> Currently it returns result from oc.pl db:
> [image: image]
> <https://cloud.githubusercontent.com/assets/2961448/13784036/fdb8b2ec-eacd-11e5-92de-a47f07ec700f.png>
>
> The question is how to resolve duplicates? Can we just change username for
> them or what?
> @wloczynutka <https://github.com/wloczynutka> any ideas?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/opencaching/opencaching-pl/issues/111#issuecomment-196891774
>



-- 
__________________________________
*Andrzej 'Łza' Woźniak*

*(+48) 798 835 592*
skype praca: *andrzej.wozniak.traveltech*
skype dom: *wloczynutka*

**Comment by kojoty** [comment]
przetestowałem - wydaje się, że nie da się już utworzyć użytkownika o tej samej nazwie;
w bazie istnieje pewna ilość kont o tej samej nazwie:
			
![image](https://cloud.githubusercontent.com/assets/2961448/14968647/260c38c0-10be-11e6-8be4-ae925d7db2c8.png)

ale proponuję zignorować temat do momentu gdy nie wyniknie z tego jakiś istotny problem.
Tym samym zamykam temat.
