### ISSUE TITLE
Remove bulletin function

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1113]
What do you think about to remove "send bulletin" function?

On OC PL last bulletin was send about 1,5 years ago, OC UK about half year ago. In both of cases effect was to listing on spamlists. I think generating 50 000 mails of identical content has no logic sense, but could be very dangerous (spamlist listing).

**Comment by harrieklomp** [comment]
On OCNL we never used this function.
Our opinion: Remove it :-)

**Comment by deg-pl** [comment]
This is not bulletin. This is spamlist subscriber ;)

**Comment by deg-pl** [comment]
We also has field get_bulletin in user table (and settings in user panel), but I decided to keep this. Maybe in future we'll use this data?

@harrieklomp @andrixnet please do simple sqlAlter https://github.com/opencaching/opencaching-pl/blob/master/sqlAlters/2017-08-09_remove_bulletin_table.sql
(yes - I forgot semicolon on the end command)

**Comment by harrieklomp** [comment]
OCNL did run this sql alter (with semicolon)

**Comment by andrixnet** [comment]
done on OCRO
