### ISSUE TITLE
error in badges calculation ?

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1115]
from mail to ocpl team:

>  
> Chciałbym zgłosić (zapewne już o nim wiecie) błąd w przyznawaniu oznak tropicieli. Mianowicie, posiadam na swoim profilu odznakę tropiciel podlaski, mimo iż nigdy nie byłem i nie szukałem keszy w tym rejonie. Najprawdopodobniej błąd jest związany z przeniesieniem jednego z mobilniaków, którego zaliczyłem w Woj. Dolnośląskim. Warto rozważyć inny model naliczania odznak dla mobilniaków lub ich wyłączenie z systemu odznak.
>  
> Dzięki za wysłuchanie,
> viajero71
> https://opencaching.pl/viewprofile.php?userid=83320

**Comment by tripper1971** [comment]
I contacted with viajero71
It wasn't an error in badges calculation it was a problem with the cache assigning to wrong region
