### ISSUE TITLE
GPX files

### ISSUE THREAD

**Issue by Amberel** [opencaching/opencaching-pl#1126]
Apologies if I'm not using this forum correctly.

I have a problem with GPX files - they do not contain much of the HTML that is present on the cache page, not even` <p>` and `</p>`, so paragraphs all run together. This applies to both GPX and GPX GC format.

Rgds, Andy

**Comment by Amberel** [comment]
The start and end paragraph HTML tags (p and /p) that I placed i my post above have been interpreted as HTML instead of being shown literally :-)

**Comment by kojoty** [comment]
(I fixed html tags in the first Andy's post above)

**Comment by following5** [comment]
The `cleanup_text()` [here](https://github.com/opencaching/opencaching-pl/blob/e26ff88f208a7f093e8c6e99c29faef896620f1e/lib/search.gpx.inc.php#L429) here removes lots of HTML tags, which is clearly a bug. Especially if you consider that new HTML tags are added to the same text [here](https://github.com/opencaching/opencaching-pl/blob/e26ff88f208a7f093e8c6e99c29faef896620f1e/lib/search.gpx.inc.php#L71). :-)

OKAPI uses this function istead:

```
function xmlescape($string)
{
    static $pattern = '/[^\x{0009}\x{000a}\x{000d}\x{0020}-\x{D7FF}\x{E000}-\x{FFFD}]+/u';
    $string = preg_replace($pattern, '', $string);
    return strtr($string, array("<" => "&lt;", ">" => "&gt;", "\"" => "&quot;", "'" => "&apos;", "&" => "&amp;"));
}
```

and OCDE uses this similar function:

```
function xmlentities($str)
{
    $str = mb_ereg_replace('[\x{00}-\x{08}\x{0B}\x{0C}\x{0E}-\x{1F}]*', '', $str);
    return htmlspecialchars($str, ENT_QUOTES, 'UTF-8');
}
```

I will try to combine them to something new.

**Comment by following5** [comment]
> I will try to combine them to something new.

No, I will use the Okapi function. It is perfect.

**Comment by following5** [comment]
The same change may also be applied to GPX log texts [here](https://github.com/opencaching/opencaching-pl/blob/e26ff88f208a7f093e8c6e99c29faef896620f1e/lib/search.gpx.inc.php#L602) and [here](https://github.com/opencaching/opencaching-pl/blob/e26ff88f208a7f093e8c6e99c29faef896620f1e/lib/search.gpxgc.inc.php#L475). While GC.com only puts plaintext + some BBcode there, both OCDE and Okapi put HTML into GPX log texts, and noone complained.
