### ISSUE TITLE
Support for all TLD

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1137]
In OC PL in many places we have code like this:

`$nodeDetect = substr($absolute_server_URI, - 3, 2);
`

But it is incompatibile with many TLD, for example - opencaching.game or opencaching.cloud. I think we should support all allowed TLD.

**Comment by andrixnet** [comment]
Agreed

**Comment by kojoty** [comment]
It seems this is not an issue now - am I wrong? If yes - please reopen.
