### ISSUE TITLE
wyswietlenia ustawienia powiadomienia o nowych skrzynkach w promieniu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#114]
```
 Po ustawieniu promienia powiadomień o nowych skrzynkach podczas wyświetlania danych użytkownika promień nie jest pokazywany:

 Powiadamianie: Powiadamianie o nowych skrzynkach w promieniu Promień km

Zamiast wartości mamy "Promień" :)
```

Original issue reported on code.google.com by `wloczynutka` on 15 May 2014 at 9:08

**Comment by kojoty** [comment]
@wloczynutka, problem chyba już nie występuje albo nie rozumiem opisu:
![image](https://cloud.githubusercontent.com/assets/2961448/13783296/1ea6e094-eacb-11e5-9c89-81d3319aa5b8.png)

potwierdzisz, że problem można zamknąć?

**Comment by wloczynutka** [comment]
rzeczywiście, taraz działa. no popatrz - nikt nie naprawiał a się naprawiło.
