### ISSUE TITLE
mywatches.php?rq=map doesn't work

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1140]
from mail to RT:

> chciałbym zgłosić awarię - nie działa mapa obserwowanych skrzynek. Sprawdzone na 3 przeglądarkach u kilku użytkowników.

**Comment by deg-pl** [comment]
Hmm... SOA#1 ;)
![tmp](https://user-images.githubusercontent.com/13884863/29414742-0a5605c2-8361-11e7-9d51-7c5b1a92410c.png)

**Comment by kojoty** [comment]
nie wiem co to SOA (http://acronyms.thefreedictionary.com/SOA ?) ale u mnie się też nie wyświetla więc cos jest chyba na rzeczy... wieczorem zobaczę.

**Comment by deg-pl** [comment]
https://pl.wikipedia.org/wiki/Standardowa_odpowied%C5%BA_administratora

**Comment by kojoty** [comment]
> https://pl.wikipedia.org/wiki/Standardowa_odpowied%C5%BA_administratora

cool, może to liczba obserwowanych, bo ja ma ich na pewno grube kilkaset i lista ładuje się baaardzo wolno a strona z mapką wcale.

**Comment by deg-pl** [comment]
Hmm... Mam ok 120 obserwowanych i ładuje się natychmiast. Ciekawe.
Coś czuję, że to znów problem jakiegoś znaku cudzysłów...

**Comment by kojoty** [comment]
tak to wygląda... chyba starczy że obserwujesz np. OP8FAU

**Comment by deg-pl** [comment]
Faktycznie - mapa mi znika, a tego kesza nie potrafię znaleźć wyszukiwarką. Mam wyniki wyszukiwania: 1, a na liście pusto.

**Comment by belbik** [comment]
Sprawdziłem na 3 komputerach i na loginach 3 różnych osób. Problem występuje tylko na moim koncie. U pozostałych mapa się wyświetla.

![obserw](https://user-images.githubusercontent.com/31103064/29416564-c9b81b1c-8366-11e7-8ee2-5344e31a5010.jpg)

**Comment by kojoty** [comment]
@belbik, spoko - już wiemy w czym problem - a jest najpewniej w niepoprawnym formatowaniu tekstów z logów, co później rozwala nam kod JS, więc to czy sie to reprodukuje czy nie zależy od tego czy się obserwuje kesza z odpowiednią treścią w logu.

poprawka wkrótce...

**Comment by kojoty** [comment]
kurczę naprawiłem zepsuty log z kesza OP8FAU - był tam jakiś bialy znak ktory psuł nam JS, ale niechcący go usunąłem i teraz nie wiem co to było :( - mnie się już teraz wszystko wyświetla :(

**Comment by deg-pl** [comment]
Bierz z wczorajszej kopii bazy.
Mam wrażenie, że musimy dokładniej weryfikować nazwy zakładanych/edytowanych keszy, bo to kolejny przypadek z podobnym problemem. Oczywiście kwestia właściwego escape'owania znaków to osobna sprawa wymagająca również naprawy.

**Comment by kojoty** [comment]
I this is fixed after completely mywatches refactoring last days.
