### ISSUE TITLE
Show number of displayed caches on cachemap v3

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1142]
From forum (https://forum.opencaching.pl/viewtopic.php?p=137905#p137905)

> Na mapie v3 brakuje mi (było kiedyś w v2, teraz jakby nie działa) zliczenia ile keszy jest wyświetlane. Na mapie opencaching.de jest

**Comment by kojoty** [comment]
Moim zdaniem to będzie trudne do implementacji. My dostajemy kafelki z ikonami keszy z okapi.

@wrygiel co o tym myślisz?

**Comment by deg-pl** [comment]
OC DE ma licznik, nie zaglądałem do ich kodu, ale może też pobierają po OKAPI. Trzeba rozeznać temat i sprawdzić co da się zrobić. To dodatkowy "bajer", więc dla niego pół systemu nie będziemy przerabiać, ale jakby dało się to łatwo z OKAPI wyciągnąć, to czemu nie.

**Comment by wrygiel** [comment]
Niestety aktualnie nie da się łatwo z OKAPI wyciągnąć.

**Comment by brasiaPL** [comment]
A wydawało mi się to takie proste:
```-licznik=0
- rysuj mapę
-- rysuj ikonkę
-- licznik=licznik+1
- wyświetl licznik
```
Niestety widać, że świat nie jest taki prosty :(

**Comment by deg-pl** [comment]
@wrygiel W wątku dotyczącym #583 napisałeś coś takiego (w innym oczywiście kontekście):

> Da się, względnie łatwo. Wystarczy wywołać metodę bbox wraz z formatterem gpx poprzez search_and_retrieve. 

Nie dałoby się tego tu jakoś w miarę prosto wykorzystać?

**Comment by kojoty** [comment]
Mapa V3 dziala inaczej:
- ładuj kafelki mapy
- ładuj przezroczyste kafelki - "nakładki" 

Tam nie ma rysowania pojedynczych ikonek keszy. Kafelki są keszowane i są zwracane jako obrazki i ogarnięcie tego wymagało by trochę "sięgania prawą ręką do lewej kieszeni" co ani wygodne ani celowe. Wydaje mi się że podanie  liczby keszy nie jest tego warte. Niemieckie oc chyba tak nie działa - oni właśnie rysują ikonki na kafelkach mapy - jedna po drugiej...

**Comment by andrixnet** [comment]
+1

**Comment by wrygiel** [comment]
> @wrygiel W wątku dotyczącym #583 napisałeś coś takiego (w innym oczywiście kontekście):
> 
> > Da się, względnie łatwo. Wystarczy wywołać metodę bbox wraz z formatterem gpx poprzez search_and_retrieve. 
> 
> Nie dałoby się tego tu jakoś w miarę prosto wykorzystać?

Dopiero zauważyłem komentarz, sorki :(

Niestety nie bardzo. Ta metoda działałaby dla małej liczby skrzynek, ale dla dużej już nie. Tam limit 500 skrzynek i on tam jest właśnie dlatego, żeby nie "zarzynać" bazy tego rodzaju zapytaniami.

A tutaj mówimy o zupełnie innym zastosowaniu - liczeniu skrzynek w danym obszarze. Żeby zrobić to efektywnie, należałoby napisać odrębne metody. Oczywiście da się zrobić to tak, żeby działało szybko (z wykorzystaniem odpowiednich dodatkowych struktur danych), ale jest to dość złożony temat.

**Comment by brasiaPL** [comment]
Jeśli przy liczeniu jest limit to proponuję po prostu licznik uruchomić do
limitu, jeśli limit zostanie osiągnięty to opisać ">500". Nawet gdyby limit
był mniejszy np. 200 to i tak byłby to fajny bajer :).

Pozdrawiam Paweł / brasia

W dniu 3 października 2017 15:10 użytkownik Wojciech Rygielski <
notifications@github.com> napisał:

**Comment by kojoty** [comment]
I think we can close it - in my opinion requested improvement is less valuable (this is only a small information addition) than the work needed to deliver such change. 

If we change the way of map generation it could be implemented but in current model it needs much more complication than it is worth (in my opinion).

If anyone doesn't agree please reopen.
