### ISSUE TITLE
OKAPI fulldump is empty

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#1147]
https://opencaching.pl/okapi/services/replicate/fulldump?consumer_key=...  delivers an empty file. On other Opencaching sites it works fine, so I guess it is a local configuration problem.

**Comment by following5** [comment]
Problem still exists.
@wrygiel

**Comment by following5** [comment]
As noone cares about this issue, I will try to debug this remotely through Okapi devel functions.

**Comment by following5** [comment]
The problem was that there is no bzip2 installed on the opencachin.pl server. I have implemented an automatic fallback to gzip.

You may still want to install bzip2 - it will save some disk space, I guess 50-100 MB.

**Comment by deg-pl** [comment]
I just installed bzip2.

**Comment by following5** [comment]
Okay. I have just remade the fulldump with bzip2 - saved 127 MB of hard disk space.
