### ISSUE TITLE
viewcache description: default css vs tinyMCE

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1150]
From OCPL forum:

> A co się dzieje w z tłem w moich keszach ? np. OP8EL2, OP8CBT? Przedtem było całe jednolite, teraz są okropne paski, które pojawiają się jak się kliknie spację. Można się tego jakoś definitywnie pozbyć?

it seems that we have default css for cache description (in viewcache.css):
```
div#viewcache-description               { font-family: arial, sans serif; line-height: 1.3em; font-size: 12px; margin-top: 5px;}
div#viewcache-description *             {max-width: 770px;line-height: 1.3em;font-size: 12px; margin: 0px 0px 0.5em 0em; }
```

Why we have a margin here?

**Comment by deg-pl** [comment]
Sp*łem tego CSSa. poprzednia wersja lepiej działała. Problem jest też z font-size dorzuconym do *, bo przy konstrukcjach typu <span style="font-size: 30px"><strong>Coś</strong></span> się psuje wielkość fontu. Odwrotnie użyte znaczniki oczywiście działają.

**Comment by harrieklomp** [comment]
I know there are more important issues with the code but we are getting more complains about the editor. So i have changed the priority a step higher.

**Comment by deg-pl** [comment]
Fixed by commit 034b24c29d4305c4218f0f6729c20f259e137397
