### ISSUE TITLE
ReportID in the email title (nr zgłoszenia w mailu)

### ISSUE THREAD

**Issue by brasiaPL** [opencaching/opencaching-pl#1152]
#From forum https://forum.opencaching.pl/viewtopic.php?f=71&p=137870#p137846 
> Każde ze zgłoszeń do COG ma nadawany indywidualny numer ID. Po tym numerze łatwo można wyszukać każde zgłoszenie, nawet zamknięte.
> Np zgłoszenie 1234: https://opencaching.pl/viewreport.php?reportid=1234
> Proponuję aby w tytule maila zwrotnego, którego dostaje się po zgłoszeniu uwzględnić numer zgłoszenia. Czyli przykładowy tytuł brzmiałby:
> [OC PL] Zgłosiłeś problem nr 12345, dotyczący skrzynki OP6789
> (dodałem przykładowy nr 12345).
> 
> Obecnie wszystkie zgłoszenia są nierozróżnialne i przeniesione do archiwum trudno znajdywalne. Myślę, że poprawiłoby to komunikację ze zgłaszającymi problem np. przy powtórnym zgłoszeniu lub też jeśli ktoś pyta o zgłoszenie bo nie dostał maila od prowadzącego.
> Poza tym taki nadany numer wygląda bardziej profesjonalnie :P - każde pismo urzędowe ma numer, na który można się powołać.

**Comment by kojoty** [comment]
@brasiaPL - dzieki za wpisanie tutaj :)

**Comment by deg-pl** [comment]
Zrobione wraz z całkowitym refactoringiem zgłoszeń. WSZYSTKIE maile wysyłane, które są związane ze zgłoszeniami mają temat:
[prefix] [R#NrZgłoszenia] Temat
R - report (eng), dla rozróżnienia innych typów alertów w przyszłości
Wyjątkiem jest oczywiście zgłoszenie skrzynki do innego użytkownika, ponieważ w takim wypadku nie jest generowany numer zgłoszenia.
W każdym mailu do COG niezależnie od tematu - w treści jest bezpośredni link do danego zgłoszenia.
A informacje o nowych zgłoszeniach zgodnie z konsultacją @brasiaPL w temacie zaraz obok prefixu mają region.
