### ISSUE TITLE
OCRO broken by last update

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1159]
error.log: 
```
[Tue Aug 29 08:27:33.941284 2017] [:error] [pid 10284:tid 139930849879808] [client A.B.C.D:47162] PHPNotice:  Undefined variable: enable_cache_access_logs in oc_www/lib/Objects/OcConfig/OcConfig.php on line 112
[Tue Aug 29 08:27:33.952095 2017] [:error] [pid 10284:tid 139930849879808] [client A.B.C.D:47162] PHPWarning:  OcPdo Error: Query: SELECT * FROM news\n            WHERE (date_expiration > NOW()\n  OR date_expiration IS NULL)\n                AND (date_publication < NOW()\n                OR date_publication IS NULL) AND show_onmainpage = 1 AND (date_mainpageexp > NOW() OR date_mainpageexp IS NULL) ORDER BY date_publication DESC LIMIT 3 OFFSET 0. Trace:  | oc_www/Utils/Database/OcDb.php::155 | oc_www/lib/Objects/News/News.php::241 | oc_www/Controllers/News/NewsListController.php::75 | oc_www/index.php::20 in oc_www/Utils/Database/OcPdo.php online 113
[Tue Aug 29 08:27:33.952139 2017] [:error] [pid 10284:tid 139930849879808] [client A.B.C.D:47162] Db message:SQLSTATE[42S22]: Column not found: 1054 Unknown column 'date_expiration' in 'where clause'
[Tue Aug 29 08:27:33.952205 2017] [:error] [pid 10284:tid 139930849879808] [client A.B.C.D:47162] PHPCatchable fatal error:  Argument 1 passed to Utils\\Database\\OcDb::dbFetchAllAsObjects() must be an instance of PDOStatement, null given, called in oc_www/lib/Objects/News/News.php on line 245 and defined in oc_www/Utils/Database/OcDb.php on line 91```

Update log: 
```
Aug 28 16:47:05 oc logger: --- Updating www.opencaching.ro...
Aug 28 16:47:07 oc logger: From https://github.com/opencaching/opencaching-pl
Aug 28 16:47:07 oc logger:  * branch                master     -> FETCH_HEAD
Aug 28 16:47:07 oc logger: Updating 5b6300f2a..90ab23fcd
Aug 28 16:47:07 oc logger: Fast-forward
Aug 28 16:47:07 oc logger:  Controllers/Cron/NotifyController.php          | 144 +++++++++++++++++++++
Aug 28 16:47:07 oc logger:  Controllers/News/NewsAdminController.php       |  11 --
Aug 28 16:47:07 oc logger:  Utils/Email/EmailSender.php                    |  56 +++++++++
Aug 28 16:47:07 oc logger:  Utils/Gis/Gis.php                              |   4 +
Aug 28 16:47:07 oc logger:  lib/Objects/News/News.php                      |  60 ---------
Aug 28 16:47:07 oc logger:  lib/Objects/Notify/Notify.php                  | 168 +++++++++++++++++++++++++
Aug 28 16:47:07 oc logger:  lib/Objects/User/User.php                      |  29 ++++-
Aug 28 16:47:07 oc logger:  lib/languages/cs.php                           |  20 ++-
Aug 28 16:47:07 oc logger:  lib/languages/de.php                           |  20 ++-
Aug 28 16:47:07 oc logger:  lib/languages/en.php                           |  20 ++-
Aug 28 16:47:07 oc logger:  lib/languages/nl.php                           |  20 ++-
Aug 28 16:47:07 oc logger:  lib/languages/pl.php                           |  20 ++-
Aug 28 16:47:07 oc logger:  lib/languages/ro.php                           |  20 ++-
Aug 28 16:47:07 oc logger:  tpl/stdstyle/email/newcache_notify.email.html  |  22 ++++
Aug 28 16:47:07 oc logger:  tpl/stdstyle/email/newcache_notify_item.html   |   9 ++
Aug 28 16:47:07 oc logger:  util.sec/notification/notifyNewcacheEmail.html |  68 ----------
Aug 28 16:47:07 oc logger:  util.sec/notification/run_notify.php           | 141 +--------------------
Aug 28 16:47:07 oc logger:  17 files changed, 479 insertions(+), 353 deletions(-)
Aug 28 16:47:07 oc logger:  create mode 100644 Controllers/Cron/NotifyController.php
Aug 28 16:47:07 oc logger:  create mode 100644 lib/Objects/Notify/Notify.php
Aug 28 16:47:07 oc logger:  create mode 100644 tpl/stdstyle/email/newcache_notify.email.html
Aug 28 16:47:07 oc logger:  create mode 100644 tpl/stdstyle/email/newcache_notify_item.html
Aug 28 16:47:07 oc logger:  delete mode 100644 util.sec/notification/notifyNewcacheEmail.html
Aug 28 16:47:08 oc logger: Current branch master is up to date.
Aug 28 16:47:08 oc logger:
Aug 28 16:47:08 oc logger: - GIT modified files:
Aug 28 16:47:08 oc logger:  Controllers/Cron/NotifyController.php          | 144 ---------------------
Aug 28 16:47:08 oc logger:  Controllers/News/NewsAdminController.php       |  11 ++
Aug 28 16:47:08 oc logger:  Utils/Email/EmailSender.php                    |  56 ---------
Aug 28 16:47:08 oc logger:  Utils/Gis/Gis.php                              |   4 -
Aug 28 16:47:08 oc logger:  lib/Objects/News/News.php                      |  60 +++++++++
Aug 28 16:47:08 oc logger:  lib/Objects/Notify/Notify.php                  | 168 -------------------------
Aug 28 16:47:08 oc logger:  lib/Objects/User/User.php                      |  29 +----
Aug 28 16:47:08 oc logger:  lib/languages/cs.php                           |  20 +--
Aug 28 16:47:08 oc logger:  lib/languages/de.php                           |  20 +--
Aug 28 16:47:08 oc logger:  lib/languages/en.php                           |  20 +--
Aug 28 16:47:08 oc logger:  lib/languages/nl.php                           |  20 +--
Aug 28 16:47:08 oc logger:  lib/languages/pl.php                           |  20 +--
Aug 28 16:47:08 oc logger:  lib/languages/ro.php                           |  20 +--
Aug 28 16:47:08 oc logger:  tpl/stdstyle/email/newcache_notify.email.html  |  22 ----
Aug 28 16:47:08 oc logger:  tpl/stdstyle/email/newcache_notify_item.html   |   9 --
Aug 28 16:47:08 oc logger:  util.sec/notification/notifyNewcacheEmail.html |  68 ++++++++++
Aug 28 16:47:08 oc logger:  util.sec/notification/run_notify.php           | 141 ++++++++++++++++++++-
Aug 28 16:47:08 oc logger:  17 files changed, 353 insertions(+), 479 deletions(-)
Aug 28 16:47:08 oc logger: - GIT update completed.
Aug 28 16:47:08 oc logger:
Aug 28 16:47:08 oc logger: Running OKAPI update scripts...
Aug 28 16:47:08 oc logger: Current OKAPI database version: 117
Aug 28 16:47:08 oc logger: It is up-to-date.
Aug 28 16:47:08 oc logger:
Aug 28 16:47:08 oc logger: Registering new cronjobs...
Aug 28 16:47:08 oc logger:
Aug 28 16:47:08 oc logger: Update complete.
Aug 28 16:47:08 oc logger: --- Done.
Aug 28 16:47:08 oc logger:
```

I've checked sqlAlters, not sure if I ran all as I was trying to catch up.
Ran them again and came up with this error at `2017-08-07_news_refactoring.sql`  
```
ERROR 1067 (42000) at line 7: Invalid default value for 'date_publication'
```

I vaguegly remember I saw this kind of error earlier this year, but I don't remember what was the solution.

**Comment by kojoty** [comment]
@andrixnet, if you would like to be sure that your DB is up-to-date with all changes check this:

http://www.opencaching.ro/okapi/devel/dbstruct?compare_to=https://opencaching.pl/okapi/devel/dbstruct

It seems there are a lot of differences - please take a look at this I hope it helps...

**Comment by harrieklomp** [comment]
Most pages do work on OCRO. Start with http://www.opencaching.ro/newcaches.php from there you can rule out what pages do not work.
It looks that http://www.opencaching.ro/index.php and http://www.opencaching.ro/news.php are not working.
Latest changes are made in news.php. Perhaps here is the problem.

**Comment by deg-pl** [comment]
Yes - kojoty has right - you have not current database schema.

First notice - We use enable_cache_access_logs for many years, but we hadn't this variable in default config! OC RO must work incorrect for many years! Quick fixed by commit da42e220b45507443d9095c08a9fe08778e5b6a0

Second and third error is result that your sqlalter was done with errors, and you wrote only "Done on OC RO". W've removed compatilibity mode in news, but your database still use old schema. Now I reverted this commit, but OC RO still don't work.
1) Please - send current errors from error.log
2) Try done 2017-08-07_news_refactoring.sql with small change - change
`ALTER TABLE `news` (...) CHANGE `date_posted` `date_publication` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP (...)`
to
`ALTER TABLE `news` (...) CHANGE `date_posted` `date_publication` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP (...)`
(change DATETIME to TIMESTAMP). Do this sqlalter instruction by instruction - first only modified ALTER TABLE, if there will be no errors - "UPDATE" lines and so on.
I don't know why revert of commit don't fix THIS problem. For quick fix you can comment "news" section in index.php - from `// news` to `tpl_set_var('display_news', $newscontent);`

BUT most important - you shoud analyse link provided by kojoty and update your database. But think about each line - don't do lines like `ALTER TABLE `log_types` DROP `ro`;`! :)

After while - I noticed that most of differences in DB has "DEFAULT NULL" or "NOT NULL" statements - I have a feeling that you have buggy MariaDB version and your site produces a lot of errors.

**Comment by andrixnet** [comment]
After talking last evening with @deg-pl we sorted out several details. 
MariaDB 5.5.56 does not support `DATETIME` data type with default value `CURRENT_TIMESTAMP`, something which also happened here https://github.com/opencaching/opencaching-pl/issues/967
There and then, we set the column type to `TIMESTAMP` which supports default value `CURRENT_TIMESTAMP`. 

The second problem arises from the fact only a single `TIMESTAMP` column with default `CURRENT_TIMESTAMP` is allowed to exist. (MariaDB 5.5.x limitation).

**Comment by andrixnet** [comment]
My current solution was to manually run the changes from `2017-08-07_news_refactoring.sql` with several tweaks. 
My current database reads: 
```
CREATE TABLE `news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` tinytext COMMENT 'Title of the news',
  `content` text,
  `user_id` int(11) NOT NULL DEFAULT '0' COMMENT 'Author userID',
  `edited_by` int(11) NOT NULL DEFAULT '0' COMMENT 'UserID who last edited this news',
  `hide_author` int(1) NOT NULL DEFAULT '1' COMMENT 'Dislpay OC Team instead of author',
  `show_onmainpage` int(1) NOT NULL DEFAULT '1' COMMENT 'Show news on mainpage',
  `show_notlogged` int(1) NOT NULL DEFAULT '0' COMMENT 'Show news to not logged users',
  `date_publication` datetime NOT NULL COMMENT 'Date from which to publish the news',
  `date_expiration` datetime DEFAULT NULL,
  `date_mainpageexp` datetime DEFAULT NULL COMMENT 'End of publication on the main page',
  `date_lastmod` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last modification date',
  PRIMARY KEY (`id`),
  KEY `show_onmainpage` (`show_onmainpage`),
  KEY `show_notlogged` (`show_notlogged`),
  KEY `date_publication` (`date_publication`),
  KEY `date_expiration` (`date_expiration`),
  KEY `date_mainpageexp` (`date_mainpageexp`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

The difference is that `date_publication` doesn't have the default CURRENT_TIMESTAMP.
Using the tool @kojoty pointed out, this is the difference: 
```
ALTER TABLE `news` MODIFY `date_publication` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date from which to publish the news';
```

**Comment by andrixnet** [comment]
Regarding the news subsystem, posting new news may be partially broken due to the lack of default column value for `date_publication`, but at least the home page and related pages now work and do not yield any more database errors.

**Comment by andrixnet** [comment]
Regarding cache access logs, I found an SQL alter from 2014 which it seems that I missed. I applied it and now the dbstruct comparison doesn't show differences in that regard.

**Comment by andrixnet** [comment]
As I told @deg-pl it is feasible to upgrade to MariaDB 10.0.x in the near future (but not before the end of september due to other constraints), but that version is the distro long-term support, production grade version.

**Comment by deg-pl** [comment]
@andrixnet I close this issue now.
Now on all nodes works on News module without compatibility mode. OC RO works also OK. Problem is diagnosed and partrially solved. You have old MariaDB version with some problems, but we have another issue #1164

**Comment by andrixnet** [comment]
There is still this database difference:
```
ALTER TABLE `news` MODIFY `date_publication` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date from which to publish the news';
```

I've set `date_lastmod timestamp default current_timestamp`, in line with other tables, but `date_publication` is not. Does the code handle this (for now), or do I need to set some trigger?
