### ISSUE TITLE
No selected size bold letters in tinyMCE

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1165]
First: I do not know if this is a bug in tinyMCE or something in OC code.
When making a cache description with some text in "bold' the bold text does not show up in correct size on cache page. This is with different letter types and different letter sizes.
Let me show this with some screenshots from start to cache page.

In editor.
![selectie_112](https://user-images.githubusercontent.com/1060518/29875421-491a3aec-8d9a-11e7-8a89-8d9215cfa818.jpg)

Source code.
![selectie_113](https://user-images.githubusercontent.com/1060518/29875474-720aa45a-8d9a-11e7-9d0b-1985598b18f2.jpg)

Result on cache page.
![selectie_111](https://user-images.githubusercontent.com/1060518/29875497-8376ca2a-8d9a-11e7-9440-0c27555ceb4e.jpg)

**Comment by deg-pl** [comment]
This is exactly the same problem with CSSs that #1150

**Comment by deg-pl** [comment]
Fixed by commit 034b24c29d4305c4218f0f6729c20f259e137397
