### ISSUE TITLE
Missing slash in user profile

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1166]
From FB conversation with @f-ranek 

> Gdzieś slasha brakuje 😉
> Klik https://opencaching.pl/mailto.php?userid=19281
> https://opencaching.pllogin.php/?target=mailto.php%3Fuserid%3D19281 
> Server not found
> Brakuje /  - powinno być https://opencaching.pl/login.php/?target=mailto.php%3Fuserid%3D19281 i działa

**Comment by kojoty** [comment]
it should be fixed now.
