### ISSUE TITLE
OCPL code may trigger wrongful OKAPI last_login update

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1168]
According to this https://github.com/opencaching/okapi/issues/439#issuecomment-326351294 when userA views the map (and/or possibly baloon popup) with cacheX owned by userX the following apparently happens: 
- OKAPI is called on behalf of userX instead of userA, in a way that triggers last_login for userX to be updated, even though it is not userX that generates this activity. 

More technical details can be provided by @following5

**Comment by following5** [comment]
This is an old problem which has been solved by [this workaround](https://github.com/opencaching/okapi/commit/5560aab7f1f9c4e56c6a598d2f17c92d04654581). Please note that I wrote "the login date of userX **was** updated" in the OKAPI issue. ;-) "was" = before the workaround was implemented.

The workaround produces a new probem: "last_login" is not be update in many cases where it should be. That's an OKAPI issue.

But there is also an OCPL issue: Private information of users is made public through the map display. E.g. you can see which caches are ignored by other users. I will open a separate issue for that and suggest to close this one.

**Comment by following5** [comment]
This issue is a duplicate of #724.

**Comment by andrixnet** [comment]
Ok, subtle misunderstanding :-)
