### ISSUE TITLE
"Show user's map" leaks private data

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#1169]
The link "show user's map" in _viewprofile_ allows anyone to see which caches are ignored by a user. Ignoring caches is a private feature, so private data is published here. Are you sure that this ok?

There may be additional private features in the map in the future, e.g. displaying markers for coordinates that a user has privately stored with a cache (OC.de has this feature). So the 'ignored' problem is just a special case of a general problem.

Technically, the problem arises from this line in cachemap3.php:

`tpl_set_var('userid', $mapForUserObj->getUserId());`

The user who requests cachemap3 here pretends to be someone else. Now on the techical level he has access to any private data of the user who's map is displayed. This produces a data security risk which is very hard to contain: The cachemap3 code may call any other code, which is not aware that it must not return any private data of the logged in user. It may even call code that alters private data, e.g. the user's settings.

This pretending-to-be-someone-else also spreads into OKAPI and produced issue #724, which has been solved by a workaround which produces new problems.

Can you explain to me why the feature "show user's map" is important?

**Comment by following5** [comment]
Sorry, I got something wrong here. Will have a deeper look into OCPL code to find out what exactly is happening.

**Comment by deg-pl** [comment]
@following5 feature "show user's map" is very important while planning common geocache trips.

**Comment by kojoty** [comment]
hi @following5 

From my personal point of view it is useful to see other user map. I often use this feature when I plan trip with other users and I would like to propose the route. I think that the only issue here is presenting "ignored" caches, but its not a big deal for me  - in my opinion ignoring is only technical operation which hide caches which I don't want to see at the map - nothing more...

**Comment by following5** [comment]
Okay.

There is still the point that the cachemap3 code makes one user to prentend to be someone else when querying map data. Lots of problems can arise from that, besides of the existing issue that last_login is not updated in cases where it should be.

A clean implementation would not tell OKAPI "I am the user X who's map is requested", but "I am user who wants requests the map of user X". This would have to be implemented as a new feature in OKAPI.
