### ISSUE TITLE
Missing last_found date

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#1177]
From https://github.com/opencaching/okapi/issues/19:

The event OP87X1 has a last_found date of null instead of 2015-08-18 21:29. You can see that when adding it to the clipboard (https://opencaching.pl/viewcache.php?cacheid=41387&print_list=y) and viewing the clipboard.

As it's two years ago, the underlying bug may already have been solved. So I suggest just to update all the event last_found dates ... 

update caches set last_found = (select max(date) from cache_logs where cache_logs.cache_id=caches.cache_id and cache_logs.type=7 and deleted=0) where caches.type=6 

or to run util.sec/repair_cache_scores.php.

**Comment by deg-pl** [comment]
I've run util.sec/repair_cache_scores.php on 12'th of August 2017.
BUT repair_cache_scores.php has bug:
```
$last_found = $db->multiVariableQueryValue("SELECT MAX(`cache_logs`.`date`) FROM `cache_logs` WHERE ((cache_logs.`type`=1) AND (cache_logs.`cache_id`= :1 ) AND (cache_logs.`deleted`=0))", null, $cache_id);
```
It is not correct for events

**Comment by deg-pl** [comment]
repair_cache_scores.php fixed, scores recalculated on all OC nodes. Seems to be fixed.

@rredan could you check your event now?

**Comment by rredan** [comment]
@deg-pl - everything's fine now. Thanks :)
