### ISSUE TITLE
Sending email should return to profile page

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1183]
From the user's profile it is possible to send an email to that user using a web form provided by the website (while maintaining the user's email address confidential). 

After that form is submitted, you are shown the same web form, but with disabled fields and a green notification bar on top: "email sent". This page however is sort of a dead-end. 

After sending the email, you should be returned to the user's profile page and be shown the geen notification.

**Comment by kojoty** [comment]
The main reasons because it works like that (I re-implemented this page) is that it was working like that before. I think I agree with you. I can implement your suggestion but not now - if any of you would like to do it earlier - feel free to take this job.

**Comment by deg-pl** [comment]
@kojoty podpinam się pod to issue. Postaram się to zrobić w wolnej chwili, przy okazji robiąc #1184 i testując UserPreferences. Nie dam rady w tej chwili - podpinam się po to, aby o tym pamiętać. Jeśli Ty zaczniesz coś pisać - daj mi po prostu znać. Gdy ja zacznę nad tym siedzieć - wspomnę o tym tutaj.

**Comment by deg-pl** [comment]
Fixed by commit 502db454a3b65dd4d3058d8891ea8bef071a5446
