### ISSUE TITLE
Checkbox to send copy of email to my own email

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1184]
When I send an email to a user (using website form), a copy is sent to my own email. 

This is a feature request that the webform contains a checkbox to decide if I want a copy of that email sent to me, or not.
Also, that checkbox should either be remembered in a cookie or as part of my profile settings.

**Comment by kojoty** [comment]
why? I send messages to users from time to time and I would like to attach my email-address in one messages and hide it in others. In my opinion this is not a permanent setting but a detailed decision, which can be different for every message sent .

**Comment by andrixnet** [comment]
@kojoty : I was refering to the checkbox for "send me a copy of this email"

**Comment by kojoty** [comment]
@andrixnet :) Yeah - you're right - I mistaked the checkboxes. Full agree now.

**Comment by deg-pl** [comment]
Fixed by commit 502db454a3b65dd4d3058d8891ea8bef071a5446
