### ISSUE TITLE
Copy of send email - shown as a reply

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1185]
The current strategy for sending to my own address a copy of the email I sent another user via the website is poorly formatted. 

The way it is formatted makes it look like a reply. 

It should look like the original, with a marking that it is a copy. Much more similar to Cc: in email.

**Comment by kojoty** [comment]
@andrixnet, formatting of emails sent by user2user is quite easy - take a look here: 
https://github.com/opencaching/opencaching-pl/blob/master/tpl/stdstyle/email/user2user/messageCopyForSender.email.html

If you have any idea of change in this matter fell free to make it better. I agree it could be better formatted.
