### ISSUE TITLE
Review OCPL code in context of OKAPI usage

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1197]
> OKAPI must only be accessed through Facade. To disable and enable error handling, call Facade::disable_error_handling() and Facade::reenable_error_handling().

(https://github.com/opencaching/okapi/pull/503#issuecomment-328791949)

**Comment by following5** [comment]
lib/mapper_okapi.php (and xmlmap.php - obsolete?) do some more calls into OKAPI code.

I think that
`$filepath = \okapi\Settings::get('VAR_DIR') . "/searchdata/" . $searchdata;`
should be replaced by
`$filepath = $dynbasepath . "searchdata/" . $searchdata;`

(see https://github.com/opencaching/opencaching-pl/blob/master/lib/search.map.inc.php#L83).

And `\okapi\core\Db::execute()` may be replaced by an OCPL PDO database function call.

**Comment by following5** [comment]
(Will have a slight performance penalty, because lib/mapper_okapi.php then will use both the OKAPI and the OCPL framework instead of only OKAPI. Alternatively, this code might be intergrated into Facade - i.e. add an import function for an OCPL "searchdata" file.)

**Comment by kojoty** [comment]
@following5, that's what I also think should be done. 

xmlmap.php is in use - in fact the script name is obsolete, but code from inside needs to be integrated to further map controller

**Comment by kojoty** [comment]
if there is anything more to do please reopen.
