### ISSUE TITLE
Review of communication with GeoKrety service

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1199]
> Od: Filip Stefaniak
> nie wiem czy jeszcze zajmujesz się interfejsem OC - GK, ale jeśli tak,
> to: niedługo przeskoczymy licznik z **GKxxxx na GKxxxxx**. Nie wiem czy to
> coś napsuje w wymianie danych (chyba nie powinno) ale na wszelki wypadek
> informuję.
>

**Comment by filipsPL** [comment]
Dzięki. W razie czego jestem tutaj.

**Comment by andrixnet** [comment]
Please continue discussion in english.

I hope I understood well, GK codes are expanding by 1 digit.

**Comment by andrixnet** [comment]
Will this be done by simply adding a new digit to new geokrets, or all GK codes will be zero prefixed? 

If the latter, how will existing codes be handled in searches and redirections?

**Comment by kojoty** [comment]
@andrixnet, exactly this is the only change. 
filipsPL has developed and maintains geokrety site

**Comment by andrixnet** [comment]
@kojoty Thank you, but you haven't clarified it for me, which is it: 
1. add digit to new GK codes
2. zero prefix all existing GK codes to new size

**Comment by filipsPL** [comment]
@andrixnet 
It has to be decided, but we favour the first option (add digit to new GK codes).

**Comment by andrixnet** [comment]
Thank you. Please let us know about the final decision.

**Comment by filipsPL** [comment]
OK. Also let me know if one of the variants is preferable to you. We may take it into account.

**Comment by following5** [comment]
Meanwhile, the counter has made the step from GKFFFF to GK10000. No problem for OCPL and OCDE database, which always had 10 characters space for the GC codes. So this issue may be closed.

But @filipsPL: On geokrety.org, the input field for searching by GC code allows only 6 characters.

**Comment by kumy** [comment]
Thanks for the info, I'll fix it this evening.

**Comment by kumy** [comment]
@following5 I missed that this morning, but if you were referring to the search box on the front page (see picture bellow), then it is not meant to search GK by "Reference Number" but by "Tracking Code" which are on 6 position. So I don't think there is a problem.

![screenshot from 2017-10-10 19-45-26](https://user-images.githubusercontent.com/176794/31401570-9a04ebc2-adf3-11e7-92c5-ebf599c0e16e.png)

BTW, I think you mingled "GK" and "GC" in your last comment ;)

**Comment by following5** [comment]
Okay!

**Comment by andrixnet** [comment]
coord.eu supports expanded GK codes: https://github.com/opencaching/oc_coord/issues/8
