### ISSUE TITLE
region from coordinates yields nothing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#120]
```
When creating or editing a cache, the button "region from coordinates" opens a 
new window to show the region where these coordinates are located, listing 
country, region as found by OCRO and region as found by Google Maps. 

In the case of OCRO, I always get an empty list. 

See attached image.

```

Original issue reported on code.google.com by `andrixnet` on 3 Jun 2014 at 1:12

Attachments:
- [ocro-region.png](https://storage.googleapis.com/google-code-attachments/opencaching-pl/issue-120/comment-0/ocro-region.png)

**Comment by kojoty** [comment]
@andrixnet , is this still an issue? Maybe we can close it?

**Comment by andrixnet** [comment]
Will have to reinvestigate. 
However my last assessment was that database contents should be redefined such that insteand of `LINESTRING`, shapes are stored as `POLYGON`.

**Comment by kojoty** [comment]
It seems that (thanks to Deg and OCUK action) I made progress in this subject. I have a new content for nuts_* tables with update to NUTS-2013 and now nuts_layers 
[nuts_codes.sql.zip](https://github.com/opencaching/opencaching-pl/files/563995/nuts_codes.sql.zip)
[nuts_layer.sql.zip](https://github.com/opencaching/opencaching-pl/files/563996/nuts_layer.sql.zip)

contains POLYGONS instead of LINESTRING. We still need tests and fixes (for example mysql WITHIN is now MBRWITHIN - we should use ST_WITHIN).

**Comment by deg-pl** [comment]
Thanks for your work!
We also should do:
`UPDATE `nuts_layer` SET `code` = REPLACE(`code`, 'UK', 'GB') WHERE `code` LIKE 'UK%';
UPDATE `nuts_codes` SET `code` = REPLACE(`code`, 'UK', 'GB') WHERE `code` LIKE 'UK%';`

**Comment by kojoty** [comment]
I'm not sure if UK == GB: [(http://brilliantmaps.com/eng-gb-uk/)] - are you sure it works OK?

**Comment by deg-pl** [comment]
Problem has source into official ISO code for United Kingdom. ISO code is... GB, not UK. This is source of differences...

**Comment by kojoty** [comment]
I prepared the new-better versionn of nuts_codes table and updated link above - here are good files for NUTS-2013 again:
[nuts_codes.sql.zip](https://github.com/opencaching/opencaching-pl/files/567865/nuts_codes.sql.zip)
[nuts_layer.sql.zip](https://github.com/opencaching/opencaching-pl/files/563996/nuts_layer.sql.zip)

**Comment by deg-pl** [comment]
OC PL and OC UK - done!
Thanks! It works very well!

**Comment by harrieklomp** [comment]
Uploaded new nuts_codes and nuts_layer tables in database of OCNL.
Should i see any differences? When making a new cache i still cannot select province in UK.

**Comment by kojoty** [comment]
@harrieklomp are you apply update for UK mentioned by @deg-pl 

> UPDATEnuts_layerSETcode= REPLACE(code, 'UK', 'GB') WHEREcodeLIKE 'UK%'; UPDATEnuts_codesSETcode= REPLACE(code, 'UK', 'GB') WHEREcodeLIKE 'UK%';

and don't forget to rebuild table cache_location...

**Comment by harrieklomp** [comment]
All done on OCNL and it works now.
Thanks all :+1:

**Comment by andrixnet** [comment]
@kojoty finally my reaserch in summer 2015 payed off. :-) 

@kojoty the SQL files should have contained a `DROP TABLE IF EXISTS nuts_...` because otherwise this data will be added to existing data. 
Alternatively, one should run `DELETE FROM nuts_...` before running this import.

**Comment by andrixnet** [comment]
Current OCRO database (using data provided initially by @wloczynutka , then later corrections by @kojoty ) contains nuts_layer defined as polygons. 

It is sufficient to check with `SELECT id,level,code,st_astext(shape) as shape FROM nuts_layer n limit 1`
the contents of the `shape` column should show `POLYGON(` or `MULTIPOLYGON(`. 

If not, then the database should be updated properly.

@kojoty @deg-pl can we store the SQL dump for `nuts_codes` and `nuts_layer` at http://wiki.opencaching.eu ?

-----------
I am investigating further this issue and some related stuff https://github.com/opencaching/opencaching-pl/issues/986

**Comment by andrixnet** [comment]
Again, I am confirming my earlier results. 
Take these SQL queries: 
`SET @g = ST_GEOMFROMTEXT('POINT(25.396729 44.498259)');` 
This defines a point specifically selected to be in a place where it is inside the MBR (Minimum Bounding Rectangle) of several shapes at the same level.

Tested on OCRO : **mysql  Ver 15.1 Distrib 5.5.54-MariaDB**
Tested on OCNL : **mysql  Ver 14.14 Distrib 5.7.16**

- ST_WITHIN is the correct test, it uses object shapes.
- WITHIN in MySQL uses object bounding rectangles. WITHIN is deprecated. 
- WITHIN in MariaDB 5.5 uses object shapes _(but should not be relied upon)_
- MBRWITHIN uses object bounding rectangles. This test is insufficient and may yield multiple results (including false positives for our purpose)

Previous dataset (`nuts_layer`) contained data defined as LINESTRING, a geometry data type which has only perimeter, not area. The SQL queries for this were more troublesome.
Today the dataset contains (or it should) data defined as POLYGON, a geometry data type which has area and the above queries yield the correct expected results.

Testcase (using the previously defined point): 
```
SELECT 
    id, level, code,
    ST_WITHIN(@g,shape) as _st_within, 
    WITHIN(@g,shape) as _within, 
    MBRWITHIN(@g,shape) as _mbrwithin, 
    name 
    FROM nuts_layer 
    LEFT JOIN nuts_codes USING (code) 
    WHERE
        code LIKE 'RO%';
```

`_st_within` column contains the correct results
`_within` column results vary between MySQL implementations
`_mbrwithin` column gives false positives (being a less specific test)

**Comment by andrixnet** [comment]
The above research, properly implemented, will yield region detection and handling at SQL level, deprecating additional PHP processing like `Gis::ptInLineRing`

**Comment by deg-pl** [comment]
@andrixnet I think that we can store ZIPed NUTS data on wiki.opencaching.eu, but we also can store it on github (see #814)

**Comment by kojoty** [comment]
@andrixnet, @deg-pl
Let's summerize; what else we should done here? 

If there is anything to do please reopen.
