### ISSUE TITLE
New issue in log

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1201]
New problem from the log:

```
[Wed Sep 13 19:02:51.039055 2017] [:error] [pid 17939] [client 37.47.42.106:19220] PHP Fatal error:  Uncaught exception 'okapi\\core\\Exception\\InvalidParam' with message 'Parameter 'y' has invalid value: Expecting non-negative integer
.' in /srv/ocpl/okapi/services/caches/map/tile/WebService.php:53

Stack trace:
#0 /srv/ocpl/okapi/services/caches/map/tile/WebService.php(78): okapi\\services\\caches\\map\\tile\\WebService::require_uint(Object(okapi\\core\\Request\\Ok
apiInternalRequest), 'y')

#1 [internal function]: okapi\\services\\caches\\map\\tile\\WebService::call(Object(okapi\\core\\Request\\OkapiInternalRequest) 

#2 /srv/ocpl/okapi/core/OkapiServiceRunner.php(138): call_user_func(Array, Object(okapi\\core\\Request\\OkapiInternalRequest))

#3 /srv/ocpl/okapi/Facade.php(94): okapi\\core\\OkapiServiceRunner::call('services/caches...', Object(okapi\\core\\Request\\OkapiInternalRequest))

#4 /srv/ocpl/lib/mapper_okapi.php(230):
 okapi\\Facade::service_display('services/caches...', '61579', Array)

#5 {main}\n  thrown in /srv/ocpl/okapi/services/caches/map/tile/WebService.php on line 53, referer: https://opencaching.pl/cachemap-full.php
```

It seems that this is generated after loading map with search-data (for example search results on the map).

**Comment by kojoty** [comment]
@following5, could you look at this - I'm not sure but it seems to have some connection with last OKAPI changes -  I haven't seen it before and we haven't changed anything in this code at OCPL side last days.

**Comment by following5** [comment]
This is not related to OKAPI changes, but probably to changes in Google Maps.

mapper_okapi.php is called with an unexpected `y` parameter (something else than an integer >= 0). This script is a callback to the Google Maps API, it is directly called from within GM code. So GM is supplying this unexpected `y` value. Now we need to find out why.

I have added diagnostic output, you will now see the supplied y value in the error message in your log file.

**Comment by following5** [comment]
> This script is a callback to the Google Maps API, it is directly called from within GM code. 

Oops, not exactly. It's called from OCPL cachemap3.js, and the params to mapper_okapi.php are supplied [here](https://github.com/opencaching/opencaching-pl/blob/master/lib/cachemap3.js#L227). But this function in cachemap3.js _is_ a callback to the GM API and just passes on the y value it is supplied by GM.

Looks like tehre is Looking at the [GM API docs](https://developers.google.com/maps/documentation/javascript/maptypes#ImageMapTypes))

**Comment by following5** [comment]
> This script is a callback to the Google Maps API, it is directly called from within GM code. 

Oops, not exactly. It's called from OCPL cachemap3.js, and the params to mapper_okapi.php are supplied [here](https://github.com/opencaching/opencaching-pl/blob/master/lib/cachemap3.js#L227). But this function in cachemap3.js _is_ a callback to the GM API and just passes on the y value it is supplied by GM.

In the [GM API docs](https://developers.google.com/maps/documentation/javascript/maptypes), there is this code example:

<pre>
 gallPetersMapType = new google.maps.ImageMapType({
    getTileUrl: function(coord, zoom) {
      var scale = 1 << zoom;

      // Wrap tiles horizontally.
      var x = ((coord.x % scale) + scale) % scale;

      // Don't wrap tiles vertically.
      var y = coord.y;
      if (y < 0 || y >= scale) return null;

      return 'https://developers.google.com/maps/documentation/' +
             'javascript/examples/full/images/gall-peters_' + zoom +
             '_' + x + '_' + y + '.png';
    },
    ...
 });

</pre>

So y actually may be < 0, and the `getTileUrl` function in cachemap3.js needs to handle this. It must not pass values < 0 to OKAPI.

**Comment by following5** [comment]
Note that this
 `var x = ((coord.x % scale) + scale) % scale;`
introduces a slight change into the appearence of the cachemap3:

Currenty, if you zoom out to level 0, you will see multiple "worlds", but the geocache markers appear only on one of them. With this change, the caches will apear on each of those worlds.

If you would like to keep the current map behaviour, the line needs to be replaced by
 `if (x < 0 || x >= scale) return null;`

**Comment by kojoty** [comment]
@following5, You're right. Many thanks for resolving this issue.
