### ISSUE TITLE
Geopath "delete comment" button doesn't work

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1215]
There is some issue around jQuery after "delete comment" button click. 
I guess it could be caused by our last cleanups and updates around jQuer/jQuery UI...

**Comment by harrieklomp** [comment]
It seems that it now works.
When delete a comment there shows a confirm box on top of the page but not visible when delete the comment. When user does not know to scroll up after delete than it looks nothing is happening.
Perhaps it is useful to make a popup?

**Comment by harrieklomp** [comment]
Or make a popup like we have on several pages like this.
![selectie_106](https://user-images.githubusercontent.com/1060518/30694817-19f3f594-9ed6-11e7-8c63-d3a0e1bc638f.png)

**Comment by harrieklomp** [comment]
Perhaps it could be possible that this confirm box will show in center of the screen?

**Comment by kojoty** [comment]
popup can be seen again - @harrieklomp, if there is anything more to do please reopen.
