### ISSUE TITLE
Too big default radius in viewcache

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1225]
We have very big radius (100km) to search nearby caches in viewcache. Users cannot modify this radius. It generates many problems:
- GPX is very big - most devices (like Garmin Dakota) doesn't support so big GPXes (about 3500+ caches and 100MB+ size!)
- export of GPX cost many resources on the server side (related with issue #1006)
I think we should set radius i.e. 20km + enable max log limit.

**Comment by kojoty** [comment]
requested change done.
