### ISSUE TITLE
Fulltext search in descriptions, logs and pictures is broken by design

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#1227]
We just detected an epic bug in ftsearch.inc.php at Opencaching.de. The OCPL code is the same (except for the PDO port), and I could verify that the same bug exists at Opencaching.pl.

Effectively, the table `search_index` only contains entries for the last modified description, picture and log entry of each cache. I.e. only the last modified desc, picture and log entry will be found when [searching](https://opencaching.pl/search.php) by text. All other are ignored.

I will do the fix for OCDE and may replicate it then to OCPL code.

The fix would add about 2 Million missing log entries to Opencaching.pl `search_index` and `search_index_times` tables. As a rough estimate, this would allocate about 1-2 GB additional hard disk space on Opencaching.pl database server, and the complete index rebuild would take about 2-6 hours. The website can stay online during the rebuild and will run normally, except for the text search in descriptions.

Are you ready for doubling Opencaching.pl database size? Or would you rather discard the broken log text search? For the NL, UK and RO sites, the database size increase will be neglectable ...

**Comment by kojoty** [comment]
moved from OKAPI https://github.com/opencaching/okapi/issues/513:

> @following5, I'm afraid OCPL has ignored this feature for long time - maybe it has never properly migrated:
> 
> search_ignore table contains only english and german words - it seems that noone has added polish ever...
> search_index_times has the last refresh from the beginning of 2015
> I haven't analyzed how the mechanism of text indexation works in details so I don't know much more about it - I try to look at this soon. Especially interesting for me is a way of update such index - I assume that every new/updated log and every new/updated cache desc. needs to be (re)indexed - how this is done?
> 
> I think it could be a nice idea to have something like that, but I checked also that we don't have much queries by full-text search (from 1.07.2017 there was 72 queries), so I have thoughts that maybe full-text search index is useless and we can just use LIKE %TEXT% sql queries - I know this is slow, unprofessional etc. - but on our DB such query takes more less - a few seconds if I search in text logs (there are ~2,5M of logs).
> 
> @deg-pl, what do you think?

**Comment by kojoty** [comment]
moved from OKAPI opencaching/okapi#513 (deg-pl reply:)

> 
> I think we don't need serching on descriptions / logs / pictures. It cost much of resources (both of searching and indexing), but users can use... Google if they really want to find specific log/description. Why to maintain second (worse) search machine? Let's focus on geocaches, not on another Google clone ;).
> We have not working fultext search code for many years, but... no of OC PL users report it as a problem...
> 
> PS: This is my personal opinion.

**Comment by following5** [comment]
> search_ignore table contains only english and german words - it seems that noone has added polish ever...

No problem. The ignore table is optional and may be used to save some disk space.

> search_index_times has the last refresh from the beginning of 2015

Then your [fill_search_index](https://github.com/opencaching/opencaching-pl/blob/master/util.sec/search_index/fill_search_index.php) cronjob has not run for a long time, or it is broken.

> I assume that every new/updated log and every new/updated cache desc. needs to be (re)indexed - how this is done?

If some text associated to a cache - title, description, logs or image title - is modified or deleted, the index for that cache is rebuild. If new descriptions, pictures or logs are added, their contents are just added to the existing index.

This index updating is done via `fill_search_index.php` cronjob, which calls the [ftsearch_refresh](https://github.com/opencaching/opencaching-pl/blob/master/lib/ftsearch.inc.php#L200)  function in `ftsearch.inc.php`.  This function has been buggy all the time, which mostly affected log and picture search.

> We have not working fultext search code for many years, but... no of OC PL users report it as a problem...

The fulltext search in cache descriptions is working pretty well (except for contents added since 2015, when the indexing cronjob stopped). This is because most caches only have one description (one language).

> I have thoughts that maybe full-text search index is useless and we can just use LIKE %TEXT% sql queries - I know this is slow, unprofessional etc. - but on our DB such query takes more less - a few seconds if I search in text logs

The indexed search takes a few milliseconds. ;-) But it's your decision on what database load is acceptable for you.

> sers can use... Google if they really want to find specific log/description

Google search cannot be combined with cache types, sizes, ratings, attributes and so on.

But if you decide to discard the text search,  this will save me the time to port the fix to PDO, so I am fine with that. :-)

**Comment by following5** [comment]
The [OCDE fix](https://github.com/OpencachingDeutschland/oc-server3/pull/622/commits/6f565cce9e196fdd701df136820332ed9a16a540) is finished. It greatly simplifies implementation and removes about 100 lines of SQL code. On the other hand, it changes about 10 database triggers and adds a stored procedure. OCPL triggers are different from OCDE triggers, but I could handle that. ;-)

What could be added are configuration settings for disabling e.g. the log text search. Then you would end up with less code and less allocated disk space than now at Opencaching.pl plus a bugfree search for cache descriptions and picture titles.

Now please do me a favour and dismiss it - this would save me from another day of coding and testing. ;)

**Comment by kojoty** [comment]
@following5, we appreciate your works and especially that you want to port this change to OCPL code. Please give us a day to decide how to deal with this issue. 

Indexing texts is not the main feature for us and the idea with using Google for search for the texts on the page seems to be reasonable and then we rather drop this part of code at all.

One more question - if we decide to drop this if it affects your works at this feature at OKAPI side? I assume that it will use the same data for search, right?

**Comment by following5** [comment]
It is not decided yet if the cache description text search will be added to OKAPI. If so, I would probably be implemented for OCDE based on the existing search index (table `search_index`), to save hard disk space.

For OCPL, there would be these options:
* Implement it in the same way as OCDE, if you decide to keep the search index.
* Implement it as a simple SQL "LIKE" statement, which would be rather slow and produce high server loads at Opencaching.pl.
* Implement an own OKAPI indexing of cache descriptions. I assume this is not feasible, as this feature is low-prio.
* Not implement it, i.e. it will be marked as "OCDE feature" in the docs always return an empty list of caches for OCPL sites.

I would not recommend the second option, and I guess wrygiel will say the same. That would allow to easily jam your website with some simple OKAPI requests.

**Comment by kojoty** [comment]
it seems this is discontinued for long time. close as it seems to not be an issue for now.
