### ISSUE TITLE
What is a purpose of "remind email" page?

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1249]
I see we have something like that: https://opencaching.pl/remindemail.php
It allows to send simple email to any user (It can be used even by not authorized users).

I can't imagine what is a use-case for this. If anyone can explain it to me please try :)
Otherwise I'm going to remove it soon.

**Comment by following5** [comment]
remindemail.php is linked on https://opencaching.pl/login.php - "Forgot your e-mail address? Ask for it here"

This page is needed if a user was offline for a long time and forgot both the password and the email address (e.g. used some special email address for the OC site and does not remember which). The user then can request an email-address reminder, and use this email address on newpw.php to enter a new password.

**Comment by kojoty** [comment]
@following5, OK now I understand - this is the last chance when user forget both his username and email used in registration. OK. I close this issue.

**Comment by kojoty** [comment]
@following5, One more question on the side: why not allow to request code needed for password change by email OR username - then email-reminder is useless.

This is much more convenient for user and many sites handle password reset case in this way...
