### ISSUE TITLE
improove logging time - log geokrety via ajax

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#125]
```
move geokrety logging from log.php to other php script called from log.php by 
ajax.
display cache log result at once, and maybe loader for geokrety logging.
```

Original issue reported on code.google.com by `wloczynutka` on 15 Jun 2014 at 9:00

**Comment by andrixnet** [comment]
Page load is still slow, Tested with cache having geokrety in it, sync with geokrety.org working.

Page load has similar loading time as geokrety.org website response speed. Tested within same minute.

**Comment by wloczynutka** [comment]
@andrixnet  You can try rewrite page to log geokrety async with ajax, as mentioned in topic of this issue. It would be welcome.

**Comment by andrixnet** [comment]
I will try to recruit a friend to help. My knowledge of Ajax and Javascript is less then that of PHP :-)

**Comment by kojoty** [comment]
@andrixnet, is it still an issue? If yes please reopen.
