### ISSUE TITLE
Small improvements to text in user profile

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1250]
form Brasia email to RT:

> Aktywowałem ręcznie konto użytkownika Eba. Zauważyłem takie wizualne niedoskonałości ;) Może tak było, ale jest to lekko mówiąc wprowadzające w błąd:
> Ostatnio zalogowany więcej niż 12 miesięcy temu - przecież nie logował się wcale
> Użytkownik został odbanowany - chyba powinno być: konto zostało aktywowane, użytkownik nie miał bana.

![image](https://user-images.githubusercontent.com/2961448/31177434-4cbb3344-a916-11e7-83c2-99279b9d8579.png)

**Comment by deg-pl** [comment]
I've fixed this issue about month ago.
