### ISSUE TITLE
Cache page map colors when not logged in

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1253]
Please see this page at OCNL, when not logged in: http://www.opencaching.nl/viewcache.php?cacheid=6975&lang=en

The cache map (static map) is shown as a rectangle (not square) with black background and dark gray text saying "you have to be logged in". 

IMO the choice of colors in this case can be improved.

![ocnl-not_logged_in](https://user-images.githubusercontent.com/3382777/31253692-8184414c-aa2e-11e7-83e7-37f1f57d0b10.png)

**Comment by kojoty** [comment]
I'll try to fix it soon.

**Comment by kojoty** [comment]
should be fix now.
