### ISSUE TITLE
Introduce a cronjob engine

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#1254]
It looks like there are only standalone cronjobs in the OCPL code. If a new cronjob is needed, a new script must be installed in the crontabs of all nodes.

What do you think about adding a cronjob engine like that of OCDE and Okapi? Only one entry in crontab, and new cronjobs are added by creating new class files. For each cronjob, the execution time<sup>x</sup> or interval is specified in the class, and the next execution time of all the jobs is maintained in a database table.

<sup>x</sup> Neither OCDE nor Okapi have fixed execution times, but just intervals. But from [this comment](https://github.com/opencaching/opencaching-pl/pull/1246#issuecomment-333998311) I know that you prefer fixed times in the night for some tasks.

**Comment by deg-pl** [comment]
This is a VERY good idea. We have problem with sync cronjobs across all nodes.

We use some kinds of cronjobs:
- running at fixed time once a day (maintenance at night), or even once per week/month (i.e. "geopath/cache of the week/month").
- running many times a day (with given interval), but we'd like to manage time when job is done. For example - ad ?:00 we publish new geocaches, several minutes later we send e-mails to users with info abount new caches
- running at specified interval - for example GeoKrety management

**Comment by following5** [comment]
The new cron engine is enabled at PL, NL and UK sites.

@andrixnet 
Could you please update the crontab, as shown [here](https://github.com/opencaching/opencaching-pl/commit/69ad770f162487ed65b718f13908d620af0c1390#diff-7a541949c6bd7d0c20559572ce922bda)? This should be the last manual crontab update; future cronjob maintenance will be done via Git.

**Comment by following5** [comment]
Thanks!
