### ISSUE TITLE
Add prefix to new log notifications

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1258]
E-mails with new log notifications are send using new Email object, but have no prefix in subject.
Example - is:
Raport nowych logów w skrzynkach Opencaching.pl: 2017-10-09 21:05:01
should be
[OCPL] Raport nowych logów w skrzynkach Opencaching.pl: 2017-10-09 21:05:01

**Comment by rapotek** [comment]
`util.sec/watchlist/runwatch.php` has not been modified to use new Email object. What is currently used for new logs notifications then?

**Comment by kojoty** [comment]
@rapotek,

Issue is about lack of prefix in email messages for new logs in watched caches. These emails are sent by util.sec/watchlist/runwatch.php script you mentionedThats all.... Like you told this script doesn't use Email class. 

This issue can be "fast-fixed" by adding a proper prefix in runwatch (be aware of other nodes - OCRO/OCNL etc.) or the whole runwatch can be refactored to use Email class as well.

**Comment by rapotek** [comment]
In case of refactoring:
- Are `/var/log/ocpl/runwatch.log` writings and Log::logentry necessary? I mean someone or some code really reads the outputs/logs?
- Are there any props for using file lock instead of f.ex. sysv semaphores? I do not have nothing against file lock but I am curious if the choice was an informed one or a random one.

**Comment by kojoty** [comment]
@rapotek, be sure that may of such questions have one and only answer: "we don't know - someone long time ago wrote such code and it just works as is..."

> Are /var/log/ocpl/runwatch.log writings and Log::logentry necessary? I mean someone or some code really reads the outputs/logs?

I guess log-entry is not needed. I don't know why we need such information. It can be useful for some debug purpose but no in this form. 

> Are there any props for using file lock instead of f.ex. sysv semaphores? I do not have nothing against file lock but I am curious if the choice was an informed one or a random one. 

I think that the best way of resolving such issue is to write simple generic class in Utils with methods:
- Lock::tryLock($key) - check and lock if open
- Lock::unlock($key) - ...
- Lock::forceUnlock($key) - unlock even if locked
and internal implementation should just works with the general rue: simpler is better
Then we should use it in the next refactors...

**Comment by deg-pl** [comment]
See also #1200

**Comment by rapotek** [comment]
OK, so #1200 says logentries table is still in use. Therefore its entries should be generated as they've been so far, with small refactoring too :smirk: 
Generic lock class is a good idea to think about in nearest future. Currently i think a configured file lock will be enough.

**Comment by deg-pl** [comment]
I think we can close this issue. Thanks @rapotek!
