### ISSUE TITLE
Search cache-size filter doesn't work

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1259]
email from Rubeus:

> Nie wiem, czy ktoś już zgłaszał, ale nie funkcjonuje poprawnie wyszukiwarka skrytek 
> Pomimo ustawionego pomijania keszy o rozmiarze "mikro", pojawiają się one w wynikach wyszukiwania.

**Comment by following5** [comment]
It was broken [here](https://github.com/opencaching/opencaching-pl/commit/7f029fa83b06551c0c073aae11b99cb09960a1e3).  "sizeName" is not evaluated, but directly taken as the name of an form element.

**Comment by following5** [comment]
Bute there are more issues with the size search. At some places in search code there are sizes 1-7, and some places 1-8.
