### ISSUE TITLE
post-commit.php fails on OCNL

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1267]
OCNL apparently is broken with regard to automatic updates from repository. 

I've looked at it last night and there's some oddity with PHP.

In `post-commit.php` there is:
```
require_once __DIR__ . '/lib/settingsGlue.inc.php';
```
This then loads `settings.inc.php`, which in turn loads `settingsDefault.inc.php` via require statements.
Apparently variables in settings.inc.php seem to get loaded, but those further on in settingsDefault.inc.php are not loaded.

The configuration variable residing in `settingsDefault.inc.php` which is needed by this script `$config['server']['update']['script']` appears to have empty value. 
(since it doesn't need personalization, it's not redefined in settings.inc.php)

settingsDefault.inc.php: 
```
// *** Repository automatic updates script location
$config['server']['update']['script'] = '/var/www/ocpl-update.sh';
```

In fact, the variable appears to be empty.
I say oddity, because it only fails on OCNL... I mean if it were a general error, none of the sites would have had working automatic update since https://github.com/opencaching/opencaching-pl/pull/1192/commits/03a8b5483815b6455c2ea4b35f466eba172e4acf 24 days ago.

And there isn't anything in error_log either on this.

This is how far I've got in my investigation.

**Comment by following5** [comment]
What's also strange here: The deployment to OCNL _sometimes_ works. E.g. I pushed two Okapi updates yesterday, which did not arrive at OCNL. But later in the evening, the site was up to date.

**Comment by harrieklomp** [comment]
When i see when there is a commit, i do it by hand in terminal.

**Comment by following5** [comment]
Is there an `$config['server']['update']['script']` setting in lib/settings.inc.php?

**Comment by following5** [comment]
Is there an $config['server']['update']['script'] setting in lib/settings.inc.php? This would override the setting in settingsDefault.inc.php.

**Comment by harrieklomp** [comment]
Okay now we are getting somewhere.
I did mis this part so i added `$config['server']['update']['script']` in lib/settings.inc.php. Andrixnet did make a new script yesterday so let see if it works now. If not, i must use the old .sh script.

**Comment by andrixnet** [comment]
@harrieklomp with my extended script, you will now see each update logged in /var/log/cron which helps you keep track of applied updates, when they took place and what exact files have changed with each update. 

It is very strange that `$config['server']['update']['script']` is not properly propagated from settingsDefault.inc.php. I don't have sufficient experience with PHP subtleties to know why.

All my tests on OCRO yielded positive results and I believe PL and UK don't have a problem either (since https://github.com/opencaching/opencaching-pl/commit/03a8b5483815b6455c2ea4b35f466eba172e4acf almost a month ago).

Now that @harrieklomp added the variable in settings.inc.php, it propagates well into post-commit.php.
However, there is a problem with `sudo` complaining 
```
sudo: sorry, you must have a tty to run sudo
```
so the result is an incomplete run.

**Comment by andrixnet** [comment]
I made a temporary fix and it appears to work now.
