### ISSUE TITLE
Invalid target redirect after logon on OCPL

### ISSUE THREAD

**Issue by rapotek** [opencaching/opencaching-pl#1268]
Steps to reproduce:

1. Logout from the service
2. Go to https://opencaching.pl/myneighborhood.php - redirects correctly to https://opencaching.pl/login.php?target=myneighborhood.php
3. Successful logon redirects to https://opencaching.plmyneighborhood.php without a slash ('/') in the middle, which is resolved to bad address

**Comment by kojoty** [comment]
I know the problem - I try to fix it soon.

**Comment by kojoty** [comment]
I hope now it is fixed.
