### ISSUE TITLE
Add email address validation 

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1278]
I see there are several number of emails in user table with trailing spaces which can't work in our code.

We need simple email validation on registration page and in email change process 

(I'm not sure - maybe there is something like that - I create an issue to don't forget about it).

**Comment by following5** [comment]
The email address validation at OCDE has recently been improved: [here](https://github.com/OpencachingDeutschland/oc-server3/commit/0bdeab6) and [here](https://github.com/OpencachingDeutschland/oc-server3/commit/09ea90e).

* use PHP function `filter_var($eMailAddress, FILTER_VALIDATE_EMAIL)`
* set HTML5 attribute `type="email"` for the email input field; some web browsers recognize that and validate the address in advance

**Comment by kojoty** [comment]
OCPL code validate email address before save in DB - most of old improper values are now fixed in OCPl db
