### ISSUE TITLE
Waypoint trailhead as stage nr.

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1287]
When making additional waypoints the waypoint Trailhead does not show the stage number.
Could it be possible to show this number?
![selectie_114](https://user-images.githubusercontent.com/1060518/31896951-4fbfb6e2-b815-11e7-9b39-7c55e79bf5af.png)

**Comment by harrieklomp** [comment]
BTW: When edit this waypoint the value is 0 (zero) again.

**Comment by following5** [comment]
The stages of a cache are the _parts of the cache_ (i.e. physical or virtual points), while the trailhead is no part of the cache. So I think it's fine that it cannot be assigned a stage number.

**Comment by harrieklomp** [comment]
I think it is also part of the cache to advice people to follow a route when there is no Physical or Virtual waypoint available or needed.

**Comment by following5** [comment]
Well, a trailhaid often is just a proposal from where to start to the cache - like a parking area waypoint, which also ist just a proposal where to park. While a stage usually is a point which _must_ be visited to to do the cache.

**Comment by harrieklomp** [comment]
Then we keep it like it is.
