### ISSUE TITLE
stats data from the future :)

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1297]
![image](https://user-images.githubusercontent.com/2961448/32434856-8f4ef5be-c2df-11e7-8e96-77a5b5374a99.png)

**Comment by rapotek** [comment]
From [Dates and Times Using the Date String Representation ](https://developers.google.com/chart/interactive/docs/datesandtimes#dates-and-times-using-the-date-string-representation)

> Important: When using this Date String Represenation, as when using the new Date() constructor, months are indexed starting at zero (January is month 0, December is month 11). 

In that case in `graphs/stat-charts.php`, line 71 replace `(string) $rStats['month']` with `(string) ($rStats['month'] - 1)` or modify the db query in similar way.

**Comment by kojoty** [comment]
@rapotek - Thanks for investigation! Are you able to create PR with this fix? If you know how to fix feel free to just fix it :)

**Comment by kojoty** [comment]
stats reloaded, everything works as expected. Issue is closed.
