### ISSUE TITLE
Open links from horizontal menu in new window

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1311]
With the new menus the links to several other sites like the forum, blog and wiki do open in the same tab/window.
Could it be possible to open these links in a new window like it was before?

**Comment by kojoty** [comment]
@harrieklomp, This is done - if you want to open link in a new window just add it in "[ ]" (as php array) - take a look at https://github.com/opencaching/opencaching-pl/blob/master/Config/Menu/horizontalBarMenu.pl.php

I'm not sure if this is best way of resolving it but this is the simplest in my opinion.

Best regards :)

**Comment by harrieklomp** [comment]
Thanks for the fast solution :+1: 
I will try to do it for OCNL
