### ISSUE TITLE
Incorrect copyright notice in source code files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#132]
```
I've noticed that many source files include a possibly incorrect copyright 
notice: 

./util/gns/gns_import.php
-------------------------
        begin                : Mon October 31 2005
        copyright            : (C) 2005 The OpenCaching Group
        forum contact at     : http://www.opencaching.com/phpBB2

                                                                ./lib/auth.inc.php                                                          --------------------
            begin                : Fri September 16 2005
            copyright            : (C) 2005 The OpenCaching Group
            forum contact at     : http://www.opencaching.com/phpBB2

And others. 

=============================================================
I searched the web and found no actual results with the exact string "The 
OpenCaching Group" but got hits from the german and US websites. 

This URL does not exist: http://www.opencaching.com/phpBB2

However, this URL (notice the .com) is the so called "opencaching" by Garmin 
website http://www.opencaching.com which is in no way affiliated with the 
opecaching project. 

I do not know much about the history of the development of the opencaching 
project over the years, but doing a little research I found this: 

- OCPL is licensed GPLv2, but the repository does not include the file with the 
license terms anywhere. 
- I have found /docs/license.txt which is an OCDE license from 2007
Opencaching Network Implementation Version 2.0 
- I have found GPLv3 license file in /lib/enlargeit, perhaps it came with this 
module
- I have found a LGPL license file in /lib/phpqrcode
- I have found a GPLv3 license file in /lib/chat

GPLv2 is mentioned in many files, others do not have any copyright notive, or a 
different notice. 

========================================================================
I will help do the necessary modifications, but I want to discuss them first:

1) GPLv2 license file should exist at project level

2) can the license change to GPLv3?

3) all source code files should include a license notification (comment)

4) old german code currently in use, what is it's license status? 
there is a 2007 OCDE license file, but there are files with notice from 2005. 
What license applies to them?
At least some of these might have been modified over the years since OCPL 
branch diverted from the original codebase. A license notification about these 
changes should also exist in each of these files.

5) This URL http://www.opencaching.com/phpBB2 should be clarified, because 
today is misleading. 
If sometime in the past the Opencaching project used opencaching.com as domain, 
before Garmin took over it, then it is clearly a mistake to still refer to it. 
Perhaps this URL should replace it: http://forum.opencaching-network.org/

6) third party modules that have their own licenses remain untouched
```

Original issue reported on code.google.com by `andrixnet` on 28 Jun 2014 at 10:24

**Comment by wloczynutka** [comment]
@andrixnet We can prepare new comment header, and If you have time, you can update all scripts. Question is if you have time to do it. If so, please let us know. If not, I will close this issue, as really not important.

**Comment by harrieklomp** [comment]
If people provide me the new comment header i will offer the time to implement it. That is much easier than programming ;-)
The most important thing is to get rid of this oc.com.  That link to http://forum.opencaching-network.org/ is more based to the Germans and for most not readable.
Just a common name like Opencaching-network or Opencaching-community wil do fine i think.
Maybe it is a good suggestion to make a international forum on www.opencaching.eu where the main language English could be.

**Comment by wrygiel** [comment]
How about removing all the notices from the standalone source files, and replacing it with one common licence.txt file in the root of the repository?

**Comment by wloczynutka** [comment]
IMHO one file is better than few hundreds same comment headers. I support
this idea.

2015-09-11 8:08 GMT+02:00 Wojciech Rygielski <notifications@github.com>:

> How about removing all the notices from the standalone source files, and
> replacing it with one common licence.txt file in the root of the repository?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/opencaching-pl/issues/132#issuecomment-139461492>
> .
>



-- 
__________________________________
*Andrzej 'Łza' Woźniak*

*(+48) 798 835 592*
skype praca: *andrzej.wozniak.traveltech*
skype dom: *wloczynutka*

**Comment by wloczynutka** [comment]
Can we use readme.md file? I think yes.

**Comment by wrygiel** [comment]
Usually licence is placed in a separate file. README.md is for general information about the project (and it is displayed automatically on GitHub entry page).

**Comment by wloczynutka** [comment]
Anyway, 

Harrie, I think you can start removing these headers from php files.

Meanwhile, should we decide, what should we place in this file? Link to any licence? which one? Any ideas?

**Comment by andrixnet** [comment]
Here is an example of **header** with *file information* and licensing information for a GPL licensed project. 

Each file contains a standard header with: 
1. a one line description of this source file, 
2. a list of copyright holders (authors),
3. a short preamble of the GPL (which is standard), which refers to the full document of the license.

This header however is not 100% identical for all files because of 1. This bit however is quite useful in identifying the purpose of a file without having to read it's contents.

```
/*
    graphs.c  - produces graphs used by the Webalizer

    Copyright (C) 1997-2009  Bradford L. Barrett

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version, and provided that the above
    copyright and permission notice is included with all distributed
    copies of this or derived software.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA

*/
```

**Comment by andrixnet** [comment]
In /docs we already have the GPL license file as GPL.txt, containing GPL version 2. 
Am I correct in assuming that GPLv2 applies to the code? 

Also, considering the history of the project, how does this apply?
https://github.com/opencaching/opencaching-pl/blob/master/docs/license.txt

If so, there is also the consideration of upgrading to GPLv3 or not. 
Here is an article by Richard Stallman on why to upgrade to GPLv3 http://gplv3.fsf.org/rms-why.html
Here are a couple of articles describing the key differences between GPLv2 and GPLv3: 
http://www.ifross.org/en/what-difference-between-gplv2-and-gplv3
http://stackoverflow.com/questions/41460/what-are-the-differences-between-gpl-v2-and-gpl-v3-licenses
and a complete guide to GPL licensing: 
http://copyleft.org/guide/

**Comment by andrixnet** [comment]
@wloczynutka I can do the changes (header comment) on some of the files together with @harrieklomp  or all of them in the course of the next few weeks. 
Anyway, there is a lot of cleanup to be done besides this. But that is another issue.

**Comment by andrixnet** [comment]
Also, from my experience, it is customary for a the GPL license file to be named "COPYING" and be placed either in the root of the source tree or in doc(s) or similar directory where documentation information is provided.

**Comment by wloczynutka** [comment]
@andrixnet we decided remove comment headres from files, and put one licence file in root directory instead. (Licence file is not created yet) 

I think @harrieklomp already removed all headers. 

Only create licence file left to do.

@opencaching/opencaching-pl-lead-programmers: we need consider GPLv3 licence. What are you think?

**Comment by andrixnet** [comment]
One detail about GPLv3 is that you can't have mixed licensing. It's either v2 or v3.

**Comment by wloczynutka** [comment]
I updated a little bit existing licence.txt to keep it up to dated witch current status.
I'm not very fimilar with these licences, and I feel not comfortable witch that file. If anyone want perform more changes, please do it.
