### ISSUE TITLE
Wrong locale in calendar picker

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1326]
new cache page calendar picker (date hidden) apparently uses polish locale. 

![calendar](https://user-images.githubusercontent.com/3382777/34653760-5f2fb3e6-f3f9-11e7-8ea3-3c3c7bf084b2.png)

**Comment by kojoty** [comment]
@andrixnet, I assume this is fixed now. If not please reopen.

**Comment by andrixnet** [comment]
Confirmed, fixed. Thank you.
