### ISSUE TITLE
new cache page missing borders

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1327]
New cache page is missing some borders in some sections. 
![borders](https://user-images.githubusercontent.com/3382777/34653774-aeb92dd4-f3f9-11e7-82b6-6949cff022e8.png)

**Comment by kojoty** [comment]
@andrixnet, I assume this is fixed now. If not please reopen.

**Comment by andrixnet** [comment]
Confirmed, fixed.
