### ISSUE TITLE
Add watch for cache status changes

### ISSUE THREAD

**Issue by rapotek** [opencaching/opencaching-pl#1332]
Enhancement: add watch concerning not only new logs but the cache status changes too. Currently watch is only possible for cache logs.

The scenario (from real life):
Owner makes the cache temporary unavailable. Another user adds the cache to the watchlist, sent once per hour. Owner makes the cache ready and immediately removes both logs about status changes: temporary unavailable and ready to search (it is legal now). The cache watcher do not receive notification about the cache is ready, because watch concerns about the new logs only and no new logs appeared in the last hour.
The result: the cache watcher still thinks it is unavailable.

Maybe the enhancement should go to prohibit removal status/system log entries by the cache owner instead?

**Comment by andrixnet** [comment]
IMO deleting system log entries should be prohibited. (both cache owner and admin)
I should rephrase: since it is possible to disable a cache by 2 means: 
1. modify cache and disable (also generates system log)
2. post a disable cache log
Deleting logs with associated cache status actions should be prohibited.

**Comment by following5** [comment]
I am not sure if it's a good idea to prohibit deleting those logs, but -- _if_ it is allowed, then not sending a notification may be considered as a feature. The owner decides not to publish the status-changing information, so it's consequent not to send a notification.

(There also is a loophole for bypassing notifications for a new cache, if the cache needs no OC team approval. I love that ... you can fool the FTF hunters. :-)

**Comment by kojoty** [comment]
I agree with @following5. If someone wants to delete this type of logs let's allow him to do that. From my point of view emails are only a kind of tip - not a guarantee of change.

I also can't see the simple way of processing this kind of information - we need to save information about every cache change... But why only status - maybe other params also can be interested...

I close this. If anyone has opposite opinion - please reopen.
