### ISSUE TITLE
Stats - finds per region - hardcoded PL regions?

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1346]
http://www.opencaching.ro/articles.php?page=s11a

![stat-11a](https://user-images.githubusercontent.com/3382777/35036595-816316d4-fb7d-11e7-92ce-eae53ec2ee68.png)

**Comment by andrixnet** [comment]
Lack of regions listed here http://www.opencaching.ro/articles.php?page=s8 might be related

**Comment by andrixnet** [comment]
And here http://www.opencaching.ro/articles.php?page=s7

**Comment by deg-pl** [comment]
Duplicate of #986

**Comment by andrixnet** [comment]
My bad. I totally missed it. Closing as dupe
