### ISSUE TITLE
Long strings in logs

### ISSUE THREAD

**Issue by rapotek** [opencaching/opencaching-pl#1349]
I do not know if it was notified before.

The scenario:
1. Click 'Post new log' in any cache.
1. Choose any type ('Found it', 'Write a note' etc)
1. In 'Notes:' area type a very long string without any spaces within.
1. Submit log and see the effect.

There's an 'overflow-wrap: break-word' css rule missing, isn't it?

**Comment by kojoty** [comment]
I assume this is fixed now. If not please reopen.
