### ISSUE TITLE
home page stats - inconsistent size

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1350]
The new homepage stats bar changes horizontal size slightly after a few clicks on the right or left arrow.

![state](https://user-images.githubusercontent.com/3382777/35046097-b3f006d6-fb9e-11e7-9736-2734567e1be7.png)

**Comment by kojoty** [comment]
I fixed it last night. @andrixnet please reopen if I'm wrong.

**Comment by andrixnet** [comment]
confirmed
