### ISSUE TITLE
Composer usage in oc code

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1366]
What do you think about wider usage composer?
I think we can moved:

- [ ] tinymce (alternatively we can switch it to some cdn)
- [x] htmlpurifier
- [x] jgraph
- [x] phpqrcode

(... anything else?)

under composer control.

**Comment by andrixnet** [comment]
I would recommend against hosting components such as tinyMCE from external CDN for consistency.

**Comment by deg-pl** [comment]
TinyMCE should not be moved to composer. TinyMCE libraries should be public accessible (via http), composer uses /vendor/ directory, which should NOT be public accessible.

I think we can close this issue now
(@kojoty ping ;) )

**Comment by deg-pl** [comment]
jpgraph in composer is outdated (version 4.0.2). This version doesn't support PHP 7.2 (see #1376). Newest version on jpgraph website is 4.2.4, which is fully compatibile with PHP 7.2

**Comment by kojoty** [comment]
@deg-pl : Right, I removed jpGraph from composer - see PR #1633
