### ISSUE TITLE
All GeoPaths on main page on OCNL

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1367]
On OCNL all latest Geopaths are shown on the mainpage and on OCPL there are only shown 5 latest GeoPaths.
Is there any setting to show also the 5 latest GeoPaths on OCNL?

![selectie_125](https://user-images.githubusercontent.com/1060518/35275757-109ae85a-0041-11e8-9e1b-c6078f34916f.png)

![selectie_126](https://user-images.githubusercontent.com/1060518/35275792-273b0af4-0041-11e8-919b-f25c0a858dfd.png)

**Comment by kojoty** [comment]
@harrieklomp, this is strange. Do you have SettingsDefault.inc.php included at the top of settings.inc.php?

This setting is here: 
https://github.com/opencaching/opencaching-pl/blob/master/lib/settingsDefault.inc.php#L289

**Comment by harrieklomp** [comment]
Yes. I have included SettingsDefault.inc.php in settings.inc.php.
![selectie_127](https://user-images.githubusercontent.com/1060518/35277225-4e163b94-0046-11e8-9ddb-aff787393301.png)

I also have (just now) add these lines to settings.inc.php.
![selectie_128](https://user-images.githubusercontent.com/1060518/35277249-6a845590-0046-11e8-97e1-88d2e339be6a.png)

**Comment by kojoty** [comment]
OK, now we need to be sure if the APC cache was flushed - to be sure this is done you can for example restart apache - (BTW: it would be a good idea to install APCu web-management tool - see for example this tutorial for details: https://anavarre.net/how-to-monitor-and-tune-apcu/ - but this is not necessary for now - just fast apache restart should flush APCU cache) - I hope this help.

**Comment by harrieklomp** [comment]
After restart apache it works on OCNL
Thanks for the help @kojoty :+1:
