### ISSUE TITLE
MyNotes refactoring is needed

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1374]
from mail to RT: misiek_siersciuch

> Witam, od kilku dni nie mogę wejść w zakładkę "Moje notatki" (https://opencaching.pl/mycache_notes.php). Bardzo długo mieli i na koniec pojawia się komunikat:
> Ta strona nie działa
> Serwer opencaching.pl nie może teraz obsłużyć tego żądania.
> HTTP ERROR 500
> Próbowałem odpalić w innej przeglądarce i na innym kompie- bez zmian. Rozmawiałem też dzisiaj z areckisem- ma podobnie.
> Kilkaset notatek mam zapisanych- nie wiem czy istnieje jakieś ograniczenie co do ilości zapisanych notatek w keszach.
> Pozdrawiam i proszę o pomoc :)

**Comment by deg-pl** [comment]
"U mnie działa". Fakt, że wolno, ale działa. Pewnie mamy tam jakiś mało optymalny kod do zaorania i napisania od nowa ;). Przy okazji paginacja by się przydała.

**Comment by deg-pl** [comment]
Error log:
`
AH01071: Got error 'PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /srv/ocpl/mycache_notes.php on line 214\n', referer: https://opencaching.pl/
`

**Comment by kojoty** [comment]
dokładnie tak - ja znam ten problem - bo to jest analogiczne do watch-listy, którą już przerabiałem kiedyś - tam też było tak, że przy kilkuset obserwowanych lista ładowała się niemal bez końca...

**Comment by rapotek** [comment]
Wszedłem w moje notatki, żeby zrobić trochę porządku. Okazało się, że w kolumnie 'Notatka' mam nie swoje notatki! Myślałem, że to tylko w dwóch przypadkach, ale wygląda na więcej. Na stronie kesza notatki są prawidłowe.

**Comment by kojoty** [comment]
wow! jesteś pewien? zaraz popatrzę na to...

**Comment by rapotek** [comment]
Przykład: mam wrażenie, że właśnie poznałem hasło od 'Wyimki z Gdańska #22'. Wiem, gdzie jest wyimek, ale przy samym keszu jeszcze nie byłem.

**Comment by kojoty** [comment]
no już widzę - ależ babol! zaraz poprawię.

**Comment by rapotek** [comment]
Już jest ok 👍

**Comment by kojoty** [comment]
no teraz powinno być OK :) Kurcze na dev miałem 2 notatki ktore sam zrobiłem i zapomniałem, że trzeba odfiltrować innych userów :)

Jak patrzyłem wczoraj w nocy po mergu to nawet tak mi sie dziwne wydało że mam tyle kordów powpisywanych (bo notatek to mam masę, ale kordy to rzadko wpisuję) ale jakoś uznałem że widocznie tak mam i już nie wniknąłem :) 

dzięki za czujność rapotek!

**Comment by deg-pl** [comment]
W sumie szkoda, że poprawiłeś. Mogło być ciekawie! Taka losowa notatka i kordy innego usera czasami potrafi otworzyć geocaching na nowy wymiar :)

**Comment by kojoty** [comment]
fakt! proponuję: głosowanie na FB w sprawie tego feture'a :)
(a co tam też mogę być wredny - albo lepiej: wściekły-kojot)

**Comment by kojoty** [comment]
OK, I think I done most of work in this subject for now - some fixes needs to be applied but the main subject is done.

**Comment by rapotek** [comment]
@kojoty tak mi przyszło do głowy rozwinięcie Twojego feature'a - zamiast
`WHERE user_id = :1 AND cache_id IN ($cacheIdsStr)`
we wiadomym zapytaniu użyć:
`WHERE cache_id IN ($cacheIdsStr) AND CASE WHEN MONTH(CURDATE()) = 4 AND DAY(CURDATE()) = 1 THEN user_id IN (SELECT MIN(cn.user_id) FROM cache_notes cn JOIN (SELECT MIN(user_id) uid FROM cache_notes) cmin JOIN (SELECT MAX(user_id) uid FROM cache_notes) cmax WHERE cn.user_id >= ROUND(cmin.uid + RAND() * (cmax.uid - cmin.uid))) ELSE user_id = :1 END`
:stuck_out_tongue_winking_eye:
