### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1376]
OC PL code on site with PHP 7.2 produces MANY PHP warnings. For example - main page (2 times):
`
AH01071: Got error 'PHP message: count(): Parameter must be an array or an object that implements Countable\n'
`

Cachemap3 (about 12 times per pageview):
`
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /srv/ocuk/okapi/Settings.php:274\nStack trace:\n#0 [internal function]: okapi\\core\\OkapiErrorHandler::handle(2, 'count(): Parame...', '/srv/ocuk/okapi...', 274, Array)\n#1 /srv/ocuk/okapi/Settings.php(274): count('deg@best.pl')\n#2 /srv/ocuk/okapi/Settings.php(263): okapi\\Settings::verify(Array)\n#3 /srv/ocuk/okapi/Settings.php(316): okapi\\Settings::load_settings()\n#4 /srv/ocuk/okapi/core/Db.php(40): okapi\\Settings::get('DB_SERVER')\n#5 /srv/ocuk/okapi/core/Okapi.php(525): okapi\\core\\Db::connect()\n#6 /srv/ocuk/okapi/Facade.php(45): okapi\\core\\Okapi::init_internals()\n#7 /srv/ocuk/lib/ClassPathDictionary.php(104): include_once('/srv/ocuk/okapi...')\n#8 [internal function]: {closure}('okapi\\\\Facade')\n#9 /srv/ocuk/lib/mapper_okapi.php(22): spl_autoload_call('okapi\\\\Facade')\n#10 {main}\n  thrown in /srv/ocuk/okapi/Settings.php on line 274\n', referer: https://opencache.uk/cachemap3.php
`

See also: https://wiki.php.net/rfc/counting_non_countables

**Comment by kojoty** [comment]
@deg-pl, czy są jakies powody do szybkiej migracji na php7.2? rozumiem, że nie bardzo - prawda? A błędy - no cóż - poprawi się :)

**Comment by deg-pl** [comment]
OKAPI also generates a lot of warnings like:

> ErrorException:
> count(): Parameter must be an array or an object that implements Countable
> 
> --- Stack trace ---
> #0 [internal function]: okapi\core\OkapiErrorHandler::handle(2, 'count(): Parame...', '/srv/oc.conspir...', 274, Array)
> #1 /srv/oc.conspiracy.pl/okapi/Settings.php(274): count('deg@best.pl')
> #2 /srv/oc.conspiracy.pl/okapi/Settings.php(263): okapi\Settings::verify(Array)
> #3 /srv/oc.conspiracy.pl/okapi/Settings.php(316): okapi\Settings::load_settings()
> #4 /srv/oc.conspiracy.pl/okapi/core/Okapi.php(472): okapi\Settings::get('SITELANG')
> #5 /srv/oc.conspiracy.pl/okapi/index.php(49): okapi\core\Okapi::gettext_domain_init()
> #6 {main}
> 
> --- OKAPI method called ---
> /okapi/cron5

@kojoty na razie nie ma powodów do migracji. Natomiast sygnalizuję problem, by nowy kod pisać już dostosowany, a stary dostosowywać. To generalnie jest błąd po stronie kodu, a wcześniejsze wersje php nie sygnalizowały tego warningiem.

**Comment by deg-pl** [comment]
I think we can close this issue. OC PL and OC UK works now on PHP 7.2

**Comment by kojoty** [comment]
@harrieklomp, @andrixnet - what version of PHP are you running now at your nodes?

**Comment by deg-pl** [comment]
@kojoty you can check it here https://www.opencaching.nl/lib/apc/apc.php and here https://www.opencaching.ro/lib/apc/apc.php ;)
