### ISSUE TITLE
homepage stats - event handling results in selected text

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1383]
![select](https://user-images.githubusercontent.com/3382777/35562227-674e9262-05bb-11e8-8d5a-a5fe508ed1e4.png)

On the homepage stats bar, if I click repeatedly the < or > button to scroll several boxes, it is easy to accidentally get text from some boxes selected as if I had dragged the selection cursor across it. 

It may be related to mouse click events processing, either by:
- the boxes moving due to a mouse down event, before a mouse up event fires
- further propagation of the mouse click event taks more time then it takes the script to move the boxes, so futher event processing mistakenly see it as a mouse down cursor drag. Something like JS preventDefault may be of use. (?)

**Comment by kojoty** [comment]
This is very complicated issue :) I disabled user selection at counters - I hope this is OK. If not please reopen.
