### ISSUE TITLE
OKAPI dbstruct compare_to does not take triggers into account

### ISSUE THREAD

**Issue by rapotek** [opencaching/opencaching-pl#1388]
The procedure described [here](https://github.com/opencaching/opencaching-pl/wiki/vm_installation_and_usage) should be updated because `http://<local_server>/okapi/devel/dbstruct?compare_to=https://opencaching.pl/okapi/devel/dbstruct` returns differences for tables only, while triggers are omitted. This can lead to inconsistencies between local development and official production site in database structure and logic and therefore to unreliable test results.

**Comment by deg-pl** [comment]
I think we should update OKAPI dbstruct to show differences between tiggers also.

**Comment by rapotek** [comment]
@deg-pl I agree, but the update can be a little bit tricky. The class used for comparing is imported to project from outside, according to its documentation. Perhaps it should be thoroughly analysed first.

**Comment by deg-pl** [comment]
Maybe we can just update this script/library/class?

**Comment by rapotek** [comment]
We can update [the class](https://github.com/opencaching/okapi/tree/master/okapi/lib/DbStructUpdater.php). I also suspect it does not compare defaults in create table definitions but I will have to check it.

I suggest to go a step further: make a script (it can be in php but allowed from cli only due to security) which takes every date-starting SQL file in `/sqlAlters` sorted ascending by the date and executes it on database ignoring errors. This script would be meant to run before dbstruct compare_to. I think both should finally make a developement database fully up-to-date with the production.

**Comment by rapotek** [comment]
I've prepared simple script `applySqlAlters.php` in `/sqlAlters` directory, [see here](https://github.com/rapotek/opencaching-pl/commit/f6768e7d9e8b65df709956140ddfb815ec1ccc05). It showed up there are some minor errors in `/sqlAlters` files (excluding 'Duplicate key', Duplicate column', 'Table already exists' etc. which are obvious when the same alters were applied earlier). I've corrected these errors (see the same commit above) and run the sequence starting with database from developement VM:
1. Call `http://<local_server>/okapi/update`
2. Run `php applySqlAlters.php` in `/sqlAlters` dir
3. Call `http://<local_server>/okapi/devel/dbstruct?compare_to=https://opencaching.pl/okapi/devel/dbstruct`
4. Apply result changes to database
5. Call `http://<local_server>/okapi/devel/dbstruct` and save the result
6. Call `https://opencaching.pl/okapi/devel/dbstruct` and save the result

Comparing the saved results showed, that apart from:
* fields and keys order in 'create table',
* triggers definers,
* case sensitive and spacing differences in triggers (which leads to the equals results in mysql)

which can be skipped in fact, there are only minor differences which in most cases should not make the developement inconsistent with production:

| Table | Production | Developement |
| ----- | ----- | ----- |
| \`cache_logs\` | \`edit_count\` int(11) NOT NULL DEFAULT '0' | \`edit_count\` int(11) NOT NULL |
| \`countries\` | \`list_default_nl\` int(1) NOT NULL DEFAULT '0' | \`list_default_nl\` int(1) NOT NULL |
| \`gns_locations\` | \`RC\` tinyint(4) NOT NULL DEFAULT '0' | \`rc\` tinyint(4) NOT NULL DEFAULT '0' |
|| \`UFI\` int(11) NOT NULL DEFAULT '0' | \`ufi\` int(11) NOT NULL DEFAULT '0' |
|| \`UNI\` int(11) NOT NULL DEFAULT '0' | \`uni\` int(11) NOT NULL DEFAULT '0' |
|| \`LAT\` double NOT NULL DEFAULT '0' | \`lat\` double NOT NULL DEFAULT '0' |
|| \`LON\` double NOT NULL DEFAULT '0' | \`lon\` double NOT NULL DEFAULT '0' |
|| PRIMARY KEY (\`UNI\`) | PRIMARY KEY (\`uni\`) |
|| KEY \`ufi\` (\`UFI\`) | KEY \`ufi\` (\`ufi\`) |
| \`languages\` | \`list_default_nl\` int(1) NOT NULL DEFAULT '0' | \`list_default_nl\` int(1) NOT NULL |
| \`parkipl\` | \`link\` (...) DEFAULT 'www.parkinarodowe.edu.pl/pn/  ' | \`link\` (...) DEFAULT 'www.parkinarodowe.edu.pl/pn/ ' |
| \`sys_logins\` | ENGINE=MyISAM DEFAULT CHARSET=utf8 | ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='login fails from last hour by IP address' |
| \`sys_sessions\` | ENGINE=MyISAM DEFAULT CHARSET=utf8 | ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='sessions of logged users' |
| \`user\` | \`password_salt\` varchar(10) NOT NULL DEFAULT '' | \`password_salt\` varchar(10) NOT NULL |
|| \`verify_all\` tinyint(1) NOT NULL DEFAULT '0' | \`verify_all\` tinyint(1) NOT NULL |

**Comment by following5** [comment]
@rapotek
> The procedure described here should be updated because http://<local_server>/okapi/devel/dbstruct?compare_to=https://opencaching.pl/okapi/devel/dbstruct returns differences for tables only, while triggers are omitted.

@deg-pl 
> I think we should update OKAPI dbstruct to show differences between tiggers also.

This has been done with https://github.com/opencaching/okapi/commit/35cf2381465f403cdca1450e112d514106f343d4.

Most differences in database structures between OC nodes are addressed by (100_init)[https://github.com/opencaching/opencaching-pl/blob/master/Utils/Database/Updates/100_init.php]. The rest is addressed in https://github.com/opencaching/opencaching-pl/issues/1899#issue-403500432.

For triggers and procedure synchronization I have opened PR #1895.
