### ISSUE TITLE
PHP fatal error regarding watchlist

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1402]
I get this in the error_log:

```
PHP Fatal error:  Cannot use isset() on the result of an expression (you c
an use "null !== expression" instead) in /serve/www/oc_ro/oc_www/lib/Objects/Wat
chlist/WatchlistItem.php on line 142
```

**Comment by rapotek** [comment]
I will take care of it in the evening. The code works in my developement and in OCPL node, so I suspect it is a matter if php version 5. Anyway it is surprising to me that `self::TABLE[$key]` is treated as an expression.

**Comment by rapotek** [comment]
@andrixnet the PR with fix has been merged yesterday at 19:30 CET. Check if the error appears in the logs now and if there are any other errors related with watchlist processing - if so I will try to look at it in the evening if I will have a time for it.

**Comment by kojoty** [comment]
@andrixnet, I assume this is done. If not please reopen.

**Comment by andrixnet** [comment]
no errors to report :-)
