### ISSUE TITLE
waypoint coords details not available

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1405]
from oc.pl forum:
> xych: 
W skrzynkach, gdzie są waypointy można kiedyś było kliknąć na współrzędne waypointa i pokazywało się okienko z tymi współrzędnymi przeliczonymi na kilka systemów. Obecnie coś jest nie tak, bo pojawia się okienko o błędzie. 
Nie jest to jakoś szczególnie potrzebna funkcjonalność, jednak jeszcze niedawno działała.

example of issue in cache: https://opencaching.pl/viewcache.php?cacheid=9763#

**Comment by harrieklomp** [comment]
I think the problem is that people cannot select en copy the coordinates and paste it in Google maps or other map. With the popup screen the coordinates where easy to copy and paste.

**Comment by harrieklomp** [comment]
I see this is about additional waypoints ;-)

**Comment by kojoty** [comment]
I removed waypoints coords format popup at all - I think this is not important feature for us - If you disagree please reopen.
