### ISSUE TITLE
Remove meta keywords

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1409]
Meta keywords are NOT used by search engines for many years. Why we still use them?

Our default keywords: geocaching, opencaching, skarby, poszukiwania, geocashing, longitude, latitude,     utm, coordinates, treasure hunting, treasure, GPS, global positioning system, garmin, magellan, mapping, geo, hiking, outdoors, sport, hunt, stash, cache, geocaching, geocache, cache, treasure, hunting, satellite, navigation, tracking, bugs, travel bugs';

**Comment by kojoty** [comment]
cool, it seems that it is right - meta-keywords are no longer needed - so let's just remove it (from settings as well).
