### ISSUE TITLE
Cache not shown on Google satellite map in tilted view

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1411]
Cache icons are not shown when displaying Google satellite layer in the map and view is tilted. Either cachemap3 or popup map on cache page.

![side-view](https://user-images.githubusercontent.com/3382777/36225286-dc9134a8-11d2-11e8-8013-5639363fb40e.jpg)
![top-view](https://user-images.githubusercontent.com/3382777/36225294-deda72f6-11d2-11e8-9847-529bfb84f141.jpg)

Either there is some limitation or trick regarding the API when it switches to tilted view, and can be worked around, or tilted view should then be disabled.

**Comment by kojoty** [comment]
@andrixnet 
I'm afraid there is no way to deal with it outside of OKAPI now (except blocking this zoom at our side).
OKAPI prepares our custom tiles which are loaded at the front of Google/Satelite/or other map tiles.
Google has higher zoom that OKAPI and it needs to be fixed at OKAPI side.

BTW. I've known about this limitation for longer time but this higher zoom is useful from time to time for me and I'm not sure if I would like to block it.

**Comment by deg-pl** [comment]
@kojoty this problem is only in "titled view". Maybe we can switch off automatic titled view at max zoom? If user wants - may manually switch this feature on.

**Comment by kojoty** [comment]
OK, I'll try to look at this

**Comment by kojoty** [comment]
@andrixnet - please check if this is requested effect. If not - please reopen.

**Comment by deg-pl** [comment]
I think this is a very good solution!

**Comment by andrixnet** [comment]
I can confirm that zooming in does not automatically switch to tilted view, thus cache icons are visible.

Tilted view (where available) remains a user selectable option.
Cache icons are still not displayed in tilted view. I'll report this to OKAPI.

Thank you.

**Comment by kojoty** [comment]
@andrixnet, I'm not sure if it has sense to report it to OKAPI - It would be really hard to prepare solution for this issue - in fact OKAPI would need to prepare special tiles with caches for such zoom in 4 kinds because tilted zoom allow to rotate to earth directions - from my point of view this is too much work. Tilted view is currently supported only by google with satellite and hybrid mode.

**Comment by andrixnet** [comment]
Wouldn't then make more sense to disable "tilted view" altogether?

**Comment by deg-pl** [comment]
NO! Please! :)
