### ISSUE TITLE
Exporting search results works inconsistently

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1416]
When performing a search, one has the option to export.
One can export either : selected caches or all caches. 

If I say export all caches and I am on page 1, I get all results exported.
If I say export all caches and I am at another page, I get only the caches from that page towards the end.
I would expect to get all caches, when I say export all caches, regardless which page i am currently displaying.
I would expect to get only the selected caches when I say export selection.

Furthermore, the information line such as: `Listing from 21 to 57: ` is behaving in the same erroneous manner as the export. 
This example is from a search that produced 57 results and I am displaying page 2, that is 20 items per page, items from 21 to 40, not 57.

**Comment by following5** [comment]
The source code looks strange:

```
    tpl_set_var('startatp1', $startat + 1);

    //if (($resultcount - $startat) < 500)
        tpl_set_var('endat', $startat + $resultcount - $startat);
    //else
        //tpl_set_var('endat', $startat + 500);
```

I guess that originally this was an export option for only the entries on the page. Then it was to be changed to "export all caches", but the change was not completed.
