### ISSUE TITLE
sizes and alignments

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1421]
![login](https://user-images.githubusercontent.com/3382777/36423142-6f51f5ac-1647-11e8-8027-dad532f62b70.jpg)

The new login buttons do not allign properly.
Tested on OCRO, languages EN, PL, NL, RO, using Firefox 52-ESR. 
On Chrome 64 and Opera 50 seems fine.

-----------
![status](https://user-images.githubusercontent.com/3382777/36423343-48fea0f2-1648-11e8-9c30-080751b6a0d2.jpg)

The new game state box set is shown as displaced the further it goes to the right. 
Tested on FF-52-ESR, reported by other user on FF-58 as well. 
Chrome 64 and Opera 50 seems fine, also smaller.

**Comment by deg-pl** [comment]
Damn - I've got FF 59 (developer) and everything works fine...

**Comment by andrixnet** [comment]
I've noticed the first one because I use FF-52-ESR (required at work).
The second I was able to confirm on FF-58 (release) as well

**Comment by deg-pl** [comment]
I've installed FF 58.0.2 and everything seems to be ok. Could you clean browser cache?
![image](https://user-images.githubusercontent.com/13884863/36424091-805c514e-1642-11e8-98c0-42fb7689b4e0.png)

**Comment by andrixnet** [comment]
Login is `<input>` while sign-up is `<a>`.
The only style that seems to affect these two elements differently is `line-height` (in the given context).
There may be additional defaults regarding <input> vs <a> that affect things, though I don't know which.

Clearing cache does not help. It is not significant, if it only affects FF-52-ESR.

The other thing, with the boxes, I can see on FF-58 as well.

**Comment by deg-pl** [comment]
I've just installed FF 52.6.0-ESR. Now I can see problem with buttons, but boxes displays OK
![image](https://user-images.githubusercontent.com/13884863/36425055-d1cd953a-1645-11e8-96a6-7a75d2904897.png)
I have no browser to reproduce problem with boxes :(

**Comment by deg-pl** [comment]
> The only style that seems to affect these two elements differently is line-height (in the given context).

@andrixnet I don't see differences in line-heigh. Could you explain me?
I converted <input type="submit"> into <button role="submit"> but without visual effects.

**Comment by deg-pl** [comment]
I've compared all styles in FF (including internal FF styles) and I find differences only in:
`text-rendering, white-space, -moz-appearance, -moz-user-select`
BUT when I set above the same for class "btn" - buttons still wasn't the same size. Has anybody any idea why buttons have different sizes?

**Comment by andrixnet** [comment]
Regarding boxes, it might be influenced by my having "large fonts" display setting. Although FF should do a uniform scaling.

**Comment by rapotek** [comment]
@deg-pl, add:
```css
.btn-sm::-moz-focus-inner {
    border: 0;
}
```
to `style-screen.css`

**Comment by deg-pl** [comment]
Qwa, @rapotek jesteś genialny.
zrobiłem .btn zamiast .btn-sm
