### ISSUE TITLE
Possible duplicates in cache_watches table

### ISSUE THREAD

**Issue by rapotek** [opencaching/opencaching-pl#1430]
I do not know yet how it is managed in PHP code, but as I checked in my dev. environment It is possible to add duplicate 'cache_id, user_id' entries to cache_watches. It may be the cause of duplicate watchlist items in the report sent by mail.

**Comment by kojoty** [comment]
OK, this is some clue.
This is query which shows duplicates in this table:
`SELECT count(*) as c, cache_id, user_id FROM `cache_watches` group by cache_id, user_id having c>1`

at prod. db it returns 382 duplicates and it's probably a cause of issue.

It would be great to review the way of using this table and remove column "id", set pair user-id-cache-id as primary key and then removed duplicates in production db.

**Comment by rapotek** [comment]
I think It is the cause and it is very easy to reproduce:

1. Open the same unwatched cache in two windows
1. Click 'Watch' in each window
1. Check cache_watches for this cache_id: there are duplicates.

I executed the runwatch processing after the procedure above and there are duplicate items in email report, as expected.

The changes operations (add to watch, remove from watch) are passed without check to okapi service where there is no check again and `insert ignore into cache_watches` or `delete from cache_watches where` only are executed.

**Comment by rapotek** [comment]
By the way: what `last_executed` column is used for?

**Comment by kojoty** [comment]
@rapotek, I'm afraid you're most known expert in this matter...
If there is no usage of this column in the current code I guess this is for nothing :)
(read: noone knows - it needs to be investigated)

**Comment by rapotek** [comment]
>  it needs to be investigated

read: drop the column and see what happens? :smirk:

**Comment by kojoty** [comment]
> it needs to be investigated
> > read: drop the column and see what happens? 😏

Nope, It means simply: it needs further investigations and after that (probably) it will be dropped because this is the next trash from the past :)

investigations means: 
- checking in current code (both OC and OKAPI) for accessing this column and sense of it if any is found
- checking in DB triggers/procedures in docs if there is anything around it

**Comment by rapotek** [comment]
@kojoty I know, it was a kind of a joke, but I still thank you for clarifying it for anyone reading :)

**Comment by kojoty** [comment]
@rapotek, widzisz ja nie piję, siedzę po nocy nad jakimś starym kodem w phpie, w wolnych chwilach szukam po lesie plastikowych pudełek i w ogóle dziwny ze mnie człowiek - wiec sam rozumiesz - nie ma się co dziwić, że niewiele kumam z tego wszystkiego co do mnie mówią normalni ludzie :)

**Comment by rapotek** [comment]
@kojoty mniej kodu, więcej pudełek - może poczujesz się mniej zakręcony :)

**Comment by kojoty** [comment]
@rapotek, chwilowo jest zimno i ciężej je znaleźć pod śniegiem

**Comment by deg-pl** [comment]
Fixed by commit cb5e34400f7d6daaf823244dd3cd8cf0e27fb8c3

@rapotek zobacz tu: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by rapotek** [comment]
@deg-pl dzięki za info, moje tytuły PR i commitów były do tej pory raczej intuicyjne. Help pozostawia trochę wątpliwości, ale to wyjdzie "w praniu".

**Comment by deg-pl** [comment]
@rapotek chodzi tylko o to, że jeśli dorzucisz np. fixes #1430 to issue się samo zamknie wrzucając automatycznie stosowne powiązanie z commitem / PRem. Ułatwia to pracę i sprawia, że w systemie nie zostają otwarte dawno rozwiązane issue.
