### ISSUE TITLE
logs autoload sometimes doesn't work?!

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1432]
from mail to RT (from: Yakub):

> Zauważyłem pewien błąd. Logi domyślnie nie ładują się przy opisie skrzynki, a dopiero przy przewinięciu do nich. Jeśli jednak opis jest krótki i całą stronę widać od razu na ekranie, to logi nie załadują się w ogóle. Jedyna opcja to: "Pokaż wszystkie" lub zmniejszenie okna przeglądarki i przescrollowanie wtedy.
> Nie jest to duży problem, ale jakbyście kiedyś poprawiali to miejcie na uwadze.

**Comment by rapotek** [comment]
Short summary in English: logs do not load together with the cache listing but only after scrolling down to them. When the listing is short and there is no scroll logs do not load at all unless 'All entries' is clicked or the browser window size is changed to smaller and then the window is scrolled down.

I can confirm the observed behavior. To reproduce f.ex. change browser scaling to smaller one (`Ctrl`+`-`) before scrolling down on any not previously viewed cache with not too long description until the whole page is visible.

**Comment by deg-pl** [comment]
Duplicate of #825
