### ISSUE TITLE
Dynamic Map is incompatibile with IE11

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1449]
JS construction for(... of...) is incompatibile with IE (any version) - see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

Such construction has been used in /tpl/stdstyle/chunks/dynamicMap/dynamicMap.tpl.php 

Problem reported by OC PL user gura11

**Comment by kojoty** [comment]
should be fixed now.
