### ISSUE TITLE
Missing setting for turning off sending emails about new caches?

### ISSUE THREAD

**Issue by rapotek** [opencaching/opencaching-pl#1452]
There was a possibility until recently (in user settings, I think) to set or unset sending emails about new caches. Now there is no such possibility neither in user settings nor in new My Neighbourhood. The only setting regarding emails is about period of sending watchlist reports.

Now I receive emails about new caches in my neighbourhood, while I do not want to have these emails sent to me. Is there any setting I do not see to turn off sending emails about new caches or there is a bug and a missing functionality?

**Comment by deg-pl** [comment]
Się pisze ;)
