### ISSUE TITLE
Wybory COG 2018 - sprawy techniczne

### ISSUE THREAD

**Issue by rapotek** [opencaching/opencaching-pl#1459]
Piszę po polsku, bo to dotyczy tylko OCPL. Rada techniczna żadnej rewolucji w serwisie z okazji wyborów do COG pewnie raczej robić nie będzie, bo i tak nie ma już na to czasu, ale może warto przygotować coś oprócz standardowej strony do głosowania. Jakieś statystyki czy coś podobnego, żeby było dostępne razem z wynikami wyborów, ucinało spekulacje itp.
Sprawa wg mnie do dyskusji, ale raczej nie takiej na miesiąc ;)

**Comment by kojoty** [comment]
ciekawe... - co miałbyś konkretnie na myśli - rozwinąłbyś wizję - chodzi o statystyki COG - typu ilość spraw etc?

**Comment by rapotek** [comment]
Nie, to akurat powinien przedstawić "odchodzący" COG na forum. Chodzi mi np. o statystyki wyborów, coś co kiedyś próbowałem przygotować w oparciu o OKAPI. Może nawet bardziej szczegółowe. Ilu było dokładnie uprawnionych, ilu głosowało, ilu oddało więcej niż jeden głos itp. Tego typu informacje, które się chyba normalnie ukazują po większości wyborów gdziekolwiek. Może macie jeszcze jakieś pomysły?

**Comment by kojoty** [comment]
aaa to może i fajnie by było kiedyś zrobić - ale to chyba w ramach "aplikacji wyborczej" - ty wiesz, że ona ma swój projekt tutaj https://github.com/mzylowski/oc-pl-elections ?

**Comment by rapotek** [comment]
Nie wiedziałem :) Ale tak czy inaczej taka informacja podsumowująca powinna być dostępna jeszcze przynajmniej jakiś czas po "zamknięciu" aplikacji wyborczej.

**Comment by deg-pl** [comment]
Ten tego... sugeruję zamknięcie tego issue. Nie ma związku z kodem OC PL. Aplikacja wyborcza to osobny kod z osobnym repo.

**Comment by rapotek** [comment]
OK, zamykam wątek. Nie myślałem o aplikacji wyborczej, tylko o czymś poza nią, ale ciągnąć na siłę nie zamierzam :)

**Comment by deg-pl** [comment]
@rapotek wybory są przeprowadzane tylko w Polsce i nic co związane z wyborami nie powinno się pojawić na tym repo, bo nie dotyczy kodu OC PL. Publikacja statystyk - czemu nie, ale nie tu.

**Comment by rapotek** [comment]
@deg-pl OK, może faktycznie złe miejsce. Założyłem issue tutaj, bo do ewentualnych statystyk konieczne byłoby skorzystanie z bazy OC. Zobaczę, może kiedyś wrzucę issue do repo oc-pl-elections. Koniec dyskusji :)
