### ISSUE TITLE
wrong links to wiki

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1463]
from oc.pl forum (autor: areckis » środa, 21 marca 2018, 12:47)

Strona newcache.php posiada trzy linki do stron w wiki, które mają coś tłumaczyć, a nie ma na nich zawartości. Są to kolejno:

- Możesz zapoznać się jak wybrać typ skrzynki, wielkość, atrybuty itp. czytając artykuł z podstawowymi informacjami.
- Czas i odległość zależą często od warunków zewnętrznych, więc jeśli nie jesteś w stanie oszacować tych danych, wpisz w powyższe pola zera. Więcej informacji znajdziesz w artykule "czas i droga". Dane te przydatne są na przykład przy skrzynkach typu multicache i wydarzenie.
- Zapoznaj się z informacją o haśle w logu.

**Comment by deg-pl** [comment]
Strona newcache jest zdecydowanie zbyt skomplikowana. Powinna mieć jeden link, a dopiero na wiki ewentualne rozgałęzienie na kolejne. Tym bardziej, że większość nodów zagranicznych nie ma tak szczegółowego Wiki.
