### ISSUE TITLE
Use a translation platform?

### ISSUE THREAD

**Issue by kumy** [opencaching/opencaching-pl#1478]
Hi there,

I've started working on the French translation. I'm used to work on translation platform such as crowdin for such contributions. Doing this in pure `php` file is a bit frustrating, no translation memory, we have to take can of correct escaping of strings…

Crowdin is free for opensource projects, we use it at GeoKrety.org and c:geo.

In order to work on French, I've temporary uploaded your `en.php` on geoKrety account https://crowdin.com/translate/geokrety/22/en-fr

I hope you'll considerate such tool! Feel free to ask for help :)

**Comment by kumy** [comment]
Link to #1477

**Comment by kojoty** [comment]
crowdin... hmm... maybe this is a good idea - I think I need to look at this closer...

**Comment by harrieklomp** [comment]
I have started a new project on https://crowdin.com/project/oc-polish-code-translations for this.  To make it free to use we need a "Project License". 
@kumy told me we can get one from https://github.com/opencaching/opencaching-pl/community. Perhaps we can use this to keep the translations online on crowdin (now it is free to use for 10 days.
The project starter can also add other people to manage this project.

**Comment by harrieklomp** [comment]
@kojoty Perhaps i can set you as manager in https://crowdin.com/project/oc-polish-code-translations. This way you can see what can be set and if this project is useful.
I think @kumy does knows more about this than i do :-)

**Comment by kumy** [comment]
I use crowdin to manage translation for geokrety.org. The process you describe is exactly the one I use. However, when new strings are uploaded, translators are automatically notified.

For the point to push back the new translations to github I've still no automatic answer for that. There is a wiki page describing the translation process for c:geo https://github.com/cgeo/cgeo/wiki/Translation-%28L18N%29 , but I still don't have took time to implement the same for GK. I actually download and commit updates manually when I'm notified of a language sync necessity.

I don't know your current process for managing translations, but how do you handle the case of a new string? Do you add it to all the languages files ? With for example in the `fr.php` file the English string as default value? How will the translators know there is some work to do ? If you add only the strings to the English file, how the translators will also know the new strings to translate ?

Crowdin should solve the last option "add only the strings to the English file" by allowing synchronization (manual or automatic) and synchronize back as a PR. - Have to study https://github.com/cgeo/cgeo/wiki/Translation-%28L18N%29

> What if I fix some translation file manually - what should I do to update translations at crowdin

When using translation platform, you must not "fix some translation file manually" anymore. You have to fix on crowdin, and commit the generated file into git.

> I guess then I need to manually upload it to crowdin (this is next additional step against current solution)

If you really have "fixed some translation file manually", then yes you have to upload the translated file to crowdin. This may eventually introduce some merge conflict.

**Comment by harrieklomp** [comment]
Because ocnl is not in sync with Github until we moved to another server, i would like to ask if another node can activate the French language. This way @kumy can see if everything is correct.

**Comment by andrixnet** [comment]
What do I need to do, besides `$config['defaultLanguageList'] `?

**Comment by harrieklomp** [comment]
@andrixnet Do you mean to activate French language?

**Comment by harrieklomp** [comment]
In your settings.in.php file you should see a line like this:

'supportedLanguages' => array ('pl', 'en', 'nl', 'ro'),

Just add "fr" to it. I do not know how much data is pulled from database.

**Comment by kojoty** [comment]
Wait guys, it's not so easy (unfortunately).
After translation of lang file it is necessary to prepare translations in DB (yeah!). There are plenty of tables when you need to add column fr and provide translations in it. 
Of course this is stupid and I believe one day we remove it but this is necessary for today.

**Comment by andrixnet** [comment]
@harrieklomp Well, I forgot all the steps I did when I first launched OCRO :-)
@kojoty : thanks, I will look it up.

**Comment by deg-pl** [comment]
Maybe it is good moment to remove all translations from database and move it into translation files?

Please don't multiply temporary solutions...

**Comment by kojoty** [comment]
I think every moment is a good moment for it. The only problem with it is simple: **this is a lot of work to do!**

Additionally this means many changes in our "old-style" code - I'm little afraid of this - it can caused many bugs. I think that we need refactoring of a few more scripts before that.

**Comment by kojoty** [comment]
@deg-pl, have you tried crowdin? There is a discussion about integration with this platform. What do you think about it?

**Comment by deg-pl** [comment]
> "The only moment when we will not have a lot of work will be the time after our death"


Author: deg, april 2018 ;)

**Comment by kojoty** [comment]
> "The only moment when we will not have a lot of work will be the time after our death"
Author: deg, april 2018 ;)

This is very pessimistic vision, especially in the Easter time :)

**Comment by harrieklomp** [comment]
I have made @deg-pl and @kojoty manager of the project on https://crowdin.com/project/oc-polish-code-translations. If you do not agree i can remove it again :-)
This way you can see what is possible and also the opportunity too read how a "Project License" can be added on https://github.com/opencaching/opencaching-pl/community.
I only ask this about the "Project License" because in 7 days the project will automatic be removed from Crowdin.

**Comment by deg-pl** [comment]
My opinion about crowdin (after some tests)
Cons:
- requires more work to mantain (but I've not tested github integration!)
- I'm used to the structure of the current file, and in the crowdin I miss a bit the grouping of strings (for example: admin_news_* in one place)
Pros:
- very good QA check! Checks case of translations, punctation, and even HTML tags! IT IS A VERY GOOD FEATURE!!! (@kojoty did you see https://crowdin.com/proofread/oc-polish-code-translations/all/en-pl + Filter -> QA Check -> All?)
- checks completeness of translations, missing strings etc.
- simple strings can be translated based on the built-in dictionary (even with match % given!) - without knowing i.e. Romanian -  I can translate strings like "Save", "Configuration" etc, Andrixnet can check these translation later
- Github integration (untested yet)

I think migration to crowdin is a good decision.

**Comment by kumy** [comment]
There is also an inline translation system.

**Comment by andrixnet** [comment]
@harrieklomp :+1: 
Please add me to translation and proofreading.

**Comment by andrixnet** [comment]
@kumy can you please add me to geokrety.org translation team for romanian? I might be able to make some improvements. Thank you.

**Comment by kumy** [comment]
@andrixnet Registrations are open for everyone, just use the "join" button on the project page. However, here is the public invitation link https://crwd.in/geokrety
Thanks for you coming contributions :)

**Comment by andrixnet** [comment]
I was reading more about integration and IMO one of the opencaching-pl project managers at Github should be the one to do the crowdin <-> github integration, as myself am only a developer. 

https://crowdin.com/project/oc-polish-code-translations/settings#integration
https://support.crowdin.com/github-integration/

**Comment by kojoty** [comment]
Colleagues,
I think we can close this issue - it seems we all want to integrate with crowdin - we only need:
- remove translations located in DB (lot of work - but it needs to be done finally)
- integrate our works with crowdin infrastructure (#1670)
