### ISSUE TITLE
php code in translation file

### ISSUE THREAD

**Issue by kumy** [opencaching/opencaching-pl#1479]
https://github.com/opencaching/opencaching-pl/blob/4c2b5b81a846d19a3bef777e1e729a8ae07ef7fb/lib/languages/en.php#L863

Are you sure about this string format? I'm disturbed by the pluses. Seems like an old php variable.

**Comment by kojoty** [comment]
Nope. This is OK. It seems that this line is passing to the JS as is, and v is a JS var - this is strange, but let it stay in this form.
