### ISSUE TITLE
Controls on cachemap3 are moving

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1489]
On all map except Google Maps zoom controls and copyright has different position than after zoom in/out of the map. It disturbs because the zoom out button appears in the place of the zoom in button (zoom controls are going up):
![image](https://user-images.githubusercontent.com/13884863/38327882-b421bdba-3849-11e8-8f68-f05f374431cd.png)

**Comment by kojoty** [comment]
sorki deg, jakoś nie skumałem o co dokładnie chodzi :)

**Comment by deg-pl** [comment]
1) Wchodzisz na mapę Cachemap3 (lub ctrl-F3) - musisz mieć ustawioną mapę inną niż mapy Google.
2) Napis z copyrightami jest w 2/3 szerokości ramki.
3) Naciskasz "+" by zwiększyć zoom
4) Napis z copyrightami przesuwa się do prawej krawędzi ramki, a kontrolki zoomu wskakują wyżej. Teraz w miejscu gdzie był "+" zoomu jest... "-" i kolejne kliknięcie w tym samym miejscu zamiast przybliżyć - oddali mapę.

**Comment by kojoty** [comment]
OK, widzę o co chodzi - ciekawy efekt :)

**Comment by kojoty** [comment]
It should be fixed now. @deg-pl, please reopen if needed.
