### ISSUE TITLE
Weather function in map v3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#149]
```
In "followed caches on a map" there is that very nice weather function. Can 
this function also be made in cachemap v3?
There is no other cachingsite who has this function. So why not show this on 
cachemap v3 :-)

Greetings,
Harrie

```

Original issue reported on code.google.com by `henricus...@gmail.com` on 24 Jul 2014 at 9:58

**Comment by harrieklomp** [comment]
"Note: The Weather and Cloud layers have been deprecated as of June 4, 2014. They will cease functioning on June 4, 2015."
This means that the weather layer is not available anymore.

**Comment by miklobit** [comment]
Very nice wether map layers are avaialble free of change (up to 60 request/min) from
http://openweathermap.org/weathermap

**Comment by andrixnet** [comment]
Perhaps a future enhancement.

**Comment by kojoty** [comment]
I see two problems: 
- first I'm not sure if this is correct to add too many complicated layers to our map - we are service for geocachers - not a service with a weather forecasts - if anyone is interesting in a weather there are many better pages which provide such data

- second - details of  http://openweathermap.org/weathermap API regulations: 

> What happens when your account exceeds a limit of calls
> We accumulate the total number of calls from all the API keys that belong to your account.
> When your account exceeds the limit, we do not block your account immediately but send you an automatic notification by email asking you to switch to one of our paid subscriptions within the reasonable term. If we do not get any feedback from you, we suspend your account.

I understand that it will not take a long time for us to get our account useless.

I don't know any source of a free weather data for us.

I'm closing this issue - please reopen if disagree.
