### ISSUE TITLE
Extra " \ " in translation via Crowdin

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1494]
When translating the lines "alert_search_by_dist_01" and "alert_search_by_dist_01" via Crowdin there is automatic a extra " \ " added in translated line. This is visible when downloading the translated language file.

![selectie_162](https://user-images.githubusercontent.com/1060518/38676881-ba8b3ef6-3e5c-11e8-8c9a-25cd7c6bf1db.png)

Can this be solved somehow? I do not know what happens what this extra backslash will do when uploaded in code.

**Comment by harrieklomp** [comment]
In English source file the original line is:
'Longitude degrees must be numeric!\nFormat: ddd mm.mmm'

Is it possible to replace the `\n` for `<br />` ?

**Comment by following5** [comment]
`<br />` won't work, but there are other options to fix this:

1. Replace it by a space. The message then will apear in one line instead of two.
2. Do [this](https://github.com/opencaching/opencaching-pl/commit/514fa7fafc949684dba8d383b18fbcd612db5d73).

Even better would be to fix this Crowdin bug - there should be no \ inserted here.

**Comment by following5** [comment]
The English strings on Crowdin don't have the double \\\\, so the \ is inserted on download.

How do you do the download? I tried it [here](https://crowdin.com/project/oc-polish-code-translations/de#), and then I get a de.zip file which only containts the English en.php ?! If I can reproduce the problem, I would send a bug report to Crowdin.

**Comment by harrieklomp** [comment]
First i go to [here](https://crowdin.com/translate/oc-polish-code-translations/3/en-nl#q=ongitude+degrees+must+be+numeric%21) and select "Other languages" and look witch language has this "\n" translation.
![selectie_268](https://user-images.githubusercontent.com/1060518/50561281-7d537900-0d09-11e9-9f40-526be4286313.png)

Than go to for example to Romanian translation and select Download from dropdown menu.
![selectie_269](https://user-images.githubusercontent.com/1060518/50561309-c0155100-0d09-11e9-9f58-5ecd12aaeeec.png)

Open or safe this file and look for "alert_search_by_dist_01"
![selectie_271](https://user-images.githubusercontent.com/1060518/50561363-3a45d580-0d0a-11e9-88c9-22e9a5ed07e7.png)
![selectie_270](https://user-images.githubusercontent.com/1060518/50561365-42057a00-0d0a-11e9-9b7a-2560b675f1af.png)

**Comment by following5** [comment]
Crowdin support has confirmed the bug and promised to fix until January 11 (developers are on holiday until Jan 7).

**Comment by following5** [comment]
(But I don't think we need to wait for that. Space is fine.)

**Comment by harrieklomp** [comment]
Is solved now by remove `\n` and add a "space".

**Comment by following5** [comment]
Can we keep the \n in English strings and Romanian translations, until Crowdin has fixed the bug? I gave them Romanian as example. So that Crowdin developers can reproduce our problem (and don't think it is already solved), and we can confirm that it is fixed.

**Comment by following5** [comment]
Thanks!

> We must NOT move this Romanian translation from Crowdin to GIT because i do not know what will happen!!!

The \\\\n needs to be changed manually when transfering Romanian to Git, until the crowdin bug is fixed.

**Comment by following5** [comment]
Here is another one: https://crowdin.com/translate/oc-polish-code-translations/3/en-pl#q=empty_entry_confirm

This \\n issue must be fixed before enabling automatic crowdin downloads. Crowdin team informed me on 8 January that they have started working on this.

**Comment by following5** [comment]
I will instruct Crowdin support that we do a workaround by temporarily removing the \\n, so that we can go on, but that it still needs to be fixed.
