### ISSUE TITLE
Attend event in future

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1502]
Perhaps it could be possible not to show logtype(s) "Attended" and/or "Maintenance performed" for a event before event has taken place.
Only "Comment" and "Will attend" should be visible.

![selectie_167](https://user-images.githubusercontent.com/1060518/38938245-5ff470e8-4325-11e8-9f10-dbeb6d3a654f.png)

**Comment by andrixnet** [comment]
And "Will attend" should exist only <= event date, not after. :-)

**Comment by mzylowski** [comment]
Similar check like in #1649 can be also added to OKAPI. Currently I don't have idea how to debug level 3 auth method on devel environment, so I can't prepare OKAPI fix. @following5

**Comment by following5** [comment]
You can debug level 3 methods by temporarily adding the DEBUG_AS_USERNAME option. E.g. for debugging logs/submit, change [this line](https://github.com/opencaching/okapi/blob/master/okapi/services/logs/submit/WebService.php#L29) to

``            'min_auth_level' => 3, 'DEBUG_AS_USERNAME' => 'mzylowski'``

or whatever your OC username is.

**Comment by following5** [comment]
> And "Will attend" should exist only <= event date, not after. :-)

An event may take more than one day, e.g. a weekend or even a whole week. What should be the deadline for logging "Will attend"?
