### ISSUE TITLE
Incorrect GPX export while cache has ampersand in GC waypoint

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1503]
If cache has ampersand in GC waypoint:
![image](https://user-images.githubusercontent.com/13884863/38955229-4d9f07b2-4354-11e8-9653-6d546d55e6cc.png)
exported GPX is not valid XML:
`<oc:other_code>GC7GH&E</oc:other_code>`

Todo
- [ ] validation format of additional waypoints while user edits cache
- [ ] properly escape ampersand sign in GPX export

**Comment by andrixnet** [comment]
Validation is a must. 
But is & really a valid character in waypoint code?

Btw, http://coord.info/GC7GH&E yields geocaching.com 404 page.

**Comment by deg-pl** [comment]
No - valid GC waypoint in this case is GC7GH7E

**Comment by andrixnet** [comment]
Then in this case it is a user error typing the code. 
IMO data validation should be done on cache edit page to ensure data is entered correctly, then GPX (and other exports) will work properly.

**Comment by following5** [comment]
> properly escape ampersand sign in GPX export

Better remove invalid characters. GC codes must only consist of 0-9 A-H JK MN PQR T V-Z

These may be mapped:
* I => J
* L => J
* O => 0
* S => 5
* U => V

**Comment by following5** [comment]
Bad GC waypoints now are omitted from GPX.
