### ISSUE TITLE
COG annotations not visible in C:GEO

### ISSUE THREAD

**Issue by DorotkaMakotka** [opencaching/opencaching-pl#1504]
It would be desirable to include COG annotations (or other additional fields) in cache description displayed in C:GEO.

**Comment by DorotkaMakotka** [comment]
Sometimes COG annotations determine the conditions that need to be fulfilled to legitimately mark the cache as found. This applies e.g. to virtual caches where a photo is required - according to COG decision. Unfortunately it turned out that C:GEO users don't know about these additional conditions. It is still recommended for such annotations to remain logically separated from owner's description.

**Comment by deg-pl** [comment]
This is not related to OC PL code, but OKAPI code. Please - report it here https://github.com/opencaching/okapi/issues

**Comment by DorotkaMakotka** [comment]
OK, done (https://github.com/opencaching/okapi/issues/533). I'm closing this issue, sorry for confusion :)

**Comment by following5** [comment]
What's a COG annotation, and where is it stored in OCPL database? What additional fields would you like to include?
