### ISSUE TITLE
Code directories reorganization

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1513]
I think one day we can try to reorganize the directories structure - I mean:

- /lib/Objects -> /Objects (or maybe /Models)
- /lib/languages -> /I18n
- /tpl/stdstyle -> /Tpl (or /Tpls or maybe /Views)
- /Config -> /Configs (if we decided that plural form is a default)

and maybe also:
- /docs -> /Docs

other ideas?

I believe we can move files by "rename" in git so the history of the source code should be saved.

I assume that it will be moved in cooperation with other works to not force you to make "massive merge" of current works in a comfortable moment for all of us.

What do you think about that?

**Comment by deg-pl** [comment]
Yeah! We should have /public with all files that should be publicly available. I mean: JS's, CSS's and router code + old php's.
**Config files**, controlers, models, views SHOULD NOT be publicly available!

**Comment by rapotek** [comment]
docs (or Docs) and sqlAlters should not be publicly available as well.
Most of my former applications were organized in a way: under main path directories js, css etc., index.php file and the application directory unavailable outside where the whole code and logic was placed.

**Comment by kojoty** [comment]
OK, so lets think about the "new" structure:

```
/public ( what actually should be here?)
   /images
   /lib (but for hosted JS libs only + some common use JS files)
   /tmp (our "dynamic" folder with files created by service with correct .gitignores - but I think that the 
             folder structure can be in repo ?)

/app/
  /Configs
  /Controllers
  /Models
  /Utils
  /Libs
  /Docs

/okapi 
/vendor (composer ?)  
/<all-the-old-stuff> 
```
Open questions for me:
- where is a place for views/templates - all the stuff from /tpl/stdstyle: there are both static *.css/*.js but also *.php scripts - do you want to have css in /public/... and php in /app/Tpls (or views) ? - whats your opinion?

**Comment by deg-pl** [comment]
Hmm... Maybe "dynamic" folder can be in repo - it is good idea, but "tmp" is not good name. Files stored there aren't temporary!

Yes - /vendor should stay in root folder

/tpl/stdstyle should be /app/View structure BUT .css/.js should be in /public/css|js

**Comment by kojoty** [comment]
> /tpl/stdstyle should be /app/View structure BUT .css/.js should be in /public/css|js

...and that's what I don't like - now I have files of the page in two dirs:

/Contollers + /tpl/...
after such change I get four dirs:
- /app/Controllers
- /app/View
- /public/js
- /public/css

The only profit is hiding php scripts - what in fact is not a great thing - in the prince of more complicated structure

**Comment by kojoty** [comment]
I found the nice inspiration - take a look:
https://github.com/php-pds/skeleton

**Comment by kojoty** [comment]
Code structure is mainly done - some of scripts are still old directories - but it needs more time to move it to the new places (as this is much more complicated). I close this issue.
