### ISSUE TITLE
Multiple "attended" logs

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1518]
If user submit "attended" event log, user can next click back in browser and resubmit next "attended" log:
![image](https://user-images.githubusercontent.com/13884863/39418836-e4d55d6e-4c5c-11e8-8447-08cd1578f03f.png)
This doesn't work with "find" logs

**Comment by rapotek** [comment]
@deg-pl miało Cię nie być... :smirk:

**Comment by deg-pl** [comment]
Na chwilę przyjechałem z pewnego eventu (na którym Kardwo walczył i zalogował go w walce 3 razy - stąd issue) i za 3h jadę dalej na kesze. Tym razem tak szybko nie wrócę ;)

Z tego co pamiętam - nad logami siedzi @kojoty . Więc jeśli chcesz - zrób szybką łatę na razie, a głębszy refactoring omów z Kojotem, żebyście dwukrotnie tego samego kodu nie pisali ;)

**Comment by kojoty** [comment]
ja jeszcze nie skonczylem obrazków - też czasem muszę coś w terenie złapać i do tego jeszcze córka ma wolne wiec okupuje mój komputer całą dobę (wiedzmin 3- kto grał ten chyba rozumie) - ale logi będą następne w kolejce - bo też są mi potrzebne (jak już czasem pisałem) do remontu geościezek.

**Comment by rapotek** [comment]
To mam wrzucić tego fast fixa? To jest raptem kilka linijek

**Comment by kojoty** [comment]
jak masz gotowe to wrzucaj - bez problemu.
