### ISSUE TITLE
Multiple opencaching-pl instances cannot be hosted on the same server

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1521]
Apparently two or more instances of **opencaching-pl** code cannot run simultaneously on the same server because some caching machanisms overlap.

At least "newest caches" section on homepage is cached as a code fragment under filesystem /tmp, rather then oc-dynamic/tmp.
This results in one instance displaying cached data generated by another instance.

I have created two instances, one for OCRO, one for OCNL, as tests here: 
http://ocro.dev.andrix.eu/
http://ocnl.dev.andrix.eu/

Another one for OCUS will follow. 

I believe it can be a real scenario that two OC instances be hosted on a single server at a point in the future.

**Comment by andrixnet** [comment]
There is a `tmp/` directory defined under oc-dynamic in settins.inc.php. It could/should be used for such operations.

**Comment by deg-pl** [comment]
Reopen. OcMemCache is incompatibile with multiple OC instances on simple machine.
const OcMemCache::KEY_PREFIX should be configurable / related with site name (@kojoty)

**Comment by kojoty** [comment]
@deg-pl myślę, że można dodać po prostu konfigurowalny prefix (z configs) dokładany do nazwy klucza, pusty jako default...

**Comment by deg-pl** [comment]
Ok. Done (after merge).
