### ISSUE TITLE
Map v3 enhancements

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#153]
I'd like to request several enhancements on Map v3: 

- [x] adjust CSS in cache popup baloon: title is too large

- [x] adjust popup baloon size: too small if cache name spans 2 lines, and overall 
could be a bit larger vertically

- [ ] make a way to be able to open very closely located caches. In the screenshot 
there are 2 caches, but only one is openable here.
(either split cache icons on mouse over - google earth style, 
or
put next/previous in popup baloon to be able to traverse the list or caches to 
close to be clickable separately)

- [ ] swap cache icons (or icon overlays) for archived and disabled: 
disabled to have a black "X" and archived to have the red "X" perhaps modified 
to have the entire icon crossed out. Now these two are too similar and easily 
confusable. 

- [ ] make ESC key be a shortcut to close the popup baloon

- [ ] add OpenStreetMap layer to the map.

- [ ] make available layers choosable via settings.inc.php
(OSMAPA and UMP useless outside Poland)

Original issue reported on code.google.com by `andrixnet` on 5 Aug 2014 at 7:46

Attachments:
- [mapv3.png](https://storage.googleapis.com/google-code-attachments/opencaching-pl/issue-153/comment-0/mapv3.png)

**Comment by kojoty** [comment]
I reedited the original list - checkboxes were added

**Comment by kojoty** [comment]
some of request done - the rest are still open...
