### ISSUE TITLE
APCu and OCNL

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1532]
In https://github.com/opencaching/opencaching-pl/commit/d0a4817db02b28cff2d6bd95cc21a520275bece0 there was a modification for older PHP because ocnl was not up to date with PHP7
Now ocnl is up to date there could be removed some lines. I do not exact know witch lines, so i leave it up to the programmers :-)

BTW. This could solve the not loading pages on ocnl: 
http://www.opencaching.nl/articles.php?page=s2
http://www.opencaching.nl/articles.php?page=s7
http://www.opencaching.nl/articles.php?page=s8

**Comment by deg-pl** [comment]
Have you installed php-apcu-bc?

**Comment by kojoty** [comment]
@harrieklomp, can you just paste here the lines which appears in apache error.log after enter to http://www.opencaching.nl/articles.php?page=s2

**Comment by harrieklomp** [comment]
@Andrixnet did find some time to move ocnl to another server last week. Perhaps this could be forgotten to install. I notified him about this issue and perhaps he can make some time to install this.
It is not critical, like s7 and s8 the data on those pages is only Polish related. Hardcoded "pl" and "PL".

**Comment by andrixnet** [comment]
```
/etc/php.d/apcu.ini                                    79/79                100%
extension=apcu.so
apc.enabled=1
apc.shm_size=32M
apc.ttl=7200
apc.enable_cli=1
```

**Comment by andrixnet** [comment]
@deg-pl I did not know apcu_bc is a requirement.
I'll try to see to it tomorrw afternoon.

**Comment by deg-pl** [comment]
@andrixnet compiled? On Debian/Ubuntu system should be enough to install via apt:
`sudo apt-get install php-apcu-bc`

Check if you have:
```
extension=apcu.so
extension=apc.so
```
in PHP configuration (i.e. 20-apcu.ini and 20-apcu_bc.ini in /etc/php/7.1/fpm/conf.d/ . You may have "apache" instead of "fpm")

**Comment by deg-pl** [comment]
@andrixnet could you paste OC NL phpinfo() output?

**Comment by andrixnet** [comment]
@deg-pl: Distro is not Debian/Ubuntu, but Slackware, so the package had to be built from source.
I've added the necessary configuration files, but overlooked a detail described here: 
https://github.com/krakjoe/apcu-bc/issues/9

After correcting the load order, the 2 pages s2, s7, s8 work.
Tested first here: http://ocnl.dev.andrix.eu/articles.php?page=s8
Then on production.

So, in conclusion: 

**opencaching-pl requirements:**
- php-apcu
- php-apcu-bc

@harrieklomp issue solved on OCNL (non-working pages). 
@harrieklomp please open a different issue for the hardcoded `PL` references on those same pages.

**Comment by andrixnet** [comment]
Thank you @deg-pl for your support.

**Comment by deg-pl** [comment]
@andrixnet @harrieklomp We have issue for harcoded PL strings in stats - https://github.com/opencaching/opencaching-pl/issues/723 and others
