### ISSUE TITLE
What happens if you paste another log code into log...

### ISSUE THREAD

**Issue by rapotek** [opencaching/opencaching-pl#1543]
An example from production env. (OCPL):

![log_in_log](https://user-images.githubusercontent.com/17698165/40326557-f2b0ce34-5d3f-11e8-83cc-84b0f240eb35.png)

Corresponding html code fragments (unnecessary items removed):
```
<div class="logs" id="log2769528">
    <p class="content-title-noshade-size1 ">...</p><p>  </p>
    <div class="viewcache_log-content ">
        <div id="viewcache-logs" class="content2-container">
<div id="log2752678" class="logs">
<div class="viewcache_log-content ">
<p>Bardzo dziękuję za pokazanie kolejnego detalu architektonicznego. Z (...), majówka 2018 :)</p>
</div>
</div>
</div>
        
    </div>
</div>
```

This example does no harm except slight visual effects but I suspect there is a possibility to do a lot more, f.ex. to make the whole cache page unreadable.

**Comment by mzylowski** [comment]
On current tinyMCE version and my chrome (Version 68.0.3440.106 (Official Build) (64-bit)) i can't reproduce this.

I believe this is fixed by @deg-pl and PR #1110.

**Comment by kojoty** [comment]
@rapotek, please check if this still an issue... Thanks!

**Comment by rapotek** [comment]
@mzylowski paste the example code as 'source code' (the '<>' button) - I think the cited above log entry was created this way.
You can easy make f.ex. the whole page unclickable by one log entry. The solution preventing this may not be a piece of cake.

**Comment by rapotek** [comment]
Closing for now, can be reopened when major log edition changes are made.
