### ISSUE TITLE
filtrowanie geoŚcieżek zdobytych i/lub posiadanych 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#155]
```
(You can use Polish or English, whichever you think is better.)
Witam:)
Jaka są możliwości techniczne aby nie wyświetlały się ikonki na mapie 
geościeżek te, które są już przez użytkownika zdobyte lub których jest 
założycielem? Można by zrobić opcje wyboru tak jak na ogólnej mapie 
skrzynek.
pozdrawiam
atena.pl
```

Original issue reported on code.google.com by `atenakat...@gmail.com` on 6 Aug 2014 at 6:38

**Comment by mzylowski** [comment]
@deg-pl 
I have hope you don't joke about virgins... :P

We have a lot of geopathes in few regions in Poland and sometimes is very difficult to searching geopathes on map. So I increase priority of this issue.

**Comment by mzylowski** [comment]
TODO:
-> Hide new part of panel for not logedin users
-> Move 'show also mini power trails' on the top of the list
