### ISSUE TITLE
geocache reactivation rules defied by author 

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1555]
There is a simple idea:

- define additional text-box in cache description to define reactivation rules defined by author of geocache - different man has different approach in this matter

- this text can be "automagically" concatenate to the cache description (let's say at the end of desc.)

from email:

> Na skutek ostatnio rozgorzałych dyskusji na temat reaktywacji skrzynek pojawiły się różne propozycje w tym względzie:
> - atrybut, 
> - dodatkowy dopisek.
> Pierwsze rozwiązanie byłoby widoczne jednak mało elastyczne i stwarza problemy np. z OKAPI. 
> Drugie rozwiązanie wydaje się lepsze. Pytanie czy jest możliwe wykonanie tego pomysłu w postaci nieobowiązkowego pola, pojawiającego się do wypełnienia przed polem kodowanym. Natomiast w opisie jeśli ktoś wypełnił pojawiłaby się informacja o reaktywacji (np. nie życzę sobie, reaktywacja tylko po kontakcie, warunki reaktywacji itd).
> Ewentualnie zmienić opis sekcji kodowanej na: 
> Podpowiedź / Opis zasad reaktywacji -  informacje będą kodowane: 
> 
> Dodatkowe pole byłoby znacznie bardziej eleganckie, Zmiana opisu dla Was pewnie jest trywialna.
> Proszę o informację czy jest to wykonalne.
> 
> Pozdrawiam Paweł / brasia / COG

**Comment by deg-pl** [comment]
Jestem przeciwko tej funkcjonalności. Utrudni zakładanie keszy dla poczatkujących, skieruje ich tok myślenia na zupełnie niewłaściwe tory, skupi jeszcze więcej ludzi na reaktywacjach. A obecnie jeśli ktoś chce - może dodać politykę reaktywacji do opisu kesza. Nie komplikujmy serwisu bez sensu. Moim zdaniem ta zmiana jest szkodliwa dla OC.

**Comment by deg-pl** [comment]
"Większość członków COG" to 7 osób. Społeczności jest znacznie więcej + nody międzynarodowe. Nie utrudniajmy ludziom zakładania i edycji skrzynek. Niedługo pól będzie tyle, że trzeba będzie dołączać wielostronicową instrukcję jak prostą skrzynkę założyć.
GC na dzień dobry ma przyjemny opis z pierwszymi krokami zakładania skrzynek, OC ma straszący regulaminem i konsekwencjami elaborat. GC ma prosty kreator prowadzący za rękę, my mamy formularz z... 61 różnymi polami i przyciskami. POLICZCIE! SZEŚĆDZIECIĄT JEDEN! Bardziej skomplikować się nie dało, a teraz jeszcze zupełnie bez sensu kierujemy uwagę nowych na problem reaktywacji. Będzie mniej keszy i więcej reaktywacji.
OC przypomina coraz bardziej twór komunistyczny. To cudowny COG wie co dla ludzi najlepsze. Jak będzie najprzyjemniej. Jak będzie najbezpieczniej. Zdanie Społeczności jest nieistotne. Odczucia nowych keszerów - po cholerę z nimi się liczyć. Naważniejsze, żeby nieomylny, reprezentujący absolutnie wszystkich keszerów COG wydał decyzję i wszyscy bili brawo.

Proszę pamiętać, że ta zmiana pociąga daleko idące zmiany również w OKAPI i aplikacjach zaleznych typu c:geo, czy Locus. Czy z twórcami tych aplikacji zostało uzgodnione, że coś wiecej będziemy im serwować a oni powinni to pokazywać? Bo jak nie, to psu na budę takie zmiany gdy będą niewidoczne.

Cholernie uszczęśliwianie keszerów na siłę. Nikt obecnie nikomu nie zabrania wpisać polityki reaktywacyjnej w treść. Ktoś to MOŻE dzisiaj zrobić. Nowy feature utrudnia działanie OC.

**Comment by kojoty** [comment]
@deg-pl, 

a/ chyba cię lekko poniosło - publiczny github to chyba jednak nie miejsce na wylewanie żółci
b/ mam wrażenie, że COG generalnie chce dobrze i porównywanie go do "tworów komunistycznych" jest  chyba lekko krzywdzące
c/ z pewnością warto dyskutować, ale spróbujmy być jednak merytoryczni
d/ moim zdaniem technicznie da sie to może (?) zaimplementować jako "doklejkę" do opisu dla OKAPI (podobny problem to o ile pamiętam notatka COG do kesza)
e/ co do "skomplikowanego" interfejsu -  no pewnie trzeba to uprościć - poza wszystkim - co nie zmienia sprawy, ze być może takie pole mogło by się tam znaleźć

**Comment by deg-pl** [comment]
Odniosę się tylko do "d", bo tylko ten punkt był merytoryczny w temacie.
Jeśli mielibyśmy cokolwiek doklejać to po jaką cholerę rozdzielać coś w edycji, by sklejać w wyświetlaniu? Ta zmiana szkodzi OC i nie niesie ze sobą żadnych korzyści!

Ja rozumiem, że jeden z COGowiczów usiłuje zalegalizować fakt, że reaktywuje kesze ekstremalne (trudność terenu 5) pudełkiem po okularach pod drzewem (byłem, widziałem, zdobyłem tego kesza). Ale to nie powód, by dla chorych działań pewnego COGowicza naciągać cały system.

**Comment by rapotek** [comment]
Z całym szacunkiem, ale też jestem zdania, że to nie jest miejsce na tego typu dyskusje. @deg-pl jedyną kwestią niemerytoryczną, którą można spróbować wyjaśnić tutaj jest stosunek naszych zagranicznych kolegów do proponowanych rozwiązań. Cała reszta już się chyba pojawiła u nas na forum

**Comment by kojoty** [comment]
I close this issue and open the new one #2295 to have a clear definition and the history of the change
