### ISSUE TITLE
Github update notification

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1558]
@ project manager: 

Please update push notification of Github master branch update for OCNL and OCRO as such: 
https://www.opencaching.nl/post-commit.php
https://www.opencaching.ro/post-commit.php

Both sites have recently switched to HTTPS and apparently the Github robot does not follow HTTP redirects.

**Comment by kojoty** [comment]
I updated both nl and ro to https.

**Comment by kojoty** [comment]
@andrixnet, please open if this is still an issue.
