### ISSUE TITLE
Incorrect event attenders count

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1559]
![image](https://user-images.githubusercontent.com/13884863/41199880-0d971398-6c9a-11e8-9bc8-ea50f14d26e8.png)
On cache page sometimes number of attenders is displayed incorectly. Maybe when user deletes "will attend" log, attenders counter is not decreased?
In "The list of participant" counter works OK.

PS: Translated word "Number" in Participant list is not a good translation. In polish "liczba" is OK.

**Comment by deg-pl** [comment]
This is not a problem with delete log. User can add multiple "will attend" log:
![image](https://user-images.githubusercontent.com/13884863/41200672-b244b5ee-6ca9-11e8-986f-b650f8456551.png)

**Comment by kojoty** [comment]
robiąc jakiś refaktoring logów trzeba zwrócić uwagę na dokładną kontrolę, bo podobnie widziałem przypadek gdzie sa dwa wpisy znaleziona

logi typu: znaleziony, nieznaleziony, uczestniczył, zamierza uczestniczyć powinny być tylko w jednym egzemplarzu

**Comment by deg-pl** [comment]
Nieznaleziona powinna być logowana wielokrotnie!

Co do "uczestniczył" i "znaleziony" - jest zabezpieczenie w kodzie. Dorzuciłem "zamierza uczestniczyć" i trochę poprawek robię. Choć generalnie ten cały kod jest do zaorania.

**Comment by kojoty** [comment]
to może jeszcze weź przeczesz bazę logów - powinno chyba być dość łatwo wyłowić takie duplikaty - i może od razu by je usunąć.

**Comment by deg-pl** [comment]
Przy okazji zaorałem revertlog. Przez revertlog można było przywrócić np. dowolną ilość logów "znaleziona" - system wcale tego nie sprawdzał.
