### ISSUE TITLE
Using GET requests for changing the state?

### ISSUE THREAD

**Issue by okainov** [opencaching/opencaching-pl#1593]
Sorry if my question is stupid or was answered somewhere, but I just wonder, is it normal\expected that you use GET requests even for changing the data?

I.e. in [mywatches.php](https://github.com/opencaching/opencaching-pl/blob/master/mywatches.php) or for ignoring caches - wouldn't it be more correct from ideological point of view to have POST there? Were there any reasons to use GET?

**Comment by kojoty** [comment]
Hi,

Right, from ideological point of view you're right, but please notice that current open aching code is not REST API - we are currently somewhere between spaghetti and old-style php MVC-like with little JS usage for selected actions.

Mywatches is called directly by browser like mywatches/map and we need simple URL to display it. 


Of course I agree that simple php API + JS client in browser is better solution but there are so many reasons why we are not in this point. We have many ideas how to deal with our code but it needs lots of resources (our time) to reimplementing whole stuff in working application. 

If you have any specific idea how to develop OC code we are open to discuss :)
