### ISSUE TITLE
When no translation, use English translation

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1594]
Because programmers always use English and Polish, so why not use automatic English translation when there is no other translation available?

When translating hardcoded (Polish) parts we always need to translate and add strings in all available language files. This problem is also when adding new code with translations.
When there is a string missing in a language the line "No translation available (identifier: this_is-a_translation-line)-todo" shows up.

This means less work for programmers when translating and less mistakes between different language files because programmers only use these 2 languages. Also programmers do not need to wait for other translators.
When new strings are added into "en.php" i upload it to Crowdin (can be done automatic) and every translator can see the new strings without scrolling all the way down in the specific language file.

**Comment by kojoty** [comment]
I agree - we should rewrite translations according to this idea
