### ISSUE TITLE
Users with own API key for Google Maps

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1598]
Could it be possible for users to use their own Google API key to show Google Maps on OC?

A personal API key could be stored is user profile (like GeoKrety Secid) and use this API key via/with cookie.

**Comment by deg-pl** [comment]
I think it breaks Google API terms (but I'm not sure ;) )

It is also extremly uncomfortable. First - for us - we have to support TWO DIFFERENT JS map engines. Second - for users - we have 39000 users monthly. Obtaining Google API Key is not easy for every of them and may require credit card number.

**Comment by kojoty** [comment]
hi Harrie, 

I'd like to avoid such solutions if I understand well what you mean. 

First, do you mean that enduser has "its own" google API key - general idea is that API key from Google is per service / site / domain - not for personal use of end-user. I'm  even not sure if this is legal from Google regulations point of view.

Second, I would prefer to skip usage of Google Maps at all - support for Google API means that we need to support two different maps API: openlayers and Google - I think this is too much for us. This is not like usage for example BIng maps where we can use its tiles from openlayers API - Google has a point in their licence that it's tiles can be use ONLY by its API - so to use it we need to support its API (much of different JS code etc.)

**Comment by harrieklomp** [comment]
Okay., is clear :-)
Thanks.
