### ISSUE TITLE
Map v4 - scale indicator, coordinates, buttons

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1611]
- [x] scale indicator
The scale indicator is a bit chunky visually. 
Too thick, too big, IMO.
It is useful, but it also could be more discreet.

- [x] coordinates display
This is a very useful feature. I would suggest a slightly translucent background to the box.

- [x] top left buttons - refresh
Fullscreen button is ok.
Refresh map button has some visual issues. It's contour isn't properly drawn for transparency/shadow.
Also, this button has no effect on some caching done server-side, so a new cache or changed coordinates are not displayed when requesting this refresh. 
From user point of view, this is wrong.

- [x] top left buttons - my location
The button is ok visually, but once pressed, apparently it cannot be unpressed. 
Also, there is no _apparent / intuitive_ way to control the radius it displays and it's meaning.

- [x] top left buttons
The background of the box containing these buttons could be made slightly translucent.

**Comment by kojoty** [comment]
@andrixnet I hope I fixed everything from this list - if you have any comments please reopen.
