### ISSUE TITLE
Site not secure - images delivered via http

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1618]
Since the move to secure connection, there are parts of the site that are still loaded via insecure connections. 

Images inserted into cache descriptions from third party hosting generate such warnings, but this is normal behaviour. This is not the purpose of this issue.

Several resources are still loaded via HTTP links on OCNL homepage: 

https://www.opencaching.nl/
![ocnl-secure](https://user-images.githubusercontent.com/3382777/45359027-f6e91f00-b5d3-11e8-874a-94f40ce35d1f.png)

**Comment by kojoty** [comment]
@andrixnet - it needs to be reviewed if the protocol (http) is hardcoded in the code or config or maybe even .htaccess files - if you would like to take a look at this feel free to post a PR with the fixes.

It seems to be quite easy to fix.

**Comment by deg-pl** [comment]
I think it is not code issue.
I think you have http in url of geopath's images stored in DB. Try:
SELECT `image` FROM `PowerTrail` WHERE 1
and check it please (and close this issue ;) ).
If geopath was created before your site has https - geopath may have http URL stored in DB

**Comment by harrieklomp** [comment]
deg-pl is correct.
All image links stored in DB before introducing https are stored as http. This is in tables "geopath" and "pictures".

**Comment by andrixnet** [comment]
It would have been best to correct this with an SQL file shared in /sqlAlters. 

On the other hand, the issue persists, more tables might be involved. 
TinyMCE smileys for example:
http://www.opencaching.nl/lib/tinymce4/plugins/emoticons/img/smiley-wink.gif
at least in logs, likely in cache desc as well. 

I will try to take a more detailed look the next few days.

**Comment by deg-pl** [comment]
Please don't create any public sqlAlter.
Change in DB is individual in each OC site.

**Comment by mzylowski** [comment]
Is there anything 'todo' in the opencaching code? All your issues seems to be "administration" and "configuration" topics. Please reopen if needed.
