### ISSUE TITLE
OKAPI update process

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1619]
OCPL needs new OKAPI update procedure.

Previously it works based on script calling for OKAPI github at private wrygiel's server, which update OKAPI code in OCPL code (https://github.com/opencaching/okapi/blob/master/etc/webhooks/postcommit.py). Now it's not work.

New way of dealing with it needs to be prepared.

Maybe OCPL can use mechanism similar to OCDE where OKAPI is taken by composer.

context: https://github.com/opencaching/opencaching-pl/pull/1617

**Comment by kojoty** [comment]
composer config: https://github.com/OpencachingDeutschland/oc-server3/blob/development/htdocs/composer.json

**Comment by kojoty** [comment]
how OCDE solve problem of moving OKAPI to composer /vendor:
https://github.com/OpencachingDeutschland/oc-server3/tree/development/htdocs/okapi

**Comment by mzylowski** [comment]
Example commit generated by ocpl-robot related with OKAPI update: https://github.com/mzylowski/opencaching-pl/commit/0c8bf82248add3852748b061d1015ba2a80d15ef

Still some improvements are required - for example OKAPI version generation

**Comment by mzylowski** [comment]
Requirements:
- [ ] vhost configuration @deg-pl (check mail)
- [ ] ocpl-robot invitation to opencaching organization / organization owner change (@wrygiel), please check email
- [ ] webhook configuration in okapi repository @following5 (please wait for my 'all green' sign)

**Comment by deg-pl** [comment]
@mzylowski I've added ocpl-robot into OC-PL collaborators and I've configured vhost (as I mentioned in mail).

**Comment by mzylowski** [comment]
@following5 
Hey! Our mechanism for okapi updating seems to work fine with my fork (https://github.com/mzylowski/opencaching-pl/commits/master)

Can you set web-hook in main okapi repository settings ?
![selection_752](https://user-images.githubusercontent.com/13780868/47447628-43706e80-d7be-11e8-92ea-43933fcb26c5.png)
Please send 'secret' to rt@opencaching.pl

**Comment by following5** [comment]
done

**Comment by following5** [comment]
Great work, thanks!
