### ISSUE TITLE
News administration. 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#167]
```
From what I understood so far, only users marked as ADMIN can post news 
articles that go into the news section. 
However, these need to be approved, which is doable at this time ONLY by 
changing a flag directly in the database. There is no UI for it. 

One question is : by design who should have the right to post a news article 
and who should be the one to approve it for publishing? 

At this time, since only admin user can post, what is the purpose of the 
approval? 
Or is it rather a "publish / display" flag, rather then approve? 

Be it publish or approve action, I request a UI for it. In which case, news 
articles should be viewable in a list, be editable, publishable, deletable. 

--------------------
Second, I request the WYSIWYG editor for the news article. 

Thank you. 
```

Original issue reported on code.google.com by `andrixnet` on 8 Oct 2014 at 8:17

**Comment by deg-pl** [comment]
What do you think about change "$use_news_approving" to false in /admin_addnews.php?
This would be a small temporary fix.

Later I could prepare a news editor.

**Comment by deg-pl** [comment]
I think that /util.sec/newsapprove/ doesn't make sense. Because both of  /admin_addnews.php and /util.sec/newsapprove/ require admin privilege. In admin_addnews.php admin user can add news, but has no rights to publish it. In /util.sec/newsapprove/ the same admin user has rights to publish his own news.

**Comment by andrixnet** [comment]
I am not sure of the organizational concepts behind this. 

There are several scenarios: 
1. any user can post a news article, requires admin to approve and publish. NOT USED, NOT RECOMMENDED

2. any admin can post a news article, requires superadmin to approve and publish. Requires organizational hierarchy of the OC Team handling administration tasks.

3. any admin can post a news article, and is posted/published directly. (setting that variable to false would enable this behaviour)

Sidenote: why superadmin is a single user? Couldn't it be just defined as `admin` = 2 in database?

**Comment by wloczynutka** [comment]
Have we in code any 'superadmin' ? Maybe I'm wrong, but I think we don't.

**Comment by andrixnet** [comment]
$super_admin_id in : 
settings-example.inc.php
admin_users.php

**Comment by wloczynutka** [comment]
I think this is unuseable.

**Comment by wloczynutka** [comment]
BTW, who is in oc settings set as $super_admin_id?

**Comment by deg-pl** [comment]
I think it should be that any admin user can post news without any approvement.
In addition, the system should log (and publish this information with news) who added news (TODO).

**Comment by mzylowski** [comment]
> Następnym ważnym dla COG tematem może być refactoring nieszczęsnego "Dodaj newsa" (admin_addnews.php). Trzeba by wywalić tą bezsensowną "autoryzację" newsów, dodać radio z wyborem że news ma być: widoczny na głównej / widoczny tylko w aktualnościach / nie widoczny, dodać możliwość łatwej edycji newsów (nie wspominając już o wygodnym edytorku wizualnym). Bo na chwilę obecną newsy na głównej praktycznie nie są wykorzystywane ze względu na to, że marnie działa zarządzanie nimi. RT musi je autoryzować (bez sensu - to nie jest kompetencja RT) i to bezpośrednio w bazie, albo za pomocą topornego utilsa, nie ma możliwości edycji czy wycofania z głównej bez rzeźbienia w bazie.
