### ISSUE TITLE
integration with crowdin

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1670]
in my opinion we need to review and integrated in our "process" mechanisms offered by crowind 
I think we need to take a look how to deal with it in our day-to-day activities.
I think we need integrate github with crowdin (there are support for it but it needs to be reviewed)

Maybe there are other problems which needs to be resolved besides:
- translations in DB
- #1494

**Comment by deg-pl** [comment]
@mzylowski May your oc-robot be used in crowdin <-> OC PL repo sync process?

**Comment by mzylowski** [comment]
I will look into this in next few days.
@harrieklomp Can you add me to crowdin project? (I just created an account - mzylowski)

**Comment by harrieklomp** [comment]
@mzylowski You now are manager.

**Comment by kojoty** [comment]
@mzylowski, have you any progress in this case? If not yet can I take a look at this?

**Comment by mzylowski** [comment]
All works was postponed due to AKQ. You can look into this if you like. I can help with integration, ocpl-robot part etc.

**Comment by kojoty** [comment]
@harrieklomp 
1. I assume till now you sync translation files manually with crowdin - right?

2. during my experiments I see some quota warning - do you know what quota on crowdin we have? 
If this quota is close to the number of current available translations it can be a problem in nearest future - then I think we can't use crowdin...

**Comment by mzylowski** [comment]
@kojoty About ocpl-robot account check email :)

**Comment by teiling88** [comment]
> do you know what quota on crowdin we have?
If I remember correctly the default quota is 5.000 phrases for an open source project.

**Comment by kojoty** [comment]
@deg-pl @harrieklomp @andrixnet @following5 @mzylowski 
From my point of view OCPL is ready to start using crowdin integrated with github.
For now account ocpl-crowdin-robot is configured to provide such changes to repo.
It can work like I described it above.

If we decide we are ready we can remove en.php from main folder at crowdin - there should stay only en.php under full path (master/lib/...). Before that we need to be sure that al the translations which have been made till now are present in code (at github) - I'm not sure - @harrieklomp, can you check it?

**A small explanations for colleagues:**
- we need to use ocpl-crowdin-robot (different account) because crowdin account needs to control webhooks at OCPL github - what needs github repo "admin" rights. 
- crowdin doesn't have access to all the repo settings (for example can't delete ocpl repo) because it uses ocpl-crowdin-robot account by token which allow only limited actions on github repo.

**Comment by mzylowski** [comment]
> we need to use ocpl-crowdin-robot (different account) because crowdin account needs to control webhooks at OCPL github - what needs github repo "admin" rights.

I still don't get why we can't use only one robot?

**Comment by kojoty** [comment]
> > we need to use ocpl-crowdin-robot (different account) because crowdin account needs to control webhooks at OCPL github - what needs github repo "admin" rights.
> 
> I still don't get why we can't use only one robot?

We can, but
- "ocpl-crowdin-robot" needs more permissions - "admin" level access to repo - to work with crowdin
- "ocpl-robot" works great without this 

This is the only reason. If we can use account with lower access level it's better (in my opinion).

Of course we can just increase the level of "ocpl-robot" permissions and use only one "robot" account.

**Comment by following5** [comment]
> If we decide we are ready we can remove en.php from main folder at crowdin - there should stay only en.php under full path 

Then all crowdin comments on en.php will get lost. Some are open issues, others are hints for translators.

**Comment by kojoty** [comment]
> > If we decide we are ready we can remove en.php from main folder at crowdin - there should stay only en.php under full path
> 
> Then all crowdin comments on en.php will get lost. Some are open issues, others are hints for translators.

Oo, I was not aware there are something like that - can we migrate it on some way? Maybe this is assigned to the phrase - not the file?

**Comment by following5** [comment]
I dont's see the comments in the new master/lib/languages/en.php entries, so they are file specific.

But in the project settings there is a file manager, which allows to drag & drop files between directories. So it should be possible to delete the new en.php from master/lib/languages, and move the old (including comments) there.

**Comment by following5** [comment]
In master/lib/languages/en.php at crowdin, all translation entries are missing for texts which are identical in the destination language as in English. E.g. when I filter for untranslated texts in German, it shows 180 entries which are present in the old en.php.

But thats's not a big problem. When master/lib/languages/en.php is replaced by the old en.php as proposed above, the translations should be complete again - and if not, the missing texts can quickly be filled in manually - two clicks per entry.

**Comment by following5** [comment]
I have suspended the automatic Crowdin sync, so that the new workflow can be established. These are the next steps:

* merge #1823
* hard reset the crowdin_master branch to master
* reenable Github Sync in Crowdin project

**Comment by kojoty** [comment]
OK, now crowdin integration is done. Thanks for all for cooperation.
