### ISSUE TITLE
Some issues with last large commit

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1684]
On searchpage there are some links missing to translations on all nodes. Please look at screenshot below.
![selectie_230](https://user-images.githubusercontent.com/1060518/46578511-9696a300-ca02-11e8-9ff5-a77361b80c3f.png)

In English translation file on line 1109 ('map_csFilter' => 'Power taril',) should this Power taril be GeoPath?

**Comment by kojoty** [comment]
@harrieklomp I hope I fixed everything now. Please reopen if needed. 

Thanks!
