### ISSUE TITLE
Admin options on GeoPaths

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1693]
Now admins (OC Team / COG in OC PL) can't see deleted GeoPath's comments and can't restore them. This should work like cache logs - OC Team see deleted logs as strikeout and can restore them.

**Comment by following5** [comment]
Can someone please test this on a production site?

**Comment by harrieklomp** [comment]
A small test on OCNL
After click on "Restore" the log is still strikeout and not restored. We get a small error like this:
```
Error: Using $this when not in object context



#0 /serve/www/oc_www/oc_www/powerTrail/ajaxRemoveOrRestoreComment.php(28): lib\Objects\ApplicationContainer::getLoggedUser()

#1 {main}
```

**Comment by harrieklomp** [comment]
BTW. The mail does not have the nodes own logo.
![selectie_295](https://user-images.githubusercontent.com/1060518/51683627-9559a800-1fea-11e9-9466-221a640c0135.png)

**Comment by following5** [comment]
Have applied a fix for restoring Geopath comment; can you test again?

**Comment by harrieklomp** [comment]
Tested again and now it works. Log is restored :-)

**Comment by following5** [comment]
Now there is the node's logo in Geopath comment notification emails.
