### ISSUE TITLE
Fonts clean-up

### ISSUE THREAD

**Issue by DorotkaMakotka** [opencaching/opencaching-pl#1705]

**Comment by DorotkaMakotka** [comment]
`font-family` property should be unified and defined in one place to avoid discrepancies within the website, so:
* I've removed (almost) all occurrences of `font-family` property
* I've decided to use some more modern web font (I chose OpenSans since it seems to be quite ordinary font yet much more elegant than what we had)
* differences are not overwhelming but still quite significant, especially when compared directly - I've attached some BEFORE/AFTER examples

**Comment by DorotkaMakotka** [comment]
![fonts_cleanup1](https://user-images.githubusercontent.com/19299162/46982398-632bd680-d0dc-11e8-9a88-133414850562.PNG)
![fonts_cleanup2](https://user-images.githubusercontent.com/19299162/46982399-63c46d00-d0dc-11e8-98e2-764457aff0bf.PNG)
![fonts_cleanup3](https://user-images.githubusercontent.com/19299162/46982401-63c46d00-d0dc-11e8-98a0-a977edd30b3f.PNG)
![fonts_cleanup4](https://user-images.githubusercontent.com/19299162/46982402-63c46d00-d0dc-11e8-92c6-61f3c41487d1.PNG)
![fonts_cleanup5](https://user-images.githubusercontent.com/19299162/46982404-645d0380-d0dc-11e8-9b5d-dafcc88729f7.PNG)
![fonts_cleanup6](https://user-images.githubusercontent.com/19299162/46982405-645d0380-d0dc-11e8-9db2-7ad9af7e5357.PNG)

**Comment by mzylowski** [comment]
Is still there anything to do?
