### ISSUE TITLE
change order for the list of dnfs

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1709]
from OCPL forum:
autor: PrincePolo » środa, 17 października 2018, 09:51
> Mam taką drobną prośbę: w menu Moje statystyki można rozwijać listy zarówno skrzynek znalezionych, jak i nieznalezionych. O ile po rozwinięciu skrzynek znalezionych ukazuje się lista w porządku chronologicznym (od ostatnio podejmowanych począwszy) i tak jest fajnie, o tyle rozwinięcie skrzynek nieznalezionych generuje listę w porządku alfabetycznym. Czy można by zastosować sortowanie po dacie w liście skrzynek nieznalezionych? Mam sporo DNF-ów i ułatwiłoby mi to obserwację, czy w ostatnio nieznalezionych coś się nowego wydarzyło.

**Comment by following5** [comment]
fixed by 7f97ead
