### ISSUE TITLE
Altitude update improvements

### ISSUE THREAD

**Issue by rapotek** [opencaching/opencaching-pl#1711]
Currently whenever a new cache is added or coordinates of an existing one are changed, the cache altitude update is called sequentially as a part of the whole save/update process. The altitude is updated using remote call to open-elevation.com, which responses very slowly if at all. In result the altitude update takes over 99% of the whole time of cache save/update.

There are quicker alternatives (f.ex. elevation-api.io) but a call depending on remote resource should not be a sequential part of save/update cache process. Therefore I recommend to:

- instead of sequential call, save notification in DB (maybe somewhere else) about altitude update need
- implement a separate process, called periodically, which will update the altitudes in background using configurable list of available services with priorities and reasonable timeouts

**Comment by kojoty** [comment]
good point! 

I think that the altitude can be set to some special value or null for example and periodic worker can update altitude for all caches with assigned value "null"

of course the provider can be change (or better added)

**Comment by kojoty** [comment]
@rapotek, ostatnio ktoś mi mówił, że new-cache strasznie muli na zapisie - teraz zrozumiałem czemu :)

**Comment by rapotek** [comment]
@kojoty, tu masz przykład z mojego deva: czas aktualizacji całkowity (microtime) - 22.401179075241 s, w tym czas akualizacji altitude - 22.392078876495 s

Co do samej aktualizacji: można to zrobić i w ten sposób jak proponujesz, przy czym trzeba uwzględnić odpowiednie wyświetlenie nulla na strone kesza. Wiem, że jest w util.sec repairGeocachesAltitude.php, ale to jest chyba tylko namiastka tego, co powinno być.

**Comment by harrieklomp** [comment]
I do not know if this is related but sometimes new caches have no altitude.
On OCNL there where some new caches with no altitude. Perhaps it was only here on OCNL see OB1B63 and OB1B5F
But it seems that this is part of the code because OCPL has the same problem. Look at OP8XDY and OP8XDX

**Comment by following5** [comment]
I can fix this after #1254 (new cronjob engine) is done. Would refactor both, OCPL and OKAPI altitude updates into one OCPL cronjob.

Resetting to null on change sounds reasonable to me, as the old altitude value is invalidated by a coordinate change.

**Comment by deg-pl** [comment]
813

**Comment by rapotek** [comment]
I am not sure, but I think this has been fixed after new cronjob engine has been implemented. Therefore I close it.
