### ISSUE TITLE
New volunteers do not show on map

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1721]
With settings via guides.nl.php new volunteers do not show on map when they have set this in their profile page.

**Comment by kojoty** [comment]
@harrieklomp 
at first (generally):
- node-specific config should has only "overrides" for default config - so instead:

```
$guides = [
    'guideActivePeriod' => 90,
    'guideGotRecommendations' => 3,
];
```
it should be:
```
// $guides['guideActivePeriod'] = 90; -- no needed - this is same as default
$guides['guideGotRecommendations'] = 3;
```

why? - because configs are read in order: default (then)-> node (then)-> local
first way redefine the $guides array at all - second one override values in $guides array

**Comment by kojoty** [comment]
second:
Map should presents all users which pass all of the requirements:
- find/create geocache within last 90 days
- have at least 3 recommendations in own 
- mark "will of being guide" in profile

Are you sure all 3 requirements are passed in your situation?
Can you provide more details...

**Comment by harrieklomp** [comment]
Changed en committed like our example. 
Now there should be 2 users who pass these requirements.

harrieklomp:
- has logged (found) last cache at 27-09-2018
- has 23 recommendations
- has marked being guide

GeoWolf:
- Last new cache at 02-09-2018
- has 12 recommendations
- has marked being guide

How long does it take to show effect when user change being guide?

**Comment by deg-pl** [comment]
@harrieklomp but I see two users which are volunteers at OC NL:
![image](https://user-images.githubusercontent.com/13884863/47567844-d977d680-d92f-11e8-8317-90e9d97d4e92.png)

Volunteers are stored in APCu cache. You can clean cache here: https://www.opencaching.nl/lib/apc/apc.php , but first you should set password in /lib/settings.inc.php:
$config['apc']['password'] = '<your_password_here>';

**Comment by harrieklomp** [comment]
Okay, it does take some time to show. I will setup APCu cache.
Now it is working.
Thanks for your time :+1: 
This issue can be closed.

**Comment by deg-pl** [comment]
I've checked - volunteers are cached for 8 hours. See https://github.com/opencaching/opencaching-pl/blob/744ef7453d98a59b36a32b06868cfc9d2202089c/Controllers/GuideController.php#L34
