### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1727]
This is introduction of the "role" for the user.
Every user has set of assigned "roles" - it means that ordinary user doesn't have any role - some user can have many of them.

I see three roles for now:

ocTeam member - same as current 'admin' (replace "admin" column)
advanced user - user with permissions to tested features etc. (for example to /test controller)
system admin - user with permissions to further technical admin panels - I'd like use this role to limit access to for example APC interface etc.
Of course the list of roles can me modified in future, but this is not configurable between nodes now (all nodes have same roles).

**Comment by kojoty** [comment]
little related to issues: #781 #299

**Comment by deg-pl** [comment]
I think important role is news publisher - user who can/may publish news on mainpage. On OC PL not only "COG" should publish but also "RT"

**Comment by kojoty** [comment]
> I think important role is news publisher - user who can/may publish news on mainpage. On OC PL not only "COG" should publish but also "RT"

OK, let's add the new role as well "newsPublisher"...

**Comment by harrieklomp** [comment]
Run sqlalter on OC NL
