### ISSUE TITLE
New newsitem not visible for not logged in users

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1735]
When publish a news item and select "Show to not logged in users" the news item is not visible to not logged in users.
![selectie_243](https://user-images.githubusercontent.com/1060518/47940248-5c79cd80-deea-11e8-8d8a-226077959bd2.png)
A not logged user would see this:
![selectie_245](https://user-images.githubusercontent.com/1060518/47940530-2a1ca000-deeb-11e8-8852-fe1a1dc6a515.png)

**Comment by harrieklomp** [comment]
@deg-pl When i look at bottom it describes "It refers both of main page and news page."
![selectie_246](https://user-images.githubusercontent.com/1060518/47948439-a0dc8c00-df31-11e8-9dd4-58c3b12e6063.png)

**Comment by deg-pl** [comment]
When I refactored news - news for not logged users was shown both on main page and news page. Later @kojoty refactored mainpage and hide ALL news for not logged users. Main reason is to show simple page for new users and encourage to register.

We have two options:
- enable news for not logged users on main page - but like per-site configurable feature
- change info text (underscored by you)

**Comment by harrieklomp** [comment]
The latests news item on OCNL we show the rules how to attend a event. This is also important for not registered users. That should be a motivation to register and to login.

For that we like to enable news for not logged in users on main page. I hope it is not to much work to implement this and make it configurable per-site :-)
