### ISSUE TITLE
What is the correct way of escaping and encoding log entries in the OCPL database?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#174]
```
As described here:

https://code.google.com/p/opencaching-api/issues/detail?id=324

OKAPI saves a new log entry to OCPL database, but it is not always displayed 
correctly. Do I store it incorrectly, or is there something to be fixed in OCPL 
code?

```

Original issue reported on code.google.com by `rygielski` on 16 Nov 2014 at 9:33

**Comment by harrieklomp** [comment]
There are still logs with this <br/> done via c:geo. In the database i have changed "Default = 0" to "default = 1" in table cache_logs. 
I hope this could work :-)

**Comment by kojoty** [comment]
@harrieklomp, @andrixnet,
 I probably don't understand the problem described here - is it still an issue? If yes please reopen and add description what is needed here. Thanks.
