### ISSUE TITLE
COG annotations not displayed with added descriptions

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#1745]
* Team member adds a COG annotation.
* Cache owner adds a description in another language.
* => COG Annotation is not displayed with the new description.

**Comment by kojoty** [comment]
yes, this is possible use-case but this is really rare or even impossible scenario.

Most situations when ocTeam add some comments is situation when cache is abandon but working and they don't want to archive it if it is still in the game but there is something to comment - for example in the original version of the description there was an additional password necessary to log but now this is not needed etc.

The oc-team comments is just something extraordinary - if geocache author cooperate it is not added - just author add necessary changes...

And finally - yes - I agree - for the right order it should be copied to the new description. We will handle it during the cacheEdit refactor :)

**Comment by following5** [comment]
Ok. I will try to adjust my expectations regarding OCPL coding standards. ;) As you explained, there are many more important things to do.
