### ISSUE TITLE
Not activated accounts

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1763]
How often is a account not activated on different nodes? What can be a reason when a account is not activated?

On OC.NL we had from 29-10-2018 to 16-11-2018 a count of 100 registrations.
After looking further in DB it looks that 43 accounts are not activated. Some accounts are fake (easy to see) with temporary e-mail address or strange usernames.
Only one has send a e-mail to OC NL for asking to activate the account.

I think there are minimal 25% of new accounts not activated!!!
Do new users not receive the activation mail or do they ignore these mails?

After investigation it shows that Microsoft mail accounts (hotmail and live) have most problems. It even shows that opencaching(nl) are in blacklist

How is this on other nodes?

**Comment by kojoty** [comment]
Hi Harrie,

I checked the stats in OCPL and:
it seems we have ~12% of accounts not activated in 2018.
queries to get the data:
```
SELECT * FROM `user` where last_login = 0 and is_active_flag = 0 and YEAR(date_created) > 2017
SELECT * FROM `user` where is_active_flag = 1 and YEAR(date_created) > 2017
```
Additionally I checked the email servers from not-activated accounts:
```
SELECT substring(email, POSITION('@' IN email), CHAR_LENGTH(email)) as server, count(*) FROM `user` where last_login = 0 and is_active_flag = 0 and YEAR(date_created) > 2017 group by server
```
@gmail.com | 222
+ less than 10 for every next server
but we are sure that emails from OCPL are received by gmail

I think, that if your users used MS accounts often and you see that MS drop your emails just try to contact MS or try to do what they polices need to accept your emails - yeah - sometimes it is the tilting at windmills - we have also occasionally problems with not delivering of our email.

I guess you check logs from your mail server to analyze what is going on...
How do you realize that OCNL address/IP is on MS blacklist?
I don't know much about cooperation with MS but for example maybe links like this can help:

https://webmasters.stackexchange.com/questions/54988/how-to-remove-our-ip-address-from-microsofts-email-blacklist

**Comment by deg-pl** [comment]
On OC UK we had problem with MS mailbox, but I removed IP from blacklist and now is much better.

We don't have auto inactivated accounts remove (https://github.com/opencaching/opencaching-pl/issues/1290) to don't block e-mail addresses and usernames.

**Comment by harrieklomp** [comment]
gmail is not the biggest problem. Most problems are MS accounts.
Some one just made a account and again the same problem and in maillog is written:

Nov 17 09:41:07 ar sendmail[5417]: wAH8f7L7005417: from=www, size=2939, class=0, nrcpts=1, msgid=<201811170841.wAH8f7L7005417@ar.opencaching.nl>, relay=www@localhost
Nov 17 09:41:07 ar sm-mta[5418]: STARTTLS=server, relay=localhost [127.0.0.1], version=TLSv1.2, verify=NOT, cipher=DHE-RSA-AES256-GCM-SHA384, bits=256/256
Nov 17 09:41:07 ar sendmail[5417]: STARTTLS=client, relay=[127.0.0.1], version=TLSv1.2, verify=FAIL, cipher=DHE-RSA-AES256-GCM-SHA384, bits=256/256
Nov 17 09:41:07 ar sm-mta[5418]: wAH8f771005418: from=<www@ar.opencaching.nl>, size=3167, class=0, nrcpts=1, msgid=<201811170841.wAH8f7L7005417@ar.opencaching.nl>, proto=ESMTPS, daemon=MTA, relay=localhost [127.0.0.1]
Nov 17 09:41:07 ar sendmail[5417]: wAH8f7L7005417: to=Thiska.007@hotmail.com, ctladdr=www (60/60), delay=00:00:00, xdelay=00:00:00, mailer=relay, pri=32939, relay=[127.0.0.1] [127.0.0.1], dsn=2.0.0, stat=Sent (wAH8f771005418 Message accepted for delivery)
Nov 17 09:41:08 ar sm-mta[5420]: wAH8f771005418: to=<Thiska.007@hotmail.com>, ctladdr=<www@ar.opencaching.nl> (60/60), delay=00:00:01, xdelay=00:00:01, mailer=esmtp, pri=123167, relay=hotmail-com.olc.protection.outlook.com. [104.47.9.33], dsn=5.0.0, stat=Service unavailable
Nov 17 09:41:08 ar sm-mta[5420]: wAH8f771005418: wAH8f870005420: DSN: Service unavailable
Nov 17 09:41:08 ar sm-mta[5420]: wAH8f870005420: to=<www@ar.opencaching.nl>, delay=00:00:00, xdelay=00:00:00, mailer=local, pri=34456, dsn=2.0.0, stat=Sent

Yes, OC NL is on a blacklist.
![selectie_251](https://user-images.githubusercontent.com/1060518/48659764-72dd6880-ea56-11e8-85f0-a49b02b6f12c.png)

I try to make a issue on your link!

**Comment by deg-pl** [comment]
On OC PL and OC UK we use DKIM (you don't use) and restrictive SPF (-all, you use ?all). It helps to reach lower spam score.

**Comment by harrieklomp** [comment]
I notified @andrixnet about this. Perhaps he can solve these settings.

**Comment by deg-pl** [comment]
@andrixnet could you explain - what the wrong header looks like?

**Comment by harrieklomp** [comment]
I have done some more testing. Last week i have made a account at outlook dot com. This evening i have changed my e-mail address on all nodes to this (garbage) outlook e-mail address. There is a big surprise or not......

- OC UK spambox (even a personal mail from @Amberel  was in spambox!!!)
- OC PL inbox
- OC RO spambox
- OC NL inbox (some luck?)
- OC US spambox
- OC DE inbox
- OC CZ spambox

This is a huge problem for most OC nodes.

**Comment by deg-pl** [comment]
You can check your server IP status here: https://sendersupport.olc.protection.outlook.com/snds/
And submit issue here: http://go.microsoft.com/fwlink/?LinkID=614866

**Comment by harrieklomp** [comment]
It looks that this problem is solved. Most accounts are now activated.
I close this but can be reopened if problem reappear.
