### ISSUE TITLE
Log a GK with log a note

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#177]
```
Normally a GK can only be logged with a foundlog on a logpage. Is it possible 
to make the code so that a GK can be logged in a notelog?

This comes in handy when make a note when dropping GK in a cache.

Thanks :-)

```

Original issue reported on code.google.com by `henricus...@gmail.com` on 30 Nov 2014 at 4:00

**Comment by andrixnet** [comment]
0. A user finding a cache should be able to log geokrety. Currently working.

1. A user that is owner of cache should be able to log geokrety via write note, anytime.

2. A user who has previously found the cache and is revisiting it should be able to log geokrety via write note. 

3. A user that attended an event should be able to log a geokrety with attended or write note (same as 2.)

**Comment by harrieklomp** [comment]
It would be great when this can be implemented. I now have 13 GK's in my inventory ;-)

**Comment by harrieklomp** [comment]
GK can now be logged at any logtype.
I close this is issue.

Thanks :+1:
