### ISSUE TITLE
Quotation marks in nickname destroys SQL queries and profile view

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#1773]
![47433871_458238741369999_3821479290856275968_n](https://user-images.githubusercontent.com/13780868/49513414-2fc22880-f891-11e8-83bc-630f40167960.png)
![47497852_332525844005137_250719656501837824_n](https://user-images.githubusercontent.com/13780868/49513415-2fc22880-f891-11e8-84c3-583916dda3f9.png)

Also registration (or nick change) should not allow to set nick with `'` `"` marks

Reported by telefonalarmowy via mail

**Comment by deg-pl** [comment]
Fixed by PR #1774
