### ISSUE TITLE
Strange line at newlogs page

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1775]
![image](https://user-images.githubusercontent.com/2961448/49657715-f3fc9f80-fa05-11e8-9b83-b4513c303690.png)

**Comment by kojoty** [comment]
hint:

> autor: sajmon » piątek, 7 grudnia 2018, 18:08
> 
> A czy nie pojawiał się już taki problem jakiś czas temu przy wpisach użytkownika z nazwą drużyny harcerskiej (niestety nie pamietam nazwy) ujętą w cudzysłów? Tu też się pojawia, może to być przyczyną?

**Comment by deg-pl** [comment]
Fixed by PR #1774
