### ISSUE TITLE
Ignored caches are still shown on the map

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1778]
From FB (Atena.pl)

> Deg wiesz może dlaczego nie znikają z mapy skrzyneczki ignorowane??? Jak zgrywam GPS też mam je w garminie:(

From FB (Bartosz-111):

> Ps. Na mapie ciagle wyświetlają się kesze z ignorow

**Comment by following5** [comment]
There's a bug with saving/initializing map filter settings. When the user opens a new map, or switches between full screen and embedded map, all filters are cleared. Then ignored caches become visible.

Generally, it can take up to 5 minutes until the map reflects any changes, e.g. adding a cache to the ignore list.

**Comment by following5** [comment]
This was fixed by 2277e7c2.
