### ISSUE TITLE
New cache: check on the map doesn't work 

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1779]
from mail to RT:
> Cześć!
> Przy zakładaniu nowej skrzynki nie działa "Sprawdź czy są już skrzynki w okolicy na Mapie". Po kliknięciu strona się przeładowuje, ale nic się nie zmienia. Sprawdzałem działanie na Firefoxie, Chrome, nawet na Edge;)
> pozdrawiam
> Kuba (Slimaki39)

**Comment by following5** [comment]
This was fixed by 6d730078. (Verified at OC.NL, because I don't have the right to create caches at OC.PL.)
