### ISSUE TITLE
Map filters not working while click "See on map Opencaching"

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#1781]
From [forum](https://forum.opencaching.pl/viewtopic.php?p=142248#p142248):

> Hej, chciałbym zgłosić pewien problem z mapą. To znaczy za każdym razem przy otwarciu konkretnego kesza i kliknięciu "Zobacz na mapie: Opencaching", mapa otwiera się w nowej karcie i niestety, ale wyłączają się wszelkie filtry (system pokazuje kesze ignorowane, własne, znalezione, tymczasowo niedostępne, zarchiwizowane itd.). Oczywiście przy włączeniu mapy przez odnośnik z menu głównego tego problemu nie ma.

**Comment by following5** [comment]
See https://github.com/opencaching/opencaching-pl/issues/1778#issuecomment-445806596 - same problem.

**Comment by following5** [comment]
This issue is fixed.

**Comment by following5** [comment]
This was fixed by 6d730078.
