### ISSUE TITLE
PDO error from new AutoArchiveCaches cronjob

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1790]
After introducing new cron module OCNL receives at 4:30 a error mail with next messages. Does other nodes have the same error?

+++ PDO Error +++ 

+++ Debug: Query: DELETE FROM `cache_arch` WHERE `cache_arch`.`cache_id` IN (

                      SELECT `caches`.`cache_id` as `cache_id`

                      FROM `caches`, `cache_arch`

                      WHERE `cache_arch`.`cache_id` = `caches`.`cache_id`

                        AND `caches`.`last_modified` >= NOW() - INTERVAL 4 MONTH 

                      )

+++ Ex_Code: HY000

+++ Ex_Msg: SQLSTATE[HY000]: General error: 1093 Table 'cache_arch' is specified twice, both as a target for 'DELETE' and as a separate source for data

+++ Ex_Trace:

#0 /serve/www/oc_www/oc_www/Utils/Database/OcDb.php(231): PDOStatement->execute()

#1 /serve/www/oc_www/oc_www/Controllers/Cron/Jobs/AutoArchiveCachesJob.php(190): Utils\Database\OcDb->simpleQuery('DELETE FROM `ca...')

#2 /serve/www/oc_www/oc_www/Controllers/Cron/Jobs/AutoArchiveCachesJob.php(39): AutoArchiveCachesJob->removeLastEditedCachesFromList()

#3 /serve/www/oc_www/oc_www/Controllers/Cron/Jobs/AutoArchiveCachesJob.php(26): AutoArchiveCachesJob->processCaches()

#4 /serve/www/oc_www/oc_www/Controllers/Cron/CronJobsController.php(84): AutoArchiveCachesJob->run()

#5 /serve/www/oc_www/oc_www/Controllers/Cron/CronJobsController.php(59): Controllers\Cron\CronJobsController->runJobs(false)

#6 /serve/www/oc_www/oc_www/Controllers/Cron/CronJobsController.php(30): Controllers\Cron\CronJobsController->processCronJobs()

#7 /serve/www/oc_www/oc_www/util.sec/cron/run_cron.php(15): Controllers\Cron\CronJobsController->index()

#8 {main}

**Comment by deg-pl** [comment]
@harrieklomp Do you use MariaDB or MySQL?
I've tested this code on my devel MariaDB, and works fine also on OC PL and OC UK (both on MariaDB)

I'll try to reproduce this error on MySQL.

**Comment by deg-pl** [comment]
@harrieklomp Should be fixed now. Please test it and reopen if issue still exists.

**Comment by harrieklomp** [comment]
No more error mail after run cronjob via https://www.opencaching.nl/Cron.CronAdmin :+1: 
Thanks!!!
