### ISSUE TITLE
Execution continues after SQL errors

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#1792]
On my devel VM, PHP scripts will not abort on most OcPdo Exceptions. They just show a warning and go on. This obviously is not safe, because the execution continues with bad data.

The reason is that OcPdo::error() is called with the default $fatal = false, and then triggers a PHP warning, which does not stop execution. So I guess it's the same on production sites.

Possible solutions:
* Discard the $fatal option, and treat all PDO errors as fatal.
* Install an error handler, which treats warnings as errors (that's what OKAPI and OCDE do).

**Comment by following5** [comment]
Also, this [does](https://github.com/opencaching/opencaching-pl/blob/master/Utils/Database/OcPdo.php#L117) not work, because the trigger_error() in the preceding line aborts the script.

**Comment by following5** [comment]
Oops, wrong link [this](https://github.com/opencaching/opencaching-pl/blob/master/Utils/Database/OcPdo.php#L112) does not work, because the E_USER_ERROR aborts the script.

**Comment by following5** [comment]
XDb works fine; the problem is only with OcDb.

**Comment by following5** [comment]
Oops, testin error. Only warning with XDb too, there was just another followup fatal error.

**Comment by kojoty** [comment]
@following5, in my opinion it sounds good!

**Comment by following5** [comment]
This issue is fixed by fc1127f9.
