### ISSUE TITLE
OC Team comments

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1796]
In the past OC Team comments where only visible for OC-Team and the mentioned cache owner. Now it is visible for every one and even not logged in users.
Should this be more private between OC Team and user? On nodes who approve caches this is used to start a conversation about the cache.

**Comment by deg-pl** [comment]
OC Team talk with cacheowner during approving process. When cache is approved, all conversation should be deleted. I think (but I'm not sure) we don't change it.
In the future I'll refactor all new cache creation process, and logs will not be used to talk OC Team with cache owner. There'll be separate space for cache approving conversations.

**Comment by harrieklomp** [comment]
Perhaps i did write it wrong. I mean that there was a separate space for this. It was private but now it is public.

![selectie_266](https://user-images.githubusercontent.com/1060518/50460814-a4145700-0979-11e9-955c-6e9438577c56.png)

**Comment by kojoty** [comment]
@harrieklomp
I almost sure that it was public all the time (or at least for a long time - I mean years)
OCPL uses this field just to add OC team comment which is directly to all which watch page of the cache.
It is used for example when cache is abandon and there is significant change affected finding which should be public known.

How many OCNL caches have problem with it?

**Comment by harrieklomp** [comment]
@kojoty 
It was somewhere changed after introduction because English translation show it is private :-)

So we used it the wrong/other way and i remember why others could not see it while approving. When a cache is not yet approved other cannot see this cache (and the OC comment). Just before the cache is approved remove the comments.
This means that it can be used is two ways. Before cache is approved communicate with cacheowner and when cache is online use it like OCPL example :-)

Problem solved :-)
