### ISSUE TITLE
Some cleanup English translation file

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1798]
When translating different languages via Crowdin there are a lot strings not used in code or strings that are still used in the code but this code is not used. I am sure that there is more and can be added later.

Existing unused code and their translations:
    • Additional cache attributes at /cache-atr.php. Do we use this code in future again or do we remove it?  Each node has his own set of attributes now. When this code should be removed there are about 47 translations that can be removed.

Strings that are not in code are:
    • 'to_print'
    • 'printer_friendly'
    • 'available_statpics'
    • 'with_all_consequences'
    • 'listed_other'
    • 'stat_picture'
    • 'download_for_various_apps'
    • 'listing_from_this_page'
    • 'number_of_visit_caches'
    • 'dont_have_recommended_caches'
    • 'your_recommendations'
    • 'was_removed'
    • 'recommended_geocaches'
    • 'number_recommendations'
    • 'delete_recommend'
    • 'not_applicable'
    • 'image_max_size2'
    • 'show_more'
    • 'to_do'
    • 'print_all'
    • 'remove_all'
    • 'notify_subject_pl'
    • 'notify_intro_pl'

**Comment by following5** [comment]
Here is a more complete list of translations which do not seem to be used anymore:

cache_menu
only_founds
only_new
add_to
remove_from
to_print
shown
printer_friendly
user_map
current_zoom
last_10_days
rest
max_caches_per_page
by_name
by_date
other_options
show_signes
show_caches
no_statpics_available
available_statpics
illegal_char
what_is_geocaching
new_caches
general
cache_recommendation
not_available2
write_to_log
password_required
show_recommended
no_choice
your_data
notification
from_home_coords
user_new_log_entries
emails_sent_label
no_userprofile
show_all_logs
profile_data
hidden_caches
in_wgs84_system
additional_attributes_hint
additional_attributes
search_wildcard_info
with_all_consequences
waypoint_label
user_desc
startPage_stsAllCaches
startPage_stsActiveCaches
startPage_stsUsers
startPage_stsFounds
filename_rules
register_msg5
register_msg6
listed_other
logoutsuccess
show_noscore
found_it
did_not_find_it
write_note
attende
will_attende
no_log_entries
your_newest_log_entries
stat_picture
download_for_various_apps
oc_statistics
only_active_caches
extra_attrs_info
find_user
show_waypoints
listing_from_this_page
number_of_visit_caches
users_active
show_labels
add_new_note
back_to_cache
cache_notes
no_note
comment_octeam_visible
approved_by_octeam
route_cache
start_point
trp_points
recently_seen
myn_notify_lbl
myn_notify_caches
myn_notify_logs
number_logentry
does_not_have_stat
stat_problems
moved_cache_info
comment_log
need_maintenance_log
comment_octeam_log
moved_log
new_coordinates
moved_distance
delete_logentry
add_comment_to_remove
removed_message_titel
dont_have_recommended_caches
your_recommendations
was_removed
recommended_geocaches
number_recommendations
delete_recommend
not_applicable
image_max_size2
show_more
openchecker_coords
openchecker_degrees
openchecker_minutes
GKApi20
GKApi21
GKApi22
to_do
feed_blog
feed_forum
adopt_35
logs_info
recomm_short
print_all
remove_all
lxg07
reports_user_lbl_content
PrimaAprilis
PMOnly
Statictics
org1
links_pagetitle
watchlist_made
watchlist_logtext
activatemail01
activatemail02
activatemail03
activatemail04
activatemail05
mailto_hello
mailto_userProfile
benelux_outside
romania_outside
uk_outside
XX
pt021
pt026
pt027
pt052
pt053
pt061
pt081
pt092
pt136
pt138
pt173
pt210
pt222
pt223
pt_show_on_main_map
region_02
graph_statistics_01
graph_statistics_05
graph_statistics_06
graph_statistics_07
gpxCog
coordsmod_lon
coordsmod_lat
coordsmod_info_02
chart
like_comment
like_it
no_like_it
fav_com
notify_subject_pl
notify_intro_pl
viewPending_08
news_status_1
news_status_2
news_status_3
news_status_4
Stats_t4_02
PageNr
Given_Recommendations
WeekCache
list_of_titled_caches_is_empty
week_titled_cache
week_titled_caches
week_titled_cache_congratulations
month_titled_cache
month_titled_caches
month_titled_cache_congratulations
show_more_titled_caches
admin_notes_admin_name
admin_notes_content
wayPointType-1
myProvince_title
merit_badge_threshold
loginForm_notRegistered
loginForm_lostPassword
mnu_newMapBeta
myRecommendations
myNotes_removeConfirmation

**Comment by harrieklomp** [comment]
I only use "search file" in Ubuntu. This search for text in all files in a map. Perhaps @following5 does it another way?

**Comment by following5** [comment]
```
<?php

include "en.php";

foreach ($translations as $key => $t)
{
    if (!grep("'$key'") && !grep("{{$key}}") && !grep("\"$key\"")) {
        echo "$key\n";
        file_put_contents('unused', "$key\n", FILE_APPEND);
    }
}

function grep($str)
{
    $str = str_replace('"', '\"', $str);
    exec("git grep \"$str\"", $results);
    foreach ($results as $r)
        if (substr($r, 0, 14) != "lib/languages/")
            return true;
    return false;
}
```

**Comment by harrieklomp** [comment]
@kojoty 
For other languages we can use Crowdin. After import the new updated English file in Crowdin all languages have the same strings. German, French and Dutch are up to date in one go. Than move those translated files into GIT and done. No need to edit each language files separate.
This is a good reason to also make the Polish and Romanian translation on Crowdin complete. It saves a lot of work afterwards :-)

Is this /cache-atr.php still used? If not we can remove it and also the corresponding English translations.

**Comment by deg-pl** [comment]
@harrieklomp can we automatize upload en.php file to Crowdin and back commit language files into OC repository?

**Comment by harrieklomp** [comment]
@deg-pl 
Yes, this all can be done automatic. If you are owner of main OCPL repository on Github you can set this on https://crowdin.com/project/oc-polish-code-translations/settings#integration. If you are not the owner than you need a token from the owner. More info you can find on https://support.crowdin.com/github-integration/
Most important is automatic upload the en.php file, so i cannot forget updates ;-) Moving the translated files to Git is no problem for me. Than i am doing something useful for OC ;-)

If you like some advice (Geokrety uses this method) you can contact @kumy

**Comment by following5** [comment]
The manual deployment by Harrie has the advantage that every change is thorougly verified before releasing it to production. But for developers who do their own translations (e.g. deg-pl and kojoty for Polish, me for German) it is slowing down things. I would like to do this
* code
* write German translation
* test German translation

without having to wait for some manual action. Best solution IMHO would be to allow both

* directly commit translations to Github by developers,
* do translations via Crowdin by non-developers, which are uploaded by Harrie.

So some merge process would need to be implemented, which merges updates from Crowdin into Git repo instead of replacing the complete translation files.

**Comment by following5** [comment]
Afaik c:geo has such a Crowdin worflow, which merges direct translation and Crowdin translations. So it is possible.

Big advantage is that developers can test translations _before_ deployment to production sites. E.g. German is pretty verbose, and sometimes text get too long for a form or table and need shortening. Or lower- and uppercase are acidentally mixed for items of the same kind.

**Comment by kumy** [comment]
If I'm not mistaken, c:geo don't use direct translation in source code, all are managed via crowdin.

Nevertheless, if you wish you can upload local translation using API https://support.crowdin.com/api/upload-translation/

**Comment by following5** [comment]
See [statement](https://forum.opencaching.de/index.php?topic=4900.msg61455#msg61455) by Bananenweizen:

"... you are not forced to translate in Crowdin, but developers can directly supply English and German with their changes ..." (discussion was about English + German at OCDE)

**Comment by following5** [comment]
Hmm, you are right - there is no merging [here](https://github.com/cgeo/cgeo/blob/master/crowdin/download#L83). But still, it's possible. Just need to include the current commit ID when uploading translations to Crowdin; then everything can be done via Git:
* download crowdin translations to temporary file
* derive a temporary branch from that commit ID
* commit the downloaded Crowdin translation there
* merge that.

Git will do all the rest, including detection of conflicts, if the same text was changed both in master and on Crowdin.

**Comment by following5** [comment]
I will try to implement that for Okapi - later. Automatic upload is needed anyway, and can be implemented independently.

**Comment by kojoty** [comment]
Let me check it - I try to enable crowdin integration with GitHub for ocpl

**Comment by kojoty** [comment]
@harrieklomp, have you requested open-source project here https://crowdin.com/page/open-source-project-setup-request ?

**Comment by harrieklomp** [comment]
@kojoty 

Yes, i have done that.

**Comment by kojoty** [comment]
@harrieklomp, 
Can you also see this label at your crowdin account?
![image](https://user-images.githubusercontent.com/2961448/50542666-4c692c00-0bc3-11e9-82dd-de29540978bf.png)

I wonder what will happen when my account expires...

**Comment by harrieklomp** [comment]
@kojoty 
No, i do not see that message. Perhaps the  message goes away when you are more active on Crowdin? Or a reaction when deleting a project?

![selectie_267](https://user-images.githubusercontent.com/1060518/50542765-3197b700-0bc5-11e9-854b-a196b7168e72.png)

**Comment by kumy** [comment]
Mine is expired since a long time, but I'm just contributing to existing projects. I think that after the trial period, personal projects are disabled. Unless you declare them as opensource thanks to the link you provided above.

In other words, after trial, you can still contribute to other projects (paid or opensource).

![screenshot from 2018-12-29 23-57-44](https://user-images.githubusercontent.com/176794/50542798-df0aca80-0bc5-11e9-9d96-ea0523d31f97.png)
https://crowdin.com/pricing#annual

**Comment by kumy** [comment]
The [Term and condition](https://support.crowdin.com/terms/) are more restrictive…

**5.6 Free Trial.**
> […] If the period of Free Trial has expired, the Account will be automatically deactivated. In order to prevent deactivation or to reactivate the Account, the Client is required to select a suitable Plan and pay the first Fee. […]

In my case, my account has never been disabled.

**Comment by kojoty** [comment]
> The [Term and condition](https://support.crowdin.com/terms/) are more restrictive…
> 
> **5.6 Free Trial.**
> 
> > […] If the period of Free Trial has expired, the Account will be automatically deactivated. In order to prevent deactivation or to reactivate the Account, the Client is required to select a suitable Plan and pay the first Fee. […]
> 
> In my case, my account has never been disabled.

OK, let's see how it will work in my case - THX!

**Comment by kojoty** [comment]
I assume this is done - am I right?
