### ISSUE TITLE
Minor errors in code (exceptions)

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1825]
ErrorException: Undefined variable: result
#0 /srv/ocpl/powerTrail/ajaxImage.php(45): Utils\Debug\ErrorHandler::handleError(8, 'Undefined varia...', '/srv/ocpl/power...', 45, Array)
#1 {main}

**Comment by kojoty** [comment]
ErrorException: Undefined index: projectId

#0 /srv/ocpl/powerTrail/ajaxGetComments.php(18): Utils\Debug\ErrorHandler::handleError(8, 'Undefined index...', '/srv/ocpl/power...', 18, Array)

#1 {main}

**Comment by kojoty** [comment]
TypeError: Argument 1 passed to lib\Objects\Coordinates\Coordinates::areSameAs() must be an instance of lib\Objects\Coordinates\Coordinates, null given, called in /srv/ocpl/editcache.php on line 1024

#0 /srv/ocpl/editcache.php(1024): lib\Objects\Coordinates\Coordinates->areSameAs(NULL)

#1 /srv/ocpl/editcache.php(489): updateAltitudeIfNeeded(Array, 66455)

#2 {main}

**Comment by kojoty** [comment]
ErrorException: Undefined variable: gpxAttributes

#0 /srv/ocpl/myroutes_search.php(936): Utils\Debug\ErrorHandler::handleError(8, 'Undefined varia...', '/srv/ocpl/myrou...', 936, Array)

#1 {main}

**Comment by following5** [comment]
Am working on bugfixes.

**Comment by kojoty** [comment]
@following5 I've just prepared fixes for these above :)

**Comment by kojoty** [comment]
OK, I push my changes - @following5 - most of there problems are in legacy code and earlier or later we refactor most of these file.
If you would like to fix the rest - you are free to go - I switch to something another.

**Comment by kojoty** [comment]
ErrorException: Invalid argument supplied for foreach()

#0 /srv/ocpl/powerTrail.php(425): Utils\Debug\ErrorHandler::handleError(2, 'Invalid argumen...', '/srv/ocpl/power...', 425, Array)

#1 /srv/ocpl/powerTrail.php(351): displayPTrails(NULL, false)

#2 {main}

**Comment by kojoty** [comment]
ErrorException: getimagesize(): Filename cannot be empty

#0 [internal function]: Utils\Debug\ErrorHandler::handleError(2, 'getimagesize():...', '/srv/ocpl/lib/S...', 27, Array)

#1 /srv/ocpl/lib/SimpleImage.php(27): getimagesize('')

#2 /srv/ocpl/powerTrail/ajaxImage.php(26): lib\SimpleImage->load('')

#3 {main}

**Comment by kojoty** [comment]
ErrorException: A non-numeric value encountered

#0 /srv/ocpl/modules/openchecker/openchecker_classes.php(184): Utils\Debug\ErrorHandler::handleError(2, 'A non-numeric v...', '/srv/ocpl/modul...', 184, Array)

#1 /srv/ocpl/openchecker.php(70): OpenCheckerCore->CoordsComparing(Object(OpenCheckerSetup))

#2 {main}

**Comment by kojoty** [comment]
ErrorException: Undefined index: cache_icon

#0 /srv/ocpl/lib/common_tpl_funcs.php(212) : eval()'d code(319): Utils\Debug\ErrorHandler::handleError(8, 'Undefined index...', '/srv/ocpl/lib/c...', 319, Array)

#1 /srv/ocpl/lib/common_tpl_funcs.php(212): eval()

#2 /srv/ocpl/cache-atr.php(9): tpl_BuildTemplate()

#3 {main}

**Comment by kojoty** [comment]
ErrorException: Undefined variable: row

#0 /srv/ocpl/editpic.php(149): Utils\Debug\ErrorHandler::handleError(8, 'Undefined varia...', '/srv/ocpl/editp...', 149, Array)

#1 {main}

**Comment by following5** [comment]
So far I only did the first one, and without any refactoring. Looks like you are much faster with this, so I would rather leave it up to you.

**Comment by harrieklomp** [comment]
`ParseError: syntax error, unexpected 'utilisateur' (T_STRING), expecting ',' or ';'



#0 /serve/www/oc_www/oc_www/articles.php(52): tpl_BuildTemplate()

#1 {main}`

**Comment by kojoty** [comment]
OK, got it - I'm not going to refactor it now - I try to just fix - or add simple WA - for there errors.
There is no need to do any deep fixes for now.

**Comment by kojoty** [comment]
> `ParseError: syntax error, unexpected 'utilisateur' (T_STRING), expecting ',' or ';'
> 
> #0 /serve/www/oc_www/oc_www/articles.php(52): tpl_BuildTemplate()
> 
> #1 {main}`

@harrieklomp 
I need more info to fix it: can you try to check in logs what is the request which caused this error.
It seems that there is a problem around apostrophe before the french word: utilisateur
But all translations in fr.php seems to be OK.

**Comment by harrieklomp** [comment]
@kojoty 
I think this was not the solution. There is something else.This only happens when French language is selected, all other languages have no problem.

In all translations on Crowdin the " \ " is added in front of a " ' " . If a line has " `d'une` "  crowdin make " `d\'une` ". This is in all languages and most of the time there is no problem but in rare cases it triggers a error.
See also #1494 

I have undone the change for "Stats_s10_01" and before commit i would like to remove (online in Git) the " \ " in line `Stats_s3a_02' => 'Cliquer sur le nom d\'une région pour voir ses statistiques',` to see if this works.

**Comment by harrieklomp** [comment]
What is the difference between a " `’` " and a " `'` " ?

When use a " `’` " in translation like `'Stats_t5_09' => 'Nom d’utilisateur',` it woks fine.
When use a "` ' `" in translation like `'Stats_s3a_02' => 'Cliquer sur le nom d\'une région pour voir ses statistiques',` than Crowdin add a " `\` " and causes some errors.

**Comment by kojoty** [comment]
@harrieklomp 
there is a huge difference in my opinion - and we shouldn't use "\'" as a apostrophe in translations (because potentially it can cause a problems when someone forget about slash, add double slash etc.).

I think we can try to use everywhere " ’ " - directly as a unicode U+2019 or just &rsquo; or even &apos; in places where we are sure that translated phrase is displayed in HTML

**Comment by harrieklomp** [comment]
I have replaced the " `'` " with a " `’` " in the line `'Stats_s3a_02' => 'Cliquer sur le nom d\'une région pour voir ses statistiques',` on Crowdin.
Let us see if the error is gone and if all works like it should after commit.

**Comment by harrieklomp** [comment]
> I have replaced the " `'` " with a " `’` " in the line `'Stats_s3a_02' => 'Cliquer sur le nom d\'une région pour voir ses statistiques',` on Crowdin.
> Let us see if the error is gone and if all works like it should after commit.

Just merged it and the error is gone :-)

**Comment by kumy** [comment]
`'Cliquer sur le nom d\'une région pour voir ses statistiques'` is a valid php string, why would it be the problem?

**Comment by kojoty** [comment]
> `'Cliquer sur le nom d\'une région pour voir ses statistiques'` is a valid php string, why would it be the problem?

Yes, you're right, but escaping apostrophe is sometimes an issue - for example if crwodin escapes the the backslash and we get `'blah d\\'something'`... It is more safe to use unicode apostrophe U+2019  or HTML entities like &apos;

Thanks.

**Comment by following5** [comment]
' is a typewriter hack, while ’ (U+2019) is the typographically correct apostroph. See e.g.
* https://en.wikipedia.org/wiki/Apostrophe
* https://de.wikipedia.org/wiki/Apostroph
* https://nl.wikipedia.org/wiki/Apostrof_(leesteken)
* https://fr.wikipedia.org/wiki/Apostrophe_(typographie)#Signes_proches
