### ISSUE TITLE
Introduce cache_size Nano

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1835]
OC.NL has re-introduced the size Micro again.
To go a step further than only show micro (like GC) it should be nice to also show Nano caches in the system.

As suggestion the Nano could have ID 1 because the Micro has ID 2. The bigger the caches sizes, the biggest the ID number.

Because the search page looks at the normal DB this can easy be solved by importing the table "cache_size" that can be uploaded in /sqlAlters. The search page would loo like:
![selectie_289](https://user-images.githubusercontent.com/1060518/51258337-07f2d400-19aa-11e9-80f9-ff4761fb15ec.png)

Is it possible to add this Nano size as ID 1 to the system?

**Comment by following5** [comment]
Nano = ID 8, see [GeoCacheCommons.php](https://github.com/opencaching/opencaching-pl/blob/master/lib/Objects/GeoCache/GeoCacheCommons.php#L32):

This it is compatible with OCDE, Okapi and OC RO, which all have 1 = "other size" / "unspecified", and 8 = Nano.

At OC RO Nano it is on the [search page](https://www.opencaching.ro/search.php), but not available when creating a cache. I guess it is not fully implemented yet in OCPL code.

**Comment by kojoty** [comment]
@harrieklomp have you tested and this works? (I mean for example creating/editing cache etc.)

**Comment by following5** [comment]
Nano is [not enabled yet](https://github.com/opencaching/opencaching-pl/blob/master/lib/Objects/GeoCache/GeoCacheCommons.php#L136).

Will fix it, this is fun. :-)

**Comment by harrieklomp** [comment]
@following5 I have seen that but that seems (personal view) is a unlogical order. When i change it in DB as ID 8 the Nano it would look like on OCRO search page. Perhaps this can be solved to a logical order like OCDE have.
![selectie_290](https://user-images.githubusercontent.com/1060518/51261386-691da600-19b0-11e9-80ea-23ca7103739e.png)

@kojoty I have tested nothing yet. I only like to know if it is possible and from there we can continue with this.

**Comment by following5** [comment]
@harrieklomp 
> Perhaps this can be solved to a logical order like OCDE have.

Sure. Order can be detached from IDs. Best would be an additional order field in the cache_size table like at OCDE.

**Comment by following5** [comment]
> Best would be an additional order field in the cache_size table like at OCDE.

Ahh no... for OCPL it should be defined in the GeoCacheCommons class.

**Comment by following5** [comment]
Best solution is to make the `cache_size` table obsolete and only use size IDs from GeoCacheCommons and `tr()` for the names. Available sizes will be configured via new Config settings for each site.

But first https://github.com/opencaching/okapi/issues/519 must be solved:

* ID 1 at OCDE and OKAPI = "Other size"
* ID 1 in current OCPL code and at OC RO = "unspecified"

This is not the same. "Unspecified" means "can be any size", while "Other size" means it is not Nano, Micro, Small etc. E.g. I use "other size" for hidden logbooks without container.

https://github.com/opencaching/okapi/issues/519 is from October 2017, and @andrixnet did not reply yet.

What would you prefer for OCPL code? "unspecified", "other", or both (each size may choose which of both they enable)?

GC / GPX has "Other", but not "Unspecified". So "unspecified" would be an OCPL-only solution. We could add it to Okapi, but it will still appear as "other" in all existing Apps. Developers would have to explicitly implement it.

**Comment by following5** [comment]
Currently there are [six caches](https://www.opencaching.ro/search.php?searchto=searchbyname&showresult=1&expert=0&output=HTML&sort=bydistance&f_inactive=1&f_ignored=1&f_userfound=1&f_userowner=1&f_watched=0&f_geokret=0&country=&region=&cachetype=1111111110&cache_attribs=&cache_attribs_not=&cachesize_1=1&cachesize_2=0&cachesize_3=0&cachesize_4=0&cachesize_5=0&cachesize_6=0&cachesize_7=0&cachesize_8=0&cachevote_1=-3&cachevote_2=3.000&cachenovote=1&cachedifficulty_1=1&cachedifficulty_2=5&cacheterrain_1=1&cacheterrain_2=5&cacherating=0&cachename=%25&gpxLogLimit=5&cachename=) of "not specified" size at OC RO. This option is not available in newcache/editcache; it must have been entered directly in the database.

**Comment by following5** [comment]
Okay... found a way to go on with Nano without solving opencaching/okapi#519. :-)

**Comment by andrixnet** [comment]
I myself have been playing with nano for a while and worked on it. When it was purely in database, I could easily work with it. When it was partly moved to the code, part parts of the site still depended on the database, it overcame my skills. Last spring I had only partial functionality (based on my work) on OCRO dev site. 

See also at least https://github.com/opencaching/opencaching-pl/issues/876
and also documentation at https://wiki.opencaching.eu/index.php?title=Cache_sizes which may need updating.

**Comment by following5** [comment]
The change #1837 removes all database dependency of cache sizes. Nano will be fully functional at RO and NL sites.

**Comment by following5** [comment]
#876 is fixed by #1837. (Note that there are no cache size images, as you suggested in #876).

> https://github.com/opencaching/opencaching-pl/projects/2
and also documentation at https://wiki.opencaching.eu/index.php?title=Cache_sizes which may need updating.

I think it's not feasible to manually maintain all those redundant docs. They will always tend to be outdated. Instead, this information can be provided via Okapi in real time.
