### ISSUE TITLE
crowdin: translation fixes in English etc.

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1844]
@harrieklomp 
I looking for solution which allow to enable English translation at Crowdin - it would be great if English phrases also would be improved by Crowdin.

Please take a look at this https://github.com/opencaching/opencaching-pl/pull/1843/files
I changed phrases: 
   'pt176' => 'Ascending',
   'pt177' => 'Descending',

What is happen:
- crowdin inserts the English phrases to all other languages files - it seems that it override proper translations in other lang-s
- something strange is with synchronization - crowdin wants to push same changes all the time...

**Comment by following5** [comment]
> crowdin inserts the English phrases to all other languages files - it seems that it override proper translations in other lang-s

Crowdin cannot know if the translations are still correct after an English texts has changed. English is the source langauge for all the translations. So it is safest to discard all translations when English has changed, enforcing new translations.

**Comment by harrieklomp** [comment]
When i uploaded the English file by hand when some English text was changed there where some options.

- Keep old translations. With this option other translators do not see that something has changed.

- Remove old translation. This option should be chosen so translators can update to correct translation.

Last option is the safest i think

**Comment by harrieklomp** [comment]
@kojoty 
Ahhhh.
I now understand the problem. The phrases in English translation are empty. If a text is filled in, the system sees it as new translation for all other translations. Conclusion.... When all English translations are filled in than all other translations are gone.
I think the solution is to upload the English translation file as translated. This will be seen by Git in PR. Just remove the English translation from that PR and commit the rest.

**Comment by harrieklomp** [comment]
For now this means that the 2 English translation in PR #1843 should be removed before commit.

**Comment by harrieklomp** [comment]
I have uploaded the original English translations to Crowdin. Now the English translation is complete on Crowdin.
Please remove the English translations from #1843 before commit!!

**Comment by kojoty** [comment]
I think this issue can be closed.
