### ISSUE TITLE
Flood of emails scenario

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1847]
Hi 

I've just observed "flood of emails" sending by OC server to cache watchers (like me).
Scenario details:
- WatchlistController.php gets pack or watchers and process them one-by-one based on DB select
- watchers are marked as "handled" at the end - when the whole pack o emails is send
- if error occurs during emails send (for example there is invalid email address) there is an error (proceeded now to exception) what breaks the script running, so at next period emails are send to the same set of watchers 

details:
```
ErrorException: Utils\Email\Email::addToAddr: improper email address: email-removed-at-github

0 [internal function]: Utils\Debug\ErrorHandler::handleError(1024, 'Utils\\Email\\Ema...', '/srv/ocpl/Utils...', 201, Array)
1 /srv/ocpl/Utils/Email/Email.php(201): trigger_error('Utils\\Email\\Ema...', 1024)
2 /srv/ocpl/Utils/Email/Email.php(110): Utils\Email\Email->error('Utils\\Email\\Ema...', Object(Exception))
3 /srv/ocpl/lib/Objects/Watchlist/WatchlistReport.php(92): Utils\Email\Email->addToAddr('mirek.kazmiercz...')
4 /srv/ocpl/Controllers/Cron/WatchlistController.php(156): lib\Objects\Watchlist\WatchlistReport->prepareAndSend(Object(lib\Objects\Watchlist\WatchlistWatcher))
5 /srv/ocpl/Controllers/Cron/WatchlistController.php(90): Controllers\Cron\WatchlistController->sendReportsAndUpdateChecks()
6 /srv/ocpl/Controllers/Cron/WatchlistController.php(60): Controllers\Cron\WatchlistController->processWatchlist()
7 /srv/ocpl/Controllers/Cron/Jobs/WatchlistNotifyJob.php(10): Controllers\Cron\WatchlistController->index()
8 /srv/ocpl/Controllers/Cron/CronJobsController.php(83): WatchlistNotifyJob->run()
9 /srv/ocpl/Controllers/Cron/CronJobsController.php(58): Controllers\Cron\CronJobsController->runJobs(false)
10 /srv/ocpl/Controllers/Cron/CronJobsController.php(30): Controllers\Cron\CronJobsController->processCronJobs()
11 /srv/ocpl/util.sec/cron/run_cron.php(15): Controllers\Cron\CronJobsController->index()
12 {main}  
```

**Comment by kojoty** [comment]
@following5 
It seems that this is a result of promotion every error to exception - am I right?
It seems to be OK for scripts called by user - but for scripts running periodically from cron it can results in flood of some kind of operations - I'm not sure how to deal with this - just let's think about it...

**Comment by kojoty** [comment]
I temporary disable error generations here: #1846

**Comment by kojoty** [comment]
I've  found it because I got 20+ duplicated emails about new logs in caches watched by me :)

**Comment by following5** [comment]
Replace the [original code line](https://github.com/opencaching/opencaching-pl/pull/1846/commits/d875bf61befa71ca3e536586a0c43ae88067339f) by

`echo "Notice: " . $message . "\n";`

and everything works like before. :-)

Of course that's no proper error handling ...

Also, watches should to be marked as "handled" one by one, as ist was in the original watchlist implementation (before refactoring).

**Comment by following5** [comment]
Email class is very buggy and needs rewrite.
