### ISSUE TITLE
Header movie visible on cgeo authorization page

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1849]
I've just reauthorized c:geo on a new phone. 
As I did so, I saw the new header movie on the page shown in the browser widget on the authorization page. 

Is this correct? 
AFAIK the header movie should have been visible only on the homepage.

**Comment by following5** [comment]
Agree that the header should be hidden, to save mobile bandwidth and screen space.

**Comment by following5** [comment]
Video is now hidden for Okapi auth login.
