### ISSUE TITLE
tinyMCE French

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1876]
When creating a cache in French language on OCNL the tinyMCE plugin does not load correct.

`Failed to load plugin url: https://www.opencaching.nl/assets/js/libs/tinyMCE/4.9.2/langs/fr.js`

There is a French .js file but has another name: fr_FR.js

**Comment by kojoty** [comment]
yeah - it seems this is just a tinyMCE issue
II think we need to copy fr_FR.js to fr.js what should be a WA for this.

**Comment by harrieklomp** [comment]
Solved :-)
