### ISSUE TITLE
Emoticons from tinyMCE depends on tinyMCE path

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#1881]
tinyMCE inserts links to the emoticons
like:
```
<img src="lib/tinymce4/plugins/emoticons/img/smiley-laughing.gif" border="0" alt="�miech" title="�miech" />
```
but now these emoticons are present under path:
``` 
assets/js/libs/tinyMCE/4.9.2/plugins/emoticons/img/
```

if path to tinyMCE is changed all these path needs to be updated across all DB columns which can contains emoticons which are:
- geocache description 
- geocache log
- geopath description
- geopath logs
- ...?
We need simple script to run every time tinyMCE is updated which fix the paths or other solution for this.

**Comment by following5** [comment]
Cache listings and logs can be stored offline, especially in data that was downloaded as GPX; logs may also copied to another geocaching website. Emoticons will also break in this replicated data. Therefore I would try to keep the icon path unchanged (TinyMCE version numbers may be omitted!). Many TinyMCE users will have the same problem, so maybe there is a setting which allows to store the emoticons at a certain path?

If it is unavoidable to change the emoticons path, then there are still some options to solve this:

* Do not completely remove the old TinyMCE installations, but keep the emoticons files.
* Create symbolic links for that. May be automatically done by an always-run "DB update".
* Bend the old emoticon URLs via Apache rewrite
* ... ?

**Comment by deg-pl** [comment]
We have emoticons disabled in TinyMCE from over one year. Maybe we can replace in DB paths to emoticon images into UTF-8 emoticons?

**Comment by kojoty** [comment]
> We have emoticons disabled in TinyMCE from over one year. Maybe we can replace in DB paths to emoticon images into UTF-8 emoticons?

good idea 
table of unicode emoticons: https://apps.timwhitlock.info/emoji/tables/unicode

**Comment by following5** [comment]
GSAK will display ? instead of the emoticons.

**Comment by following5** [comment]
Couldn't this be fixed by letting SimpleRouter redirect the old icons path? Would avoid editing cache and log contents *and* stay compatible with externel copies of the content.

**Comment by kojoty** [comment]
Fixed by htaccess redirect.
