### ISSUE TITLE
Logs not working properly at OCRO

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1885]
Recently I discovered that logs are not shown for any cache, neither the viewlogs page works. 
In cache page there are no autoloaded logs. 
Separetely, viewlogs.php shows an empty page. 

Server log shows: 
```
PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /wwwroot/viewlogs.php on line 203, referer: https://www.opencaching.ro/viewcache.php?cacheid=133
```

**Comment by following5** [comment]
What PHP version is running on OC RO?

**Comment by following5** [comment]
Problem solved, OC RO logs are back. :-)
