### ISSUE TITLE
E-mail float when no cache of the month

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1927]
Because OCNL is not much used there are no more caches that can have the title cache of the month.
Now every 5 minutes there is a error mail.
Is there a way to prevent this e-mail float?

**Comment by harrieklomp** [comment]
Changed `$titled_cache_nr_found=1;` to lowest.
Should be solved for now.

**Comment by following5** [comment]
There is a bugfix PR: #1904
