### ISSUE TITLE
Undefined index: h_ignored

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#194]
Błąd wprowadzony w commicie:

"""
Revision: 530e1bdad1b3249362cac4a6a9e4cdad3afa870e
Author: p.juzwiak@gmail.com <p.juzwiak@gmail.com@19cba9c3-8ce2-6c67-1c13-32ea8d8b491d>
Date: 2015-06-18 22:02:37
Message:
geopath integration with cache-info baloon on the mapv3
"""

Wynika z tego, że w swoim pliku xmlmap.php nie debugujesz PHP-owych błędów E_NOTICE, a OKAPI - o ile się tego nie wyłączy - przy każdym includowaniu fasady traktuje je jako błędy. Możesz poprawić albo dodając isset w odpowiednich miejscach, albo wyłączając error handler OKAPI - to jest opisane w nagłówku pliku okapi/facade.php (metoda disable_error_handling()).

<pre>
OKAPI caught the following exception while executing API method request.
This is an error in OUR code and should be fixed. Please contact the
developer of the module that threw this error. Thanks!

===== ERROR MESSAGE =====
Undefined index: h_ignored
=========================

--- Stack trace ---
#0 /var/www/ocpl/lib/xmlmap.php(147): okapi\OkapiErrorHandler::handle(8, 'Undefined index...', '/var/www/ocpl/l...', 147, Array)
#1 /var/www/ocpl/lib/xmlmap.php(67): tmp_Xmlmap->parseUrlSearchParams()
#2 /var/www/ocpl/lib/xmlmap.php(8): tmp_Xmlmap->__construct()
#3 {main}

--- OKAPI method called ---
/lib/xmlmap.php

--- OKAPI version ---
1089 (2148472bb90ef4ac14abe73c0fb9b65e7b0a1cfb)

--- Request headers ---
Host: opencaching.pl
Accept: */*
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1)
</pre>

**Comment by kojoty** [comment]
Jestem na urlopie w terenie i ciężko mi się tu odnieść. Jak mi się uda znaleźć chwilkę i dostęp do neta to może zerknę na to, a już na pewno popatrzę po powrocie ale to dopiero za 2 tygodnie...

**Comment by wrygiel** [comment]
Spoko, to nic pilnego. Poprawiłbym sam, ale po prostu chciałbym żebyś zrozumiał o co w tym chodzi, bo jesteś jedną z trzech osób, która wykorzystuje OKAPI w kodzie. ;)
