### ISSUE TITLE
Opencaching.RO installation is outdated

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#1943]
The following changes need to be applied to OC RO system:

* Install new cronjob engine - see https://github.com/opencaching/opencaching-pl/commit/69ad770f162487ed65b718f13908d620af0c1390#diff-14.
* Install new database update system - see https://github.com/opencaching/opencaching-pl/commit/21de6fd4aa412c9b6fe7acbb943eec93eb069485#diff-4.

These changes block lots of open issues, which need the new cronjob or update engine.

As already discussed [here](https://github.com/opencaching/opencaching-pl/pull/1810#issuecomment-455455553), the OC RO code deployment needs to be disconnected, so that development can continue. I think this should be done in the next few days, before doing more refactoring steps that may introduce new bugs.

I had informed @andrixnet about this problem 10 days ago by email, but did not receive an answer yet.

**Comment by andrixnet** [comment]
I've updated OCRO with the new cronjob and database update system. 

Sorry for my late reply, me and my family have been down with the flu for almost two weeks. 

Please don't disconnect OC RO from code deployment.

**Comment by following5** [comment]
> I've updated OCRO with the new cronjob and database update system.

Thanks. I cant' verify if the cronjobs are running, but the DB updating is **not** working properly at OC RO. Needs further diagnosis.

**Comment by following5** [comment]
> I cant' verify if the cronjobs are running,

Bullshit - we made the cron admin page public exactly for this reason. Cronjobs are alive at OC RO.

**Comment by following5** [comment]
I used a PHP 7 feature for DB updating; OC RO still runs PHP 5.6.

@deg-pl @kojoty 
What is the current PHP version requirement of OCPL code? Should it stay comaptible with PHP 5.6, or is there already code that requires PHP 7?

If 5.6 is to be suppored, than 5.6 should be running on the developer VM instead of 7.

**Comment by kojoty** [comment]
> What is the current PHP version requirement of OCPL code? Should it stay comaptible with PHP 5.6, or is there already code that requires PHP 7?

Yeah... Yest this is an issue.
**Shortly**: all ours OC nodes except OCRO are running PHP7,
Yes we need to stay PHP 5.6 compatible with our code until OCRO upgrade

**Longer story:**
We talked about it long time ago.
OCRO has older OS and switching to PHP7 needs time for whole server upgrade and Andrei still don't have a time for it 

**Much longer story - solution:**
In my opinion in our model the synchronization of server configuration is a constant pain

Fortunately we have only 4 nodes so this is quite easy to check which configuration of PHP is running on given server
There is even a sys-page: https://opencaching.pl/sys/phpinfo
(to access it you need account on given node + sysAdmin role)

I think that the best (and only) solution for this problem is Docker.
We should migrate the OC services to docker containers and then all nodes should use same containers for running OC services. I even spend some time dreaming about it... 

Then we have exactly the same server configuration (I mean same PHP version, same apache version, same DB version etc.) Still every node has its own database, its own configuration (I mean OC-configs). 

Lot of hosting providers support docker containers.
This is even more beauty because also developer setups there can used same containers...

...but there are significant problems:
- 1. docker + Windows = problems - so people which would like to develop OC code undes windows has many complications (currently our dev-VM can be run on windows without any problem)
- 2. it needs some time to prepare the whole setup with dockers and it's not easy - especially because it seems that we need 3 containers: DB + PHP + WebServer
- 3. the performance impact is unknown - docker is a light virtualization - but I don't know...

**Comment by deg-pl** [comment]
I am not an advocate of migration to Doker. On the other issues, I agree with kojoty.

**Comment by following5** [comment]
Ok. I will make DB update PHP 5.6 compatible, and configure my IDE to check for PHP 5.6 syntax.

**Comment by following5** [comment]
PHP issue fixed by 1ef9e02 and MySQL 5.0 compatibility by b19a44e. Now there is the same user rights issue like at OC NL; privileged DB user must be configured at OC RO.

**Comment by following5** [comment]
Actually it is MySQL 5.5. Confused that with the PHP client version, which is not relevant.

**Comment by andrixnet** [comment]
I am working on it right now. 
As suggested by following5, I added some privileges as well. 

https://www.opencaching.ro/update yields an error message in HTML (it should be plain text), yet I received no email. 
Still digging.

**Comment by andrixnet** [comment]
I see in the mailserver logs the following: 
email from=<www@oc.opencaching.ro> (it should be noreply@ ...)
to=techNtify@opencaching.pl
stat=Sent

I conclude that some sort of notification was sent. 

However, as I see, no notification was sent to $config['nodeTechContactEmail'] = 'echipa@opencaching.ro';

Neither is this technical contact or other OCRO contact reached through techNtify@opencaching.pl
So I do not know the contents of that email and I am unable to debug further. 

Please help.

**Comment by andrixnet** [comment]
How do I assign multiple roles to a user? 
I've read some code in UserCommons.php, but it is unclear to me.

**Comment by andrixnet** [comment]
I also see in my mailserver logs 

```
Feb 23 12:24:56 oc sm-mta[14475]: x1NAMjTD014473: to=<techNtify@opencaching.pl>, ctladdr=<www@oc.opencaching.ro> (60/60), delay=00:02:11, xdelay=00:02:11, mailer=esmtp, pri=122923, relay=mail.iq.pl. [86.111.241.4], dsn=5.0.0, stat=Service unavailable 
```

**Comment by andrixnet** [comment]
I can't find `techNtify@opencaching.pl` anywhere in the code at OCRO. (searching contents of .php files)
I can, however, find techN**o**tify@opencaching.pl in /okapi_settings.php

**Comment by andrixnet** [comment]
Ok, I found this: `$config['technicalNotificationEmail'] = 'techNtify#@opencac#hing.pl';` in `/config/email.default.php`

Is this correct? It's the same in master repo: https://github.com/opencaching/opencaching-pl/blob/master/config/email.default.php

**Comment by andrixnet** [comment]
I know I've been away for some time, I am desperately trying to correct that and have a lot of catching up to do. 
Question: is the new configuration architecture under /config documented somewhere? 
Do changes there for a .ro.php file need to be deployed via GIT update? 
Do the variable definitions under /config take precendence over the same variable in /lib/settingsDefault.inc.php? 
Do the variable definitions under /config take precendence over the same variable in /lib/settings.inc.php?

**Comment by following5** [comment]
Okay, database updates at OC RO are working now.

@kojoty 
Could you have a look at that email issue?
> Ok, I found this: `$config['technicalNotificationEmail'] = 'techNtify#@opencac#hing.pl';` in `/config/email.default.php`

"techNtify" looks like a typo ...

**Comment by kojoty** [comment]
> Okay, database updates at OC RO are working now.
> 
> @kojoty
> Could you have a look at that email issue?
> 
> > Ok, I found this: `$config['technicalNotificationEmail'] = 'techNtify#@opencac#hing.pl';` in `/config/email.default.php`
> 
> "techNtify" looks like a typo ...

fixed: https://github.com/opencaching/opencaching-pl/commit/b895d3567b0082f59febdf8d1ea984b912cdef38

**Comment by kojoty** [comment]
> How do I assign multiple roles to a user?
> I've read some code in UserCommons.php, but it is unclear to me.

@andrixnet I've discovered your question:
Right now there is no interface and the only way is to do it manually in DB. There is also no way to see who has which role differently than directly in DB. 

Roles are not for "ordinary" users - this is something internal - only for advanced, deeper involved users or admins. It is especially useful for us (OCPL) where we want to have different sets of users as ocTeam, techAdmins, some advanced users which help us in tests etc... 

If you have any questions or concerns ask me directly.

**Comment by kojoty** [comment]
> I can't find `techNtify@opencaching.pl` anywhere in the code at OCRO. (searching contents of .php files)
> I can, however, find techN**o**[tify@opencaching.pl](mailto:tify@opencaching.pl) in /okapi_settings.php

@andrixnet in the meantime we introduce the mechanism which allow all of us see what happens on all the nodes - the common email address techNotify@o..p...pl

I added it to configs of all nodes but (I'm sorry for that) I made a typo in OCRO config.
Now it should be fixed. 

This address is used only to inform developers about technical errors discovered in the code at all nodes - it allow for example me better knows the results of my changes - often after merging bigger PRs there are some issues which I try to fix ASAP and common notification about errors helps with it (especially sometimes there can be some node-specific results of changes)

**Comment by andrixnet** [comment]
@kojoty Understood. Contacted you for details. 
What else needs to be done at OCRO (besides server upgrade for newer PHP) at this time?

**Comment by following5** [comment]
Nothing more to do. :)
