### ISSUE TITLE
Wrong log text when adopting cache

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#1949]
When a cache adoption is finalized, a log entry is added to the cache saying the cache was transfered from userX to userY. Or at least that is what it should read. 

At this time apparently the log entry is written as "cache transfered from User -> User".
The profile links for each user are correct, but the link text, which should contain the username is fixed.

**Comment by deg-pl** [comment]
It is not possible. Please, don't fix it!
GDPR law give our users "law to be forgotten". If user request to erase all his data, we should erase (change/anonymisation) also his username. If we put his username in logs - we cannot change fixed username in logs!
I've changed fixed username in logs into links, because our lawer pointed out that it is necessary.

Please - leave it as is!

**Comment by kojoty** [comment]
@andrixnet 
I'm not a layer but in my opinion THIS IS STUPID (but YES - after many discussions and consultations the opinion we have in this matter is exactly like Deg described above).

My private opinion is that we are wrong in this interpretation and the OC username is not a strict "personal data" and if we remove username on user request and allow changing of the nick it could stay in this kind of logs - but my colleges from OCTEAM are more preservative in this matter :) - maybe it's better.

**Comment by following5** [comment]
>  the OC username is not a strict "personal data"

agree

At OC.de it is even worse: They consider all log entries and geocache listings als potential personal data and will delete/hide them on request of the user. This policy is in place since a few months.

**Comment by deg-pl** [comment]
Username is not strict personal data but MAY be personal data.
For example - user who owns 1800+ caches on OC PL had username exactly like his name and surname. This IS personal data, and OUR (not user's) obligation is remove it.

**Comment by kojoty** [comment]
(this is theoretical discussion - I don't want to change anything in this matter - there are much more important subjects)
