### ISSUE TITLE
niepoprawny link do regulaminu.

### ISSUE THREAD

**Issue by wloczynutka** [opencaching/opencaching-pl#195]
Reprodukcja błędu: 
1. wejdź na http://www.opencaching.pl/register.php (na pozostałych domenach (ro/nl) również występuje)
2. wybierz język PL jeśli jest inny
3. kliknij w link do regulaminu - jest niepoprawny

**Comment by f-ranek** [comment]
Solved on .pl and .nl
.ro seems to be missing autoupdate received from Git

**Comment by f-ranek** [comment]
Everyone please note: from some time ago, we don't use {rules_url} defined previously in settings.ing.php. Now, we use following section to define wiki links
```php
$wiki_url  = '//wiki.opencaching.pl';
$wikiLinks = array(
    'main'  => $wiki_url,
    'rules' => $wiki_url.'/index.php/Regulamin_OC_PL',
    'rules_en' => $wiki_url.'/index.php/OC_PL_Conditions_of_Use',
    'cacheParams' => $wiki_url.'/index.php/Parametry_skrzynki',
    and so on
)
```
All the occurrences of {rules_url} etc should be replaced in the following manner, i.e.
{rules_url} -> {wiki_links_rules}
{cache_params_url} -> {wiki_links_cacheParams}
{rating_desc_url} -> {wiki_links_ratingDesc}

I have still found some incorrect references in languages/ro, but haven't yet fixed them.

**Comment by wloczynutka** [comment]
I think this issue is solved. If i'm wrong please reopen
