### ISSUE TITLE
Translation for history.tpl.php

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#196]
I would like to translate the file /tpl/stdstyle/articles/history.tpl.php. As far i can see there are two options to do this.
- Make new files named "history_pl-pl.tpl.php", "history_pl-nl.tpl.php", "history_pl-en.tpl.php" and so on for the Polish site. Make other files like "history_nl-nl.tpl.php", "history_nl-pl.tpl.php" and so on for the Dutch site. Than make the needed changes in settings file.
- Put the whole text in translation files and make the needed changes in settings file.

Please advice what the best solution is.
This also needs to be done with the file /tpl/stdstyle/impressum/.tpl.php.

**Comment by wloczynutka** [comment]
Is the file history.tpl.php in use? How to get there? I cannot see any link from main page

**Comment by harrieklomp** [comment]
Yes this file is in use. At the bottom of each page in the footer. it is called "History OC PL"

**Comment by andrixnet** [comment]
This reminds me of the problem of having some pages on a per node basis, with translation in each language. 
Harrie is right, the history page of OCNL, much like the contact and about, some text in homepage, possibly links pages, is specific to OCNL, rather then a translation in dutch of the history page. 
And also, his history page, while specific to OCNL, should have translations in the other languages. 
The OCPL history page is different, and should have it's own translations on OCPL node. 
And so on.

I have described this previously, perhaps in another issue, or maybe via email. Anyway, I can't find the reference right now.

**Comment by wloczynutka** [comment]
IMHO, all our opencachings (PL, Benelux, RO) has common root, and it is described in mentioned subpage. Why do not preserve it and add, at the bottom own stories both for NL and RO? For our users it is good to know that opencaching is also running on other nodes, and know nodes history. And following programming practice called KISS (Keep it simple stiupid) do not complicate creating another subpages.

**Comment by andrixnet** [comment]
I agree, solely for the history page, that it may be handled in the way described in the previous comment. 

Even if my team were to write an independent history article about OCRO, it could not be done without talking about OCPL and OCNL. 

However I raised a point earlier about several pages / articles, that could and should be handled in a generalized manner, allowing both per node individual content and translation for each language for said content.
And with all due respect, but the current implementation of the contact page via settings.inc.php is anything but simple. 

Thank you.

**Comment by harrieklomp** [comment]
Than i make the the choice myself. I will try to do it the same way like the contactpage. I do like the KISS way because i must do things simple ;-)
It could be done in one long line per language and each language file and can be different per node.

**Comment by harrieklomp** [comment]
There are 2 things in the footer.
- About. This could describe what opencaching is and what nodes there are. This can be a standard text in different languages.
- History. Is about the specific node with his own story about how it was founded and other things that are interesting for a user to read.

**Comment by deg-pl** [comment]
I think to include "about" and "history" pages in repo is not good solution. EVERY node has OWN history, in own language. Better place for "history" page is Wiki - every node has own Wiki, content of Wiki is easy editable by OC Team. My proposition is customise bottom menu and add external links to Wiki's.

If any node want to have international "history"/"about" pages - may write some pages in Wiki - each in other language.

**Comment by deg-pl** [comment]
Example settings:

> /*
>  * Bottom menu
>  * See settingsDefault.inc.php for default values
>  */
> // You can enable menu item by setting ['link'] and ['visible'] - for example:
> $config['bottom_menu']['impressum']['link'] = 'https://wiki.opencaching.pl/index.php/Opencaching_PL';
> $config['bottom_menu']['impressum']['visible'] = true;
> // You can also use your configured Wiki links:
> $config['bottom_menu']['history']['link'] = $wikiLinks['history'];
> $config['bottom_menu']['history']['visible'] = true;
> // You can disable single menu item:
> $config['bottom_menu']['main_page']['visible'] = false;
> // Or you can even add menu item. But remember - second index is a position from language file (/lib/languages/??.php)
> // and should be added to translation files first (in below case - 'guides').
> $config['bottom_menu']['guides']['link'] = '/cacheguides.php';
> $config['bottom_menu']['guides']['visible'] = true;

**Comment by deg-pl** [comment]
@harrieklomp @andrixnet - please change your settings file as above example (if you want impressum and history items in bottom menu)

**Comment by deg-pl** [comment]
@harrieklomp have you:

`require __DIR__ . '/settingsDefault.inc.php';`

in your /lib/settings.inc.php?

**Comment by harrieklomp** [comment]
@deg-pl Yes, i have this on top of settings.inc.php but it is disabled with "//".
Links will be added on bottom when wiki pages are made on OCNL.
