### ISSUE TITLE
Cache shortlink no longer works on devel VM

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#1963]
E.g. http://local.opencaching.pl/OP0001 now redirects to http://local.opencaching.pl/srv/ocpl/viewcache.php?wp=OP0001.

This is related to the recent /.htaccess changes. When I go back to commit b35b74b1 it works.

**Comment by kojoty** [comment]
It is just temp. fixed - please fetch the current code with 4a498144dae005c495f9cefbd36c1b1b7e898e42.
This is tmp WA because I want to come back to http redirect. 
I'm going prepare the final fix this evening.

**Comment by following5** [comment]
thanks

**Comment by kojoty** [comment]
It seems now it works. Please reopen if this is still an issue.
