### ISSUE TITLE
Hardcoded breaks in archive mail

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#1975]
When receiving mails about autoarchiving the line breaks are hardcoded.
This is in all monthly mails when autoarchiving a cache.

![selectie_306](https://user-images.githubusercontent.com/1060518/52914303-0b3df000-32c7-11e9-928e-ed4335a6c7d0.png)

**Comment by kojoty** [comment]
should be fixed with ` [88ffc37](/opencaching/opencaching-pl/pull/1974/commits/88ffc374a825467d76802ec1eaad088570717baf)`
