### ISSUE TITLE
Deploying SQL changes

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#200]
As the project advances, there are changes in the database structure from time to time. 
Most of them are additions or improvements, which, when applied, do not affect existing user data. 

Perhaps there would be a good idea to integrate database changes into the update process in a similar fashion to how OKAPI updates it's own database structure, or at least this is my understanding. 

Example scenario: 
- database changes that do not affect user data and can be processed automatically, without sysadmin intervention
- run cron job to update: 
     a) update site via GIT
     b) call a script to consolidate changes, apply database changes
     c) call OKAPI update script

Currently the update subsystem uses only a) and c). 

Example scenario 2: 
- database changes that require sysadmin review and possibly intervention
OR
OS needs changes that require sysadmin review and intervention
- before posting changes to master branch, send emails directly to each sysadmin, requesting database changes review. Allot a certain time for it. (ex. 3-7 days). 
- if not all sysadmins reply in due time, contact those again, allow one more day. If no answer, consider that node as lagging behind and remove GIT update notification for that node.
- apply update on master branch (all active and up to date nodes have applied necessary changes).

Lagging nodes may come up to date at a later time and contact the developer team to rejoin the update stream. It would be a good idea to have a place where active and inactive nodes using this project's automatic update system are shown and kept up to date.

Thank you.

**Comment by wrygiel** [comment]
I agree. The postcommit.php script could run all the necessary SQL statements itself (and notify the admins on the status).

**Comment by harrieklomp** [comment]
Is fine for me.
But i think first the database of each node has to be manually synchronized.  There are some tables on the Dutch database where i have added a "nl", "de" and "ro" column. This to show correct translations on the website.

**Comment by wloczynutka** [comment]
Preferable, these translations, if possible, should be moved to language files. It is good practice to keep things in one place.

**Comment by wloczynutka** [comment]
@andrixnet @wrygiel Are you sure it is safe enough? As we experienced last moths, we cannot trust everyone, and some people could commit drop tables/database statement. Programmers itself or people who can get acces to somebody computer / github account.

**Comment by wrygiel** [comment]
@wloczynutka - all commiters are already in their rights to do it. All of us can commit a malicious script and execute it.

**Comment by andrixnet** [comment]
I agree with @wrygiel , however the actual contributors (accounts with rights to do so) are very few and I believe them to be trustworthy. This is a rather small community that takes care of each other.

**Comment by andrixnet** [comment]
On the other hand, from administrative point of view, each node should have backups set up. 
On OCRO I've deployed a set of scripts that keep daily backups of the database for 14 days and automatically manage this. I'm working on another set of scripts to rsync the site files and these backups to another server. 
I will gladly share any of them.

**Comment by wrygiel** [comment]
BTW, perhaps some of you don't remember, but I have included a simple
comparison script in OKAPI:

http://www.opencaching.ro/okapi/devel/dbstruct?compare_to=http://opencaching.pl/okapi/devel/dbstruct

On Mon, Sep 7, 2015 at 1:47 PM, andrixnet <notifications@github.com> wrote:

> On the other hand, from administrative point of view, each node should
> have backups set up.
> On OCRO I've deployed a set of scripts that keep daily backups of the
> database for 14 days and automatically manage this. I'm working on another
> set of scripts to rsync the site files and these backups to another server.
> I will gladly share any of them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/opencaching-pl/issues/200#issuecomment-138277678>
> .
>



-- 
Every man has a perfect right to his opinion, provided it agrees with ours.
http://rygielski.net/

**Comment by andrixnet** [comment]
I've just checked and the differences between OCRO and OCPL databases
are quite extensive. Same goes for OCNL.
I would have to analyze them in detail and I am sure I will have questions.

On the other hand, the fact that this script
http://opencaching.pl/okapi/devel/dbstruct (actually for each node)
dumps the entire database schema in the browser, without any measure of
administrative authentication is a significant leak of common sense
information security.

**Comment by wloczynutka** [comment]
Same as public code at github :-)

2015-09-09 10:48 GMT+02:00 andrixnet <notifications@github.com>:

> I've just checked and the differences between OCRO and OCPL databases
> are quite extensive. Same goes for OCNL.
> I would have to analyze them in detail and I am sure I will have questions.
>
> On the other hand, the fact that this script
> http://opencaching.pl/okapi/devel/dbstruct (actually for each node)
> dumps the entire database schema in the browser, without any measure of
> administrative authentication is a significant leak of common sense
> information security.
>
> On 2015-09-08 8:48 PM, Wojciech Rygielski wrote:
> > BTW, perhaps some of you don't remember, but I have included a simple
> > comparison script in OKAPI:
> >
> >
> http://www.opencaching.ro/okapi/devel/dbstruct?compare_to=http://opencaching.pl/okapi/devel/dbstruct
> >
> > On Mon, Sep 7, 2015 at 1:47 PM, andrixnet <notifications@github.com>
> > wrote:
> >
> > > On the other hand, from administrative point of view, each node should
> > > have backups set up.
> > > On OCRO I've deployed a set of scripts that keep daily backups of the
> > > database for 14 days and automatically manage this. I'm working on
> > another
> > > set of scripts to rsync the site files and these backups to another
> > server.
> > > I will gladly share any of them.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/opencaching/opencaching-pl/issues/200#issuecomment-138277678
> >
> > > .
> > >
> >
> >
> >
> > --
> > Every man has a perfect right to his opinion, provided it agrees with
> > ours.
> > http://rygielski.net/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/opencaching/opencaching-pl/issues/200#issuecomment-138646754
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/opencaching-pl/issues/200#issuecomment-138833196>
> .
>



-- 
__________________________________
*Andrzej 'Łza' Woźniak*

*(+48) 798 835 592*
skype praca: *andrzej.wozniak.traveltech*
skype dom: *wloczynutka*

**Comment by wrygiel** [comment]
And publically available virtual machine with similar database structure installed on it. ;) Pros and cons of open source apps, I guess... I see no fix for this!

**Comment by wloczynutka** [comment]
I've heard once, that command

*> rm -rf /*

can resolve many issues, maybe could be used for this issue too?

2015-09-09 11:40 GMT+02:00 Wojciech Rygielski <notifications@github.com>:

> And publically available virtual machine with similar database structure
> installed on it. ;) Pros and cons of open source apps, I guess... I see no
> fix for this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/opencaching-pl/issues/200#issuecomment-138856882>
> .
>



-- 
__________________________________
*Andrzej 'Łza' Woźniak*

*(+48) 798 835 592*
skype praca: *andrzej.wozniak.traveltech*
skype dom: *wloczynutka*

**Comment by wrygiel** [comment]
;)

**Comment by andrixnet** [comment]
back on track, based on what OKAPI can do updating itself, how can we extend it to the entire site? 

And we should align the database structure of each node to a common point before deploying this functionality.

**Comment by wrygiel** [comment]
Someone would need to offer to implement this first. You can copy my OKAPI code if you want.

**Comment by andrixnet** [comment]
The matter is too complex for me to tackle, but I will gladly help testing on production environment, after initial tests on dev machine.

**Comment by wloczynutka** [comment]
This is complex task and need a lot of working hours. We still have no enough developers. While more urgent issuees waiting to be done, I see no possibility to develop this in nearest futoure or even in far future. For now I'm closing this issue. Can be reopened when any of developer will confirm that hi is taking it.
