### ISSUE TITLE
Search by alternate waypoint codes not working

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#201]
1) Entering an OC waypoint code specific for this node in the top-right search box yields the expected result. (when search by waypoint is checked)

2) Entering an OC waypoint code specific for this node, without the prefix, yields the same result. 
Example: searching for "OR0127" returns this cache, also searching for "0127" returns the same result. 
This is a nice feature.

3) Entering "GC5T012" in the the search box (which is an alternate waypoint for "OR0127") yields no result: 

```
Page error

Error ocured while page display.

Page: search
Error info: Waypoint must be in one of the following formats: OPxxxx, ORxxxx, OBxxxx, GCxxxxx, NCxxxx
```

As a sidenote, *function wpToId($wp)* handles only wp_oc, wp_gc and wp_nc columns.

**Comment by harrieklomp** [comment]
If there is a NC cache in the database than it works. @ Andrei, Try to edit one of your own caches and add "N02DEC" in the NaviCache field in also listed on. Save this change. Than do the same search in the top-right search box with this "N02DEC".
I am about to go to work but when i get back tomorrowmorning  i will try to solve this.

**Comment by harrieklomp** [comment]
I cannot find a way to change this. When a programmer can fix this, please go ahead :-)
