### ISSUE TITLE
Differences between OCNA and OCUS

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#2015]
While working on OCUS or is it OCNA?
What should be used on this site, on different pages OCNA are shown but also OCUS.
Could it be cleared up what to use as standard?

@TermiteHunter and @Mr-Yuck let us know what to use and why :-)

**Comment by TermiteHunter** [comment]
With the addition of Mexico and Canada we changed to OCNA. Open Caching North AmericaPlease use OCNAOn Apr 9, 2019 9:34 AM, harrieklomp <notifications@github.com> wrote:While working on OCUS or is it OCNA?
What should be used on this site, on different pages OCNA are shown but also OCUS.
Could it be cleared up what to use as standard?
@TermiteHunter and @Mr-Yuck let us know what to use and why :-)

**Comment by harrieklomp** [comment]
If possible OCNA will be used :-)

Solved
