### ISSUE TITLE
opencaching.eu visual editor not working

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2018]
While trying to edit a page at www.opencaching.eu wiki I found out that I cannot save changes.

Using the visual wiki editor, saving changes does not work. You press the button, nothing happens. 
Tested with Firefox 52 ESR x86 and 66 x64.

In the console I see the following error: 

```
JQMIGRATE: Migrate is installed with logging active, version 3.0.1 load.php:173:149
This page is using the deprecated ResourceLoader module "mediawiki.api.options".
Use "mediawiki.api" instead. load.php:290:491
Toolgroups must have a 'name' property
load.php:299:127
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! index.php
TypeError: converter.isForParser is not a function[Learn More] load.php:608:224
```

Using the source editor works.

**Comment by deg-pl** [comment]
I can't repeat your error. Tested on Chrome 73.0.3683.103 and Firefox 66.0.3 both 64bit (see https://wiki.opencaching.eu/index.php?title=Main_Page&action=history)

**Comment by andrixnet** [comment]
That is very odd. 
I also tried with Chrome Version 73.0.3683.86 (Official Build) (64-bit)
Same problem. 

Tried with Opera 58.0.3135.127 and 60.0.3255.56
Same problem. 

------------
Then went to a different computer.
Tested with Chrome 73.0.3683.103. Same problem. 

I am trying to edit Cache types page, and change one table cell. (each attempt). Saving does not work in any of these cases. 

(all tests on Win7 x64, 2 different computers using different internet providers)
I don't know how to debug this further at this time :-(

**Comment by andrixnet** [comment]
Using Google Chrome I was able to edit successfuly this page: https://wiki.opencaching.eu/index.php?title=Coord.eu 
but this page https://wiki.opencaching.eu/index.php?title=Cache_types still won't save.

**Comment by deg-pl** [comment]
I've reinstalled VisualEditor (the same version) and now seems to work OK.
Please check it. If it doesn't work - please clean your browser cache.

**Comment by andrixnet** [comment]
It works! 
Thanks!
