### ISSUE TITLE
Password reset email - incomplete link

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2022]
During OCNA migration, using the devel OCNA site, users apparently cannot change their own password for the following reason: 

- Fill the password reset form
- wait for email
- receive email, click on link to change password (in the email)
The link is missing the hostname part:

http://userauthorization/newPasswordInput/user/iSQn3zUODxGYA7UzX2ldYyf4pX77Pg3FQ3hl

Not only that, but the first word is changed to lowercase, because the path is 
/UserAuthorization/newPasswordInput/ ..... 

Conffiguration file properly defines the hostname:
```$absolute_server_URI = 'http://ocus.dev.andrix.eu/';```

--------------
by comparison, running the reset procedure on OCNL results into a correct URL in the password reset email.

I was unable to locate the code responsible for it. Recent changes into object model are beyond my understanding of PHP. 

Code is at latest master at the time of this writing.

**Comment by kojoty** [comment]
I'll try to look at this today.

**Comment by harrieklomp** [comment]
It is not in the code i think. Perhaps something local on DEVEL server.
When i ask new password on DEVEL OCNL http://ocnl.dev.andrix.eu/index.php there is the same problem.

**Comment by andrixnet** [comment]
Interesing and odd. 
The code generating emails has changed not too long ago. I have no idea about it, nor how to debug it, unfortunately, so anything problematic from there in relation to the underlying OS is unknown to me. 

In the logs I can only see "email sent OK"

**Comment by deg-pl** [comment]
I checked - password reset on OC US works correctly.
Server address in password reminder link is given from $_SERVER['HTTP_HOST'].
