### ISSUE TITLE
Exit online translation

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#2025]
When a user has role "advUser", he or she can activate online translations. This work perfect :+1:  .
Somehow it seems impossible to deactivate this online translation for this user.
When this user does logout and log in as another user (no "advUser') than this translation function is still activated.

Perhaps add a "Exit translation" button or what GeoKrety has. Automatic exit when select another site language via click on language flags.

BTW. There are no ore flags visible at the bottom when this translation function is active.

**Comment by kojoty** [comment]
good point! I try to fix it one day - anyway - scenario with "login as different user" is quite exotic...
Thanks Harie.
