### ISSUE TITLE
newlogs.php isn't sorted by date.

### ISSUE THREAD

**Issue by digdilem** [opencaching/opencaching-pl#2038]
Eg: 
https://opencache.uk/newlogs.php
Note: also evident on 
* https://opencache.uk/newlogs.php 

Date of logs is not sorted by date, DESC, as expected.

However, these (presumably an older version) are sorting as expected:
* http://www.opencaching.us/newlogs.php
* https://opencaching.cz/newlogs.php

I'm guessing a query has changed in the source?

**Comment by kojoty** [comment]
Latest logs are now rewrited. Dates seems to be OK.
