### ISSUE TITLE
Download own logs via GPX

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#204]
There are people who like to download their own logs via a GPX. Is it possible to implement this in the code?
For example click in left menu on "My statistics" and click on "show" on the line "Number of found caches:". Could on this resultpage downloadable button(s) be added, like we have on the resultpage after a search via the searchpage?

**Comment by wloczynutka** [comment]
Logs? oc do not allow downloading logs I think. We only porovide
downloading geocaches (including logs).

caches Found by specified user Can be done via search.php, (you can specify
finderid)

(
http://opencaching.pl/search.php?showresult=1&expert=0&output=HTML&sort=byname&searchbyfinder=&f_inactive=0&f_ignored=0&f_userfound=0&f_userowner=0&finderid=9067
)

Logged user can acces it from user profile.

2015-09-13 22:45 GMT+02:00 harrieklomp <notifications@github.com>:

> There are people who like to download their own logs via a GPX. Is it
> possible to implement this in the code?
> For example click in left menu on "My statistics" and click on "show" on
> the line "Number of found caches:". Could on this resultpage downloadable
> button(s) be added, like we have on the resultpage after a search via the
> searchpage?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/opencaching-pl/issues/204>.
>



-- 
__________________________________
*Andrzej 'Łza' Woźniak*

*(+48) 798 835 592*
skype praca: *andrzej.wozniak.traveltech*
skype dom: *wloczynutka*

**Comment by harrieklomp** [comment]
That own logs can not be downloaded on OC i know, that is why i ask if this can be implemented in the code.
Please look at http://www.opencaching.nl/my_logsFind.php?userid=3 or change the link to .pl and your own user ID. Could this page have his own "Download as GPX" button?

**Comment by wloczynutka** [comment]
But you want download geocaches or only logs?

**Comment by harrieklomp** [comment]
I only want to download my own logs.

**Comment by wloczynutka** [comment]
At the moment we have no possibility to export pure log enteries at all. This is more than add button to mentioned page - You need to write code taking log-enteries from database, and exporting as xml / text / csv / whatever.

**Comment by following5** [comment]
The GPX format does not allow to store logs without cache listings. A GPX file basically is a list of waypoints with coordinates and other properties, and logs have no coordinates. They just may be appended to waypoints.

You can download your logs via OKAPI, for whatever purpose you need them:
http://www.opencaching.nl/okapi/services/logs/userlogs.html

**Comment by harrieklomp** [comment]
Yes i know that cache listings are necessary in the GPX.
On http://www.opencaching.nl/my_logsFind.php?userid=3 all data is collected from the database (Cache name, cache ID, user ID, log ID and other things). This page shows each cache with only one log. This same data can be used to generate a GPX.

There are different pages from where can be downloaded a GPX.  Like http://www.opencaching.pl/myroutes_search.php or http://www.opencaching.pl/mywatches.php. 
Perhaps one of these GPX generators can be used for my_logsFind.php?

Like i mentioned in my first post is that users ask me for this. They like to use it in GSAK or other similar programs. I believe it is possible on GC to download your finds GPX, but for that you need to pay ;-)

**Comment by wloczynutka** [comment]
@harrieklomp As I understand your prievous posts, You wanted feature downloading only logs, not geocaches.

gpx witch found geocaches by specified user can be all the times downloaded within opencahing working on our code. Plese read and test this comment:
https://github.com/opencaching/opencaching-pl/issues/204#issuecomment-139980938

**Comment by harrieklomp** [comment]
@wloczynutka  I think i have explained it the wrong way. 
Yes, you are correct that i can download a GPX from caches that are found by me. But this GPX contains also all logs that are made in each cache from all other finders. This GPX contains also all data that is available and most of it we do not need for this future.
![selectie_104](https://cloud.githubusercontent.com/assets/1060518/9980367/e6e97ffa-5f96-11e5-8dc3-c73e5ecb725a.png)
What i am looking for is a light weight GPX generator that collect only the necessary data from the database from a cache that a user has found.
The GPX would look something like this.
![selectie_105](https://cloud.githubusercontent.com/assets/1060518/9980390/2f4df996-5f98-11e5-8358-c84266f9b28b.png)
Because my_logsFind.php does collect exact the data that is needed for this function (you see some cache information and only your own logs on this page) i suggested to make a light weight GPX generator in my_logsFind.php that uses the same data.

I hope i have made myself clear this time :-)

**Comment by wloczynutka** [comment]
This time is perfect :-)

**Comment by harrieklomp** [comment]
Great :-)

**Comment by andrixnet** [comment]
Please recheck after https://github.com/opencaching/opencaching-pl/pull/931

**Comment by following5** [comment]
I think the easiest way to implement this would be via OKAPI. Add an option "include only my logs" here and implement it in OKAPI:

![logs](https://user-images.githubusercontent.com/1614754/31365165-b7614178-ad69-11e7-8e06-b12928f86d86.png)

Do you still need this, @harrieklomp?

**Comment by harrieklomp** [comment]
@following5 Yes, i think users need this. This comes in handy when users do use GSAK or similar program.

**Comment by following5** [comment]
This hass been implemented with d95b241.
