### ISSUE TITLE
missing ocpl email address

### ISSUE THREAD

**Issue by wloczynutka** [opencaching/opencaching-pl#205]
Otrzymałem dzisiaj następującego maila:

Dnia XX użytkownik XX wysłał nowe zgłoszenie problemu.

Dotyczy ono skrzynki XXXX

Zespół OC PL rozpatrzy zgłoszenie w możliwie krótkim terminie. Jeżeli potrzebujesz skontaktować się z zespołem OC w sprawie tego zgłoszenia, wystarczy że odpowiesz na tę wiadomość.

Powód zgłoszenia: Skrzynka wymaga archiwizacji

Treść zgłoszenia:
------------------- początek ------------------
Do skrzynki nie będzie już dostępu. Miejsce zamknięte dla zwiedających
------------------- koniec -------------------

Jeśli chciałbym skontaktować się z zespołem OC - mam odpisać na niniejszego maila. Ale jako nadawca tego maila występuje wyłącznie "skarżący się" użytkownik. Nie występuje nikt w CC - jak mam przedstawić swoje stanowisko?

**Comment by deg-pl** [comment]
This is done through Reports refactoring
