### ISSUE TITLE
Maintenance to other caches

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#2057]
Perhaps ti is mentioned before so close this when it has.
Should users maintain other cache? This should be done by the owner.

![Selectie_346](https://user-images.githubusercontent.com/1060518/58374131-e649c080-7f38-11e9-894e-150992ce00d6.png)

**Comment by kojoty** [comment]
HI Harrie, 

From my point of view it's not a bug. 

Many times I maintained some geocaches by replacing broken box, added new foil bag for log etc. and I believe it is a good occasion to log "maintenance".

**Comment by harrieklomp** [comment]
I did not say it is a bug. I was only surprised :-)

Okay, no problem. I close this.
