### ISSUE TITLE
Nano cache and GeoPath

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#2066]
When add a nano cache to GeoPtath there is a error on the site.
On the place wher the error is shown there should be a list with cache types and cache sizes.

![Selectie_351](https://user-images.githubusercontent.com/1060518/59037784-419d7c00-8872-11e9-8c7d-753b922b7a02.png)

normal it is like below.

![Selectie_352](https://user-images.githubusercontent.com/1060518/59039391-11a3a800-8875-11e9-89b3-b443d1e5a8dc.png)

Perhaps it could be possible to add cachesize 8 to GeoPath and show it as size nano.

**Comment by harrieklomp** [comment]
At my local DEVEL site it should be possible to resolve this problem.

![Selectie_362](https://user-images.githubusercontent.com/1060518/61219599-d79bb080-a714-11e9-9922-678a9f77b16e.png)

More testing in progress.

**Comment by andrixnet** [comment]
We should use the GeocacheCommon definitions rather then hardcoded numbers, too.

**Comment by harrieklomp** [comment]
Is solved now via #2086
