### ISSUE TITLE
titled caches - missing when other languages are selected

### ISSUE THREAD

**Issue by wloczynutka** [opencaching/opencaching-pl#207]
1. Go to main page
2. select other language than PL(for example EN)

cache titled section is missing.

**Comment by harrieklomp** [comment]
There are some other things to improve this nice function.
- On http://opencaching.pl/cache_titled.php there is only Polish language available, like "Nazwa", "Region", Właściciel" and "Data wyróżn".
- Make it possible to set this function fur use per week or month. (could be done via settings file)
- The shown date on http://opencaching.pl/cache_titled.php could also be done via settings file so the date does show how settings are on the node.

**Comment by wloczynutka** [comment]
date / datetime format are already delcared and should be taken from settings.inc.php:

$dateFormat
$datetimeFormat

**Comment by tripper1971** [comment]
Harrie

1. done
2. As I wrote you, you can use this function as the cache of week or the cache of month, as you wish The only one difference is a definition in crontab. If you want use this function as the cache of month, launch it monthly (by cron). There isn't necessery to create configuration for week or for month via settings file.
3. done

**Comment by wloczynutka** [comment]
"The only one difference is a definition in crontab. If you want use this function as the cache of month, launch it monthly (by cron)"

nie do końca - bo nazwa "skrzynka tygodnia" zostaje niezelaznie od tego co jaki czas jest odpalony cron. Dobrze by było wymyślić mechanizm, który sam sprawdzi czy jest to skrzynka tygodnia, czy miesiąca i użyje odpowiedniego tłumaczenia.

**Comment by tripper1971** [comment]
do końca
dlatego, że każdy serwis używa własnej częstotliwości odpalania skrzynki, a co za tym idzie odpowiedniego nazewnictwa



  ----- Original Message -----

**Comment by wloczynutka** [comment]
nie proszempana :-) 
Używasz identyfikatora titled_cache i titled_caches niezależnie czy cron będzie odpalony raz na tydzień czy raz na miesiąc. A te zwroty są jak byk przetłumaczone 'skrzynka/i tygodnia'. Pliki językowe są identyczne dla wszystkich serwisów.

**Comment by harrieklomp** [comment]
This is only for use in translation files. If i translate in Dutch that this i a month cache. When i switch to English or Polish then i read that it is a week cache.
This is what i mean to use two translation options.

Greetings,
Harrie

**Comment by tripper1971** [comment]
OK, masz rację, pod warunkiem że w Holandii ktos się przełączy na wersję polską wtedy zamiast holenderskiego tesktu ze jest to skrzynka miesiaca otrzyma tekst polski ze jest to skrzynka tygodnia (wersje angielskie zakladam ze beda neutralne: czyli titled cache) - tylko na ile jest to prawdopodobna sytuacja ?

**Comment by wrygiel** [comment]
Gdy się przełączy na angielską, też będzie problem. A to chyba jest dość
prawdopodobne w każdym OC. ;)

2015-09-29 21:42 GMT+02:00 tripper1971 <notifications@github.com>:

> OK, masz rację, pod warunkiem że w Holandii ktos się przełączy na wersję
> polską wtedy zamiast holenderskiego tesktu ze jest to skrzynka miesiaca
> otrzyma tekst polski ze jest to skrzynka tygodnia (wersje angielskie
> zakladam ze beda neutralne: czyli titled cache) - tylko na ile jest to
> prawdopodobna sytuacja ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/opencaching-pl/issues/207#issuecomment-144167384>
> .
>



-- 
I didn't fight my way to the top of the food chain to be a vegetarian.
http://rygielski.net/

**Comment by tripper1971** [comment]
Wojtek
Ale pomysł polegał na tym aby w wersji angielskiej zostawić neutralne stwierdzenia, nie odnoszące się do tego czy jest to skrzynka tygodnia czy miesiąca czy też np kwartału. Tam miało zostać tylko stwierdzenia że jest to skrzynka (skrzynki) wyróżnione

**Comment by tripper1971** [comment]
Harrie, OK, I'll reconsider it.

**Comment by harrieklomp** [comment]
Ok. Thanks.

**Comment by harrieklomp** [comment]
This function does work fine on OC sites.
Could it please made it possible that it is visible in other languages. For example go to mainpage of oc.pl and select English or Dutch language. Now this function is not visible. Or got to mainpage of oc.nl and select Polish or English language and here the function is not visible.

It would be great when this is visible in all languages :-)
