### ISSUE TITLE
Problem z paginacją 

### ISSUE THREAD

**Issue by magentos-pl** [opencaching/opencaching-pl#213]
Witamy,
mamy pewien problem techniczny. Jesteśmy użytkownikiem o nicku Zawsze25. Kiedy na naszym profilu wchodzimy: Moje statystyki/Najnowsze wpisy do logów.../pokaż wszystkie - to niestety nie ma szans aby wszystkie zobaczyć. Działa tylko 9 stron. W tej chwili najstarszy widoczny wpis to 19.10.2013 (a nasz najstarszy wpis był 31.08.2013 Leśnik-Bunkier pętla). Teraz jeśli dokonamy kolejnego wpisu, to ten też zniknie i następne itd. Cały czas tylko 9 stron. Bardzo prosimy o naprawienie tego błędu.

**Comment by deg-pl** [comment]
Poprawki te łatają trzy błędy
1. Zgłoszony przez użytkownika Zawsze25 dość specyficzny błąd w my_logsFind.php (i my_logs.php - tego nie zgłosił, ale błąd był identyczny). Polegał na tym, że jeśli ktoś miał między 450 a 500 znalezień, teoretycznie nie mógł zobaczyć swoich najstarszych znalezień, ponieważ za stroną "9" strzałka prowadząca do stron 10+ była szara i nieaktywna.
2. Ograniczyłem ilość "stron" wyświetlanych przez my_logsFind.php i my_logs.php do tych, które faktycznie powinny być wyświetlane. Do tej pory np. jeśli ktoś miał 1-no znalezienie, to w swoich statystykach nadal widział strony od 2 do 9 - zupełnie niepotrzebnie. Teraz wyświetla się tylko tyle stron ile powinno i ani jednej więcej :)
3. Strzałka w prawo przy numerach stron działa poprawnie - jest wyszarzona zawsze na ostatniej grupie stron. Do tej pory szara była tylko wtedy, gdy ktoś miał poniżej 500 znalezień :)
