### ISSUE TITLE
SimpleRouter should check if controller is not abstract class

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#2133]
If somebody tries to reach https://OC/base/something SimpleRouter tries to call abstract BaseController and generates error for user and mail for admins:
`Error: Cannot instantiate abstract class src\Controllers\BaseController
`
SimpleRouter should check if controller is NOT abstract. If is - should return 404 page, not error as above.

**Comment by kojoty** [comment]
should be fixed now.
