### ISSUE TITLE
Require PHP 7.1+

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#2136]
All PHP versions prior than 7.2 has status "end of life" (source https://www.php.net/supported-versions.php)

Currently our code require PHP 7.0+. Now I test on my devel OC code with PHP 7.4 and code require some fixes.
Can we require PHP 7.1+? Version 7.1 introduced nullable declarations of return values - for example:
`public function FromWPFactory(string $wp): ?GeoCache
`
(this means, that method returns GeoCache object or null)

OC PL runs on 7.2.25
OC UK on 7.3.11
OC US on 7.1.31
OC NL on 7.1.31
OC RO - ??? (@andrixnet)

Can we require PHP 7.1+?

**Comment by andrixnet** [comment]
When would this be applied to master? 
My ISP is moving it's infrastructure and I intend to migrate my servers (and doing a fresh system install with this occasion, including newer versions of packages such as PHP). Currently I am waiting for technical and commercial confirmation from them. (it was initiated last week).

**Comment by deg-pl** [comment]
@andrixnet I was sure, that OC RO use PHP7.0+, but now I see version 5.6.40.
When you can upgrade to 7.x? I have done some refactor (see PR #2138), and I wrote code for 7.0+, so it is important.

I suggest you PHP 7.3. I use this version on OC UK without any problems. PHP 7.4 require more strict syntax, and should not be used on OC production servers.

**Comment by andrixnet** [comment]
I have finalized the paperwork with my ISP and will receive a new VPS to migrate to this week.
By the end of the year OCRO will run on newer version of PHP.
Initial deploy will be 7.1, and I will make tests to move to 7.3 too.

**Comment by andrixnet** [comment]
Got a messge from my ISP today. I shall resume work on migrating OCRO to new server.
Initial deployment will be at PHP-7.1 and move to 7.3 as soon as I get a stable package built on my dev machine. Thank you for your patience.

**Comment by andrixnet** [comment]
OCRO has finished migrating to a new server. 
Now running on PHP-7.1.31.

**Comment by mzylowski** [comment]
I believe after @andrixnet comment this issue can be closed?
Feel free to reopen if needed.
