### ISSUE TITLE
Automatyczne tłumaczenia opisów nie działają

### ISSUE THREAD

**Issue by azhag-pl** [opencaching/opencaching-pl#214]
Jeśli przełączymy język strony na inny niż polski, to zamiast opisu strony jest tylko:

> Automatic translation thanks to:
> Technologia Google™

I nic poza tym. Jeśli Google pokręciło i nie da się z tym nic zrobić, to już lepiej zostawić oryginalny opis.

**Comment by kojoty** [comment]
It seems that google introduced paid access to translation api and closed the free version:

> What happened to earlier free versions of Translate API?
> Google Translate API v1 is no longer available as of December 1, 2011 and has been replaced by Google Translate API v2. Google Translate API v1 was officially deprecated on May 26, 2011. The decision to deprecate the API and replace it with the paid service was made due to the substantial economic burden caused by extensive abuse.
[https://cloud.google.com/translate/v2/faq#pricing]

This seems also that the only free option to have translation is to use google translation plugin:
[https://support.google.com/translate/answer/2534601?hl=en]

We need to decide if we want to use it...
