### ISSUE TITLE
Cache can not be displayed.

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#215]
Recently I get this error: 
http://www.opencaching.ro/viewcache.php?cacheid=295

Cache can not be displayed.
Possible causes:

    Cache not found in database
    Cache is not published
    Cache is suspended by OC Team

==================================
This happens for any cache. 

This is from error.log
PHP Notice:  Undefined variable: wikiLinks in /oc_www/lib/common.inc.php on line 279
PHP Warning:  Invalid argument supplied for foreach() in /oc_www/lib/common.inc.php on line 279
PHP Notice:  Undefined variable: cache_record in /oc_www/viewcache.php on line 187
PHP Notice:  Undefined variable: cache_record in /oc_www/viewcache.php on line 197
PHP Notice:  Undefined variable: enable_google_translation in /oc_www/viewcache.php on line 1992
PHP Notice:  Undefined variable: enable_google_translation in /oc_www/viewcache.php on line 2091

According to the last update script run, the code is up to date. 

Database seems to be intact, no crashed tables. 

Also, the main horizontal menu is not seen on the viewcache.php page. 

Thank you.

**Comment by harrieklomp** [comment]
It looks that this is only on oc.ro.
Did you recently change something on your server like your one of the settingsfiles or in the database?

**Comment by andrixnet** [comment]
no changes in my settings file since this spring. 
restarting mysql does not solve the problem.
restarting httpd does not solve the problem. 

I eliminated the wikiLinks error by defining an empty variable in settings.inc.php (my wiki is not available at this time).

**Comment by andrixnet** [comment]
Happens for all caches, regardless of status column in caches table, happens when I am logged in and also when not logged in.

**Comment by andrixnet** [comment]
With help from harrieklomp I managed to isolate the problem and managed to solve it. 
The problem was this: https://github.com/opencaching/opencaching-pl/blob/master/sqlAlters/2015-09-19_cache_titled.sql

Due to sysadmin's family reasons, the site went on working unattended for the past 2 months. The new functionality regarding titled caches and it's SQL changes were not attended to. 

Which reminds of issue #200 that may avoid such situations. 

Thank you.
