### ISSUE TITLE
Login with FB and Google

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#2159]
Some time ago i remember there was a extra config in settings file to login via FB and Google.

`// FB login conf
$config['oAuth']['facebook']['prodEnabled'] = false;
$config['oAuth']['facebook']['testEnabled'] = false;
$config['oAuth']['facebook']['appId'] = null;
$config['oAuth']['facebook']['appSecret'] = null;

// Google login conf
$config['oAuth']['google']['prodEnabled'] = false;
$config['oAuth']['google']['testEnabled'] = false;
$config['oAuth']['google']['clientId'] = null;
$config['oAuth']['google']['clientSecret'] = null;`

Does this work and if yes how should be the settings?

**Comment by kojoty** [comment]
@harrieklomp 
I started to work on this but for now this is still  not done. 
You do not need to do anything with this - just leave it on defaults.
I will come back to this in future or remove it from settings.
