### ISSUE TITLE
code fixes in context of php7.4

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#2207]
Main issue is: 

**Array-style access of non-arrays 
Trying to use values of type null, bool, int, float or resource as an array (such as $null["key"]) will now generate a notice.**

what conflicts with legacy code $usr[...] access - especially when user is not logged.

**Comment by kojoty** [comment]
changes are delivered. Do you know any new issue for php-7.4 in our code? Please reopen if anything is found.

**Comment by deg-pl** [comment]
We have some PHP7.4 issues yet, so I reopen this issue

**Comment by kojoty** [comment]
It seems all nodes running 7.4 so it can be closed
