### ISSUE TITLE
confirmCacheCandidate removal

### ISSUE THREAD

**Issue by jrmajor** [opencaching/opencaching-pl#2228]
https://github.com/opencaching/opencaching-pl/blob/839a9da897714e7762c7d844d4eb6241dcc7e67a/confirmCacheCandidate.php#L3-L4

https://github.com/opencaching/opencaching-pl/blob/839a9da897714e7762c7d844d4eb6241dcc7e67a/src/Controllers/GeoPathController.php#L274-L275

It's been almost two years since these comments were added. Can `confirmCacheCandidate.php` and this method be safely deleted now?

**Comment by kojoty** [comment]
this file is not needed now - feel free to remove it - Thanks!
