### ISSUE TITLE
Remove Garmin plugin support

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#2247]
It seems we still have (non-working) support for legacy Garmin plugin.
![image](https://user-images.githubusercontent.com/2961448/113631657-0df82c80-966a-11eb-9ece-cc6332a2dac5.png)

It can be probably removed from the code.

**Comment by kojoty** [comment]
Legacy garmin plugin is now removed

**Comment by andrixnet** [comment]
Although no longer having any effect, I would like to also remove configuration items for this, items which are outside the repository controlled files. Can you tell node admins which are these items? Besides `$config['garmin-key']`, if any ?
Thank you.

**Comment by kojoty** [comment]
@andrixnet I hope to move all settings from settings.inc.php soon to /config

#2266 has more such things.
I think there is no need to clean legacy settings files for now.
