### ISSUE TITLE
OC site configuration - be more user friendly

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2263]
The new configuration subsystem under /config is an extensive project and much appreciated. 
However at least some of it is by no means user-friendly, nor sysadmin friendly. 

Configuration values should be simple for non-PHP developer persons as well, which, for example:
```$menu = [
    'mnu_cacheAdoption' => SimpleRouter::getLink(CacheAdoptionController::class),```
is not. 

In an older attempt to unify and clean up configurations I was inspired by MediaWiki. 

I respectfully suggest and request improving the /config infrastructure in ways that are friendlier towards non-PHP developer sysadmin **and** documented.

**Comment by kojoty** [comment]
Yes it could be more easy but please consider my arguments:

OC is not something what can be maintain by non technical user at all. Anyone who would like to create own node need someone with basic knowledge about websewers, php, dbs etc. 

Probably it's possible to make /config more readable and maintenable. Now it's quite easy as we have o config class
