### ISSUE TITLE
link to terracaching webservice

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#229]
zgłoszenie do RT:

> piszę w w sprawie linka do alternatywnego serwisu wobec OC.pl. Chodzi mi 
> o terracaching.com. Zmienił się link i nie jest już zaczynający się od 
> www lecz od play, więc np.
> http://www.terracaching.com/Cache/TC9HLN - jest błędny, a poprawny 
> wygląda tak: http://play.terracaching.com/Cache/TC9HLN
> W opencaching.pl nadal błędnie kieruje na 
> http://www.terracaching.com/Cache/...
>

**Comment by mzylowski** [comment]
I think it can be closed now :)

**Comment by wloczynutka** [comment]
W przyszłości możesz w commicie użyć zwrotu np.: 'Fixes #230' i wtedy issue się zamknie automatycznie po wmergowaniu do mastera.
