### ISSUE TITLE
PHP-5.6 and APC

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#234]
Based on the fact that PHP-5.4 has reached End-of-Live cycle from PHP developers and from the PHP-5 generation, PHP-5.6 is currently under active development and will receive security updates for the next 3 years. 
There are however incompatibilities between PHP versions, so PHP applications running on 5.4 may not run 100% correctly on 5.5 or 5.6. 

Furthermore, OCPL depends on APC module for PHP. 
This module has been deprecated and it is not available for PHP-5.5 and 5.6. 
A replacement module exists, under the name APCu, containing the same functionalities as APC (according to stackoverflow, it is 100% compatible) with the exception of opcache, which has been integrated in PHP as OpCache. 

APCu generation 5 does not compile for PHP-5.x
APCu generation 4 does compile for PHP-5.6 but it would also require a review by developers and a fair amount of testing to ensure proper compatibility. 

Without APC, and with advice, I changed a couple of lines in languanges.inc.php, but that is not the only place where APC was used. 

Currently all cron jobs and several other functions of the website are dead. So far I have traced down these: 
lib/userInputFilters/userInputFilter.php
lib/search-signatures.inc.php

Applying the same quickfixes to these got some of the pages working again. (seach, part of cron).

**Comment by wloczynutka** [comment]
apc_ from languanges.inc.php were removed witch commit 6eea692

**Comment by andrixnet** [comment]
Finally managed to compile and install php-apcu-4.0.10 on OCRO. 
The site began working again, now on php-5.6

Without APC (php-apcu), after commit 6eea692, at least cron jobs did not work
and viewcache.php did not work because of lib/userInputFilters/userInputFilter.php

With php-apcu I no longer get the errors related to apc_fetch(). 
This is what I can tell at sysadmin level. If there are other programming level differences, I do not know. 

If this also solves languages.inc.php (before commit 6eea692) and gives better performance, then commit 6eea692 could be rolled back (also if managing the strings as plain text rather then PHP syntax is deemed easier).

**Comment by andrixnet** [comment]
I have the following settings for php-apcu:

```
extension=apcu.so
apc.enabled=1
apc.shm_size=32M
apc.ttl=7200
apc.enable_cli=1
```

Should I change any of these defaults?

**Comment by wrygiel** [comment]
They seem ok to me!

**Comment by wloczynutka** [comment]
> If this also solves languages.inc.php (before commit 6eea692
<https://github.com/opencaching/opencaching-pl/commit/6eea69219d0b25c2ae75cf79fd7c46ca0a2e54c1>)
and gives better performance, then commit 6eea692
<https://github.com/opencaching/opencaching-pl/commit/6eea69219d0b25c2ae75cf79fd7c46ca0a2e54c1>
could
be rolled back

I believe after this commit performance is better. Loading languages were
done not very optimal way before.

Sound good that you've installed succesfully apcu library.

2016-02-09 10:59 GMT+01:00 andrixnet <notifications@github.com>:

> Finally managed to compile and install php-apcu-4.0.10 on OCRO.
> The site began working again, now on php-5.6
>
> Without APC (php-apcu), after commit 6eea692
> <https://github.com/opencaching/opencaching-pl/commit/6eea69219d0b25c2ae75cf79fd7c46ca0a2e54c1>,
> at least cron jobs did not work
> and viewcache.php did not work because of
> lib/userInputFilters/userInputFilter.php
>
> With php-apcu I no longer get the errors related to apc_fetch().
> This is what I can tell at sysadmin level. If there are other programming
> level differences, I do not know.
>
> If this also solves languages.inc.php (before commit 6eea692
> <https://github.com/opencaching/opencaching-pl/commit/6eea69219d0b25c2ae75cf79fd7c46ca0a2e54c1>)
> and gives better performance, then commit 6eea692
> <https://github.com/opencaching/opencaching-pl/commit/6eea69219d0b25c2ae75cf79fd7c46ca0a2e54c1>
> could be rolled back (also if managing the strings as plain text rather
> then PHP syntax is deemed easier).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/opencaching-pl/issues/234#issuecomment-181790817>
> .
>



-- 
__________________________________
*Andrzej 'Łza' Woźniak*

*(+48) 798 835 592*
skype praca: *andrzej.wozniak.traveltech*
skype dom: *wloczynutka*

**Comment by andrixnet** [comment]
Then considering other parts of the code using this library now work, I believe it is safe to assume the following: 
For sysadmins: upgrading from PHP-5.4 to PHP-5.6 requires the removal of APC library and installation of APCu-4.x library. 
For testing and new installations: PHP-5.6 with additional library requirements = APCu-4.x

https://pecl.php.net/package/APCu
Note: latest APCu-4.x is 4.0.10
Note: APCu-5.x does not compile with PHP-5.6, thus version 4.x

**Comment by wloczynutka** [comment]
for testing: on windows I was unable to succesfully install any apcu library for php 5.6.12. If anybody find a way, please share.

**Comment by andrixnet** [comment]
not even apcu-4.x?
