### ISSUE TITLE
Cache map shows no caches (OCNA)

### ISSUE THREAD

**Issue by BonEchoGeocacher** [opencaching/opencaching-pl#2344]
Hello

The cache map on OCNA does not display any caches, and this has been an issue for some time (>1 month). I'm not really sure when this issue started. I tried a different system, browser and checked with another user who reports having the same issue. 
https://www.opencaching.us/MainMap/embeded

Thank-you for your help

**Comment by deg-pl** [comment]
I'm pretty sure, it is problem with your server. We receive plenty of error messages from OC US:
```
===== ERROR MESSAGE =====
ErrorException:
imagegd2(): GD2 image support has been disabled
=========================
```
It suggests problem with GD library. If I remember well, @andrixnet upgraded some libraries related with GD. It was about 1 month ago.  Next he noticed problems - exactly with GD and main map - see https://github.com/opencaching/okapi/issues/619

If you and @andrixnet like, I may help you fix this problem, but I need shell (ssh) access to your server.

**Comment by deg-pl** [comment]
I done little review - in modern libgd libraries (versions 2.3.3+) gd/gd2 format support is removed. So I think we should rewrite some OC PL code (but rather OKAPI).

Workaround for now: downgrade libgd to version below 2.3.3.

**Comment by TermiteHunter** [comment]
Downgrade did not correct issue.

Admin Greater Charlotte Geocaching Club - Charlottegeocaching.com
Admin Open Caching North America – Opencaching.us
