### ISSUE TITLE
Editing cache description without previously configured reactivation rule leads to issue with sending form

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#2345]
Steps to reproduce
1. Go to cache description edit (for cache that reactivation rule is not set yet)
2. Set reactivation option that you choose
3. Try to send form
4. Sending is not possible because form is still asking for reactivation rule.

![Screenshot_64](https://user-images.githubusercontent.com/13780868/158792824-e10e4dbc-0e83-4bd2-a0f9-cd4219143c79.png)

**Comment by rapotek** [comment]
Tried to reproduce in my development site on a few caches as well as on my only cache in opencaching.pl: all is working correctly, I did not manage to get the above effect.

**Comment by deg-pl** [comment]
@rapotek did you try using Chrome?
I have the same problem like @mzylowski

**Comment by rapotek** [comment]
No, I use only firefox for opencaching. Didn't know it is a browser-dependent problem.

**Comment by mzylowski** [comment]
Sorry for inaccurate reproduction steps. I wasn't sure exactly all steps I did.

Great that we have now working fix. Thanks @rapotek and let's merge this. ;)

**Comment by rapotek** [comment]
I thought I named a PR (using "fixes" word) to close this issue on merge, but it is still open. I think it should be closed for now.

**Comment by deg-pl** [comment]
@rapotek you're right!
It's strange a little.
