### ISSUE TITLE
It is possible to log "find" EVENT via mobile version

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#236]
... and even it is possible to give recommendation ;)

![event](https://cloud.githubusercontent.com/assets/13884863/12966536/884e3b9a-d05f-11e5-92e8-16ac0df109b6.jpg)

**Comment by wloczynutka** [comment]
Ja jestem za zrobieniem jednego kontrolera który trzyma pieczę nad wpisami do logów. 
W tej chwili mamy co najmniej 3 luźne skrypty (w wersji zwykłej, mobilnej i okapi). w wersji zwykłej jest bałagan, wersja mobilna jest kompletnie zwalona, okapi z kolei używa kilkudziesięciu zdeprecjonowanych poleceń, wycofanych z nowej wersji php.

**Comment by kojoty** [comment]
ja jestem za poważnym rozważeniem **usunięcia wersji mobilnej**. Nie wiem ilu ona ma użytkowników (od sprawdzenia tego bym zaczął),  ale raz jeszcze w erze c:geo uważam, że to nie ma już racji bytu - no chyba, że znajdzie się ktoś kto miałby ochotę to rozwijać -  i poprawiać takie bugi.

Proponowałbym wstawić tam jakiś baner, poddać sprawę konsultacjom na forum i jeśli nie znajdą się jakieś poważne argumenty za utrzymywaniem tego zdjąć ten kod w ciągu paru tygodni...

**Comment by wrygiel** [comment]
> okapi z kolei używa kilkudziesięciu zdeprecjonowanych poleceń, wycofanych z nowej wersji php.

Napisałeś to tak, jakby dwie pozostałe wersje tych poleceń nie używały - a z tego co wiem, cały kod OCPL używa `mysql_*` ;)

Warto też w tym kontekście wspomnieć, że te polecenia są wycofywane nie dlatego, że są niebezpieczne same w sobie, lecz dlatego, żeby uświadomić deweloperom, że *mogą* być niebezpieczne (chodzi głównie o fakt, że połowa przykładów użycia krążących w sieci jest niebezpieczna - przez co początkujący deweloperzy się źle uczą).

Ze swojej strony mogę zapewnić, że ja byłem tych niebezpieczeństw świadomy na daleko przed tym, jak zacząłem pisać OKAPI. ;) A co za tym idzie, jestem raczej przekonany, że w moim kodzie żadnego SQL-injection nie znajdziesz, mimo faktu, że używa `mysql_*`.

**Comment by wrygiel** [comment]
> Proponowałbym wstawić tam jakiś baner, poddać sprawę konsultacjom na forum i jeśli nie znajdą się jakieś poważne argumenty za utrzymywaniem tego zdjąć ten kod w ciągu paru tygodni...

Moim zdaniem, to dobry kierunek. Jeśli jakiś deweloper z tego korzysta i lubi, to szybko się zgłosi. Utrzymywanie czegoś, czym nikt się nie opiekuje, jest trochę złym pomysłem.

W przypadku usunięcia - trzeba będzie porobić stosowne redirecty.

**Comment by wloczynutka** [comment]
> Napisałeś to tak, jakby dwie pozostałe wersje tych poleceń nie używały - a z tego co wiem, cały kod OCPL używa mysql_

Chciałem tylko zwrócić uwagę, że kluczowe funkcje silnika powinny być realizowane w jednym miejscu aplikacji a nie w trzech. I że każde z tych miejsc nie jest perspektywiczne, bo wszystkie mają głębokie wady.

**Comment by miklobit** [comment]
Ja czasem używam wersji mobilnej i uważam że coś takiego powinno jak najbardziej zostać bo jest  prostą i szybką opcją dostępu do OC niezależnie od posiadanego OS'a w telefonie.
Ale faktem jest,  że powinien być wspólny kontroler do logowania i eventy to nie jest jedyny powód. Inny to np. mobilne  o które walczę z RR i też (ew.) uzgodnione zmiany (dt logowania) musiałby identycznie działać na wszystkich kanałach (www/mobile/okapi)
Jeśli ktoś by się zabrał za zrobienie takiego kontrolera to ja mogę dostosować wersję mobilną.

**Comment by kojoty** [comment]
trochę się ten wątek rozrasta, ale ja bym proponował, żeby **"tym jednym miejscem" do kontaktu z bazą danych było OKAPI** - tj postuluję aby to OKAPI było w możliwie wielu miejscach **"warstwą pośredniczącą"** - uzasadnienie:

- okapi jest obecnie najszerzej używane przez różne zagraniczne serwisy - a kod OC poza okapi tylko przez pl/ro/nl (jeśli zrobimy jakiś kod miedzy okapi a bazą to trzeba będzie go przenieść także na inne serwisy albo robić jakieś haki bla,bla,bla - ogólnie klops)
- okapi jest (w porównaniu z kodem oc) uporządkowane i porządnie utrzymywane i udokumentowane (o ile się orientuję)

sprawa jest rozwojowa i wymaga większej dyskusji, ale moim zdaniem fajnie by było, jakbyśmy szli w tę stronę. Ewentualna przeróbka logowania - moim zdaniem - mogła by się oprzeć na:
- poprawieniu kodu OKAPI - o ile to konieczne
- przerobieniu wersji web i mobilnej tak by kontakt z bazą odbywał się przez OKAPI
- zrobieniu-rozszerzeniu modeli (katalog /objects) tak, by używać ich w wersji web i mobilnej, ale dane pobierać/zapisywać przez OKAPI

**Comment by wrygiel** [comment]
@wloczynutka 
> Chciałem tylko zwrócić uwagę, że kluczowe funkcje silnika powinny być realizowane w jednym miejscu aplikacji a nie w trzech. I że każde z tych miejsc nie jest perspektywiczne, bo wszystkie mają głębokie wady.

No ale ja właśnie nie rozumiem skąd to stwierdzenie, że OKAPI ma "głębokie wady"? Po uwzględnieniu tego, co napisałem wyżej - jakie wady w OKAPI widzisz?

@kojoty 
> okapi jest (w porównaniu z kodem oc) uporządkowane i porządnie utrzymywane i udokumentowane (o ile się orientuję)

Też tak myślę ;) Hue, hue...

Ale mimo wszystko trochę się akcji przeniesienia tego do OKAPI obawiam. Owszem, udostępnienie wszystkiego przez metodę OKAPI, o ile jest porządnie zrobione, ma wiele plusów (przede wszystkim ten, że rozwijają się dzięki temu również aplikacje mobilne). Ale ma też jeden minus - jest po prostu **trudne**. Nie wiem na ile to widzicie i jesteście w stanie oszacować, ale projektowanie zgodnie z zasadą kompatybilności wstecz zajmuje programiście naprawdę dużo czasu, a już szczególnie wtedy, gdy zachodzą zmiany w logice aplikacji. Zaszywanie tego w OKAPI oznaczać będzie, że wszystkie takie zmiany będą musiały być od tego momentu projektowane z uwzględnieniem wszystkich deweloperów aplikacji mobilnych, z uwzględnieniem różnic między OCPL i OCDE, itp. - czy faktycznie ktoś z Was będzie miał na to czas?

Proponuję jednak trochę alternatywne podejście - przeniesienie aktualnej implementacji metody metody `services/logs/submit` do jakieś klasy w OCPL, następnie przepisanie metody OKAPI tak, aby korzystała z tej klasy. Klasa musiałaby implementować interfejs (np. `ILogsSubmitter`), który byłby wystawiony w repozytorium OKAPI, zadaniem programisty tej klasy byłoby trzymanie się tego interfejsu w sposób kompatybilny wstecz. Jednocześnie klasa mogłaby implementować inne metody, spoza tego interfejsu. OKAPI korzystałoby tylko z tych metod, które byłyby w interfejsie. A logowanie przez WWW mogłoby korzystać również z metod spoza interfejsu. Zysk jest taki, że tylko w przypadku wybranych metod musielibyście dbać o kompatybilność wstecz.

**Comment by deg-pl** [comment]
@harrieklomp translate please "attended" and "will_attend" in file mobile/lib/lang/nl

**Comment by harrieklomp** [comment]
Done :-)
BTW. Is it possible to provide issues and changes in English language? This would be better to understand for us.
Thanks in advance.

**Comment by deg-pl** [comment]
Done ;)
