### ISSUE TITLE
Add GA stats to mobile OC site

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#239]
We are currently track main OC site by Google Analitics service. 
It would be great to use GA to track stats for mobile.opencaching.pl as well.

TriPPer knows how to deal with GA.

**Comment by miklobit** [comment]
GA poza tym, że dostarcza googlom kolejnej porcje informacji o użytkowniku (czy sobie tego życzy czy nie) dla nas nie daje nic więcej niż jakikolwiek darmowy analizator logów choćby http://www.awstats.org/.
A analizator od razu pokaże info historyczne a nie dopiero od teraz.

**Comment by kojoty** [comment]
@miklobit, Zgadzam się z tym co mówisz w pełnej rozciągłości. 

Różnica jest tylko taka, że GA mamy od ręki - po dodaniu paru linijek. Jeśli jesteś w stanie stworzyć analogiczne rozwiązanie na bazie analizatora logów to ja jestem absolutnie za. Obawiam się tylko, że ogarnięcie tego zajmie wiele więcej godzin i dlatego proponowałem GA.

**Comment by starypatyk** [comment]
Statystyki awstats są od dawna skonfigurowane. Wyniki (aktualizowane raz na dobę) można zobaczyć pod adresem:
https://opencaching.pl/statystyki/awstats.pl?config=ocpl

PS. Dawno tam nie zaglądałem, więc dopiero teraz zauważyłem, że wygasł certyfikat...

**Comment by kojoty** [comment]
o super, strypatyk zamknął temat :) 

dzięki!

**Comment by tripper1971** [comment]
Ale awstats (wydaje mi się), że nie mierzą czasu wykonania skryptów (mierzenie było wykonywane w kontekście statystyk - jaki mają wpływ na ogólny czas pracy serwera) - od tego się zaczęło moje zainteresowanie GA. 
A skoro już to miałem, to pociągnąłem temat dalej.

Pozdrawiam
triPPer/Jacek

  ----- Original Message -----

**Comment by miklobit** [comment]
Awstats tylko z logu http analizuje ale w sumie to mogłyby czas skryptów też zliczać gdyby był logowany.
Żeby faktyczny czas wykonania skryptu wrzucić do logu (od otrzymania requestu do wysłania pierwszych danych) trzeba by zainstalować mod_log_firstbyte do apach'a. 
W kwestii GA do strony mobilnej - gdyby to miało być dodane to pod tym samym ID  co główna domena czy nowym ? Bo jak pod tym samym to te ścieżki które są identyczne w obu wersjach ( np /index.php )  będę liczone razem a chyba nie o to chodzi.

**Comment by wrygiel** [comment]
> Ale awstats (wydaje mi się), że nie mierzą czasu wykonania skryptów (mierzenie było wykonywane w kontekście statystyk - jaki mają wpływ na ogólny czas pracy serwera)

Google Analytics nie mierzy czasu wykonania skryptów, a jedynie czas ładowania strony - jest dużo różnica między jednym i drugim. Do dokładnego pomiaru czasu wykonania skryptów zawsze wykorzystuje się oprogramowanie po stronie serwera (a nigdy po stronie przeglądarki).

**Comment by miklobit** [comment]
A w tej chwili jaki jest format logu http na serwerze -  ? Jeżeli w logu będzie zapisywany czas obsługi żądań ( parametr %D - czas brutto - od otrzymania do wysłania ostatniego bajtu odpowiedzi, czyli de facto czas ładowania strony) , to można mieć te same dane co z GA ale bez konieczności wołania wszędzie w  kodzie funkcji, które inicjują liczenie.
W Awstats można dodawać (z tego co widzę to chyba nawet bez kodowania) swoje dodatkowe raporty.

**Comment by starypatyk** [comment]
W tej chwili wykorzystywany jest format "combined" posiadający następujące pola:

`LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined`

(oczywiście bez sprawdzenia w dokumentacji nie pamiętam, co oznaczają poszczególne parametry...)

Wydaje mi się, że nic nie stoi na przeszkodzie, żeby dodać pole %D, trzeba tylko dostosować konfigurację awstats.

**Comment by miklobit** [comment]
m.opencaching.pl dodane do GA (na koncie trippera) jako osobna witryna

**Comment by andrixnet** [comment]
subscribe

**Comment by harrieklomp** [comment]
Now OC NL does also have Google Analytics service :-)
