### ISSUE TITLE
New OC devel VM (v9)

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#2392]
Our latest VM (v8) is installed on Ubuntu 16.04 with i386 architecture. That causes many compatibility issues when trying to run the current OC master branch. 
Current master requires PHP at least 7.4, but the best is to have 8.0. Both of those versions are no longer available to be installed.

Things that I tried to update our current VM:
* Update to 18.04 (possible), ends with PHP 7.2. Update to 20.04 (impossible because of not supported architecture (there is no ubuntu available newer than 18.04 for i386 architecture).
* Highly not recommended but I tried twice - running multi arch ubuntu by instructions like this: https://askubuntu.com/questions/81824/how-can-i-switch-a-32-bit-installation-to-a-64-bit-one Both times I completely messed up the VM :D
* Installing PHP 8.0 from a custom repository is also impossible:
All manuals mention about `ppa:ondrej/php` repository to do that, but... https://github.com/oerdnj/deb.sury.org/issues/1922
The only way I see to get php8.0 on Ubuntu 18.04 right now is to obtain PHP deb package files from another place (?) or build from sources (xD).

Due to those circumstances, I believe we need to build OC devel v9 completely from scratch from latest ubuntu amd64 etc.

Generally, I can try to do that, but I need some help:
- [ ] Latest database dump
- [ ] All crons configured currently on production
- [ ] Dynamic files (?)
- [x] PHP configuration files from current prod
- [x] Versions of core packages like PHP, MariaDB etc

But maybe we can workaround this issue for now if someone with a working VM with the current master branch will upload entire disk?

**Comment by kojoty** [comment]
HI @mzylowski 

I can provide for you later today:
- list of packages from prduction
- details of configuration 

Later I will provide fresh db dump for development (it needs some time to prepare it).

Could you also please update / create the list of steps to prepare OC dev VM - just please note everything you needed to do.

**Comment by kojoty** [comment]
I shared the config of OCPL by email - I would prefer to not upload it here...

**Comment by mzylowski** [comment]
Thanks @kojoty 
I started working on this issue here: https://github.com/opencaching/deployment/pull/4 (previously devel-dockerfiles repository) Work for it was never finished and I see no reason to put effort in dockerizing opencaching right now).

My plan is to implement this new devel VM fully as a code (kind of IaaS idea) by ansible deployment. This will give us possibility to just commit stuff to this deployment repository to update VM, and to keep a single point of truth for our OC installation procedure.

**Comment by woliuha** [comment]
支持中文，can sopport Chinese

**Comment by mzylowski** [comment]
@kojoty I'm at the point of development a new VM when lack of current devel VM blocks me. Can you provide some devel dump?

**Comment by mzylowski** [comment]
@kojoty nevermind. For now I took database from devel vm 8.0 and applied all sql alters.

**Comment by mzylowski** [comment]
Closing this one after release of 9.0-beta VM: https://github.com/opencaching/deployment/releases/tag/9.0-beta

All future discussions should be moved to issues in https://github.com/opencaching/deployment repo.
