### ISSUE TITLE
Some style inconsistencies (?)

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2394]
Viewing this cache https://www.opencaching.ro/viewcache.php?wp=OR016B I noticed improper text spacing (red text). 
Upon further analysis, I see that spacing is overridden in viewcache.css as such: 

`div#viewcache-description {
	max-width: 100%;
	line-height: 1.3em;
	font-size: 12px;
}`
The culprit here is line-height, which may be an adequate value for regular text, but not for `<h1>` - a valid markup through the visual cache description editor. 

Also, the following might help with responsivity: 
`div#viewcache-description img {
	max-width: 770px;
}`
to be replaced with `max-width: 100%;`

**Comment by stefopl** [comment]
Done in PR #2396.
