### ISSUE TITLE
Google chats in geopaths don't work

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#2401]
![image](https://github.com/opencaching/opencaching-pl/assets/13884863/ee8d10b1-2ccf-4d7a-8b74-b75b4b6ac631)

From e-mail:
Hej, 

dostałem zgłoszenie, że nie ładują się obrazki (wykresy) w geościeżkach. U mnie też tak jest. Lumen też sprawdzała i też mówiła, że nie ma tego. W załączniku macie screena jak to wygląda. 

dzięki i pozdrówka :)

**Comment by TermiteHunter** [comment]
Appears to be working fine at Opencaching.us
________________________________
From: Grzegorz Deja - deg ***@***.***>
Sent: Thursday, April 11, 2024 4:39 AM
To: opencaching/opencaching-pl ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [opencaching/opencaching-pl] Google chats in geopaths don't work (Issue #2401)


image.png (view on web)<https://github.com/opencaching/opencaching-pl/assets/13884863/ee8d10b1-2ccf-4d7a-8b74-b75b4b6ac631>

From e-mail:
Hej,

dostałem zgłoszenie, że nie ładują się obrazki (wykresy) w geościeżkach. U mnie też tak jest. Lumen też sprawdzała i też mówiła, że nie ma tego. W załączniku macie screena jak to wygląda.

dzięki i pozdrówka :)
