### ISSUE TITLE
403 Forbidden Error After Attempting to Log In on Cache and PowerTrail Pages

### ISSUE THREAD

**Issue by stefopl** [opencaching/opencaching-pl#2409]
#### Affected URLs:
Cache page: https://opencaching.pl/viewcache.php?wp=OP9WQ4
PowerTrail page: https://opencaching.pl/powerTrail.php?ptAction=showSerie&ptrail=2224

#### Error URLs:
Cache page redirection: https://opencaching.pl/UserAuthorization/verifyAuthCookie?target=%2Fviewcache.php%3Fwp%3DOP9WQ4
PowerTrail page redirection: https://opencaching.pl/UserAuthorization/verifyAuthCookie?target=%2FpowerTrail.php%3FptAction%3DshowSerie%26ptrail%3D2224

#### Error Message:
```
403 Forbidden
You don't have permission to access this resource.
Apache Server at opencaching.pl Port 443
```

#### The expected URLs should be:
~~Cache page: https://opencaching.pl/UserAuthorization/verifyAuthCookie?target=/viewcache.php?wp=OP9WQ4~~
~~PowerTrail page: https://opencaching.pl/UserAuthorization/verifyAuthCookie?target=/powerTrail.php?ptAction=showSerie&ptrail=2224~~

**Comment by stefopl** [comment]
The problem seems to be with the configuration of PHP, Apache2, or mod_security, because I can't reproduce the issue on my local or dev

The problem occurs on https://opencache.uk but doesn't occur on https://www.opencaching.ro https://www.opencaching.nl

**Comment by stefopl** [comment]
@deg-pl @kojoty mógłby ktoś na to spojrzeć? Użytkownicy wchodzą na stronę kesza np. z maila lub z c:geo i nie mogą się zalogować. 
Obejściem jest otworzenie strony głównej i zalogowanie się tam, a potem ponowne przejście na stronę kesza co jest uciążliwe a poza tym użytkownicy o tym nie wiedzą. Inna opcja to wyłączenie auto wylogowywania w edycji profilu.

**Comment by kojoty** [comment]
Hej, kurcze nie wyrabiam się lokalnie - postaram się zerknąć w najbliższych dniach

**Comment by deg-pl** [comment]
Ja niestety mam ciężko chorego ojca w szpitalu, opieka zżera mi wiele godzin dziennie (mieszkam 70km od szpitala).
@stefopl jakbym Ci utworzył użytkownika na serwerze, dałbyś radę zdiagnozować problem? Jeśli tak, podeślij mi swój klucz SSH na deg małpa opencaching kropka pl
@kojoty co o tym myślisz?

**Comment by stefopl** [comment]
The intervention of server administrators is needed. https://www.opencaching.ro/ https://www.opencaching.nl/ https://www.opencaching.us/. Due to changes in the .htaccess file, a 500 Error has appeared. A fix that resolves the issue is already in the Git repository, but it needs to be applied manually.

It is also recommended to install and activate mod_version in Apache2.

@andrixnet @harrieklomp

**Comment by andrixnet** [comment]
I get in the error log the following: `.htaccess: RewriteRule: unknown flag 'UnsafeAllow3F'`

Apache is 2.4.58. mod_version is active. 

This after manually updating from repository.

**Comment by andrixnet** [comment]
According to this https://www.apachelounge.com/changelog-2.4.html the new flag was introduced in 2.4.60 so the version check is wrong.

**Comment by andrixnet** [comment]
https://github.com/opencaching/opencaching-pl/commit/a6ba0540affac98843a17a915dcfde6aa8304193
fixes OCRO, OCNL, OCUS.

**Comment by andrixnet** [comment]
Upon server hosting upgrade the version conditionals will be removed. I'll tend to that when the time comes.

**Comment by deg-pl** [comment]
@andrixnet thank you for your quick response!
