### ISSUE TITLE
Description in wrong language after editing

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2414]
I have a cache that has description in RO (site default languate).
I add an alternate description in HU (site short languages list has english, I have to click on "show all languages")

Afterwards, I go and edit the HU description. The language dropdown reverts to "English". If I don't notice this, the description gets saved as EN language.

**Comment by stefopl** [comment]
Hey @andrixnet I see you're active. I made simple fix and PR #2415. Kojoty approved it, so you can merge.

**Comment by andrixnet** [comment]
Thank you.
