### ISSUE TITLE
Editing waypoint coordinates difficulties

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2418]
When creating a waypoint and one types in the coordinates the following behaviours happen: 

1. **add waypoint;** user types degrees; user presses TAB for next input field.
00.000 is briefly selected, then deselected and cursor is placed at the end. 
User must then press backspace to delete these, or use the mouse to select them and delete them. 
This is counter productive. 

In the context of "add waypoint" the input placeholder would be a much better alternative and the javascript should be removed. 

2. **add waypoint;** Also, IMO the "Cancel" button should come second. See #2416 discussion.

3. **edit waypoint;** user types degrees; user presses TAB for next input field.
MM.mmm is briefly selected, then deselected and cursor is placed at the end. 

I would recommend using the same behaviour as the one on cache edit page for cache coordinates, ie without javascript on this field.

4. **edit waypoint;** IMO the order of buttons should be:
[ Save waypoint ] [ Delete waypoint ] [ Cancel ]

5. **edit waypoint;** "submit" button currently uses the same translation string as for the add waypoint page. It should have it's own string saying "Save waypoint" since this is the actual action performed.

**Comment by stefopl** [comment]
@andrixnet are you working on this task? I can do it.

As for 5. I think it's just a matter of translation. In most languages, we have "Save waypoint" which is universal and fits both new waypoint and edit waypoint.

**Comment by andrixnet** [comment]
> @andrixnet are you working on this task? I can do it.

Please do it. 
I am so rusty at this time, I might break more then I would repair :-( 

> 
> As for 5. I think it's just a matter of translation. In most languages, we have "Save waypoint" which is universal and fits both new waypoint and edit waypoint.

Indeed. I agree. My romanian translation was based on the english strings, so those would need correcting first, I believe. Since moving to Crowdin I don't know anymore how to modify these. (rusty again)

Much appreciated.

**Comment by deg-pl** [comment]
@andrixnet You have manager rights on Crowdin.

**Comment by andrixnet** [comment]
Thanks. 
I'll get back onto Crowdin to improve/complete translations.
