### ISSUE TITLE
Logtype 6 is incorrectly interpreted as "need archive" in mobile version

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#243]
Przy okazji grzebania w wersji mobilnej różne "kwiatki" wychodzą. Zaraz to poprawię ;)
![mobile](https://cloud.githubusercontent.com/assets/13884863/13188542/5a0f34ce-d752-11e5-85ee-c4443f97508c.png)

**Comment by deg-pl** [comment]
@harrieklomp and @andrixnet - please make translation "made_service" in mobile/lib/lang/nl|ro and close this issue.

**Comment by harrieklomp** [comment]
Updated Dutch language file.

**Comment by deg-pl** [comment]
@andrixnet - are you here? (ping ;) )
Could you translate "made_service" in file mobile/lib/lang/ro ?
You may even paste translation here, as a comment.

**Comment by andrixnet** [comment]
Sorry I was absent due to health reasons. I will get to it ASAP

**Comment by andrixnet** [comment]
Question before applying translation : I am unsure how to translate this properly. 
Which meaning is closest: 
1) I made service (looks like Google Translated this, sounds awful in english)
2) Cache repaired (but implies damage, while there are other tasks that can be performed under this context which are not necessarily repairs)
3) Maintenance performed (more generic then "repair")

**Comment by deg-pl** [comment]
I think that number 3. (and I think, we should also change the english translation ;) )

**Comment by andrixnet** [comment]
Updated english and romanian translations.
Then I think the "Needs_Translations" label is no longer needed and the issue may be closed.
Please look at my changes:
https://github.com/opencaching/opencaching-pl/commit/07c0fcba0a5040f0b75cf3d15962e751115ceedf
https://github.com/opencaching/opencaching-pl/commit/ec02fb11f2eb0c27e31961c8d03279154e673430
https://github.com/opencaching/opencaching-pl/commit/023b01d62dc4b2d69cad322879cb325926515723

**Comment by kojoty** [comment]
translations are ready - I remove "needs_translations" label..
