### ISSUE TITLE
Undefined property View::$geocache in common_tpl_funcs.php due to invalid URL

### ISSUE THREAD

**Issue by stefopl** [opencaching/opencaching-pl#2434]
An ErrorException is triggered when attempting to access the cache edit page under the following conditions:

- the user is not the cache owner,
- the cache does not exist,
- or the /viewcache.php address is accessed without parameters.

```
ErrorException: [/srv/ocpl/lib/common_tpl_funcs.php(182) : eval()'d code:742] Undefined property: src\Utils\View\View::$geocache
#0 /srv/ocpl/lib/common_tpl_funcs.php(182) : eval()'d code(742): src\Utils\Debug\ErrorHandler::handleError()
#1 /srv/ocpl/lib/common_tpl_funcs.php(182): eval()
#2 /srv/ocpl/editcache.php(1174): tpl_BuildTemplate()
#3 {main}
```

https://github.com/opencaching/opencaching-pl/blob/d0cb7b5e555e3c422112ce19ec2ae035b1467247/editcache.php#L1161-L1175

Replacing ```TODO:``` with ```$view->redirect('/')``` will prevent loading the ```editcache.tpl.php``` template, but is the redirect enough? Or should there be an additional message for the user to inform them about the issue?

I think the problem occurs when the user manually manipulates the URL.

**Comment by deg-pl** [comment]
I think redirect is enough.
