### ISSUE TITLE
"Number of moved caches" and "... recommendations given" = 0 on viewprofile.php

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#244]
Source: http://forum.opencaching.pl/viewtopic.php?p=132740#p132740

http://opencaching.pl/viewprofile.php -> displays "0",
http://opencaching.pl/viewprofile.php?userid=46071 (my ID) -> displays correctly 
![staty](https://cloud.githubusercontent.com/assets/13884863/13191625/5ba34060-d765-11e5-87fb-816c904877c7.png)

**Comment by kojoty** [comment]
poprawka w drodze...

**Comment by deg-pl** [comment]
Śmiga świetnie! To się nazywa szybkość reakcji! Brawo @kojoty !

**Comment by kojoty** [comment]
akurat to było łatwe :)
