### ISSUE TITLE
Cache adoption SYSTEM Note

### ISSUE THREAD

**Issue by stefopl** [opencaching/opencaching-pl#2447]
![image](https://github.com/user-attachments/assets/015fcffb-49ee-4172-81d8-6a5d3b54037f)

Systemowy komentarz dotyczący adopcji zawiera prawidłowe linki do profili użytkowników, ale są one nazwane Użytkownik -> Użytkownik. Czy powinny tu być nazwy użytkowników? 

A może to celowy zabieg, aby uniknąć sytuacji:
- Jeden z użytkowników po adopcji zmieni nazwę, wpis pozostanie niezmieniony.
- Użytkownik został zablokowany, lub jego nazwa została zmoderowana, wpis nadal będzie zwierał dawną nazwę.
- Użytkownik zażądał usunięcia konta/zaprzestania przetwarzania danych będzie trzeba dopilnować, aby takie wpisy poprawić w bazie.

https://opencaching.pl/viewlogs.php?logid=4688122

![image](https://github.com/user-attachments/assets/3bf596db-d41a-42e2-89a1-dc0fd9d633e3)

**Comment by deg-pl** [comment]
To jest celowe działanie i nie powinno być zmieniane. Powody są dwa:
- użytkownik w przyszłości może zmienić swój nick i wtedy wpis w logach byłby nieaktualny
- użytkownik może zażądać zaprzestania przetwarzania danych osobowych. Anonimizujemy wtedy nazwę użytkownika (bo może mieć w formacie JanKowalski), a wszystkie wpisy do logów pozostałyby bez zmian - z danymi osobowymi, co byłoby złamaniem RODO.
