### ISSUE TITLE
No pictures shown in new VM devel

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#245]
I do not know if this is a issue in the new VM but there are no pictures visible. Is there someone who has the same problem in newest VM version 6? Or is it a setting that i missed?

![selectie_129](https://cloud.githubusercontent.com/assets/1060518/13191735/130569b8-d766-11e5-82a8-4c8c03e05e62.png)

**Comment by wrygiel** [comment]
No pictures were uploaded to the version of VM. (If we wanted to upload all the pictures, this would increase the size of the VM to ~10 GB.)

**Comment by harrieklomp** [comment]
That is correct.
I mean when i log a cache on the VM and upload a picture it will be stored on the VM. The last screenshot does show that on the bottom.

**Comment by wrygiel** [comment]
Ok, I understand now! Seems to be a bug in the settings then. I will try to take a look at it next time I will be upgrading VM (possibly in March).

**Comment by harrieklomp** [comment]
:+1:
