### ISSUE TITLE
COG: Notatka dot. uzytkownika

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#246]
> Do napisania tego maila natchnęła mnie m.in. sprawa XXX, który miał nałożoną weryfikację nie wiadomo dlaczego.
> 
> Proponuję wprowadzić możliwość wpisania notatek do użytkowania strony. Notatki podobne do notatek, które można napisać przy skrzynce, ale widoczne dla wszystkich członków COG i RR.
> Ktoś daje bana, ktoś umożliwia zakładanie skrzynek bez limitu, dostajemy zgody nieletnich itp. Ludzie w COG się zmieniają, przestają pamiętać i nie ma śladu. Owszem jest forum, ale znaleźć tam cokolwiek coraz trudniej. A tak ślad zostawałby zawsze do sprawdzenia.
> Widzę dwie możliwości implementacji:
> 1. przy "grzebaniu" w ustawieniach użytkownika pojawia się okienko do wpisania i nawet  brak wpisu zostawia login.
> 2. Tylko okienko, pozostawiając wpisy uczciwości użytkowników.
> 
> Co sądzicie o tym pomyśle? 
> Nie znam się na php, ale myślę, że nie byłoby wiekszego problemu z wprowadzeniem, szczególnie punktu 2 (podobny moduł jak notatki do skrzynki).
> 
> Pozdrawiam Paweł   / brasia - COG
---------------------------------
> Cześć,
> jestem za, bo tak powinno być od dawna, że ktokolwiek coś robi to pisze dlaczego, na jak długo i takie tam… .
> Popieram.
>  
> Pozdrawiam
> szanto/COG
> pomorskie

**Comment by harrieklomp** [comment]
This new page looks very nice :+1: 

Now this is for only one user/account. Is it also possible for the same admin to get a list from all users who have a case like "banned"?
For example: I have banned a user for one month and banned another user on a different date also for a month. As Admin i have to remember that these users have to be unbanned after some time.

A list of users who are banned and users who needs all new caches to be approved would be good.

If this is unclear please ask me :-)

**Comment by kojoty** [comment]
Harrie, I think this is another thing and It sounds reasonable.
I create separate issue for this enhancement to not forget about this idea :) 
#265

**Comment by kojoty** [comment]
@mzylowski kilka uwag, jak by to jeszcze lekko rozszerzyć:
- nie mamy chyba logowania dodania akcji: ignoreFoundLimit z panelu COG - podpowiedz mi - to zostało świadomie pominięte?

...i takie ujednolicenie tego co można zrobić/zobaczyć z profilu użytkownika i panelu COG
- w panelu COG chyba fajne by było okienko, w którym można dodać notatkę - analogicznie jak w profilu użytkownika - dla wygody admina
- może by tak ta sama tabelka z historią akcji admina mogła być wyświetlana w panelu COG pod danymi użytkownika...

co myślisz? może miałbyś ochotę już z rozpędu i to zrobić?

**Comment by mzylowski** [comment]
ignoreFoundLimit przeoczyłem, wieczorem dokładnie na to zerknę
Jak mi się uda to w sobotę będzie commit.

**Comment by mzylowski** [comment]
Tak to widzę:
Na stronie http://opencaching.pl/viewprofile.php?userid=X widoczna jest tylko tabelka z informacjami + odnośnik na stronę http://opencaching.pl/viewprofile.php?userid=X
Na stronie http://opencaching.pl/admin_users.php?userid=X widoczna jest tabelka oraz możliwość dodawania informacji o użytkowniku (okienko do wpisania).
Myślę że przenoszenie zawartości z admin_users jest do profilu jest trochę bez sesu. Albo statystyki użytkownika, albo zarządzanie nim.

@kojoty Co uważasz?
