### ISSUE TITLE
Fix of map links in cache desc.

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#247]
> Czołem
> pod mapką na stronie kesza są linki do dużych map: Opencaching, OSMapa, itd. i wreszcie Automapa. Chodzi o to, że link Automapa otwiera szukacz.pl, który używa map OSM. Więc link nie jest potrzebny bo się dubluje z OSMapa, ewentualnie wypada go nazwać Szukacz.
> ## 
> 
> Alf/red/

**Comment by deg-pl** [comment]
Wydaje mi się, że ten link jest po prostu niepotrzebny, szczególnie, że używa OSM.

**Comment by kojoty** [comment]
trzeba by to zbadać dokładnie, bo szukacz to chyba coś więcej niż osm - ale może ja się mylę bo ja tego nigdy jakoś nie używałem... jak dla mnie mapa oc jest najbardziej użyteczna niemal zawsze

**Comment by deg-pl** [comment]
Automapę na Szukacz zmieniłem (strasznie się napracowałem :D ), a przy okazji zmieniłem opis mapy "Opencaching.pl" na "Opencaching", bo link ten kieruje do lokalnej wersji serwisu, a nie do PL.
Pozostały tematy do zastanowienia się i zrobienia:
- zmiana tego fragmentu kodu na międzynarodowy. Bo na chwilę obecną wszystkie kraje korzystają z tych samych map - właściwych dla Polski.
- zastanowienie się czy ten link ma sens, czy ktoś używa takich map
- naprawa/usunięcie Zumi

**Comment by harrieklomp** [comment]
There are different maps available on the site and from my point of view, it is useless for other nodes like .nl and.ro. There are two sulutions.

- Move these maplinks to settings file. Now every node can change the name and/or link.
- Remove the links. People can click on the small map itself or go to a larger map on the site.

**Comment by kojoty** [comment]
> Move these maplinks to settings file. Now every node can change the name and/or link.

In my opinion links are quite useful (for me especially link to google maps) and I think this is the  best way to solve it

**Comment by harrieklomp** [comment]
Than moving it to settings file could be a good solution.
But i cannot program this so it would be nice when a programmer can do this :-)

**Comment by kojoty** [comment]
I created separate issue on implementation of config for the links  #255.

Another question here is: which links currently at oc.pl are valuable?
I think that Zumi should be removed as useless...

**Comment by deg-pl** [comment]
I think that "Szukacz" should be removed too...

**Comment by deg-pl** [comment]
"Szukacz" now is working fine, Zumi is removed, maps are per node configurable ($config['maps']['external']).
