### ISSUE TITLE
Make the links to maps in cache desc. configurable by settings file

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#255]
this is continuation of #247 

@deg-pl 

> Automapę na Szukacz zmieniłem (strasznie się napracowałem :D ), a przy okazji zmieniłem opis mapy "Opencaching.pl" na "Opencaching", bo link ten kieruje do lokalnej wersji serwisu, a nie do PL.
> Pozostały tematy do zastanowienia się i zrobienia:
> 
> zmiana tego fragmentu kodu na międzynarodowy. Bo na chwilę obecną wszystkie kraje korzystają z tych samych map - właściwych dla Polski.
> zastanowienie się czy ten link ma sens, czy ktoś używa takich map
> naprawa/usunięcie Zumi

@harrieklomp

> There are different maps available on the site and from my point of view, it is useless for other nodes like .nl and .ro.

**Comment by deg-pl** [comment]
Now is configurable via $config['maps']['external'], so I close this issue.
