### ISSUE TITLE
It is possible to rate DNF cache via Field Notes (via log_cache_multi.php or log_cache_multi_panelframes.htm)

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#262]
![dnf](https://cloud.githubusercontent.com/assets/13884863/13298192/11610e54-db36-11e5-8413-430a384a8eb1.png)

**Comment by andrixnet** [comment]
I presume this issue is about the fact that one can load "field notes" and submit a DNF log and be able to rate the cache, but one should not be able to rate a cache with a DNF log.

**Comment by deg-pl** [comment]
Yes. Exactly!
