### ISSUE TITLE
Set date only one when user log few caches

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#268]
I have idea about cache logging.
When user have a lot caches to log, and all of those caches are found in the same day it is unnecessary to change date over and over again.
We can just save date somewhere (for example in $_SESSION) when user logged first cache and retrieve it in next logging.

What do you think?

**Comment by wloczynutka** [comment]
duplicated: https://github.com/opencaching/opencaching-pl/issues/144, please continue discusion there.

**Comment by mzylowski** [comment]
Sorry, I missed that one..
