### ISSUE TITLE
removing mysql_* from ocpl code

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#276]
The purpose of this issue: collect all our points of view + ideas about why, when, and how to remove all mysql_* calls from oc.pl code.

Let's conclude:
- we need to do that because of incoming php7 without mysql_* - am I right?
- we want to migrate to php7 because EOL of php5* (what will happen in ???)

Let's use this issue to discuss those things...

**Comment by wloczynutka** [comment]
- mysql_* is not safe and were depreciated since php 5.5 
- php 7 is not 'incoming'. It was published few moinths ago and now is most recent and most optimal envoriment to run php applications.

**Comment by andrixnet** [comment]
Correct. And almost.

On the development side, PHP-7 is the next step, with significant work
to be done to make the code compatible with this new version of the
interpreter, where many things have changed.

On the system administration side, PHP-7 is definitely still "brand new"
and has yet to prove itself in the fields of stability, reliability and
security.
being so new (rewrite and lots of new code), there will definitely be a
good number bugs and security issues related to the rewrite process yet
to be discovered and fixed.

On the management side, one should consider moving in 2 directions:
a) maintain production applications on PHP-5.6, currently actively supported
b) plan on developing future applications on PHP-7
c) work on development and testing of existing (production) applications
to be able to migrate them to PHP-7 in the medium-term future.
(that is while current 5.x branch is actively supported)

**Comment by kojoty** [comment]
OK, colleagues: I've done fast review and I can take this challenge - I believe I can do that in finite time :) 

There are > 1600 of calls of mysql_* but there are only a few mysql_* used cases and it seems that refactoring of them is not so difficult and it can be done in parts - step-by-step. 

I found used cases:
- execute sql query: **mysql_query($sql)**
- get result row number: **mysql_num_rows($rs)**
- get data from result in 3 forms: 
   - **mysql_fetch_array($rs)**
   - **mysql_fetch_row($rs)**
   - **mysql_result($rs,0)**
- free the results - **mysql_free_result($rs)**
- and rare:
   - **mysql_escape_string($string) / mysql_real_escape_string($string)**
   - **mysql_errno() / mysql_error()**
- and also rare around db connection:
   - **mysql_pconnect**
   - **mysql_select_db**
   - **mysql_close**

in addition:
 - sql() should be also change to the "new form"

**but I need your help** in creation of the conception of the "new solution" which will be implemented across the whole code. Let's describe how communication with DB _should_ be done.

My simple and fast solution:
[https://docs.google.com/document/d/1QM7xuQ0Ptb7kvWZ1TRoC0Hr42LgCgecknC4VSPgJpc4/edit#heading=h.vg3ji92tc6iq]

**Comment by wloczynutka** [comment]
Powiem ci, że proste i chyba ganialne. Tej sikry mi brakowało.
Wyjdae mi się, że wystarczy do istnejącej już naszej klasy bazodanowej dataBase (leży w lib/Database/Db.php) dodać następujące metody:

	public static function query($sqlQuery, $params)
	{
		$this->simpleQuery($query, $params);
		return $this;
	}

	public static function numRows(dataBase $dbObj)
	{
		return $dbObj->rowCount();
	}

	public static function fetchArray(dataBase $dbObj)
	{
		return $dbObj->dbResultFetchAll();
	}

	public static function fetchRow(dataBase $dbObj)
	{
		return $dbObj->dbResultFetchOneRowOnly();
	}

	public static function freeResult(dataBase $dbObj)
	{
		$dbObj->reset();
	}

i to powinno załatwić część zagadki. pozostanie wymyślenie zastąpienia funkcji do eskapowania stringów.

**Comment by wloczynutka** [comment]
Auto-poprawka: nie trzeba dodawać do istniejącej klasy, można zrobić odrębną, korzystającą z klasydataBase

**Comment by andrixnet** [comment]
PHP support information can be found here: http://php.net/supported-versions.php
PHP-5.6: 
 - active support until 31 Dec 2016 	in 9 months
 - security support until 31 Dec 2018 	in 2 years, 9 months

PHP-5.5 support ends in 4 months.
Older versions are no longer supported. 

Please note that PHP-5.6 and PHP-7.0 releases have similar support lifetimes.

**Comment by wloczynutka** [comment]
@kojoty mogę pomóc. Proponuję zrobić gałąź w głównym repo i tam commitować zmiany.

**Comment by kojoty** [comment]
@wloczynutka, super ;)
Moja wizja zatem:
- po pierwsze nie robić tego na branchu - jak zrobimy 1600 zmian w kodzie to później zintegrowanie tego z tym co się zmieni w międzyczasie i przetestowanie całości będzie trudne - zamiast tego commitować kolejno małe, ale przetestowane zmiany - w ten sposób będziemy stale na bieżąco i kod na każdym (po każdym commicie) powinien zawsze działać bez błędów 

- po drugie review istniejącego kodu dostępu do db - ja się dobrze na tym nie znam - tzn. nie do końca wiem jak najlepiej powinno to być zrobione (w kontekście wielu procesów apacha, połączeń persistent, statycznych zmiennych w php etc.) ale mam nadzieję lekko zgłębić ten temat z Twoją pomocą :)
ja popatrzę dziś na to i może jak temat okaże się skomplikowany to może nawet byśmy sobie jakieś spotkanie na skypie ustalili - ale to zobaczymy czy będzie o czym debatować...

- po trzecie jak już wspólnie ustalimy jak powinna docelowo wyglądać klasa db jestem za tym by kolejno zmieniać pliki - umówimy się kto zaczyna z której strony tak by nie wchodzić sobie w drogę i do dzieła...

co o tym myślisz?

**Comment by wloczynutka** [comment]
Pełna zgoda.

**Comment by kojoty** [comment]
@wloczynutka, 
popatrzyłem, coś poczytałem i mam kilka drobnych wniosków do dyskusji:

1. Poprawmy nazwę klasy DB: `database` -> np. `Db`
    - to będzie często używane, niech nazwa będzie krótka i klasa wielką literą 
    - to można zrobić jednym commitem w całym kodzie
    - to jest pierdoła, nie wiem jak ciebie, ale mnie kłuje w oczy :) 

2. Zintegrujmy `DataBaseSingleton` z `database`:
    - niech obiekt bazodanowy będzie się pobierać przez `Db::instance()`
    - ewentualnie może zostać jak jest tylko zmieńmy nazwę klasy na `DbSingleton`

3. czemu nie ustawimy: `PDO::ATTR_PERSISTENT => true`

4. Dlaczego `PDO` jest zamknięte wewnątrz klasy `dataBase`?
    - nie można by zrobić tak by database dziedziczyła po PDO i całość funkcjonalności PDO była dostępna na zewnątrz?
    - funkcje które ułatwiają/upraszczają użycie PDO mogły by zostać - jeśli są użyteczne
    - \.\.\.ale po co coś takiego: 
```
                 public function dbResultFetch()
                 {
                    return $this->dbData->fetch();
                 }
``` 
zamiast po prostu wołać `$db->fetch()` prosto z` PDO`?


**Jakbyśmy to wyjaśnili i ewentualnie wdrożyli jakieś zmiany, można by się wziąć za przerabianie kolejnych plików. Co ty na to?**

**Comment by wrygiel** [comment]
BTW, w ramach wątku #180 stworzyłem swego czasu klasy `MyDB` i `MyPDO` (nazwałem je "My" w celu odróżnienia od architektury, którą pisał równolegle Łza). Jeśli planujecie robić jakiś porządek w tym zakresie, to może warto przy okazji je albo usunąć, albo zintegrować z pozostałymi. Ta moja klasa `MyPDO` dziedziczy z PDO, a `MyDB` służy do pobrania singletona.

**Comment by wloczynutka** [comment]
@kojoty 
1. słusznie, większa czytelność i zgodność z psr
2. może być, tylko trzeba będzie wyłapac w kodzie wszystskie użycia bez singletona. 
3. nie wiem do czego to służy, a w tym momencie nie mam czasu się dokształcić, więc się nie wypowiem
4. bo klasa jest nie najlepiej, a może raczej trzeba powiedzieć, źle napisana.

śmiało implementuj.

W międzyczasie próbowałem zrobić test i dostawić te metody statyczne o których pisałem wyżej i na jednym pliku pozamieniać wywołania. To mniej więcej jest w stanie działać. (doszło jeszcze przeparsowanie zapytań - zamiana z $1, $2 ... na :1, :2 ...). Trzeba będzie jednak coś wymyślić z wywołaniami mysql_real_escape_string, albo przerabiać ręcznie

**Comment by wloczynutka** [comment]
mysql_real_escape_string jest 53 sztuki 
czym to bezpiecznie zastąpić? Nie mam pojęcia. To dosyć wrażliwe miejsce.

**Comment by wloczynutka** [comment]
internety mówią ze można tak: http://stackoverflow.com/questions/1162491/alternative-to-mysql-real-escape-string-without-connecting-to-db

**Comment by wloczynutka** [comment]
A co myślicie o użyciu jakiegoś komponentu bazodanowego z jakiegoś frameworka (np. doctrine)?
(http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/data-retrieval-and-manipulation.html)

**Comment by wrygiel** [comment]
> A co myślicie o użyciu jakiegoś komponentu bazodanowego z jakiegoś frameworka (np. doctrine)?

Tego rodzaju frameworki, jeśli w ogóle oferują cokolwiek więcej niż "czyste" PDO, to zwykle są to funkcjonalności ściśle związane z tymi frameworkami. A jeśli tak jest, to warto to robić raczej tylko wtedy, gdy chcielibyście całkowicie przerzucić MVC na frameworka.

**Comment by kojoty** [comment]
w sumie wrygiel powiedział co myślę
dodatkowy minus to konieczność dostosowywania obecnego kodu do "jakiegoś" rozwiązania...

ja też jestem ostrożnie przeciw.

**Comment by kojoty** [comment]
@wloczynutka @wrygiel Zerknijcie proszę i dajcie znać co myślicie na temat mojej wizji bo chciałbym ruszać z refaktoringiem kodu. 

W katalogi /Utils/database są 3 nowe klasy bazodanowe:
- OcPDO - to PDO + kode debugowy i inicjalizacja w ramach OC
- OcDb - to funkcje z dotychczasowej klasy /lib/Database/database (lekko tylko miejscami coś tam zmieniłem / dostosowałem)
- XDb - to wrapper na OcDb który ułatwia jedynie refaktoring (ma proste odpowiedniki funkcji, które trzeba usunąć)

Proces widzę tak:
 - będę zmieniał kolejno pliki, tak by kolejne pliki przechodziły na używanie wyłącznie kodu bazodanowego z /Utils/Database
- będę starał się testować na bieżąco, niemniej mogą pojawić się jakieś problemy - czasem ciężko może być wyłapać wszystkie zależności albo ścieżki na jakich skrypt jest wykonywany
- zmian jest duuużo, ale jestem optymistą
- pierwszy zmieniony plik: jako przykład macie w pullrequescie XXX (zaraz zrobię)

**Comment by wrygiel2** [comment]
Najblizszych pare dni bede na delegacji w Brukseli, raczej nie dam rady
dokladniej obejrzec. Ale ogolnie mam silne wrazenie, ze robisz to dokladnie
tak, jak ja sam bym to zrobil :)

**Comment by wloczynutka** [comment]
Jak dla mnie super. 
Fajnie sobie poradziłeś z mysql_escape. Nie wiedziałem że tak można :+1:

**Comment by wloczynutka** [comment]
@kojoty mogę parę plików dziabnąć. Przydziel mi jakieś 5 sztuk, (żebyśmy się nie zdublowali) to będę łatał w wolnych chwilach.

Chyba że np. chciałbyś, żeby przerobić cały moduł geoŚcieżek na użycie nowych klas, to mogę się tym zając.

**Comment by kojoty** [comment]
wiesz co, może ja już to pociągnę w całości to będzie jednolicie co? - ja już tu powoli sobie automatyzmy wyrabiam w rozpoznawaniu tego jak to podmieniać

Ty na pewno nudzić się nie będziesz w międzyczasie... 

(np. nie wiem czy wiesz, że zrobiłem kiedyś parametr do mapy_v3: przykład [http://opencaching.pl/cachemap-full.php?pt=178] do wyświetlania geościezki - można by to jakoś zintegrować z geościezkami (jakiś link-button czy coś?)

co do geościeżek:
wydaje mi się, że tam gdzie już były używane klasy z /lib/Database wystarczy tylko inicjalizację podmienić na OcDb::instance()  i wszystko powinno działać... więc pracy to tam nie ma - no pewnie trzeba by to potestować czy wszystko działa - bo może wystąpią jakieś problemy - jak z myprofile...

**Comment by kojoty** [comment]
**OK Success! I commit the last pack of changes around this subject: we don't have mysql_* in code now**
A few stays in obsolete and not used util.sec scripts I left for further decision...

@wloczynutka 
I think now I can refactor the rest of DB access code to use only code from Utils/Database - but I'm going to open separate issue for this change...

I think this issue can be closed now :)
