### ISSUE TITLE
Registration activation email

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#285]
Registration activation email contains a code to confirm your account and a link where to enter that code. 
Problem: the code is listed only as plain text
Suggestion: the code should be listed both as plain text and as a clickable link that automatically performs the activation. 
This should dramatically simplify the registration and activation process and improve the overall initial user experience. 

Second, the activation email contains lots of informative text that is useful, but is not the primary concern for this email, yet it is located at the top. User must scroll and search for the activation sequence. 
Suggestion: Make the activation email do just that: activate the account. 
Either move the informational text below the activation text, or generate a new "welcome" email after activation, email which will contain this informational text. 

Third: this email contains info about the rules regarding publishing new caches (must find at least 10, your first 3 will be moderated). 
While this is listed as separate translation strings, these strings should only be included if this functionality is enabled in settings (on OCRO it is not) and the limits described should be taken from settings instead of being hardcoded in the translation text. 
As such, they are not valid across nodes.

**Comment by mzylowski** [comment]
Solution posted here, should solve #465 in more elegant way than now.
