### ISSUE TITLE
Translation clarifications

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#298]
I am opening this issue in a general way, with the intent on having it open indefinitely (any string addition may spawn the need for clarification), or at least until translation can be handled by a collaborative platform such as crowdin.net that has support for this kind of problems. 

Since the project originated in a non-english speaking country and [some] translations (including english) was at least in part done by the help of Google Translate rather then people, there are quite a number of strings which are incorrect gramatically, do not sound like that language (I'm talking mainly english here), or make little sense. 

I am concentrating on english since it is the widest spoken language in computers and it has adapted very well and efficiently to computing, and can be used as a common base to translate strings into other languages, since more people know english well and can derive meaning in their own native language from it. 

I am opening this issue as a place for discussion on each such string whose translation might be improved.

If someone can suggest a better method of handling this kind of problems, by all means, pray tell. 
Thank you.

**Comment by andrixnet** [comment]
Many strings related to searches use the work "seek". 
In the context of a search page, which verb is better ? 
(seek a cache; seek a cache in region, etc)
1) seek
2) find
3) search
4) other?

**Comment by harrieklomp** [comment]
Why not look at oc.us? Those guys do speak that language very well ;-)

**Comment by andrixnet** [comment]
Some strings seem to be tailored very specifically towards OCPL node. 
For example reportcache07 to 09; cacheStatus_6; viewPending_19; cacheArchived_04; 

The translation of these is not adequate as multi language string because they refer to acronyms specific only to OCPL node. For example polish language version of the string on OCNL/OCRO would be wrong because the acronym is only valid for OCPL community in Poland.

**Comment by andrixnet** [comment]
@harrieklomp you may be right about oc.us, but is it based on current opencaching-pl code? AFAIK it is not. Even if it was based on opencaching-pl code at some point in the past, even if we gain access to their source code, strings are bound to have different meanings since it has evolved differently...

**Comment by andrixnet** [comment]
Also there are several empty strings in english file defined as 
'' => '',

**Comment by harrieklomp** [comment]
Your mentioned translations.
- reportcache07 to 09. (If oc.pl agrees). Remove OC PL so this will be a common translation. This i have done in Dutch translation. 
- For cacheStatus_6; viewPending_19; cacheArchived_04. Replace COG with OC-Team. This also if Polish COG agrees.

These only are suggestions so we can talk about it.

**Comment by andrixnet** [comment]
The example @harrieklomp refers to has another side to it. There are strings and texts that actually need to exist in each language, but on a per node basis. 

For example: cacheStatus_6; etc make sense and is probably deeply rooted and established in Poland to say "COG Team" and it's meaning is clear and powerful. And makes sense on OCPL to have "COG Team" in all languages for this string, because this is valid in Poland. 

On the other hand, on OCNL and OCRO (and other future nodes based on this code) the term "COG" has no meaning (being a polish only acronym) and "OC-Team" (or smth similar) makes more sense and have this in each language shown on these nodes. 

This is another facet to the translation problems.

**Comment by andrixnet** [comment]
english strings: 
'no_note' => 'I don"t have any cache note',
notice the " (double quote) character in don't. 

This is incorrect english. There are other strings in the english file with the same problem. 
One with better experience with PHP quoting and escaping should take a look. 
Thank you.

**Comment by wloczynutka** [comment]
double quote inside of transaltion string can be replaced witch \'

**Comment by kojoty** [comment]
I generally agree with the main object of this thread which I read as: _english in our translation is not perfect._  

I see many separate threads here and most of them are just a defects, and it should be fixed so I think that every of us:
-  can just submit a change as a pull request - then we can all review and optionally discuss the fix
-  open separate issue if [don't want / can't / don't have a time] to fix it yourself, and then other person fix it in a future

I think we can continue this discussion but lets mark it as **"general discussion"** to be sure that it can be easy distinguished from problems/new ideas which are waiting for fix/implement.

**Comment by kojoty** [comment]
I also made a label Component_Translation to mark issue around i18n of the code. Can it be like that?

**Comment by andrixnet** [comment]
Yes, of course. :-) 
My english is not perfect either, but I think I can contribute some to improving the english strings with the help of my wife, who is an english language teacher and has a master's degree in translations.

The main purpose of this thread, as I opened it, would be to discuss which would be the best (or closest meaning) translation for a certain string, given the context and original meaning. 
I would also help a lot in improving the romanian translation and in the future the addition of a hungarian translation. 

Thank you very much.

**Comment by wrygiel2** [comment]
@andrixnet, I think you use better English than most OCPL programmers.
Perhaps you should just fix it the way you think is appropriate, and then
let us review your changes. I speak both Polish and English quite fluently,
so I would be able to pinpoint any logical differences.

**Comment by andrixnet** [comment]
Very well. I shall proceed that way and request reviews. 

However I am still seeking advice on how to proceed with strings that are node specific across all languages. 
Thank you.

**Comment by wrygiel** [comment]
The sad fact is, I don't have time to read all OC emails recently. :( I can review a commit, but I won't be able to read all the discussions in the issue tracker. But hopefully others will help you!

BTW, GitHub recognized my as @wrygiel2 instead of @wrygiel. ;) Probably it's because I sent it from my phone, which is perhaps associated with a different email address...

**Comment by andrixnet** [comment]
viewcache page, top part, basic statistics, also bottom, logs. 
When one write a log type "write note" it is called "note". 
When seen in statistics and log entries, they are called "comments". 

Which term applies best ? (should be unified)

**Comment by andrixnet** [comment]
What does `tpl_set_var('search_time', 'b.d.'); ` stand for? 

Is `b.d.` polish equivalent for `N/A` (not available) ?

**Comment by wloczynutka** [comment]
yes.

**Comment by andrixnet** [comment]
@wloczynutka then I will add a new string insteand of several hardcoded instances.

**Comment by wloczynutka** [comment]
I'm glad, please go on.

**Comment by andrixnet** [comment]
What about https://github.com/opencaching/opencaching-pl/issues/298#issuecomment-203412491 ?
