### ISSUE TITLE
Google Analytics - OCPL only

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#300]
In file /lib/js/ga.js there are references to OCPL specific data.
`ga('create', 'UA-45656189-1', 'opencaching.pl');`

This is only for tracking on opencaching.pl node. I presume it does not work on other nodes, having different domains (?)

Is there a way to adjust this such that each node may use it's own Google Analytics tracking account without the need to actually set this in the repository?

**Comment by kojoty** [comment]
good point, we should do that :)
@tripper1971 is that possible that GA shows sum of statistics for all nodes (nl,pl,ro) now?

**Comment by tripper1971** [comment]
Now, GA shows stats only for .pl
If you want to see stats for .nl or .ro you should register these in GA

Jacek

  ----- Original Message -----

**Comment by andrixnet** [comment]
And how can this be done in a way available to node admin, without
intervention in project repository?

**Comment by andrixnet** [comment]
Fixed according to https://github.com/opencaching/opencaching-pl/issues/769
