### ISSUE TITLE
Continuing oc.nl

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#301]
In 2013 i decided as owner of oc.nl to change the German code for the Polish code. This because the site looked still as the original OC site and there are more very great functions.
I did get all the help i needed to make the site work like it is now and i thank you all for this.

After several years the code has turned out from mostly hardcoded Polish to a international site with complete translations. I spend very much time to translate and if possible develop or change some things without any knowledge about programming. Yes, i am proud of myself, but making the code international was not possible without the help of LZA and others. Also i did submit some issues and most are solved by Polish developers and some issues are still there. Those issues who are still open can be solved but not necessary needed to be solved, so be it, i am a very easy person.

Running a international site comes with different opinions, people and problems, we all know that. BUT......

When i ask in a friendly way if a function can also implemented via settings file (sorry LZA, nothing personal :-) ) like asked on [this commit](https://github.com/opencaching/opencaching-pl/commit/e33ea16f3694866f881e35d321d3cc2e6613395f#commitcomment-16511880) i do expect a less rude answer or a answer with a undertone. I only did ask this because oc.nl has not that much caches like oc.pl has and oc.nl also not have that much logs to do two caches of the week on the main page. Believe me when i say that i wish it was better on oc.nl after so many time of work and money. About €800 (3.457,20 zloty) a year.

IMHO we can make a choice. We all can continue to keep OC international including other nodes with the small problems that belong to this, or continue the way so only the Polish site can have the benefits of your hard work.

Please let us discus this in a proper way :-)

**Comment by wloczynutka** [comment]
It ws not my intend to be rude. Sorry if I was. Please tak my ppologise for that. Please keep i mind, that I used 'IMHO' that means it is my personal opinion, not "must opinkon". I'm not a sociopatic dictator and I will no force my ideas against all others admins and developers, especially that my impact to OC code last moths is really small.

**Comment by wrygiel2** [comment]
Most of requests recently reported by Harrie and @andrixnet seem reasonable
to me.

In general, having too much settings is also considered bad for user
experience. But in this particular case, we have a limited number of users
who see them (OC programmers and admins), so perhaps it does not really
apply here.

**Comment by harrieklomp** [comment]
@wloczynutka Is taken no hard feelings :-)
