### ISSUE TITLE
hardcoded locale

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#302]
There are quite a number of files that define in a hardcoded way (one or both of these): 

```
setlocale(LC_TIME, 'pl_PL.utf-8');
setlocale(LC_CTYPE, 'pl_PL.UTF-8');
```

Being an international and multilanguage site, this should not be this way. 
However I am not sure how to solve this: 
1) locale defined in settings
2) locale defined according to current display language

I would be inclined towards 2) because this implies things such as date and time display format, which should be handled according to display language rather then country of origin (ie the node).

**Comment by wrygiel2** [comment]
OKAPI uses the second approach too.

**Comment by andrixnet** [comment]
also, setting locale shouldn't be done once, for the entire flow, like in common.inc.php (or similar) instead of individual pages?
(ok, some pages may not use it explicitely, but that is not a reason against the above statement)

**Comment by kojoty** [comment]
locale are set in common.inc.php based on lang value - there is no need to set it if common.inc.php is included.
