### ISSUE TITLE
Lack of ratings in GeoPath description

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#309]
from fb:

> Tomanek Tomanek
> Witam! Gdzieś uciekły oceny skrzynek w geościeżkach.
> 

![image](https://cloud.githubusercontent.com/assets/2961448/13553447/032d5da4-e38a-11e5-83eb-9a96013184f4.png)

**Comment by wloczynutka** [comment]
I'm investigating.

**Comment by deg-pl** [comment]
But not everything works properly. Let me repair this ;) 
![final](https://cloud.githubusercontent.com/assets/13884863/13557033/0fb62372-e3e8-11e5-9806-2291c292ab34.png)
