### ISSUE TITLE
RR Team elections in OCPL database

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#322]
With all due respect to the entirea polish Opencaching team, RR Team elections deserve a separate mini website and database. 

Currently there are tables and data in OCPL database that are specific to the polish RR Team elections only. Unless this is deemed an Opencaching Node functionality and a requirement for organizations operating Opencaching nodes, it should be moved from here to a separate and dedicated project and website. 

Thank you for understanding.

**Comment by harrieklomp** [comment]
You can remove these tables from your database. There are no links in normal use of the site.

**Comment by andrixnet** [comment]
These are the rr_ocpl_* tables, right? Any others?

**Comment by andrixnet** [comment]
One more thing: these should be removed from the OOPENCACHING-PL database structure for new installations. 

Also, should, at any point, a database structure update system be deployed (like OKAPI has) the OCPL node would become in conflict. So the suggestion to move them to a separate database stands.

**Comment by kojoty** [comment]
those tables are useless at oc.pl now also, but removing voting system at all is not so easy task

I understand and support a good idea to separate this code from common code, but we need to find a best way of doing that - for example to not make the user of oc.pl to log-in again for voting etc.

Maybe we can make from voting-pages a generic solution useful for voting for all nodes?

BTW: I'm going to prepare clean-up of unnecessary tables in db this week and rr_ocpl_* tabes are on my list of tables to remove...

**Comment by harrieklomp** [comment]
@andrixnet Yes, these are all rr_ocpl_* tables.
@kojoty All ajax_chat_* can be removed from database.

**Comment by kojoty** [comment]
@harrieklomp, I know :) take a look at my previous analysis here: [https://docs.google.com/spreadsheets/d/1T45XyjeHRIPu4hSxSTdxOzymZcgAwR9WraJBmuwb_T0/edit#gid=0] All tables marked by red color in G column should probably be removed.

**Comment by andrixnet** [comment]
A voting system inside OPENCACHING-PL code may exist, if it is beneficial to all nodes.
On the other hand, an external application may access the `user` table from OCPL database (as external database). But this would require a separate login. 

Another possibility would be to define a directory (eg /modules) in gitignore for OPENCACHING-PL and the voting part be developed as a separate project, this way integratable only into certain OC nodes and using the same login as the main website.

**Comment by andrixnet** [comment]
@kojoty with https://github.com/opencaching/opencaching-pl/pull/324 the tables related to this issue have been removed. 
You should also update your document: https://docs.google.com/spreadsheets/d/1T45XyjeHRIPu4hSxSTdxOzymZcgAwR9WraJBmuwb_T0/edit#gid=0

I have updated the skeleton documentation for the database here https://github.com/opencaching/opencaching-pl/pull/331

IMO this issue can be closed.

**Comment by kojoty** [comment]
I think it can stay as long as we remove the voting code from common sources at all.

There is still the last rr_ocpl_\*_2016 tables in DB, because we still have the code related to it.
I hope @mzylowski will prepare the new voting solution (I saw work is in progress) for us and then we can also finally resolve this issue.

**Comment by mzylowski** [comment]
@kojoty: We still have any code related to rr_ocpl_*_2016?
I have not found any.
Can I prepare sql alert for remove this table?

**Comment by kojoty** [comment]
Yes, I think so.
