### ISSUE TITLE
Interface for uploading picture on server

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#328]
Now we have the same code in newpic.php, newpic-gps.php, editpic.php for image uploading and resizing. We need one class for that. 
Related with #275 #326

**Comment by kojoty** [comment]
... and there is image upload implemented in geopaths - am I wrong?

**Comment by mzylowski** [comment]
You are right..

**Comment by andrixnet** [comment]
and it currently does not use the same image resize interface.

**Comment by wloczynutka** [comment]
in geopaths is used only for uploading geoPath logo.

**Comment by kojoty** [comment]
@deg-pl, żeby była jasność co ja robię tutaj:

chcę zrobić uniwersalny interfejs do uploadu plików na serwer, który będzie można łatwo użyć we wszystkich miejscach, w których mamy upload, a więc:
- obrazki w keszach
- mp3 w keszach
- obrazki w logach keszy
- obrazki w logach geościezek (do zaimplementowania w przyszłości)
- logo geościeżki 
- obrazki w opisach geościezki (do zaimplementowania w przyszłości)
- avatary użytkowników
- ...no i nasze wszystkie przyszłe pomysły

Współczesne przeglądarki mają sporo fajnych featurów typu drag&drop plików, upload w tle z paskiem postępu etc. Ogarnięcie tego wymaga jednak trochę kodu, który powinien być w naszym przypadku wspólnym kodem używanym w tej samej formie wszędzie w kodzie OCPL. 

W pierwszej kolejności chcę zrobić coś co pozwoli na wyswietlenie "popupa" do uploadu plików.
Interfejs widzę taki:
- w kodzie widoku pojawia się przycisk (czy coś tam) co po kliknięciu wywoła funkcję JS - roboczo nazywam ją ocUpload()
- ocUpload przyjmie jako argument: 
  - parametry do uploadu (wygenerowane z modelu w php - osobny temat)
  - callback w JS do wywołania po zakończonym uploadzie
- następnie ocUpload wyswietli na srodku ekranu okienko, w którym będzie można uploadować plik (lub kilka plików - wszystko zgodnie z podanymi parametrami)
- upload odbędzie się bez przeładowania strony
- po zakończonym uploadzie ocUpload wywoła podany callback zwracając: status + listę plików uploadowanych na serwer (zgodnie z podanymi parametrami)
- w ramach callbacku będzie można już dowolnie zadziałać np. podmieniając w danym widoku coś na nowy plik - już z url-em na serwerze czy edytując opis czy coś tam jeszcze...
- ocUplaod obsługuje tylko "proces uploadu" na bazie zadanych parametrów 

Dzięki temu upload będzie "nowoczesny" i wszędzie na stronie będzie wyglądał jednolicie.
To na początek.

Co będzie dalej zobaczymy - czy zaimplementuję to do wszystkich miejsc gdzie obecnie robimy upload czy zrobimy to później - to się jeszcze zobaczy.

@deg-pl - ja nie planuję przerabiać nic w profilu użytkownika - więc możesz już działać - załóż tylko, że będziesz miał funckję ocUplaod(), która po zakończeniu zawoła callback, w którym zwróci status (czy udało się coś uploadować) i url do pliku na serwerze.

ocUpload będzie chunkiem, ale to będzie coś na kształt wtyczki JS - po stronie serwera trzeba będzie też obsłużyć upload - ale to już osobny temat :)

**Comment by deg-pl** [comment]
@kojoty dzięki za wytłumaczenie. Jak pisałem - ja z uploadem wstrzymuję się do zakończenia Twoich prac. Nawet wstrzymuję się z wyborem sposobu przechowywania avatarów - do tej pory przyjąłem zastosowanie dodatkowego pola w tabeli users, ale się z tego wycofuję dopóki Twój interfejs nie będzie gotowy.
Z tego co wiem - przerabiasz też logi w keszach i geościeżkach - fajnie byłoby, gdyby tam obok nazwy użytkownika, pojawiał się też jego avatar. Stąd też mój PR.

**Comment by kojoty** [comment]
@rapotek @deg, ja mam tu właśnie jeszcze kilka kwestii do rozkminy - możemy sobie nad tym pogadać - załóżmy, że tutaj;
- obrazki - obecnie jest tak, że obrazki sa w jednej tabelki - mam wrażenie, że to nie ma uzasadnienia i najlepiej by było zrobić osobne tabele - trzymanie wszystkiego w jednej tablicy chyba nie ma uzasadnienia - jedyne operacje jakie wykonujemy na obrazkach to: "daj mi obrazki dla danego loga|kesza|..." + oczywiście insert/update/delete - nie widzę innych operacji wiec lepiej by było, jakbyśmy mieli tablice: log_pics, cache_pics, avatar_pics, geopath_pics etc... zgadzacie się ze mną? - przerobienie tego na produkcyjnych bazach danych będzie wymagało drobnej gimnastyki, ale wierzę, że damy radę - no i jeszcze zmian w OKAPI

- do tego trochę myslę nad załączaniem mp3 do keszy - niby mamy taką funkcjonalność - ale czy to nam realnie potrzebne - może by to wywalić? ale może nie - może jako taki bajer też w sumie zostać - wiele nas nie kosztuje

- do tego wydaje mi się, że potrzebujemy zrobić taki szybki jakiś "edytor" do fotek - bo fajnie by było jakby dać użytkownikom do ręki 2 narzędzie: obracanie fotki o 90 stopni (koniecznie) + przycinanie (ewentualnie)

**Comment by deg-pl** [comment]
Po prostu nie wiedziałem jak będą wyglądały obrazki po refactoringu.
Jeśli o mnie chodzi, to avatary (ponieważ każdy będzie miał 0 lub 1) mogą być składowane w odrębnym katalogu z nazwami zgodnymi z user_id. Wtedy wystarczy tylko proste sprawdzenie czy plik istnieje - jeśli tak, zwróć jego nazwę, jeśli nie - zwróć nazwę domyślnego avatara. Wtedy może to działać zupełnie niezależnie od bazy danych.

Dużo mamy takich keszy z hostowanym MP3? Jak dla mnie to przerost formy nad treścią.

Prosty (w obsłudze) edytor zdjęć to byłaby znakomita funkcjonalność! Bardzo tego brakuje - czasami się fotki userom wklejają w złej orientacji. Albo chcieliby przyciąć avatara. Edytor by to BARDZO uprościł. Jeśli tylko jesteś w stanie - zrób to! :)

**Comment by wloczynutka** [comment]
➢ trochę myslę nad załączaniem mp3 do keszy

Kiedyś był taki typ kesza „podcast” (nie wiem czy jeszcze ten typ utrzymujemy, tam było potrzebne załadowanie mp3. Mp3 zawierały opis w postaci audio jak dojść do kesza. 

Są / były też kesze z kardridżami whereigo, nie wiem czy to umarło czy nie – jeśli nie umarło, warto też umożliwić załadowanie takiego pliku z kardridżem.

Wysłane z aplikacji Poczta dla Windows 10

Od: kojoty
Wysłano: środa, 17 października 2018 11:05
Do: opencaching/opencaching-pl
DW: Łza z Włóczynutki; Comment
Temat: Re: [opencaching/opencaching-pl] Interface for uploading picture onserver (#328)

@rapotek @deg, ja mam tu właśnie jeszcze kilka kwestii do rozkminy - możemy sobie nad tym pogadać - załóżmy, że tutaj;
• obrazki - obecnie jest tak, że obrazki sa w jednej tabelki - mam wrażenie, że to nie ma uzasadnienia i najlepiej by było zrobić osobne tabele - trzymanie wszystkiego w jednej tablicy chyba nie ma uzasadnienia - jedyne operacje jakie wykonujemy na obrazkach to: "daj mi obrazki dla danego loga|kesza|..." + oczywiście insert/update/delete - nie widzę innych operacji wiec lepiej by było, jakbyśmy mieli tablice: log_pics, cache_pics, avatar_pics, geopath_pics etc... zgadzacie się ze mną? - przerobienie tego na produkcyjnych bazach danych będzie wymagało drobnej gimnastyki, ale wierzę, że damy radę - no i jeszcze zmian w OKAPI
• do tego trochę myslę nad załączaniem mp3 do keszy - niby mamy taką funkcjonalność - ale czy to nam realnie potrzebne - może by to wywalić? ale może nie - może jako taki bajer też w sumie zostać - wiele nas nie kosztuje
• do tego wydaje mi się, że potrzebujemy zrobić taki szybki jakiś "edytor" do fotek - bo fajnie by było jakby dać użytkownikom do ręki 2 narzędzie: obracanie fotki o 90 stopni (koniecznie) + przycinanie (ewentualnie)

**Comment by kojoty** [comment]
Jeśli ktoś z was akurat nie wie to jeszcze wyjaśnię:
- mp3 jest aktualnie "załączalne" do keszy typu multi|quiz|nietyp - trochę to gupie, ale tak działa
- typ podcast chyba został zarzucony
- wherigo - jak najbardziej - być może w ogóle można by pozwolić na załączenie dowolnego pliku - choć martwię się lekko o to, że będą tu lądować jakies zawirusowane exe-ki

**Comment by rapotek** [comment]
Moim zdaniem lepiej ograniczyć możliwości uploadowania różnych treści nad którymi nie mamy kontroli, bo patrząc na to, co się obecnie dzieje, w przyszłości prawnicy od praw autorskich, ACTA 2 itp. będą mieli używanie.

**Comment by kojoty** [comment]
OK, first part of changes is done: generic plugin for files upload is merged. 
I think that refactoring of places where files are uploaded (where uploadChunk plugin can be used)  should be a separated task.

**Comment by kojoty** [comment]
Some visual improvements for upoadChunk are in the way and will be delivered soon by @DorotkaMakotka

**Comment by kojoty** [comment]
Upload chunk is ready now
