### ISSUE TITLE
Translations: Incomplete Flopp's map

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#332]
www.opencaching.pl uses Flopp's map, but there is no polish translation for it.
See https://github.com/flopp/FloppsTolleKarte/issues/36

I am posting this here as well since there is a level of integration between OPENCACHING-PL project, www.opencaching.pl OC node and Flopp's map, however it is possible that the polish team may be unaware of https://github.com/flopp/FloppsTolleKarte/issues/36

Thank you.

**Comment by harrieklomp** [comment]
There is now a Polish translation on Flopp's map.
