### ISSUE TITLE
Number of watchers may be negative

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#336]
... but should be zero or positive.
![watchers](https://cloud.githubusercontent.com/assets/13884863/13716163/a7bee9d4-e7d9-11e5-847a-45b48f398c29.png)

**Comment by wloczynutka** [comment]
it goes from DB. 
![image](https://cloud.githubusercontent.com/assets/11460149/13716261/51479e60-e7da-11e5-92cb-bb7dd1685983.png)

**Comment by deg-pl** [comment]
So problem is probably in watchcache.php / removewatch.php (?)

**Comment by wloczynutka** [comment]
could be.

**Comment by deg-pl** [comment]
wget http://opencaching.pl/util.sec/repair_cache_scores.php from localhost (OC PL server) repaired it

**Comment by mzylowski** [comment]
We still have problem in code.
How I understand you run this script today, but in the morning I still saw -1 watchers here:
http://opencaching.pl/viewcache.php?wp=OP89CY
I should be fixed in the code.

**Comment by kojoty** [comment]
I think this issue is fixed now (watch-controls were rewritten). If this is still an issue please reopen.
