### ISSUE TITLE
Incorrect log order under cache description

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#345]
biegacz via mail:

> Od kilku dni widzę, że podczas przeglądania wpisów internetowych. logi często są nie chronologicznie wyświetlane. Dziś zaobserwowałem, że wyświetlanie logów jest dublowane np "Polska Przepychu Pełna" - OP8449.

from FB:
> coś nie trybi z dynamicznym ładowaniem logów:
![image](https://cloud.githubusercontent.com/assets/2961448/13763673/4cdce7a2-ea48-11e5-8708-878d04d460f2.png)

**Comment by following5** [comment]
Database index broken? repair table cache_logs?

**Comment by kojoty** [comment]
one more comment from users:

> Nie zauważyłem tego podczas szybkiego przewijania strony. Raczej dzieje się to od razu. Wszedłem na stronę jakiejś skrzynki i się wyświetlił jako pierwszy wpis z 2014 roku, następne leciały datą rosnącą i w pewnym momencie był przeskok na najnowsze wpisy i dopiero wpisy były datą malejącą. Dopiero jak wyświetliłem wszystkie wpisy to pokazały się w prawidłowej kolejności. 
> Teraz siedzę na innym kompie i tutaj nie ma takiej sytuacji. Może to tylko mój indywidualny problem na lapku?
>

**Comment by harrieklomp** [comment]
When a cachepage shows up there are many the same logs. After a refresh the cachepage the correct amount of logs shows up. Try http://opencaching.pl/viewcache.php?cacheid=48970 and than refresh the page.
This happens on all nodes.

**Comment by wloczynutka** [comment]
under chrome is OK.
Again FF make trouble. Seems FF continue IE hertitage.

**Comment by andrixnet** [comment]
I've accessed for the first time the cache page indicated by @harrieklomp and I got a single entry loaded (apparently) dynamically (scroll size changed). Using Firefox. 

There may be some issues with caching. In part these can be controlled with HTTP headers.

**Comment by kojoty** [comment]
Bad news: at my chrome there is an issue: not all logs are displayed: it seems when I scroll down too fast or something one or more ajax request is canceled?

**Comment by wloczynutka** [comment]
which geocache?

**Comment by kojoty** [comment]
try any with many logs (30+). Fast scroll down and compare how many logs you see with number of logs... I tried a few different caches....
For example:

**Comment by kojoty** [comment]
what I see:
![image](https://cloud.githubusercontent.com/assets/2961448/13791096/ce6dfb14-eaeb-11e5-90a1-d514a51cc05e.png)

what should be there:
![image](https://cloud.githubusercontent.com/assets/2961448/13791114/e0681b10-eaeb-11e5-9453-0bf0b9601e72.png)

**Comment by wloczynutka** [comment]
zobacz teraz. (Teraz pewnei FF nie będzie działał :-/)

**Comment by kojoty** [comment]
na chromie jest OK, na innych przeglądarkach jeszcze nie sprawdzałem
