### ISSUE TITLE
User can't restore deleted log for his own cache

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#346]
email from Michał / polcia&szymaneq:

> Mam jeszcze jedno pytanie...
> Czy teraz użytkownik nie może przywrócić skasowanego wpisu we własnej skrzynce? 
> Mam takie zgłoszenie - koleś skasował wszystkie wpisy w swojej skrzynce i kazałem mu je przywrócić, ale zapytał mnie jak to zrobić i przesłał zdjęcie, że nie ma opcji "przywróć wpis". Rzeczywiście ma rację. Nie ma możliwości przywrócenia skasowanego wpisu we własnej skrzynce. Czy teraz tylko COG może przywracać wpisy?

**Comment by mzylowski** [comment]
A to już dość długo tak jest. Jak ponad pół roku temu wywaliłem wpis Harpusa z mojej skrzynki to też musiał do COGu pisać o przywrócenie.
Nie jestem pewien czy to problem do rozwiązania czy raczej tak ma być.

**Comment by wloczynutka** [comment]
Nie pamiętam, żeby użytkownik mógł kiedykolwiek  przywracać usunięte wpisy. jesli tak było, to był bug. Raczej nie powinien mieć takiej opcji. (np. taka sytuacja: COG usuwa obraźliwe/fałszywe wpisy a on je sobie przywraca i tak w kółko)

**Comment by deg-pl** [comment]
Mam wrażenie, że tak było i... tak powinno być.

**Comment by kojoty** [comment]
@wloczynutka - ale tu chodzi o przywrócenie komentarza we **własnym** keszu... nawet jeśli to tak nie działało - nie wiem - można sprawdzić w wolnej chwili jak było przed twoimi zmianami - to wydaje mi, że powinniśmy taką funkcjonalność dorobić... CoG może zawsze zamknąć takiego kesza zupełnie...

**Comment by wloczynutka** [comment]
przywracanie komentarzy chyba sam dodawałem :-), w tym commicie:

https://github.com/opencaching/opencaching-pl/commit/cd49a9f02157b57de0f425404bbce190c0ebd79e#diff-e40a390c08b1d365f94085d7b1c35198

Jak widać zawsze było dostępne tylko dla COG (if($usr['admin])) i moim zdaniem tak powinno pozostać.
Użytkownik w mojej opinii nie powinien mieć mocy przywracania usuniętych logów, nawet we własnym keszu, tym bardziej nie swoich wpisów i nie przez siebie usuniętych)

**Comment by mzylowski** [comment]
Zgadzam się z wolczynutka.
