### ISSUE TITLE
GeoKrety data exchange

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#348]
There are data exchange problems on OCRO and after talking to @harrieklomp, after contacting the GeoKrety team, I believe it stands an issue here as well. 

Installation instructions did not mention about setting a value in sysconfig table. With help from @harrieklomp I corrected this. Now OCRO cronjob for GeoKrety works (as in there are no errors outputed)

(I will handle this when I finish with the installation and system configuration instructions).

On OCRO the table gk_item_type is empty. According to /util.sec/geokrety/... this table should be filled with data from geokrety.org

On OCRO the table gk_move_type is empty. The PHP code does not contain any reference to this table, also there is no initial data for it. 

These ^^^^^^^^^^^ are resource data that don't change often, but they CAN change over time. 

Table gk_move is empty. 
Table gk_move_waypoint is empty. 
Table gk_user is empty. This table should be filled from GeoKrety.org dynamically. @harrieklomp offered me a copy from his node, but it is not proper.

**Comment by andrixnet** [comment]
Geokrety.org have added support for OR waypoints. 

Syncing data with geokrety.org works, at least in part. 
Geokrety info in cache updates properly with cron job.

These are still empty. Not sure if it is correct.
-------------------------------
Table gk_move is empty.
Table gk_move_waypoint is empty.
Table gk_user is empty.

**Comment by kojoty** [comment]
@andrixnet, do you still need help with this issue? If this is resolved please close it, if not please call me :) - I'll try to help you with it.

**Comment by andrixnet** [comment]
@kojoty I am away and will return on Aug 21st. Thank you very much. Will recheck then.

**Comment by kojoty** [comment]
@andrixnet, please reopen this issue if necessary
