### ISSUE TITLE
access rights to util.sec properly configured

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#350]
While the method may work for a private project, having /util.sec/.htaccess of the repository contain the actual IP addresses of the nodes and other members of the project allowed to run scripts in this directory is a big NO and definitely a "**bad practice**". 

Proper access rights to this directory belong in each node's webserver configuration file.

I am working on a set of more up to date installation instructions, which will correct this aspect.
Then it will need to be deployed on each production and development node to become a proper implementation.

**Comment by kojoty** [comment]
@andrixnet,

all scripts under util.sec should be called only:
- by cron 
- optionally by user from command line interface

I think we should:
- temporary disable access to this scripts at all in htaccess - I think anyone should call it from the web
- redesign scripts code to prevent call from the web

**Comment by andrixnet** [comment]
Either: 
- move the access restrictions from .htaccess to webserver config for this site
- redesign scripts to work from command line (cron) only

Both methods are good.

**Comment by andrixnet** [comment]
To be solved as #1415
