### ISSUE TITLE
User stats: Number of moved caches shows duplicates?

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#353]
[email from michał \<chudy...\>]

> ... chodzi o przeniesione mobilne skrzynki. Konkretnie - przeniosłem ogólnie trzy kesze, ale dwa z nich dwukrotnie. W statystykach wyświetla się "Liczba przeniesionych skrzynek: 5. W rzeczywistości zostały przeniesione trzy. Czy tak powinno być czy jest to błąd? Wydaje mi się, że system powinien liczyć inaczej

It seems that now: every log with transfer of the mobile cache is counted to "transfers".
Is that OK?

**Comment by wloczynutka** [comment]
author did not predicted that someone can move same geocache more than one time. Maybe fixing translation from "geocaches moved" to "transfer count" would be enough.
