### ISSUE TITLE
Small translation issue

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#354]
On main page there is a small translation issue when there are no upcoming events. On oc.pl this is not visible because there are events. This is only visible on oc.ro and oc.nl.
When English or any other site language is selected, the line "There are no events planned for the nearest future" will always be the node language.

![selectie_139](https://cloud.githubusercontent.com/assets/1060518/13846558/485898e6-ec48-11e5-9265-324d83f3f422.png)
screenshot from oc.ro

![selectie_140](https://cloud.githubusercontent.com/assets/1060518/13846564/5319336c-ec48-11e5-8dcc-f3939acf7ae5.png)
screenshot from oc.nl

**Comment by andrixnet** [comment]
Very good observation. I will try to look into it.
