### ISSUE TITLE
okapi_settings.php handling of node IDs

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#358]
```
        'ORIGIN_URL' => (
            isset($origin_oc_url) ? $origin_oc_url :
            ($oc_nodeid == 14) ? "http://www.opencaching.nl/" :
            "http://opencaching.pl/"
        ),
```

This should be changed to a better approach. 
Currently I believe the `if` clause should be entirely replaced with `$absolute_server_URI`

---

This being a sensitive setting, I would suggest someone with more experience fiddle with it.

**Comment by following5** [comment]
The OKAPI ORIGIN_URL is used to distinguish between sites that use different static-data sets. More precise: Currently it is only used to distinguish between sites that use 
* different geocache attribute sets, or 
* different nature protection area tables (the table definitions, not the contents!).

Sites with same static-data sets share the same ORIGIN_URL, to avoid redundancies e.g. in the [attribute definition file](https://github.com/opencaching/opencaching-pl/blob/master/okapi/services/attrs/attribute-definitions.xml). If you would insert "http://opencaching.ro" there, attributes in OKAPI would stop working at opencaching.ro.

So please close this issue, this setting should not be changed.

**Comment by following5** [comment]
> this setting should not be changed.

Except if you can make sure that `$origin_oc_url` is properly defined in the settings.inc.php of the different sites. E.g. if Opencaching.NL has a `$origin_oc_url = "http://www.opencaching.nl/";` in its settings.inc.php, then the node-14-condition can be eliminated here.

**Comment by andrixnet** [comment]
Question: in what way does ORIGIN_URL differ (value and meaning) from SITE_URL ?
I am not sure I understand properly / well enough the connections (for development installations):
Otherwise, it seems clear that it refers to attributes on a per website URL basis. 
(rather then node ID? or branch?)

okapi/settings.php
>         /**
>          * URL of the official OC site. For production sites, it should equal
>          * SITE_URL (this is also the default). For development installations,
>          * it should point to the official OC site from which you got your
>          * database dump (e.g. "http://opencaching.pl/").
>          */
>         'ORIGIN_URL' => null,
> 

I have `'SITE_URL' => $absolute_server_URI`, in okapi_settings.php
and 
`$absolute_server_URI = 'http://www.opencaching.ro/';` in lib/settings.inc.php

At the time I installed the site there was no documentation stating anything about `$origin_oc_url` variable, nor was it in settings-example.inc.php. Thus, this variable does not exist on OCRO. Nor does it exist on OCNL. _At this time. _

I can define it in settings.inc.php and I am sure @harrieklomp will define it as well. 

---------------

On the other hand, I see an if in `okapi/services/caches/geocaches.php` : 
```
           if (Settings::get('OC_BRANCH') == 'oc.de')
[...]
            else if (Settings::get('ORIGIN_URL') == 'http://opencaching.pl/' ||
                     Settings::get('ORIGIN_URL') == 'http://www.opencaching.nl/')
[...]
            else
            {
                # OC.US and .UK do not have a 'parkipl' table.
                # OC.US has a 'us_parks' table instead.
                # Natura 2000 is Europe-only.
                $rs = null;
            }
```

At first glance, it looks strange to me the fact that website names are specified explicitely. 
Then it hit me: OC UK and OC US are based on an older version of OPENCACHING-PL code.
Also, OC RO is not taken into account here.

Giving it further thought, there must be a way this can be done more elegantly and without that much strict dependence on specific websites.

Maybe we could define in lib/settingsDefault.inc.php : 
`$config['npa']['natura2000']['continental_europe'] = true;`
and use this for the above `else if` to differentiate between sites that can use the Natura 2000 dataset for continental Europe, or not (like UK, US, etc).

**Comment by following5** [comment]
>  it looks strange to me the fact that website names are specified explicitely. 

Those names are just IDs for different _database forks_. Instead of "http://opencaching.pl/" and "'http://www.opencaching.nl/", they could have been named "OCPL-style database" and "OCNL-style database". Don't worry and trust in the wisdom of OKAPI developers, it's fine this way. :)

**Comment by andrixnet** [comment]
I am not doubting, rather trying to better understand the reasoning behind it.

I'll add $origin_oc_url variable in settings.inc.php on OC RO as soon as I finish translating attribute-definitions.xml.
