### ISSUE TITLE
Invalid publication date of geopath 357 (Na siedmu wzgórzach)

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#360]
Year is (minus) -0001

![7 wzgorz](https://cloud.githubusercontent.com/assets/13884863/13891888/27673fe0-ed54-11e5-9b8f-22052ce3d9c5.png)

**Comment by wloczynutka** [comment]
I think this is caused by missing validation date at php side. i reproduced this error: manually edit date field after datepicker is closed.
:

**Comment by wloczynutka** [comment]
validation added. Unfortunatelly it is not implemented to display any message when user-input is not validated, or other error occured. maybe in future someone can do this. Backend is resulting witch simple json-encoded array, ajax can easy catch this data.
--
User should now correct date himself. (I don't know real datetime published this geoŚcieżka,so I didn't corrected it.)
