### ISSUE TITLE
Enable secure (https) connections to OC service

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#363]
I think opencaching should be also accessed over ssl (https) connections. I guess there are some difficulties around it but let's try to gather it in one place.

Why (at least):
- [https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins] - means that map geolocation will not work in a future without https

**Comment by kojoty** [comment]
Other issues in this matter:
#181  - SSL certificates for opencaching-pl based nodes

**Comment by wrygiel** [comment]
Recently, it's quite easy to get free SSL certificates.

**Comment by wrygiel** [comment]
It's important to remember, that **OKAPI must be able to work on HTTP**. It also MAY work on HTTPS, but we can never redirect entire domain to HTTPS automatically.

**Comment by wloczynutka** [comment]
Some time ago i sent request for free cert. I get answer, that no chance to get free certificate with our aged ocpl server software. System is simply not secure. If software will be updated some day, then we can continue talkin on this topic. For now it is just wasting the time.

**Comment by wrygiel** [comment]
I'm quite sure there are other services that allow you to get your certificate in an automated way (no human contact needed whatsoever). But you're right - we should upgrade the server before we do this.

**Comment by andrixnet** [comment]
@wloczynutka very recently discovered "DROWN" attack impacts a huge number of servers, even with latest software, but not properly fine tuned SSL configuration. 
I am researching into the necessary config.

**Comment by andrixnet** [comment]
Regarding OKAPI necessity to work over plain HTTP, both OEPNCACHING-PL PHP code and webserver configuration must be researched in order to ensure proper usage of HTTPS for the website, yet allow OKAPI to be called both with and without HTTPS. And this is a delicate one.

**Comment by andrixnet** [comment]
@wloczynutka what was the rating of your server according to https://www.ssllabs.com/ssltest/ (before the DROWN attach discovery on March 4th 2016) ?

**Comment by andrixnet** [comment]
I am currently running Linux Slackware64-14.1 with all official security updates deployed.
Apache/2.4.16 ; OpenSSL 1.0.1s
With the webserver and openssl properly configured, I can deploy secured websites that receive overall rating A or higher from https://www.ssllabs.com/ssltest/

I can offer my assistance to any OC node sysadmin.

**Comment by andrixnet** [comment]
One important note about best practices. 
Having a mixed content website (parts accessible only via HTTPS and parts accessible via HTTP, or HTTP and HTTPS) is a very big counter-recommendation. 

Considering this and the requirement that OKAPI is accessible via plain HTTP, would rather suggest that OKAPI be deployed under a different domain name (like okapi.opencaching.XX) and DocumentRoot  (server side).
This would ensure that entire www.opencaching.XX website is fully secured and OKAPI available over plain HTTP. 

Come to think of it better, other combinations that make exclusions and exceptions would only complicate configuration and code and be dirty fixes.

**Comment by deg-pl** [comment]
@andrixnet Before march '16 rating of server was the same (F)

**Comment by wrygiel** [comment]
OKAPI's `base_url` cannot be changed. This is the only cause why OKAPI must be available via HTTP too. Changing this URL will break **all** the existing OAuth applications. Redirection is not a valid solution (it breaks OAuth signatures).

Many sites are accessible both ways. It's perfectly safe if configured properly.

**Comment by bohrsty** [comment]
OCDE is currently running in mixed state, HTTP and HTTPS are both usable. at the moment we're using a sponsored certificate from our hoster, but if that will expire we will switch to some free from [letsecnrypt](https://letsencrypt.org/). they offer certificates signed by an official ca valid for 90 days, but you can automaticaly check and renew them using a little script an cron job. the OCDE testserver currently uses such certificate ([test.opencaching.de](https://test.opencaching.de)) and if somebody is interested in the configuration and installation of the script and cron job, let me know, i can give a short documentation here (or somewhere else)...

i could also share our apache ssl config if someone is interested getting the grade A on ssllabs test, but they depend currently on apache 2.4 and nearly lastest version of openssl... but with a little investigation we should be able to get even older linux installation running HTTPS without beeing affected by the recently detected vulnerabilites...

regards Nils (aka bohrsty)
OCDE teamleader technics (= main sysadmin)

**Comment by andrixnet** [comment]
@bohrsty let us both share the configurations and related instructions. 
I will prepare a document early next week.

**Comment by andrixnet** [comment]
Webserver configuration: 
either in httpd.conf or included from separate file: 

_Enable the SSLCipherSuite according to your needs to serve XP clients or not._

```
#
# This is the Apache server configuration file providing SSL support.
# It contains the configuration directives to instruct the server how to
# serve pages over an https connection. For detailed information about these
# directives see <URL:http://httpd.apache.org/docs/2.4/mod/mod_ssl.html>
#
# Do NOT simply read the instructions in here without understanding
# what they do.  They're here only as hints or reminders.  If you are unsure
# consult the online docs. You have been warned.
#
# Required modules: mod_log_config, mod_setenvif, mod_ssl,
#          socache_shmcb_module (for default value of SSLSessionCache)

#
# Pseudo Random Number Generator (PRNG):
# Configure one or more sources to seed the PRNG of the SSL library.
# The seed data should be of good random quality.
# WARNING! On some platforms /dev/random blocks if not enough entropy
# is available. This means you then cannot use the /dev/random device
# because it would lead to very long connection times (as long as
# it requires to make more entropy available). But usually those
# platforms additionally provide a /dev/urandom device which doesn't
# block. So, if available, use this one instead. Read the mod_ssl User
# Manual for more details.
#
#SSLRandomSeed startup file:/dev/random  512
#SSLRandomSeed startup file:/dev/urandom 512
#SSLRandomSeed connect file:/dev/random  512
#SSLRandomSeed connect file:/dev/urandom 512
#

# When we also provide SSL we have to listen to the
# standard HTTP port (see above) and to the HTTPS port
#
# Note: Configurations that use IPv6 but not IPv4-mapped addresses need two
#       Listen directives: "Listen [::]:443" and "Listen 0.0.0.0:443"
#
Listen 443

##
##  SSL Global Context
##
##  All SSL configuration in this context applies both to
##  the main server and all SSL-enabled virtual hosts.
##

###
# recommended Apache SSL cipher suites for maximum security without SSLv2 and without BEAST vulnerability
SSLProtocol -ALL +TLSv1 +TLSv1.1 +TLSv1.2

# 2013 strong cipher suite (allows Internet Explorer from Windows XP)
SSLCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
# 2014 strong cipher suite (drop XP support)
#SSLCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!3DES:!DES:!MD5:!PSK:!RC4:!RSA;

# Recommended by Mozilla
#SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK;

###
# Enable OCSP stapling

SSLUseStapling on
SSLStaplingResponderTimeout 5
SSLStaplingReturnResponderErrors off
SSLStaplingCache shmcb:/var/run/ocsp_stapling_cache(128000)

#   Pass Phrase Dialog:
#   Configure the pass phrase gathering process.
#   The filtering dialog program (`builtin' is an internal
#   terminal dialog) has to provide the pass phrase on stdout.
SSLPassPhraseDialog  builtin

#   Inter-Process Session Cache:
#   Configure the SSL Session Cache: First the mechanism
#   to use and second the expiring timeout (in seconds).
#SSLSessionCache         "dbm:/var/run/ssl_scache"
SSLSessionCache        "shmcb:/var/run/ssl_scache(512000)"
SSLSessionCacheTimeout  300
```

------------------------------
Specifically in the VirtualHost definition of your website: 

```
<VirtualHost *:443>
   ServerName XXXXXXXXXXXXXXXX
   [...]

<IfModule ssl_module>
    SSLEngine on

    SSLCertificateFile "/etc/cert/your_certificate.crt"
    SSLCertificateKeyFile "/etc/cert/your_certificate_key.key"
    SSLCACertificateFile "/etc/cert/CA__that_signed_your_certificate.crt"

# For debugging purposes, if needed
#    CustomLog /var/log/httpd/ssl_request.log "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"

    # Enable HTTP Strict-Transport-Security (HSTS)
    Header always set Strict-Transport-Security "max-age=31536000; includeSubdomains; preload"
</IfModule>

    <Directory /path/to/your/website>
        AllowOverride all
        Require all granted
        # Set this to refuse non-SSL connections (if same space is available via HTTP as well)
        # or put this in individual .htaccess files according to your needs
        SSLRequireSSL
    </Directory>

### add the following to your cgi-bin .htaccess if you use CGI scripts
#Options +ExecCGI
#SSLOptions +StdEnvVars

### Customize and add this rule to provide proper environment variables to
### your scripts
#<FilesMatch "\.(cgi|shtml|phtml|php)$">
#    SSLOptions +StdEnvVars
#</FilesMatch>

</VirtualHost>
```

**Comment by deg-pl** [comment]
Could anybody from @opencaching/opencaching-pl-lead-programmers test it?

"Standard" adresses - should not to be rewrited:
```
https://ocdevel.best.pl
https://ocdevel.best.pl/news.php

```
Adresess:
```
http://ocdevel.best.pl
http://www.ocdevel.best.pl
https://www.ocdevel.best.pl
```
should redirect to https://ocdevel.best.pl

Adresess:
```
http://ocdevel.best.pl/news.php
http://www.ocdevel.best.pl/news.php
https://www.ocdevel.best.pl/news.php
```
should redirect to https://ocdevel.best.pl/news.php

Adresses, should not to be rewrited/redirected: (example URI of OKAPI)
```
http://ocdevel.best.pl/okapi/services/apiref/method_index
http://www.ocdevel.best.pl/okapi/services/apiref/method_index
https://ocdevel.best.pl/okapi/services/apiref/method_index
https://www.ocdevel.best.pl/okapi/services/apiref/method_index
```
@andrixnet ?

**Comment by andrixnet** [comment]
I'll be out of town for the next 2 days. Will continue on saturday.
I appologize for the delay.

Andrei

**Comment by andrixnet** [comment]
**Main site: **
```
<VirtualHost *:443>
  ServerName ocdevel.best.pl
  [...]
</VirtualHost>
```

```
# Redirecting several names
<VirtualHost *:80>
  ServerName www.ocdevel.best.pl
  ServerAlias some.other.ocdevel.best.pl
### total redirect to new site
#  Redirect / https://ocdevel.best.pl
### Redirect keeping path
  RedirectMatch  ^/(.*)$ https://ocdevel.best.pl/$1
</VirtualHost>
```

---------------
Now comes the tricky part... if you want to redirect https://www.ocdevel.best.pl -> https://ocdevel.best.pl 

First advice: DON'T!

1. to catch https://www.ocdevel.best.pl you need one more IP address. 
Name based virtualhosting won't work because most clients don't implement it. Especially API libraries.

2. you WILL need either individual certificates for each name, a certificate with multiple names or a wildcard (expensive, most likely not granted by letsencrypt) certificate for *.ocdevel.best.pl
This is to avoid invalid certificate errors for your clients. 

Second point also applies to situations where you use multiple names for same VirtualHost by declaring ServerName and ServerAlias.
-----------------
The `RedirectMatch` directive above takes care of preserving the full path of the initial request, so clients get redirected to same URL path, only with different hostname and protocol.

**Comment by andrixnet** [comment]
OKAPI redirection, hostnames and http / https problem: 

My guess is that APIs like the one used by c:geo need the `RedirectMatch` rule (with URL path preservation) instead of whole site `Redirect`. 

Please test with `RedirectMatch` as described above and without _rewrite rules in .htaccess_.

@following5 please tell us about how OCDE makes OKAPI available via http while the rest of the site is https.

IMHO if the website switches to https, the following should be good (if not best) practices: 
1. choose a single name to use via https
2. publish that name as a rule to all (most) third party application developers
3. catch accepted aliases (over http) and redirect them to secure site
4. define a transition period during which the website works both over http and https. 
(use <VirtualHost *:80 *:443> for main site)
5. allow OKAPI to work over plain http as exception (OKAPI design requirement; allow non-up-to-date OKAPI clients access)

Just a quick overview before my transportation arrives :-)

**Comment by following5** [comment]
> @following5 please tell us about how OCDE makes OKAPI available via http while the rest of the site is https.

The www.opencaching.de apache is configured to run the site in dual-protocol http & https: Any part of the website can be accessed via both http and https. The reason for this is to stay backward-compatible to client software which is not SSL-enabled, e.g. old XML interface clients, and other tools which directly parse HTML pages. And to allow both protocols for OKAPI, which is common for APIs.

[This change](https://github.com/OpencachingDeutschland/oc-server3/commit/f995f49a1cb2b8e40edd6ca0400d5573b5b0c484) intoduced https into the OCDE code; it allows to run the website either in http mode, in https mode or in dual-protocol mode.

If you don't want http any more for OCPL, you may enable both protocols in the webserver (define two virtual hosts) but redirect any http accesses to https within the OC code. `isset($_SERVER['HTTPS'])` tells you if the current request is https.

OKAPI currently behaves well only on http. https://github.com/opencaching/okapi/issues/343 is about making it https-aware. My [fix](https://github.com/following5/okapi/commit/e97f35e95fb70757531a85587b40ffc514cac9f9) for that is waiting for review since half a year. ;)

**Comment by deg-pl** [comment]
> Now comes the tricky part... if you want to redirect https://www.ocdevel.best.pl -> https://ocdevel.best.pl
> 
> First advice: DON'T!
> 
>     to catch https://www.ocdevel.best.pl you need one more IP address. Name based virtualhosting won't work because most clients don't implement it. Especially API libraries.
> 
> Certificates are checked, keys are exchanged, secure channel is set up, all this before the HTTP request is sent via the secure channel.
> 
>     you WILL need either individual certificates for each name, a certificate with multiple names or a wildcard (expensive, most likely not granted by letsencrypt) certificate for *.ocdevel.best.pl This is to avoid invalid certificate errors for your clients.
> 
> Second point also applies to situations where you use multiple names for same VirtualHost by declaring ServerName and ServerAlias.

But... It is not a problem! I have certificate for ocdevel.best.pl and www.ocdevel.best.pl - both from letsencrypt!
This is not a theoretical example. It is operating a website.
On single IP I have separate certificates for www.ocdevel.best.pl, ocdevel.best.pl, wiki.ocdevel.best.pl, forum.ocdevel.best.pl and some more. All certificates are free certs from letsencrypt.

OC code is now universal. Can work as http only / https only / mixed mode. Of course with little modifications of settings.inc.php

**Comment by deg-pl** [comment]
List of software which is not compatibile with SNI -> https://en.wikipedia.org/wiki/Server_Name_Indication#Support

**Comment by andrixnet** [comment]
I admit I spoke more based on my experience at work, where we use purchased certificates for individual host names. 
In the usage scenario of OC code with letsencrypt (while that service exists) having multiple names can be configured such that it is not a problem.

**Comment by andrixnet** [comment]
SNI configuration for apache:
https://wiki.apache.org/httpd/NameBasedSSLVHostsWithSNI

**Comment by mzylowski** [comment]
If there still is any work to do, please reopen ;]
