### ISSUE TITLE
 move country translations from DB to translation files

### ISSUE THREAD

**Issue by wloczynutka** [opencaching/opencaching-pl#368]
function db_CountryFromShort($countryCode) is depreciated and can be replaced witch tr($countryCode).

Countries transaltions are already in translation files.

**Comment by andrixnet** [comment]
All these files contain SQL queries involving the `countries` table. 
Most also call the columns for various languages. 
```
editcache.php
GetRegions.php
myprofile.php
newcache.php
newcaches.php
newcachesrest.php
region.php
register.php
search.php
util.sec\cache_locations\cache_location.class.php
util.sec\cron\modules\cache_location.class.php
util.sec\dbcheck\index.php
xml\ocxml11.php
xml\ocxml11b.php
xml\ocxml11-old.php
xml\ocxml12.php
xml\ocxmlutf8.php
```

**Comment by andrixnet** [comment]
Should be retitled: move country translations from DB to translation files ?

**Comment by andrixnet** [comment]
Also, country table contains columns for individual languages `list_default_XX`. 
These seem to overlap (in principle) with `$defaultCountryList` and/or `$config['defaultCountry']` and/or `$config['defaultLanguageList']`

If it should be reported as separate issue, will do that.

**Comment by kojoty** [comment]
access to country db is now removed from OCPL code - there is still  some in OKAPI code
Countries list can be retrieved by src\Utils\Gis\Countries util class, translations are in tranlation files

**Comment by andrixnet** [comment]
Does this closure remove `countries` table as well?

**Comment by kojoty** [comment]
@andrixnet 
as I wrote above this is not used in OCPL code - this is still in use from OKAPI code - we need to find the way to unify this between OCPL code and OKAPI - let's open new issue in OKAPI repo.

**Comment by andrixnet** [comment]
@kojoty please do. You are more knowledgeable about it.
