### ISSUE TITLE
Dodanie obsługi send2cgeo

### ISSUE THREAD

**Issue by azhag-pl** [opencaching/opencaching-pl#371]
Dla użytkowników aplikacji C:geo oraz konkurencyjnego serwisu istnieje dodatek do zapisywania kesza w aplikacji z poziomu strony internetowej: http://www.cgeo.org/send2cgeo.html

Byłoby fajnie jakby ta funkcja była zaimplementowana również na OC.

**Comment by wloczynutka** [comment]
Zagadnienia opisane na podanej stronie leżą po stronie użytkownika (instalacja rozszerzeń i skryptów w przeglądarce). Wsparcie dla opencaching.pl przez podane skrypty zależy tylko i wyłącznie od ich twórców. (tu: programistów c.geo.) Dane skrzynek i użytkowników udostępniamy przez okapi. Zapotrzebowanie na wsparcie dla OC należy więc zgłosić do zespołu c.geo. Jeśli programiści c.geo bedą czegoś od nas potrzebować w tym temacie, to na pewno pomożemy.

**Comment by azhag-pl** [comment]
Jeśli chodzi o instalację rozszerzenia i userscriptu w przeglądarce, to chodzi tu wyłącznie o dodanie prostego odnośnika https://send2.cgeo.org/add.html?cache=KOD_KESZA poprzez obejście zamkniętego ekosystemu GC. Coś, co można zaimplementować w kodzie OC bezpośrednio.

Niestety druga część send2cgeo, podlinkowana wyżej strona nie ma (na razie) obsługi opencachingowego kodu skrzynki — ręczne wywołanie np. https://send2.cgeo.org/add.html?cache=OP1234 niby zwraca wiadomość „Success!”, ale w aplikacji nic sie nie dzieje.

Dodałem na BTS C:geo [odpowiednie zgłoszenie](https://github.com/cgeo/cgeo/issues/5554). Jeśli obsługa OC w send2cgeo po stronie serwera (i aplikacji?) zostałaby dodana, można liczyć na dodanie odpowiedniego przycisku bezpośrednio na stronie OC? Tak jak jest już wysyłanie kesza do urządzeń Garmina.

**Comment by kojoty** [comment]
na dodanie przycisku z pewnością można liczyć :)

**Comment by wloczynutka** [comment]
Chyba sporo ludzi używa c.geo, można by dorzucić przycisk do sekcji "Pobierz dane".

**Comment by azhag-pl** [comment]
Okazuje się, że OC już jest w pewnym stopniu obsługiwany przez send2cgeo, jednakże nie opublikowali jeszcze tego oficjalnie z powodu braku należytych testów: https://github.com/cgeo/cgeo/issues/5554

Wstępnie przetestowałem i wydaje się, że działa jak należy (nawiasem mówiąc moje wcześniejsze stwierdzenie, że „w aplikacji nic sie nie dzieje” było wynikiem niezrozumienia zasady działania. :)

W podlinkowanym zgłoszeniu podali wersję userscriptu dla OC.pl/.nl, która działa jak należy. Działa też wejście bezpośrednio na https://send2.cgeo.org/add.html?cache=OP1234, więc można to bez problemu zaimplementować tak jak chcemy (czy raczej: chcecie).

Jeszcze napiszę na forum z prośbą o dokładniejsze przetestowanie.

**Comment by azhag-pl** [comment]
Tak to wygląda w usersripcie:

- dodany przycisk: https://dug.net.pl/~azhag/opencaching/s2cgeo1.png
- po kliknięciu JS wyświetla na kilka sekund taki iframe o adresie https://send2.cgeo.org/add.html?cache=OP1234: https://dug.net.pl/~azhag/opencaching/s2cgeo2.png

Ponieważ pokazuje on efekt działania lub konieczność dopiero skonfigurowania send2cgeo ("zarejestrowanie" przeglądarki i podanie PIN-u wygenerowanego w apce) do prawidłowego działania, należy wg mnie pokazywać zawartość tej strony.

Czy jako iframe, czy jako osobne okienko (jak po kliknięciu na "Wyślij WayPoint do GPS") to już sprawa raczej drugorzędna (choć iframe wygląda fajniej).

**Comment by azhag-pl** [comment]
Na szybko przetestowałem. Przy braku "zarejestrowanej" przeglądarki (czyli bez odpowiedniego ciasteczka), ładnie wyskakuje okienko "Register first". Przy "zarejestrowanej" również wyskakuje okienko, ale nieomal od razu się zamyka — nie wiem czy ze strony OC można wymusić timeout, czy to kwestia send2cgeo i nic z tym nie zrobimy.

Ale w każdym razie funkcja działa. Po kilknięciu na dodany odnośnik i wybraniu importu w c:geo ładnie zapisuje wybrane kesze. :)

Dzięki jeszcze raz!

**Comment by wloczynutka** [comment]
Poczekajmy z tydzień, niech się uleży, Zobaczymy jak większa ilość użytkowników zacznie korzystać. Potem trzeba będzie dorobić tłumaczenia i zmiany kosmetyczne. Jeśli to ma być używane z poziomu przeglądarek mobilnych to guzik powinien być na tyle duży, żeby łatwo się go klikało paluchem.

Nie wiem czemu okno się samo zamyka. Wydaje mi się że to powoduje jakiś skrypt po stronie c.geo. po naszej stronie jest tylko funkcja która to okno otwiera.

**Comment by azhag-pl** [comment]
Rzeczywiście, jest jak byk:

    <script language="javascript" type="text/javascript">
    
    </script>

Spróbuję zagadać, żeby ustawili małe opóźnienie.
