### ISSUE TITLE
Cache attributes - deprecated / old / unused (?)

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#380]
While working on the english translation, I've come upon some strings that seem to have no use in the website. 

One such example is: `'horse_path'`
The only reference seems to be in tpl/stdstyle/cache-atr.tpl.php
```
   if ($atr38 == horses)
                    echo '<img src="/images/cacheatr/ears.gif" border="1" title="' . tr('horse_path') . '" />';
```
cache-atr.tpl.php is not referenced anywhere.

I've seen no reference to this attribute on any OPENCACHING-PL based website. 

My question is: can attributes that are no longer used (perhaps remnants from the original fork from the german code) be removed? Should they? Even the graphics are different entirely.

**Comment by wloczynutka** [comment]
I think yes. 
And code you quted is invalid, (will throw notice, and never gets inside of 'if')

**Comment by andrixnet** [comment]
Reassigned to https://github.com/opencaching/opencaching-pl/issues/462
