### ISSUE TITLE
Viruses and other unwanted sh*t

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#381]
For more than 10 years i use Linux and never needed a virus scanner, until this morning. My browser did link me to http://ww2.opencaching.nl/?folio=7POYGN0G2 and not to http://www.opencaching.nl. This was with FireFox and Chromium.
After installing a Linux virus scanner and scanning some maps it found 62 viruses :-( .
Also i did scan the map OCPL git. This contains all downloaded files from Github and is my VM. The result shows in the next image.
![selectie_142](https://cloud.githubusercontent.com/assets/1060518/13992504/9db90914-f11c-11e5-8aae-ca3420385995.png)
Now i wonder, are these finds real trojans and are all other files safe?

**Comment by wrygiel** [comment]
Are you using heuristic analysis?

**Comment by harrieklomp** [comment]
I have used ClamTK, a free virus scanner.

**Comment by harrieklomp** [comment]
This was a local problem.
