### ISSUE TITLE
Redirection to wrong page after click on 'watch' in viewcache.php

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#384]
> Cześć,
> Nie mogę dziś dodać skrzynki do obserwowanych.
> Po kliknienięciu linku "Obserwuj" przerzuca mnie na nieco zmodyfikowaną stronę "Aktualności"

Reproduction (after watch click):
![kopytko](https://cloud.githubusercontent.com/assets/13780868/14001934/ef6d6cc4-f148-11e5-923b-7acc220467ee.png)

Maybe related with: #336

**Comment by wloczynutka** [comment]
coś specyficznego dla środowiska produkcyjnego. (php 5.3 ???) U mnie lokalnie działa bez zarzutu.
Domyślam się, że na produkcji $error w linijce 9 nie ma wartości "false" i przetwarzana jest komenda z konca skryptu. Musi się coś dziać w common.inc.php, nie za bardzo mam jak sprawdzić, dlaczego $error się tak ustawia na produkcji? jakoś specyficznie się inicjuje połączenie z bazą?

**Comment by mzylowski** [comment]
Zassałeś ostatnie zmiany na swoim środowisku lokalnym?
Z ostatnich zmian to edycje w 'watch cache' były w kojotowym commicie bazodanowym (#377), ale na pierwszy rzut oka nie ma tam nic strasznego.
(Ja jestem odcięty aktualnie od lokalnego środowiska)

**Comment by wloczynutka** [comment]
tak, zassałem.
W sumie ten if ($error == false) tam już nie ma sensu, skoro nie jest używane połączenie z bazą z common.inc.php, spróbuję to zmienić.

**Comment by kojoty** [comment]
To na 99% Mika wina. Niby staram się wszystko testować ale czasem coś tam mi umknie. Poprawie z rana. Sorki za problemy...

**Comment by wloczynutka** [comment]
A jednak nie to co pisałem. coś innego.

**Comment by wloczynutka** [comment]
Coś jest jeszcze z inkrementacją pola watcher w tabeli caches.

**Comment by kojoty** [comment]
@wloczynutka tak z ciekawości - czemu twoja zmiana pomogła?

> Coś jest jeszcze z inkrementacją pola watcher w tabeli caches.
może teraz w kodzie już by było OK, bo wcześnej było to robione tak, że wartośc w tym polu była modyfikowana na zasadzie:
- select z bazy
- inkementacja / dekrementacja w php
- zapis do bazy 
...i to wszystko bez transakcji wiec mógł się jakiś wyscig zdarzyć i już mieliśmy ujemną wartość w tym polu, ja to przy okazji poprawiłem, więc może jakby jeszcze w bazie wszystkei wartości ujemne zamienić na 0 i by było już spoko...

**Comment by wloczynutka** [comment]
czemu twoja zmiana pomogła?

Sam do końca nie wiem - Twój kod był poprawny i u mnie lokalnie działał bez zarzutu. Podejrzewam, że albo w starym php  albo w starym oprogramowaniu bazy musi być jakiś przedawniony bug. Już tu miałem podobne jazdy, więc jakoś intuicyjnie udało mi się wytypować sprawcę. Gdy wartość pola była 0, to zwracało false. (a powinno 0). Nowy php/mysql się już tak nie zachowuje, a ten dziad serwerowy tak.) 

> i to wszystko bez transakcji wiec mógł się jakiś wyscig zdarzyć i już mieliśmy ujemną wartość 

Tak tu może być przyczyna, ale dodanie transakcji nic by nie dało, raczej musiało by być nałożenie blokady na tablekę pomiędzy odczytem a zapisem pola. (transakcja nie wpływa na inny proces który może równocześnie inkrementować wartość z tego samego wiersza i pola.

> , więc może jakby jeszcze w bazie wszystkei wartości ujemne zamienić na 0 

trzeb by sprawdzić jeszcze jak jest realizowane zdejmowanie obserwatora, może być podobnie. I wrtości nie na zero, tylko trzeba by uzupłenić jednorazowo selectem z liczby obserwatorów z tabelki cache_watches

**Comment by kojoty** [comment]
pełna zgoda :)

**Comment by mzylowski** [comment]
Let's continue it in #336
