### ISSUE TITLE
Remove validator links in footer

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#385]
The "W3C XHTML 1.0" validator and "W3C CSS 2.0" validator links should be removed from the footer, at least for now. 

XHTML validator returns 75 Errors, 18 warning(s)  on home page
CSS validator returns Errors (8) Warnings (29) on home page. 

I believe it is bad image to show/advertise these in the footer of every page under the above conditions.

**Comment by andrixnet** [comment]
Commented out in main.tpl.php (only occurence).
I chose to comment it based on the premise that in the future the website will again conform and validate correctly.

**Comment by andrixnet** [comment]
Done. (you can see it on OCRO, which is temporarily not synced). 
Will request a pull when all english strings I am working on have been cleaned up.

**Comment by kojoty** [comment]
BTW, I think that we can check in future what is reported by validators - probably we should fix it also...

**Comment by andrixnet** [comment]
of course.

Just that I don't think others should see the results, having errors is
bad for our image
