### ISSUE TITLE
Super Admin

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#386]
> // user_id of admin who have more options than COG users to remove all logs or other more options in admin_users.php
> 
> $super_admin_id in :
> settings-example.inc.php
> admin_users.php
> 

If Super Admin is to remain and be properly implemented, I believe it should feature the following: 
* setting the super admin to be a single user in settings.inc.php? or a list of users? 
* Super admin, if set in settings.inc.php must not require `user`.`admin`=1
* have a distinct superadmin panel (left menu) below admin panel
* superadmin panel to contain pages for each feature specific to the superadmin.
* it should at least be able to: 

- [ ] user list page with GUI to assign / remove admin privileges
- [ ] delete user account (all personal information removed, account inactive, but remains assigned)
- [ ] remove logs (as mentioned above)
- [ ] other tasks suitable for this role
- [ ] revoke OKAPI key (?)
- [ ] reset some flags in database, such as Geokrety last access time to now() (?), etc

-------------
I believe that all these tasks are application tasks that should be performed from a GUI by a userland administrator.
Website configuration and database administration are separate tasks, perhaps even for a different system administrator.

If super admin is considered useless and to be removed (though I believe it is a good idea), then please mark as WONTFIX.

**Comment by wloczynutka** [comment]
I think we do not need superadmin. There is no superadmin already in code. this 3 lines is not working i suppouse. It can be removed.

**Comment by andrixnet** [comment]
@wloczynutka fine by me :-)
