### ISSUE TITLE
Problem with cache status - automaticaly changed from 'Not yet available' to 'Ready for search' without owner  approval!

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#395]
From fb:

> Witam. Czy jest coś grzebane przy geosciezkach bądź w kodzie tychże? Dodaje sobie skrzynki do geosciezki która jest jeszcze nie gotowa, skrzynki są niepublikowane itp,trzymam sobie w je potajemnym sekrecie, a nagle system sam mi je publikuje? Trochę nie fair, bo przez to był mały niekontrolowany wyciek informacji. Tyle dobrego że skrzynek nie ma jeszcze w terenie bo ktoś mógłby sobie pojechać i ja podjąć Emotikon smile Zwłaszcza że opublikowanej skrzynki nie da się "ukryć". Druga sprawa jest taka że niektóre skrzynki jak.zakladam, mają adnotacje przy publikowaniu jej w określonym terminie "publikuj w 1970 roku" ;D Jak ktoś coś wie na temat "samopublikacji" keszy to proszę o reakcje,narazie kresle je w zeszycie bo nie uśmiecha mi się dostać maila w środku nocy o nowej,mojej skrzynce, tak jak.mialo to.miejsce wczoraj Emotikon smile Pozdrawiam!

Other comment:
> Dziś przygotowywałem kesza. Standardowo zaznaczyłem opcję "jeszcze nie publikuj". Jakiś czas później wchodzę na stronę kesza i.... Skrzynka gotowa do szukania i 6 wejść. Nigdy wcześniej nie miałem tego problemu, a tu proszę... Trochę niefajnie.

**Comment by wloczynutka** [comment]
co to za geościeżka? (Nie sądzę, żeby sama się opublikowała)

**Comment by deg-pl** [comment]
One more http://opencaching.pl/viewlogs.php?logid=2064724

**Comment by kojoty** [comment]
ok, chyba widzę na czym polega problem:
przy edycji skrzynki ustawia się data publikacji
![image](https://cloud.githubusercontent.com/assets/2961448/14054937/c87bf112-f2dd-11e5-9bb4-0002e4803040.png)

i to dlatego się "autopublikuje"...

Nie wykluczam, ze to znowu moja wina...
debuguję :)

**Comment by kojoty** [comment]
ok już wiem:
w bazie typ data: ustawione na 'null' (w uszach) zamiast null daje wynik = 0 i aktywuje kesza...
oczywiscie uszy dodaje PDO kiedy binduje zmienną o wartości null...
