### ISSUE TITLE
Incorrect data in viewprofile.php

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#403]
From Forum:

> Zerkam sobie na profil dowolnego usera: zniknęły ostatnie logi w jego skrzynkach. Z góry dziękuję.

and

> Liczba dni "keszowania" wynosi 1.
> Mało koszulę ostatnio, jednak bez przesady :)

From my (deg) profile:
![staty](https://cloud.githubusercontent.com/assets/13884863/14059501/7e80435a-f342-11e5-8bd6-f41e4b12d8ea.png)

Maybe new "null" problem? :)

**Comment by kojoty** [comment]
oczywiście mój problem...
poprawka w drodze

**Comment by kojoty** [comment]
chyba działa...
niestety to nie koniecznie ostatni tego typu błąd...
