### ISSUE TITLE
"Created caches in geopaths" statistic in user profile display too much...

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#407]
za fb:

> Tomanek Tomanek Witam! Zauważyłem, że w profilu użytkownika pojawiła się nowa kategoria "punkty za skrzynki założone"-w geościeżkach. Rozumiem, że za chwilę pojawią się nowe staty i nowe grupy debeściaków. Ale co? W moim profilu widoczna jest geościeżka, która nigdy nie była odpalona (i nie będzie) i służy raczej jako "tester" do różnych rzeczy (np. budowaniu geoszkicu, albowiem narzędzi takich u nas brak). Wydaje mnie się, że geościeżki nieodpalone nie powinny być liczone, do tych "punktasów" za "skrzynki założone" w geościeżkach i widoczne w profilu użytkownika.

oraz 

> Renata Grocka Pozycja (Założył skrzynki w xxx geościeżkach) jest niepoprawna. Pokazuje ona bowiem ilość geościeżek, w których jestem założycielem/współzałożycielem a nie geościeżek, w których mam de facto założone swoje własne kesze. Poza tym według mnie pokazywanie w profilu geościeżek, które ktoś założył a są jeszcze niewidoczne psuje zabawę. Człowiek tworzy coś, co jeszcze nie jest dopracowane/puszczone publicznie - a wszyscy inni widzą już jakąś część tego dzieła. Co prawda jest to tylko nazwa i logo (w samą geościeżkę zajrzeć się nie da), mimo to nie wszyscy zorientowali się, że takie właśnie geościeżki ujrzą światło dzienne. W efekcie wystarczy wejść na profile okolicznych keszerów i już wiadomo, co niedługo powstanie. Zamknięcie geościeżki nie powoduje jej usunięcia z widoku profilu usera. Sama idea takich statystyk w profilach jest ciekawa. 

jak na moje oko:bug 
@wloczynutka - wołam bo to chyba w kontekście twoich zmian...

**Comment by wloczynutka** [comment]
spróbuję z tym powalczyć.
