### ISSUE TITLE
QRcode generator bugs and features

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#41]
```
1. path-related problems, QRcodes are working when $dynbasepath points to 
www-root, because image is saved under $dynbasepath + "/tmp/qrcode.jpg", and 
then referenced as img src="/tmp/qrcode.jpg" from html

2. when multiple users generate qr-codes simultaneously, one can get code of 
another user, because all of them are stored in a single location in a 
filesystem
```

Original issue reported on code.google.com by `boguslaw...@gmail.com` on 17 Feb 2014 at 12:38

**Comment by kojoty** [comment]
Instead of fixing this my proposition is to:
- remove qr-code generator at all from OC code
- add rich description with links to free online generators at wiki subpage
- add wiki subpage link to the menu 

I can't see any sens in hosting one-more qr-code generator...

**Comment by harrieklomp** [comment]
Why not keep it on the oc sites?
OC offers a lot off extras, where other sites misses this future and other futures.

Personally i suggest to keep this on the OC sites and hope it will stay :-)

**Comment by andrixnet** [comment]
@harrieklomp :+1: 

In fact I wanted to suggest also an item in cache parameters list that gives the plain QR-code (no additional template) as well.

**Comment by andrixnet** [comment]
Regarding the bugs : 

> 1. path-related problems, QRcodes are working when $dynbasepath points to 
> www-root, because image is saved under $dynbasepath + "/tmp/qrcode.jpg", and 
> then referenced as img src="/tmp/qrcode.jpg" from html

- use website base URL and URL rewrite : http://opencaching.pl/OP1234 (shorter string, smaller code)
- generate a QR code (only the code) for each cache in a different file (named according to cache codem thus unique). Use PNG, compresses better for B&W image of the code.
- create this code at cache creation time and store it. 
- offer the QR code in cache description as a JS popup
- offer the QR code label generator (current QR code page)

> 2. when multiple users generate qr-codes simultaneously, one can get code of 
> another user, because all of them are stored in a single location in a 
> filesystem
- Use the already existing QR codes (could/should be generated at the time the cache is created).
- Allow creation of QR code based labels using selectable templates
- allow creation of custom codes based on user supplied string (ie coordinates, additional waypoints, etc)
- create the label file name using a hash between cache code (or user string) and template and user generating it. Save file into temporary location. Offer the file for download.
- use cron job to delete old files (older then 1 day?)

**Comment by kojoty** [comment]
@harrieklomp, @andrixnet 
I agree that qr-code is a nice gadget and it can be useful in geocaching, but take a look how many great free qr-code generators are online:
[(https://www.google.com/?gws_rd=ssl#q=qr+code+generator+free+online)]

We have a lot of work with our "fundamental" features around geocaching and I can't see much sense in spending time on maintenance "gadgets" if much better generators can be found around in the Internet...

One more argument:
In April 2016 oc.pl has 130 views of qrcode-generator page.

Of course this is only my current opinion - maybe I'm wrong with it.

**Comment by andrixnet** [comment]
130 views out of how many cache hides?

**Comment by kojoty** [comment]
> 130 views out of how many cache hides in April?

I don't know (I'll check in the db) but:
- newcache.php page had more that 3500 views in the same time 
- currently I found more than 1500 caches at oc.pl and I know **one** cache (maybe I forget something?) which uses qrcode as a part of the game so if you want to proof that this is a an often used feature - I disagree...

**Comment by deg-pl** [comment]
I agree with @kojoty
I've found 4000+ caches and about 3-4 which uses QRcodes...
Munzee is for people who like QRcodes ;)

**Comment by harrieklomp** [comment]
@deg-pl and @kojoty  , How many of your finds are nano and micro caches (traditional caches) and how many from those caches are in a trail? I do not count the final (Quiz) caches that are the bonus of a trail.

I am only trying to say that the game Geocaching has been changed from finding a treasure to find as many as possible caches. Sure, this is a unwanted (personal opinion) evolution of the game. For those (trail) caches you do not need a QR generator.

On OC.NL i have decided that people cannot make Micro caches any more to prevent this competition. This way OC.NL is trying to let people make the original caches how it was invented. For that we like to offer a own QRcode generator without a link to a external generator.

A suggestion is to make this QR button via settings file and leave the generator in the code. This way each node can decide if QR generator is used. When it is not used often there should not be a problem and no need to rebuild it. Perhaps in future when someone has time can rebuild this generator.

**Comment by kojoty** [comment]
@harrieklomp, I checked the size-stat for myself:
``` 
SELECT count(*), size FROM caches 
WHERE cache_id IN (
SELECT `cache_id` FROM `cache_logs` WHERE `user_id` = '59636' and type = 1) 
GROUP BY size

576	2 - micro
563	3 - small
277	4 - regular
40	5 - large
17	6 - v-large
57	7 - no-cont. 
```

> I am only trying to say that the game Geocaching has been changed from finding a treasure to find as many as possible caches. Sure, this is a unwanted (personal opinion) evolution of the game

This is side-discussion but I disagree - it depends of people - I can't see any clear trend around me...

To the point:
OK, If this qr-code generator is important for you - OK - let's maintain it - It's not a big deal finally :smiley:

**Comment by kojoty** [comment]
changes made around commit https://github.com/kojoty/opencaching-pl/commit/dc26c4d46967eb1484c455cb278b4794d7f2bf5a

- pure QR-code and oc-labelled QR-code are stored in separated files with unique names
- QR-code images older than 1 hour are automatically removed
- small UI improvements

**Comment by kojoty** [comment]
OK I think QR code gen. is OK now - please reopen if I'm wrong.
