### ISSUE TITLE
Set new route should show node's country

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#411]
http://www.opencaching.ro/myroutes_add_map2.php on OC RO and OC NL shows Poland on the map (by default). 

This page should have coordinates and zoom level configured separately (per node). 
Coordinates could be the same as home page mini-map, but zoom level must be different.

**Comment by harrieklomp** [comment]
Followed all links to different nodes and is shows the correct country map. It seems this issue is solved and can be closed.

**Comment by andrixnet** [comment]
I might have solved it when I worked on GPX files, just forgot to close the corresponding issue. My appologies.
