### ISSUE TITLE
Move a label of coordinates

### ISSUE THREAD

**Issue by tripper1971** [opencaching/opencaching-pl#414]
Move a label of coordinates on satellite map (full screen)

Paulina Jac Jak już tak wszystko poprawiacie. To przesuńcie pasek współrzędnych na powiększonej mapie. Bo jak widać go nie widać.

**Comment by kojoty** [comment]
@tripper1971, Ty rozumiesz o co chodzi w tym problemie?

**Comment by deg-pl** [comment]
O to chodzi:
![12916155_1043619329017927_8739793583564053049_o](https://cloud.githubusercontent.com/assets/13884863/14086480/9ee2c890-f525-11e5-99f6-52b9bc5a5fd6.jpg)

**Comment by kojoty** [comment]
OK dzięki, kumam, coś pokombinuję...

**Comment by kojoty** [comment]
przesunięte na lewo, najbardziej jak się da...
