### ISSUE TITLE
Issues around event logs: duplicate "will attend" + wrong emails 

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#418]
from email:
> wpisalam sie dwa razy na event 
> zorientowalam sie przypadkiem
> i jak usunelam swoj wpis 
> to dostalam maila o tytule "Twój wpis do logu został usunięty przez właściciela skrzynki "

**Comment by deg-pl** [comment]
Dokładnie tak jest - przy usunięciu swojego wpisu dostaję niepotrzebnego maila, że wpis usunięty przez właściciela skrzynki. Nawet issue miałem założyć, ale nie zdążyłem ;)

**Comment by wloczynutka** [comment]
zaraz zajrzę, pewnie jakiegos ifa zapomniałem/źle napisałem
