### ISSUE TITLE
Incorrect adresses in activation e-mail

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#420]
Activation e-mail from opencaching.ro:
![ro](https://cloud.githubusercontent.com/assets/13884863/14126617/915db23c-f612-11e5-8626-1f6d60835e89.png)

**Comment by wloczynutka** [comment]
I done similar fixes yesterday for removelog email. Maybe this can help:  https://github.com/opencaching/opencaching-pl/commit/97c60406c7bd168ce3afc2ca8d765e8dd3a96558.
