### ISSUE TITLE
Friendlier URLs

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#424]
When viewing a cache, the website always presents the following URL:
`http://www.opencaching.XX/viewcache.php?cacheid=123`
All actions that link to `viewcache.php` reference it by id. 
All actions that return to `viewcache.php` reference it by id.

ID is an internal number from the database. While it may be the most efficient way of referencing a row in a table, it is of no use to the end user. 

The `viewcache.php` also accepts `wp=OX1234` parameter. 
Having **OX1234** displayed in the URL is of great help to the user, to identify the cache. 

.htaccess redirection exists for the following: 
`http://www.opencaching.XX/OXcode` -> `http://www.opencaching.XX/viewcache.php?wp=OX1234`
(another way of referencing the cache in a very short and humanly easy to remember way). 

---

This feature request asks for: 
- all links to `viewcache.php` to show this type of URL in browser location:
  `http://www.opencaching.XX/viewcache.php?wp=OX1234`
- all returns to `viewcache.php` to show this type of URL in browser location:
  `http://www.opencaching.XX/viewcache.php?wp=OX1234`
- viewcache.php feature either the cache name as link to `http://www.opencaching.XX/OXcode` or a separate way of showing and sharing this URL. (ie for social websites)

**Comment by wloczynutka** [comment]
Routing is advanced toipic. Modern frameworks give chance to define route
as programmer wants, and display human-friendly url, like f.e.
opencaching.pl/geocache/OX1234 or opencaching.pl/log/123456789 and similar.
It would be great to have similar in oc but needs deep refactoring, and
pass every action via controller instead separate scripts.

2016-03-30 14:56 GMT+02:00 andrixnet <notifications@github.com>:

> When viewing a cache, the website always presents the following URL:
> http://www.opencaching.XX/viewcache.php?cacheid=123
> All actions that link to viewcache.php reference it by id.
> All actions that return to viewcache.php reference it by id.
>
> ID is an internal number from the database. While it may be the most
> efficient way of referencing a row in a table, it is of no use to the end
> user.
>
> The viewcache.php also accepts wp=OX1234 parameter.
> Having *OX1234* displayed in the URL is of great help to the user, to
> identify the cache.
>
> .htaccess redirection exists for the following:
> http://www.opencaching.XX/OXcode ->
> http://www.opencaching.XX/viewcache.php?wp=OX1234
> (another way of referencing the cache in a very short and humanly easy to
> remember way).
> ------------------------------
>
> This feature request asks for:
>
>    - all links to viewcache.php to show this type of URL in browser
>    location: http://www.opencaching.XX/viewcache.php?wp=OX1234
>    - all returns to viewcache.php to show this type of URL in browser
>    location: http://www.opencaching.XX/viewcache.php?wp=OX1234
>    - viewcache.php feature either the cache name as link to
>    http://www.opencaching.XX/OXcode or a separate way of showing and
>    sharing this URL. (ie for social websites)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/opencaching-pl/issues/424>
>



-- 
__________________________________
*Andrzej 'Łza' Woźniak*

*(+48) 798 835 592*
skype praca: *andrzej.wozniak.traveltech*
skype dom: *wloczynutka*

**Comment by andrixnet** [comment]
Until then, if I can do it with my limited PHP skills, I will try to implement this in each script.

**Comment by kojoty** [comment]
I think we should go this way in a future, but let's discuss it together. I think we should prepare the plan of modernization of the oc service and implement it step by step - not everything in the same time.

**Comment by wloczynutka** [comment]
I agree with @kojoty. routing must be done after planning, to give way to
easy route all actions in our application.

2016-03-30 15:41 GMT+02:00 kojoty <notifications@github.com>:

> I think we should go this way in a future, but let's discuss it together.
> I think we should prepare the plan of modernization of the oc service and
> implement it step by step - not everything in the same time.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/opencaching-pl/issues/424#issuecomment-203438683>
>



-- 
__________________________________
*Andrzej 'Łza' Woźniak*

*(+48) 798 835 592*
skype praca: *andrzej.wozniak.traveltech*
skype dom: *wloczynutka*

**Comment by andrixnet** [comment]
Wouldn't reimplementing like that require an significant, if not almost complete rewrite of the entire code?

Perhaps, until then, we could include the simplest form of friendly URL in viewcache.php, displayed to the user, like the last point above?

**Comment by kojoty** [comment]
@andrixnet, 

> Until then, if I can do it with my limited PHP skills, I will try to implement this in each script.

This seems to be a bigger refactoring - if you mean general change - are you sure this is possible without negative impact at the stability of the code?
  
If you think only about viewcache script - go ahead - it seems to be quite easy
 thing...

**Comment by andrixnet** [comment]
Changing in each script may slightly affect DB performance, although, not much, if any at all, if `code` column is an index. 
Testing should show if there is any stability problem, but the only real problems may be because of incorrect code (bugs) introduced. 

Anyway, it must be tested thoroughly and I wouldn't request a pull on this matter before that.

**Comment by wloczynutka** [comment]
@andrixnet You can pass identifier as other part of url or by post, to avoid selecting by waypointidentifier.
But first of all I reomend studying this: http://symfony.com/doc/current/book/routing.html to get knowdlege how is is done in quite nice way.

**Comment by kojoty** [comment]
Update: routing is now implemented (https://github.com/opencaching/opencaching-pl/blob/master/Utils/Uri/SimpleRouter.php). Now we need to add generic geocache controller and the link can be seen as: 
`opencaching.xx/geocache/get/op1234
                              /geocache/edit/op1234
                              /log/op1234
`
...and so on.

**Comment by kojoty** [comment]
OK, I think that this issue can be closed now: 
- routing is implemented
- detailed path can be refactored
