### ISSUE TITLE
viewcache.php hiding or not including?

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#425]
viewcache.php contains a lot of sections that are hidden from view with HTML comment tags. 
While this is OK for some sections that are to be ommited from print view, it is NOT OK for sections that should not be included AT ALL. It has the potential to lead to information leakage and possible abuse of disabled or not normally available features like the openchecker or cache notes, etc.

This also exposes template variables and string variables in source code which is not parsed.

For example: http://www.opencaching.ro/viewcache.php?cacheid=295 
- shows in source code a section about MP3 files (as comments)
- exposes variables: `<span style="font-size:13px;">{notes_content}</span>`
- exposes FORM element for cache notes `<form action="viewcache.php?cacheid=295#cache_note1" method="post" name="cache_note">`
- exposes FORM element for modified coordinates `<form action="viewcache.php?cacheid=295" method="post" name="form_coords_mod">` 
  This cache does not require one.

---

IMO all unecessary sections of HTML code from a template should be completely ommited.

Print view could use either PHP and comments or Javascript and setting CSS display="none" to hide.

**Comment by kojoty** [comment]
I think this issue was fixed with my last viewcache.php refactoring - if not please reopen it.
