### ISSUE TITLE
add cache "publication date" - change in "activation" mechanism

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#426]
z fb:

> ... da się zmienić zeby najnowsze skrzynki pokazywała stronka od daty opublikowania? Bo teraz segreguje wzgledem daty założenia, która niekiedy nie ma nic wspolnego z opublikowaniem...

Now _cache.date_activate_ field contains date of publication only if the time of publication is set and this date is reset to _null_ after activation...

**Comment by andrixnet** [comment]
I am not sure I understand the logic well enough.

**Comment by deg-pl** [comment]
Duplicate of #1386
