### ISSUE TITLE
UI improvment around send2c:geo link

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#440]
Issue from https://github.com/opencaching/opencaching-pl/commit/ff0ab320300b2ab6f455bb7720d88dfcfb168e53 discussion.
Button for send cache to GPS also shud be moved into "mobileApps" section.
Also better name than 'mobileApps' will be 'send to mobile devices' or just 'mobile devices'.

**Comment by wloczynutka** [comment]
Also proper translations should be added.
