### ISSUE TITLE
Problem z nowozakładanymi skrzynkami / Problem with new caches

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#444]
Założyłem przed chwilą skrzynkę i nie mogę do niej nawet zajrzeć.
![nowa skrzynka](https://cloud.githubusercontent.com/assets/13884863/14218091/64736874-f852-11e5-81bd-2ab30d857f75.png)
Przyznać się - kto sknocił? :) Albo lepiej niech naprawi ;)

**Comment by wloczynutka** [comment]
lepiej powiedz jak Ci się udało ominąć walidację trudności. Ustawiłeś 0 i przeszło, czy ustawiłeś coś innego a system władował do bazy 0? jesteś w stanie odtworzyć błąd?
(Poprawiłem w bazie wartość `terrain` z 'null' na 2 i teraz bangla. teoretycznie walidator nie powinien dopuścić do wpisania nulla)

**Comment by deg-pl** [comment]
Ustawiłem trudność na 2/2

**Comment by deg-pl** [comment]
Na moim serwerze devel mam dokładnie to samo - założyłem podobną skrzynkę i wywala mi identyczny problem. Terrain mam null, watcher i ignorer_count też mam null (zamiast 0)

**Comment by wloczynutka** [comment]
@kojoty chyba Twoje, wydaje mi się że może być winne zapytanie newcache.php, linia 682-695. Nie mogę się tam rozeznać w tych pytajnikach :-(
Mogę tylko gdybać teoretycznie, bo lokalnie nie działa mi newcache.php - (buntuje się na kilku rzeczach z zainkludowanych plików i na szybko tego nie wyłącze.)

**Comment by deg-pl** [comment]
Zerknijcie przy okazji do bazy, jakie skrzynki były ostatnio założone - pewnie nie tylko ja mam z tym problem i trzeba też inne odczarować

**Comment by wloczynutka** [comment]
poprawiłem paręnaście minut temu 3 skrzynki.

**Comment by kojoty** [comment]
już lookam, pewnie znów coś mojego...

**Comment by kojoty** [comment]
ok poprawka zaaplikowana, powinno być lepiej, teraz sprawdzam bazę...

**Comment by mzylowski** [comment]
Na pewno coś będzie ;]
![selection_006](https://cloud.githubusercontent.com/assets/13780868/14220939/96641fac-f863-11e5-8e7b-b2d3830795fe.png)

**Comment by kojoty** [comment]
poprawione w bazie... powinno być ok.
