### ISSUE TITLE
Delete logs not working properly

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#451]
When delete a log via "The latest logs" on left menu on /viewlogs.php?logid=??? the delete button does not work.
On the cachepage itself the delete button works, but without the proper warning (confirm_remove_log). This happens when a cache owner does delete a log, and if the logger want to remove a log.
I remember that this warning was build in the code.

**Comment by kojoty** [comment]
@wloczynutka it seems that 'del-button' calls not implemented in viewlogs JS functinon rmLog() - it should be ported/share with viewcache...

**Comment by wloczynutka** [comment]
I try fix it as well tonight.

**Comment by harrieklomp** [comment]
Thanks :+1: 
In recent past when delete a log a popup shows with the question "Are you sure to delete this log?". Now this does not happen.
Could this be activated again?

**Comment by harrieklomp** [comment]
After looking further i noticed that removelog.php is cleaned up that way, that no e-mails are send to notify users of removing logs and the warning is gone.

Did i miss something why this done?

**Comment by wloczynutka** [comment]
emails are sent from email controller (via log controller)

**Comment by harrieklomp** [comment]
Thanks :+1:
