### ISSUE TITLE
Missing top menu on some pages

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#453]
Overview of missing top menu pages. Please edit this comment when something is solved or another page has no top menu.
This will close issues #40 #126 #394 
- add_octeam_comment.php
- admin_users.php
- articles.php?page=cog
- articles.php?page=impressum
- cache-atr.php If this page is still in use. see issue  #380 for the attributes.
- cache_titled.php
- chowner.php?cacheid=****
- editwp.php
- gallery_cache.php
- mailto.php
- myn_ftf.php
- myroutes_add_map2.php
- myroutes_add.php
- myroutes_search.php
- reportcache.php
- viewcache.php?cacheid=0 (This page shows when cache does not exist.)
- viewreport.php

**Comment by andrixnet** [comment]
subscribe

**Comment by andrixnet** [comment]
also missing from `viewcache.php` if waypoint not found

**Comment by kojoty** [comment]
...and missing at /myn_ftf.php
