### ISSUE TITLE
Errors in logs: 'Division by zero'

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#456]
To not forget to fix them...

`[Sun Apr 03 07:51:01 2016] [error] [client 83.8.221.247] PHP Warning:  Division by zero in /var/www/ocpl/powerTrail/ajaxGetPowerTrailCaches.php on line 141, referer: http://opencaching.pl/powerTrail.php?ptAction=showSerie&ptrail=401`

`[Sun Apr 03 11:37:06 2016] [error] [client 79.186.224.68] PHP Warning:  Division by zero in /var/www/ocpl/lib/t5.php on line 23, referer: http://opencaching.pl/articles.php?page=stat`

**Comment by mzylowski** [comment]
As I think commit 2e88f87 by @wloczynutka fixed this. Please reopen if still an issue
