### ISSUE TITLE
wrong geocache created/modified/placed dates after edit geocache.

### ISSUE THREAD

**Issue by wloczynutka** [opencaching/opencaching-pl#459]
details: http://forum.opencaching.pl/viewtopic.php?p=133215#p133202
similar to #444

**Comment by kojoty** [comment]
być może znów jakieś pokłosie moich zmian - spawdzę dziś...

**Comment by kojoty** [comment]
być może było coś na rzeczy ale teraz wydaje się, że wszystko działa poprawnie....
Jeśli ktoś znajdzie sposób reprodukcji problemu chętnie poprawię...

**Comment by deg-pl** [comment]
Skrzyneczka z datą ukrycia dzisiaj, a od roku są znalezienia http://opencaching.pl/viewcache.php?cacheid=41318

**Comment by kojoty** [comment]
@deg-pl, "datę ukrycia" można edytować w opisie skrzynki i można sobie ustawić tam cokolwiek...
