### ISSUE TITLE
Incorrect stats

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#467]
From FB (user czajorek (user Atyde also has this problem)):

klikając na "moje statystyki" Liczba znalezionych skrzynek: 2071,
natomiast jak się kliknie na ogólne statystyki i tam "Ranking użytkowników według liczby odkryć" to wynik pokazuje liczbę: 2066...
dodam, że te dane się rozjechały po pierwszym kwietnia, wcześniej było wszystko w porządku... czyżby nasi programiści za dużo podowcipkowali?

**Comment by wloczynutka** [comment]
To raczje nie jest błąd, tylko interpretacja danych: jedna statystyka wlicza eventy a druga nie.

**Comment by wloczynutka** [comment]
(prima aprilisowe statystyki nie ingerują w żadne zapisy w bazie)

**Comment by deg-pl** [comment]
Raczej nie - u mnie znalezione skrzynki idealnie pokrywają się ze statystykami, u Czajorka nie. Gdyby do tego dorzucić kwestię eventów - rozjechałoby się jeszcze bardziej.
Czajorek - znalezienia keszy: 2071
- eventy: 45. Więc kesze + eventy 2116
A w statystykach ogólnych ma 2066.

Ja tu i tu mam 3669, więc się zgadza, nie mieszając w to eventów.

**Comment by deg-pl** [comment]
Atyde wskazywała, że problem u niej był przez 1 kwietnia

**Comment by kojoty** [comment]
wiec tak:
- "Liczba znalezionych skrzynek:" z viewprofile  - jest brana z tabeli users::founds (czyli taka wtórna wartość)
- liczba keszy w rankingu pochodzi z obliczenia liczby logów znaleziony w tabeli logów - czyli poprawna pierwotna wartość...

hipotezy: 
- mamy jakieś nieścisłości
- trzeba popatrzec czy przy logowaniu zawsze poprawnie sie podbija stat w tabeli "user" (może to moje zmiany zapytań coś uszkodziły - zerknę)
- trzeba zapuścić query, które obliczy wartości found/not/found dla kazdego usera i wpisze w tabele user

**Comment by deg-pl** [comment]
Mam wrażenie, że to efekt działań przy zmianach z mysql*. Ja keszuję na bieżąco i na bieżąco loguję, a problemu nie mam (wczoraj wrzucałem najnowsze logi). Logi wrzucam zarówno przez SzybkiWpis (OKAPI), plik visits jak i ręcznie. Czyli prawodpodobnie wystąpił przez krótki czas był błąd. Teraz wystarczyłoby uaktualnić user::founds i powinno być OK.

Ciekawa wypowiedź Atyde:
Teraz wszystko się zgadza a wcześniej była różnica 2-3 skrzynek.

**Comment by Dezerterzy** [comment]
Dawno, dawno temu u mnie była różnica jednej lub dwóch skrzynek pomiędzy OC (profil), a liczbą prezentowaną przez c:geo. Na dzień dzisiejszy liczba znalezień jest równa i zgadza się z moimi "notatkami". Wtedy, po przeprowadzeniu wnikliwego śledztwa, różnicę powiązałem z zablokowaniem przez COG/RR kilku skrzynek, które wcześniej znalazłem. Zróbcie eksperyment. W swoim profilu wyświetlacie listę keszy znalezionych, przechodzicie do ostatniej karty (strony) i zliczacie ile wpisów tam widnieje. Przykładowo u mnie powinno to być 37 wpisów (3537 znalezień, po 50 wpisów na stronę = 71 stron). Na 71 karcie zamiast 37, są 34 logi "znaleziona". Na wykazie nie ma skrzynek zablokowanych (system je "ukrywa"). Co do dwóch brakujących wpisów jestem pewien (Mój Notatnik - OP72DD, GŁAZ NIEMIERZYŃSKI - OP7D64). Trzeci brak jest podejrzany ale sądzę że może chodzić o Kurrr....czaczek pieczony.... zgubiłem kesza - OP7248. I może stąd różnica?

**Comment by Dezerterzy** [comment]
Profil czajorka - "najstarsze logowania"
http://opencaching.pl/my_logsFind.php?userid=12815&start=2050
Strona powinna zawierać 21 pozycji - zawiera 15.

**Comment by Dezerterzy** [comment]
I inny ciekawy przypadek, w pewnym sensie kontrprzykład do pomysłu, że to "zablokowane" psują staty.
Znajomy (http://opencaching.pl/my_logsFind.php?userid=50029&start=850) 872 znalezienia. Liczba w profilu zgadza się z tą podawaną w starych statach. Też zdobył GŁAZ NIEMIERZYŃSKI - OP7D64 i w jego przypadku liczba znalezień na ostatniej karcie jest pomniejszona o 1 -> kesz zablokowany.

**Comment by wloczynutka** [comment]
@dezerterzy może zamiast teoretyzować zainstalował byś byś sobie kod oc lokalnie lub VM-kę lokalnie i pomógł nam to zdiagnozować w kodzie?

**Comment by Dezerterzy** [comment]
Ok. Instalka wg starej instrukcji kojotów, czy coś się zmieniło?

**Comment by wloczynutka** [comment]
będizesz używać VM czy xammpa, czy jeszcze czegoś inngo?

**Comment by wloczynutka** [comment]
podejrzewam, że inkrementacja jest robiona w wadliwy sposób.

**Comment by Dezerterzy** [comment]
@wloczynutka Wybieram xampp

**Comment by wloczynutka** [comment]
to musisz ściągnąć kod, zrobić vhosta, doinstalować bibliotekę apc lub apcu (w zależności czy masz php <=5.6 czy >=7), zaimportowac bazę deweloperską i powinno śmigać. Zaraz zobaczę czy mam gdzieś w chmurze kopię bazy deweloperskiej, jak nie mam to w nocy zrobię dumpa i udostępnię - chyba że ktoś będzie szybszy.

**Comment by wloczynutka** [comment]
Niestety nie mam dumpa. Będę musiał zrobić, 
@opencaching/opencaching-pl-lead-programmers może ktoś z was ma pod ręką dumpa bazy deweloperskiej i mógłby udostępnić dezerterom?

**Comment by kojoty** [comment]
koledzy przeskoczcie na inny kanał komunikacji :)
co do PHP7: @Dezerterzy nie instaluj php7 - kod oc nie będzie działał - tylko @wloczynutka jest takim hardcorem :)
co do dumpa bazy - ja mogę udostepnic mój, ale wieczorem

**Comment by kojoty** [comment]
@wloczynutka już wiem gdzie leży błąd:
- w LogEntryController::removeLog mamy rekalkulację statów czyli podliczenie liczby znalezień i wpisanie do tabeli user (ALE TYLKO ZNALEZIEŃ:: log_type =1)
- w log.php/editlog.php/revertlog.php mamy inkrementację statystyki znalezień ( w tabeli user ale dla typów logu znaleziony i uczestniczy w evencie (log_type=1|7)

zatem każde uczestnictwo podbija staty, ale każde skasowanie logu znów ją obniża...

trzeba by zdecydować czy liczymy uczestnictwo czy nie i to ujednolicić...

**Comment by kojoty** [comment]
w ramach fixa rekalkulacja w LogEntryController::removeLog zalicza też eventy...
