### ISSUE TITLE
Log display eats some HTML entity encoding

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#469]
If you enter e.g. "&lt;text&gt;" in the log editor, it will be (correctly) saved as "&amp;lt;text&amp;gt;". But when displaying, this will be decoded to "&lt;text&gt;" (HTML!) and get lost - users won't see it.

OKAPI is working around this for years: If "&lt;text&gt;" is submitted in a log, it will store it as  "&amp;amp;#<i></i>60;text&amp;amp;#<i></i>62;". This will be decoded to "&amp;#<i></i>60;text&amp;#<i></i>62;" when logs are displayed, which gives the original text as output.

A fully backward-compatible solution would be to add the same workaround to OCPL log.php and editlog.php:

```
$log_text = str_replace("&amp;", "&amp;#38;", $log_text);
$log_text = str_replace("&lt;", "&amp;#60;", $log_text);
$log_text = str_replace("&gt;", "&amp;#62;", $log_text);
```

If you decide to change the log _displaying_ code instead, this would mean that
- existing log texts would need to be re-encoded, and
- OKAPI log submitting would need to be updated synchronously to the OCPL code change.

**Comment by following5** [comment]
> This will be decoded to "&#60;text&#62;" when logs are displayed, which gives the original text as output.

It will also be correctly decoded when editing the log entry.

**Comment by kojoty** [comment]
I understand it can be closed. If not please reopen. Thanks.
