### ISSUE TITLE
Do we really need per user shell accounts on the new server?

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#493]
Przeklejam z emaila:

> Mam pytanie do wszystkich: Wymieńcie proszę rzeczy, do których
> wykorzystujecie swoje konta shellowe na OC?

> Jeśli okaże się, że konta bez-rootowe zakładamy tylko po to, aby
> użytkownikom dać dostęp do logów, to czy nie lepiej udostępnić te logi
> poprzez jakąś usługę po HTTP, a kont nie zakładać?

**Comment by deg-pl** [comment]
Na chwilę obecną konta bezrootowe dają cholernie duże uprawnienia, włącznie z pełnym dostępem do bazy OC.
Myślałem, by na nowym serwerze ograniczyć dostęp do /var/www tylko dla wybranej grupy.
Ale z drugiej strony - może faktycznie konta shellowe bez praw do sudo nie mają sensu?

**Comment by mzylowski** [comment]
Jestem umiarkowanie negatywnie nastawiony do tego pomysłu.
Ja tam osobiście wolę lognąć się przez ssh i pogrepować sobie logi niż pobierać wielkie pliki przez http.
Ponakładajcie duże restrykcje na tych użytkowników i już. Zresztą jest tu mowa tylko o kilku kontach.
Dalej: zerknięcie jak ustawiona jest jakaś zmienna w configu. Dla mnie przygotowywanie commita zmieniającego maile to był problem - nie wszystkie zmienne są poustawiane na VMce wrygla. Szczerze to ostatecznie nie wiem jaki będzie na produkcji tytuł mojego maila.
Konta shellowe - tak, ale tylko z uprawnieniami do czytania pewnych rzeczy.

Co do uprawnień do bazy danych myślę że powinniśmy mieć dostęp taki jaki mamy mieć przez phpmyadmina. (Bo z tego co zrozumiałem, umówiliśmy się że każdy będzie miał konto).
Dla mnie to też jest masakra bo na ten moment w ogóle nie mogę zerknąć na bazę danych a ta okrojona na VMce pokazuje bardzo mało danych. Sporo tabel jest pustych, nie wiem co sqlAlerts weszło na produkcję a co nie itd...
Co do samych uprawnień to uważam że non-sudo powinni mieć uprawnienia do robienia selectów i updatów.
Selectów chyba nie trzeba tłumaczyć.
Update - przykładowa sytuacja: ktoś w commitował coś co przypadkowo zeruje jakąś wartość w tabeli. Użytkownicy płaczą, że nie mogę wyświetlić opisu skrzynki. Robię revert na repo, robię update w tabeli  i wszystko działa. A tak będzie trzeba czekać na kogoś z sudo.
Reszta uprawnień - alter, kasowanie itd tylko oczywiście tylko dla sudo.

Można ewentualnie ograniczyć się tylko do phpmyadmina i wtedy całkiem wyciąć sql non-sudo. Kwestia prywatnych preferencji. Jak będę chciał sobie kawałek bazy wyeksportować do vmki to osobiście będę wolał użyć shella niż phpmyadmina.

**Comment by wrygiel** [comment]
> Ja tam osobiście wolę lognąć się przez ssh i pogrepować sobie logi niż pobierać wielkie pliki przez http.

Nie mówiłem nic o pobieraniu logów ;) Jeśli tylko o grepowanie chodzi, to proste przeglądarki tego typu wystarczą: http://tailon.readthedocs.org/en/latest/

> Dalej: zerknięcie jak ustawiona jest jakaś zmienna w configu.

Na nowym serwerze jedynie sudoersi będą mieli dostęp do pliku settings - to chyba ustaliliśmy na ostatnim spotkaniu Skype. Ale ogólnie zgadzam się, że macie okropny burdel w tych plikach. Tylko niektóre zmienne powinny być tajne, a przez to, że nie macie tych ustawień w repo, to tajne są wszystkie. To chyba jednak temat na odrębny wątek.

Kwestia bazy danych to też odrębny wątek - skupmy się tutaj na shellu proszę. Napiszcie co potrzebujecie robić z shella, oprócz przeglądania logów.

**Comment by wrygiel** [comment]
> Jak będę chciał sobie kawałek bazy wyeksportować do vmki to osobiście będę wolał użyć shella niż phpmyadmina.

O takie argumenty chodzi właśnie. Zbierzmy wszystkie takie powodu, potem trzeba rozważyć za i przeciw.

**Comment by mzylowski** [comment]
- dostęp do konsoli sql
- możliwość patrzenia w logi - niby są narzędzia, ale nie wiem na ile sobie toto poradzi z jakimiś dużymi plikami
- chciałbym jako maintainer wiki móc pogrzebać w configu albo rozszerzeniach wiki, a nie biegać za każdym razem do dega
- upgreadować wiki
To tak na szybko.

**Comment by kojoty** [comment]
w kontekście configów:

> Na nowym serwerze jedynie sudoersi będą mieli dostęp do pliku settings - to chyba ustaliliśmy na ostatnim spotkaniu Skype. Ale ogólnie zgadzam się, że macie okropny burdel w tych plikach. Tylko niektóre zmienne powinny być tajne, a przez to, że nie macie tych ustawień w repo, to tajne są wszystkie. To chyba jednak temat na odrębny wątek.

ja mam zamiar jak tylko ogarnę temat wyrugowania mysql_* (a tutaj mam już spory postęp) zamierzam zająć się refaktoringiem konfiguracji.

Moja wizja jest taka, by konfigurację rozdzielić na wiele plików i wtedy nie będzie problemu z tym by dowolnie wachlować ich uprawnieniami i np. plik z hasłem do bazy będzie mógł być jakoś restrykcyjnie traktowany...

**Comment by wrygiel** [comment]
To może zróbmy tak:

* Te osoby, które zajmują się regularnymi aktualizacjami np. wiki czy forum dostaną shella, bo to do pracy na pewno potrzebne.
* Wystawimy przeglądarkę logów i phpmyadmina wszystkim chętnym i zobaczymy czy to wystarcza w zastępstwie kont shellowych.

> Myślałem, by na nowym serwerze ograniczyć dostęp do /var/www tylko dla wybranej grupy.

Ok, też jestem za. Podejrzewam, że takich grup trzeba będzie potworzyć więcej (forum-admins, wiki-admins - nawet jeśli jednoosobowe, to pewnie i tak tak by było przejrzyściej, co?).

**Comment by deg-pl** [comment]
Moja jest za ;). Z grupami to dobry pomysł - łatwe w zarządzaniu.

**Comment by wrygiel** [comment]
Musimy dokładniej podzielić te obowiązki. Ja już straciłem ze 2 roboczo-dni na konfigurowanie, trochę mam dość ;) Zostało mi jeszcze skonfigurowanie crontaba i integracji z Gitem, ale potem będę już chciał przekazać pałeczkę...

@kojoty, nadal nie mam Twojego klucza. Może mam coś nie tak z filtrami poczty? Dziwna sprawa.

**Comment by wrygiel** [comment]
BTW, mój raport wszystkich operacji na serwerze urósł już do 12kB. Nie wydaje mi się, żeby było tam cokolwiek tajnego. Może jednak wrzucę go do repo?

**Comment by deg-pl** [comment]
Możesz wrzucić linka, bo jest ładnie sformatowany ;)
PS: Zamiast dorzucać poszczególnych userów przez visudo, nie lepiej wrzucić linijkę:
# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

**Comment by wrygiel** [comment]
Jasne - zmień co chcesz. Ogólnie nie krępujcie się zmieniać wszystkiego tam. To, że byłem "pierwszy na serwerze" nic nie zmienia ;) Tylko prosiłbym o dopisywanie każdej zmiany do raportu, żeby każdy inny z RT mógł potem to przejrzeć i podpowiedzieć co trzeba (albo nauczyć się czegoś).

**Comment by mzylowski** [comment]
@wrygiel Wrzuć do naszego folderu na google drive ;]
Wtedy każdy będzie mógł tam swobodnie dopisywać swoje rzeczy.

**Comment by wrygiel** [comment]
Google Drive nie wspiera MarkDowna, a tego typu dokumentację jednak sporo wygodniej w MarkDownie się pisze (zwłaszcza, że ostatecznie trafi i tak do GitHuba). Dlatego użyłem https://hackmd.io/. Każdy z linkiem może edytować dokument w `.md`. Na razie wysyłałem wszystkim z `sudo`, ale zaraz Ci też podeślę linka.

**Comment by andrixnet** [comment]
Please add a summary in english on the final resolution for this issue. It may be useful as a guide to other node administrators and teams as well. 

Thank you

**Comment by mzylowski** [comment]
If there still is any work to do, please reopen ;]
