### ISSUE TITLE
Visibility of the settings file

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#494]
As far as I know, we have decided that only sudo users should know database passwords on the new server. Currently the settings file is readable by all shell users. If we decide that only sudo users will be allowed to have a shell account (issue #493), then it's no problem. But otherwise, probably we should change its permissions.

Of course, every committer would still be able to peek into this file via a malicious commit, but this would leave a trace.

**Comment by deg-pl** [comment]
Yes. I think this is a VERY good idea. The same applies to Wiki, Forum etc.
But settings.inc.php file is in .gitignore so solution is not at gihtub but at OC PL server.

Few days ago I made backup of Wiki and Forum (I'm shell user, not sudo), and a moment later - I done mysqldump of database for Wiki and Forum. I think that normal shell user shouldn't to be able to do this.

**Comment by andrixnet** [comment]
It depends on sudo configuration. If user can sudo to another regular user, then it is fine and controllable. 
If user can sudo to root, then things are a lot more complicated and delicate. 
Since settings.inc.php contains DB password, obviously it should only be accessible to users allowed to access database with same rights. 

In the end it all comes down to trusting your own people, their abilities and their actions.

**Comment by andrixnet** [comment]
P.S. with the move to a new server, I respectfully request that https://github.com/opencaching/opencaching-pl/issues/105 be solved on OC PL node as well. 
Thank you

**Comment by andrixnet** [comment]
@deg-pl it would be rather hard to prevent any mysql tool (including mysqldump) from such a user, when he/she already knows the user and password the website uses (and has full rights on that database)

It is however recommended that regular database backups are performed and that they be stored out of reach of such users.

**Comment by deg-pl** [comment]
@andrixnet you didn't understand me (I know - my english if poor ;) ). A regular (shell) user should NOT has access to web server files (OC, wiki, forum etc.).
Now, at OC PL, I (normal shell user) have acces to web server files, so I have access to DB data including user and pass.

**Comment by mzylowski** [comment]
We decided all critical settings (like database pass, google key etc) will be kept in node. The reset of settings will be visible in repo. Also there will be implement mechanism for per-node settings (similar to OKAPI). All of this will be done with #290
