### ISSUE TITLE
Errors till adding/removing pictures - editcache.php

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#495]
Adding:
[Sun Apr 10 12:50:17.504822 2016] [:error] [pid 19214] [client 89.65.18.106:54474] PHP Warning:  OcPdo Error: Query: UPDATE `caches` SET `picturescount`=`picturescount`+1, `last_modified`=NOW()\n                                **WHERE `cache_id`= ?** LIMIT 1. Trace:  | /srv/ocpl/Utils/Database/XDb.php::140 | /srv/ocpl/newpic.php::200 in /srv/ocpl/Utils/Database/OcPdo.php on line 112, referer: https://ocdevel.best.pl/newpic.php?objectid=13652&type=2&def_seq=1

Removing:
[Sun Apr 10 12:47:42.898750 2016] [:error] [pid 19214] [client 89.65.18.106:54447] PHP Warning:  OcPdo Error: Query: UPDATE `caches` SET `picturescount`=`picturescount`-1, `last_modified`=NOW() \n                        **WHERE `cache_id`= ?** . Trace:  | /srv/ocpl/Utils/Database/XDb.php::140 | /srv/ocpl/removepic.php::73 in /srv/ocpl/Utils/Database/OcPdo.php on line 112, referer: https://ocdevel.best.pl/editcache.php?cacheid=13652

**Comment by kojoty** [comment]
@deg-pl,

hej, u mnie się nie reprodukuje.
Co zrobić, żeby się to pojawiło...?

**Comment by deg-pl** [comment]
Dokładnie Jak dodaję i usuwam obrazek.
Nie analizowałem dokładnie, ale nie jest winna fraza "WHERE cache_id = ?" ?

**Comment by kojoty** [comment]
hmm... no nie? ty masz aktualny kod?

**Comment by kojoty** [comment]
to się reprodukuje dla każdego kesza? Otwierasz sobie jakiś kesz do edycji dodajesz obrazek i masz ten error?

**Comment by deg-pl** [comment]
Ech... już mam. To błąd mojej bazy developerskiej. Dostałem ją od Bogusia jakiś czas temu i jak widzę nie jest idealna. Poprawiłem u siebie bazę i działa. Sorry za zawracanie głowy.
