### ISSUE TITLE
Errors in stat pages (/articles.php?page=s9&region=PL12)

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#496]
[Sun Apr 10 13:10:05.497689 2016] [:error] [pid 19270] [client 89.65.18.106:54788] PHP Notice:  Use of undefined constant count - assumed 'count' in /srv/ocpl/lib/common.inc.php(585) : eval()'d code on line 294
[Sun Apr 10 13:10:05.497731 2016] [:error] [pid 19270] [client 89.65.18.106:54788] PHP Notice:  Use of undefined constant userid - assumed 'userid' in /srv/ocpl/lib/common.inc.php(585) : eval()'d code on line 295
[Sun Apr 10 13:10:05.497755 2016] [:error] [pid 19270] [client 89.65.18.106:54788] PHP Notice:  Use of undefined constant nick - assumed 'nick' in /srv/ocpl/lib/common.inc.php(585) : eval()'d code on line 295

**Comment by kojoty** [comment]
przy okazji zmian wokół mysql będzie poprawione...

**Comment by kojoty** [comment]
poprawione gdzieś po drodze - w każdym razie już tego nie widać...
