### ISSUE TITLE
Set cords when geopath is open on the map_v3

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#497]
from forum:

> Postautor: brasia » czwartek, 7 kwietnia 2016, 11:11
> 
> Jeśli na wybranej geościeżce mapę przełącza się na widok pełnookienkowy to mapa centruje się na kordach domowych a nie kordach GŚ.

**Comment by kojoty** [comment]
@łza - Jakbyś mógł w wolnej chwili to dokończyć... wiec pozwolę sobie przydzielić do Ciebie...

Rozwiązanie to ustawienie 
($_REQUEST['lat']) ($_REQUEST['lon']) w url jakim wołana jest mapa na poprawne wartości...

pozdrowienia!

**Comment by Dezerterzy** [comment]
http://forum.opencaching.pl/viewtopic.php?f=9&t=4801&p=133115#p133115
Było 26.03. Zniknęło w natłoku ;)
Pamiętajcie o "powrotach" - wraca na mapę, nie do traila.
