### ISSUE TITLE
Poczta wysyłana z nowego serwera

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#500]
Pocztę testuję tak:

```
echo test | mail rygielski@mimuw.edu.pl
echo test2 | mail rygielski@gmail.com
```

Dochodzi tylko drugi z tych emaili. Konto `mimuw.edu.pl` powinno forwardować emaile na gmaila, ale widocznie blokuje się na filtrach spamowych (i nie dochodzi do forwardu). Sam gmail również ostrzega, że coś jest nie tak:

![image](https://cloud.githubusercontent.com/assets/2168535/14424088/773806a6-ffdf-11e5-8f92-36453a45aab4.png)

**Comment by wrygiel** [comment]
Wiem, że jeszcze nie miałeś czasu się tym zająć, ale wrzucam tutaj i tak, żeby się nie zapomniało :)

**Comment by wrygiel** [comment]
Być może prosta zmiana `hostname` wystarczyłaby, ale zamiast grzebać wolałbym żebyśmy trzymali się jednego podziału obowiązków, czyli m.in. rzeczy związane z pocztą bym przypinał do Ciebie, nawet jeśli podejrzewam, że wiem jak poprawić. W porządku?

**Comment by deg-pl** [comment]
Zaglądam na szybko, bo jestem zawalony trochę pracą.
Po pierwsze potrzebujemy nazwy zarejestrowanej w DNSie. Może być cert.opencaching.pl (to jest w DNSie), może być (chyba lepiej) new.opencaching.pl (to trzeba zarejestrować).
Następnie trzeba zmienić hostname. Bo teraz serwer wysyła z domeny opencaching2.provps.pl, co zdecydowanie nie jest prawidłowe (nie ma nas w SPFie tej domeny, bo... taki adres nie istnieje).

Maile generalnie są wysyłane w świat i do mimuw.edu.pl też docierają od samego początku, ale z pewnością ten serwer je odrzuca po prostym sprawdzeniu w DNSie.

Czyli:
- trzeba ustawić hostname na istniejący, zarejestrowany w DNSie adres
- przy okazji wyłączyć obsługę IPv6 w posfixie, bo się trochę o to rzuca w logach ;)

**Comment by mzylowski** [comment]
If there still is any work to do, please reopen ;]
