### ISSUE TITLE
Uninstall PHP tidy from new server?

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#502]
@andrixnet wrote:

> * Is Tidy (and php-tidy) still a requirement ? See https://github.com/opencaching/opencaching-pl/issues/116

**Comment by wrygiel** [comment]
It seems to be required. Grepped the code and there are some occurrences, e.g. `tidy_parse_string`.

**Comment by andrixnet** [comment]
Are they still in actual use? 
I don't know for sure about OC NL, but on OC RO I don't have the library and haven't seen errors relating to it.

**Comment by andrixnet** [comment]
`tidy_parse_string` is present in logbook/cachevalidator.php
`tidy_html_description` is commented in search.gpxgc.inc.php and search.gpx.inc.php

Also, tidy library is listed as **optional** dependency to HTML Purifier library included in the code.

**Comment by wrygiel** [comment]
Ok, I will remove it then. If it turns out to be required, someone will add it again.

**Comment by wrygiel** [comment]
Done.
