### ISSUE TITLE
php-apc vs php-apcu?

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#503]
I have installed php-apc on the new server, but perhaps we need php-apcu? Or, none of them?

@andrixnet wrote:

> I may not know the Debian or Ubuntu package naming conventions, but since PHP-5.5 the APC library is called php-apcu

**Comment by wloczynutka** [comment]
We still need one of them, It is still included in several scripts. If I undesrand well, apc is depreciated and abandoned for many years and not suported in php >= 7. Apcu is still suported and suitable for php 7.
apcu is not backward compatibile witch apc. (uses functions apcu_* while apc uses functions apc_*, but when i replaced apc_* with apcu_* it works on my local machine).

If you installed apc it is quite enough, but it will be neccesary to upgrade to apcu while upgrading to php7. (or maybe we will be able to remv it from our code)

**Comment by wrygiel** [comment]
Read a little about the subject.

* Original APC provided both **opcode caching** and **data caching**.
* Starting with PHP 5.5, **opcode caching** is provided by a bundled OpCache component.
* APCu is APC stripped of opcode caching. So it provides **data caching** only.

Since OpCache seems to be PHP developer's "accelerator of choice", it seems more reasonable to switch to APCu. I will uninstall `php-apc` and install `php-apcu` instead.

**Comment by wrygiel** [comment]
PS. pisząc "read a little" mam na myśli czas przeszły w określeniu do siebie :) Wyjaśniam, bo jeśli się to przeczyta inaczej, to może brzmieć jak obelga ;) Może zmienię na inną formę...

**Comment by andrixnet** [comment]
More on this topic can be found here https://github.com/opencaching/opencaching-pl/issues/234 which was triggered when I performed a security update that upgraded php-5.4 directly. to 5.6.

**Comment by wrygiel** [comment]
BTW, when I run `apt-get install php5-apcu` I got this:

    php5-apcu is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

Weird.
