### ISSUE TITLE
Install proj.4?

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#504]
@andrixnet wrote (regarding the new server env):

> Is proj.4 library no longer required? 

Actually, I don't know what proj.4 even is ;) Perhaps other developers will know if it is required?

**Comment by andrixnet** [comment]
https://en.wikipedia.org/wiki/PROJ.4
PROJ.4 (or proj) is a library for performing conversions between cartographic projections.

AFAIK it was a requirement of the code at some point in the past.
The only reference to it in OC code I found in docs/license.txt
On OC RO I don't have this library installed and I haven't encountered anything that might relate to it (?)

**Comment by wrygiel** [comment]
On out old server `libproj-dev` is not installed, but `gdal-bin` is. Not sure if this is required though. Let's try *not* installing it - if it is required, we will know eventually.
