### ISSUE TITLE
Apache configuration change

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#505]
Current Apache configuration on the new server:

```apache
<VirtualHost *:80>
    DocumentRoot /srv/ocpl
    ServerName new.opencaching.pl
    Options -Indexes

    Alias /images/uploads/ /srv/ocpl-dynamic-files/images/uploads/
    Alias /uploads/ /srv/ocpl-dynamic-files/images/uploads/
    Alias /upload/ /srv/ocpl-dynamic-files/images/uploads/
    Alias /wigo/ /srv/ocpl-dynamic-files/wigo/
    Alias /download/ /srv/ocpl-dynamic-files/download/
    Alias /images/statpics/ /srv/ocpl-dynamic-files/images/statpics/
    Alias /images/mini-mapa/ /srv/ocpl-dynamic-files/images/mini-mapa/
    Alias /mp3/ /srv/ocpl-dynamic-files/mp3/
    Alias /tmp/ /srv/ocpl-dynamic-files/tmp/

    ErrorLog ${APACHE_LOG_DIR}/error.log
    LogLevel warn
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

<Directory /srv/ocpl>
    Require all granted
    AllowOverride all
</Directory>
```

@andrixnet suggested the following Apache configuration:

```apache
<VirtualHost *:80>
    ServerName opencaching.pl
	# shown on server generated pages, such as 404 errors, etc
	ServerAdmin rt@opencaching.pl
    
    ErrorLog ${APACHE_LOG_DIR}/error.log
    LogLevel warn
    CustomLog ${APACHE_LOG_DIR}/access.log combined

	DocumentRoot /srv/ocpl
	# Should not need other types of file with -Indexes below
	DirectoryIndex index.php
    Options -Indexes

    Alias /images/uploads/ /srv/ocpl-dynamic-files/images/uploads/
    Alias /uploads/ /srv/ocpl-dynamic-files/images/uploads/
    Alias /upload/ /srv/ocpl-dynamic-files/images/uploads/
    Alias /wigo/ /srv/ocpl-dynamic-files/wigo/
    Alias /download/ /srv/ocpl-dynamic-files/download/
    Alias /images/statpics/ /srv/ocpl-dynamic-files/images/statpics/
    Alias /images/mini-mapa/ /srv/ocpl-dynamic-files/images/mini-mapa/
    Alias /mp3/ /srv/ocpl-dynamic-files/mp3/
    Alias /tmp/ /srv/ocpl-dynamic-files/tmp/

        php_value short_open_tag 1
# Total request size
        php_admin_value post_max_size 10M
# Largest file upload
        php_admin_value upload_max_filesize 5M


</VirtualHost>

<VirtualHost>
	ServerName www.opencaching.pl
	### also use the directive below to aggregate more aliases
	#ServerAlias X.opencaching.pl
	Redirect permanent / http://opencaching.pl/
</VirtualHost>

<Directory /srv/ocpl>
    Require all granted
    AllowOverride all
</Directory>
```

**Comment by wrygiel** [comment]
Ok, I will try to respond for each of your suggestions:

* `ServerName` needs to stay with the `new.` prefix for now. @deg-pl is testing SSL/TLS configuration, so we need a separate public domain.
* `ServerAdmin` was already set in the root level (see line 343 of the Action Log).
* Could you explain a little more why you suggest to add `DirectoryIndex index.php`?
* `php_value short_open_tag 1` - as far as I know, we don't want this anymore. If I remember correctly, @wloczynutka has got rid short tags from OCPL code some time ago?
* `php_admin_value post_max_size 10M` and `php_admin_value upload_max_filesize 5M` - seems reasonable! @opencaching/okapi-lead-programmers what do you think? Current defaults are 8M and 2M respectively.
* BTW, is it better to put these php values here, or in `php.ini`? I'm not sure which of these two options is more "fashionable".
* `www.` prefix redirection - you're right! This should be added too.

Thanks!

**Comment by wrygiel** [comment]
Oops, I wanted to reference @opencaching/opencaching-pl-lead-programmers, not OKAPI programmers, sorry ;)

**Comment by andrixnet** [comment]
- I understand about ServerName staying at new.XXXXXXX. I wrote it to clearly show the redirection.
- ServerAdmin was added globally (I missed that). This was intended to set it for this particular VirtualHost.
- I don't know what are the global defaults on your apache, but DirectoryIndex here explicitely tells Apache to look for index.php file when a directory is requested (like / for example). 
Also, since there are no static files in the site and indexes are not allowed, no other fallback filenames are needed in this directive. 
- if short tags were removed entirely, then `php_value short_open_tag 1` is indeed no longer necessary
- `php_admin_value post_max_size 10M` should accomodate the largest possible POST request, including headers, all parameters and uploaded file(s), according to application configuration (file size limits in settings.inc.php)
- `php_admin_value upload_max_filesize 5M` upload limit for a single file should match the highest file size limit in the application, in settings.inc.php
- the above values are from OC RO at this time. Modify accordingly. 
- setting these values here vs php.ini allows the administrator to have different server defaults, that may apply to other hosted sites, but explicitely apply these values for this VirtualHost. 
It is not a question of fashion. For example you may have 5 and 1 values globally, that would apply to a blog, a wiki, but have 10 and 5 specifically to apply to OC PL. 
- about www redirection in an independent way, this must also be applied in the code https://github.com/opencaching/opencaching-pl/pull/508

**Comment by andrixnet** [comment]
On OC RO I have also set the following: 

```    <Directory /www/oc_ro/oc_dynamic>
        Options -Indexes
        Require all granted
    </Directory>
```

Not sure if the VirtualHost specified -Indexes applies to aliased directories, so this explicitely applies it to oc_dynamic

**Comment by andrixnet** [comment]
```
    <Directory /www/oc_ro/oc_www/okapi>
        Options -Indexes
        AllowOverride All
        php_value short_open_tag 1
        php_admin_value safe_mode "off"
    </Directory>
```

These were part of the configuratio instructions for OKAPI part. 
@opencaching/okapi-lead-programmers please comment on the 2 php configuration variables.

**Comment by deg-pl** [comment]
I think we don't need two <VirtualHost>.
See "Canonical Hostnames" at https://httpd.apache.org/docs/2.4/rewrite/remapping.html

**Comment by andrixnet** [comment]
Also, in main site VirtualHost I added the following: 
```
    RedirectMatch permanent /wiki(.*)$ http://wiki.opencaching.ro/
    RedirectMatch permanent /mobile(.*)$ http://m.opencaching.ro/
```
trying to catch improper links and also to allow less specific links. The first about the wiki you should consider separately, your wiki is extensive, mine is offline for the moment after being penetrated a few months ago. 
The mobile redirect should prevent any improper access to the mobile section from within the main site.

**Comment by andrixnet** [comment]
@deg-pl : On the contrary, using 2 VirtualHosts is the best solution according to https://httpd.apache.org/docs/2.4/rewrite/remapping.html#canonicalhost

> Canonical Hostnames
> 
> Description:
>The goal of this rule is to force the use of a particular hostname, in preference to other hostnames which may be used to reach the same site. For example, if you wish to force the use of www.example.com instead of example.com, you might use a variant of the following recipe.
> Solution:
> 
>The very best way to solve this doesn't involve mod_rewrite at all, but rather uses the Redirect directive placed in a virtual host for the non-canonical hostname(s).
> 
>     <VirtualHost *:80>
>       ServerName undesired.example.com
>       ServerAlias example.com notthis.example.com
> 
>       Redirect "/" "http://www.example.com/"
>     </VirtualHost>
> 
>     <VirtualHost *:80>
>       ServerName www.example.com
>     </VirtualHost>

**Comment by deg-pl** [comment]
Yes. You're right - I'm not sure that we can do something like this (without loop of redirects):

```
<If "%{HTTP_HOST} != 'opencaching.pl'">
	Redirect "/" "http://opencaching.pl/"
</If>
```

**Comment by andrixnet** [comment]
And it would have to be more complex to allow mobile site to exist...

**Comment by wrygiel** [comment]
Added www redirect.

I'm now wondering about `<Directory /www/oc_ro/oc_dynamic>`. I didn't put anything like it in our config, yet `/srv/ocpl-dynamic-files` is already filled with files created by `www-data`. How's that possible...?

**Comment by deg-pl** [comment]
In a few moments we will have
`Redirect "/" "http**s**://opencaching.pl/"`
:)

**Comment by wrygiel** [comment]
> @opencaching/okapi-lead-programmers please comment on the 2 php configuration variables.

OKAPI used to use short tags, but it doesn't anymore. As to the "safe_mode", it was removed in PHP 5.4. So, I won't be adding any of these at this time, we'll try if it runs as it is.

**Comment by wrygiel** [comment]
> I'm now wondering about `<Directory /www/oc_ro/oc_dynamic>`. I didn't put anything like it in our config, yet `/srv/ocpl-dynamic-files` is already filled with files created by `www-data`. How's that possible...?

Ok. The `<Directory>` directive seems to have nothing to do with permissions. Permissions are controlled by `chmod`, and I have allowed `www-data` to write there.

So, I don't see a reason to add this:

```
    <Directory /www/oc_ro/oc_dynamic>
        Options -Indexes
        Require all granted
    </Directory>
```

**Comment by wrygiel** [comment]
Done.

**Comment by andrixnet** [comment]
If the VirtualHost directive `Options -Indexes` protects aliased directories, then it is not necessary.

**Comment by wrygiel** [comment]
AFAIK, `Options -Indexes` is for VirtualHosts, not directories. So it covers aliases too.

**Comment by wrygiel** [comment]
`index.php` seems to be properly accessed even without adding `DirectoryIndex index.php`, so I'll skip that too.

**Comment by wrygiel** [comment]
Ok, I think we've covered everything mentioned in this issue...

**Comment by andrixnet** [comment]
It is noteworthy if webserver default configuration looks for different index files.

**Comment by deg-pl** [comment]
@wrygiel - you should add `DirectoryIndex index.php`, because of wrong order at file /etc/apache2/mods-available/dir.conf
```
<IfModule mod_dir.c>
        DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm
</IfModule>

```

**Comment by deg-pl** [comment]
On new OCPL should be:
`ServerName cert.opencaching.pl`
or @kojoty should add new.opencaching.pl into DNS again ;)

**Comment by deg-pl** [comment]
"Dobra zmiana" wersja OCPL :)
![dobra zmiana](https://cloud.githubusercontent.com/assets/13884863/14478310/f72bbc28-0114-11e6-8e16-7be565c1377e.png)

**Comment by andrixnet** [comment]
@deg-pl Please share your complete SSL configuration.

**Comment by deg-pl** [comment]
letsencrypt is full automatic solution. Adds to site conf file include of /etc/options-ssl-apache.conf
```
# Baseline setting to Include for SSL sites

SSLEngine on

# Intermediate configuration, tweak to your needs
SSLProtocol             all -SSLv2 -SSLv3
SSLCipherSuite          ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
SSLHonorCipherOrder     on
SSLCompression          off

SSLOptions +StrictRequire

# Add vhost name to log entries:
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" vhost_combined
LogFormat "%v %h %l %u %t \"%r\" %>s %b" vhost_common
```

**Comment by deg-pl** [comment]
Rewrite www.OC -> OC within ONE vhost:
```
    ServerName opencaching.pl
    ServerAlias www.opencaching.pl
    RewriteEngine on
    RewriteCond %{HTTP_HOST} ^www\. [NC]
    RewriteCond %{REQUEST_URI} !^/okapi/
    RewriteRule (.*) http://opencaching.pl$1 [R=302,L]
```
When we'll full migrate to https last rule will be:
`    RewriteRule (.*) https://opencaching.pl$1 [R=301,L]`

**Comment by wrygiel** [comment]
> When we'll full migrate to https last rule will be:
> `    RewriteRule (.*) https://opencaching.pl$1 [R=301,L]`

OKAPI must also be excluded from this rule (with `RewriteCond %{REQUEST_URI} !^/okapi/`). All clients must still be allowed to connect via HTTP.

**Comment by deg-pl** [comment]
Of course! I wrote:
When we'll full migrate to https **last rule** will be
It means, that rules will be:
```
    RewriteCond %{HTTP_HOST} ^www\. [NC]
    **RewriteCond %{REQUEST_URI} !^/okapi/**
    RewriteRule (.*) https://opencaching.pl$1 [R=302,L]

```

**Comment by wrygiel** [comment]
In that case, your final set will redirect to HTTPS from http://www.opencaching.pl/, but it won't redirect to HTTPS from http://opencaching.pl :)

**Comment by deg-pl** [comment]
Yes.
In the future we will have other redirects in http config and other in https config.
In http config we'll redirect all traffic to https://opencaching.pl (except OKAPI), and in https config redirect will be as above.
