### ISSUE TITLE
Incorrect system to modify coords of mobile caches

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#511]
Z maila od RoDaJJ:
System przenosząc skrzynkę nie kontroluje w pełni logiki daty  jaką użytkownik podaje przy wpisie
tylko grzecznie zmienia współrzędne (nie dbając o chronologię).
Innymi słowy skrzynka widnieje na mapie w miejscu, gdzie dokonano ostatniego (fizycznego) wpisu,
a nie w miejscu najnowszego (w sensie daty) wpisu o przeniesieniu.
Ponieważ wiele osób loguje skrzynki z opóźnieniem rodzi to konsekwencje sporego rozdźwięku między wskazaniami z mapy a tym co mówi wpis z najnowszą datą.
Przykład testowy:
"Leśnik wagabunda, globtroter, powsinoga - OP7939"
Teoretycznie powinna widnieć na mapie w Gliwicach (najnowszy wpis o przeniesieniu),
a widnieje w Bieszczadach,
na podstawie wpisu datowanego na 2014 (wprowadzonego testowo z opóźnieniem i skasowanego).

Analogiczne operacje na geokretach dokonują się poprawnie. Zachowana jest chronologia przenosin.

**Comment by wloczynutka** [comment]
Być może rzeczywiście mechanim tak działa, ale coś tu nie gra z użytkownikami: Jak ktoś może znaleźć skrzynkę w miejscu Y skoro jeszcze nie została tam zalogowana, więc oficjalnie jest w miejscu X?

**Comment by deg-pl** [comment]
Ktoś po prostu zalogował jakieś ultra stare przeniesienie i kordy wywaliło ;). Niezależnie czy logowanie starego przeniesienia ma sens, czy nie - coś trzeba z tym zrobić.

**Comment by wloczynutka** [comment]
To nie tak. Fizycznego przeniesienia prawdopodobnie nie było, a jeśli było to jakieś szemrane. (z rąk do rąk - nie da się znaleść skrzynki na współrzędnych X gdy fizycznie jest na współrzędnych Y), po prostu użyszkodnicy znowu kombinują. 

Trzeba wprowadzić to co proponował chyba Miklobit (albo siletnA, już nie pamiętam): wpis 'zabrana' i swoiste 'blokowanie' skrzynki do czasu wpisania logu 'przeniesiona'.

**Comment by deg-pl** [comment]
Ma to sens!

**Comment by wloczynutka** [comment]
Trzeba by dopytać który z panów był autorem koncepcji i o odświeżenie tejże. To była dobra koncepcja, a moja pamięć jest już zawodna w tym temacie.

**Comment by deg-pl** [comment]
@miklobit  - co Ty na to?

**Comment by miklobit** [comment]
Była dyskusja z RR na ten temat i propozycja to był nowy typ logu "zabrana" z  automatyczną zmianą statusu na niedostępną w chwili wpisania. Status na aktywną mógłby zmienić ponownie albo owner  (ręcznie przez edycję ) albo aktualny posiadacz wpisem typu "przeniesiona".  Żeby nie komplikować (bo nowy typ logu musiałby być obsłużony przez okapi i zewnętrzne aplikacje) to stanęło na tym że przeniesienie musiało być obowiązkowe a zmiana statusu na niedostępną byłaby automatyczna przy zalogowaniu "znaleziona".  W momencie kiedy kesz jest niedostępny tylko aktualny owner miałby prawo wpisać log przeniesienia (ponownie aktywując kesza) co  by załatwiło problem chronologii.  Więc przy tych założeniach  jakieś zaprzeszłe znalezienie nie mogłoby wpływać na status kesza a zaprzeszłe przeniesienie na jego aktualne współrzędne.

**Comment by miklobit** [comment]
Tak po przemyśleniu - należało by zablokować dla mobilnych możliwość logowania wstecz.oraz  logowania kesza w stanie "niedostępny" dla innych osób niż owner (założyciel lub aktualny)    Zakładając, że znalezienie =  zabranie kesza  = stan neidostęny, to od  momentu znalezienia/zabrania  , do momentu odłożenia/zalogowania przeniesienia  nikt nie ma prawa logować znalezienia (bo to jest fikcyjne znalezienie: kesza nie ma ani w terenie ani na mapie)..

**Comment by deg-pl** [comment]
A może najprostszym na chwilę obecną rozwiązaniem (bo mamy pełne ręce roboty) byłoby po prostu weryfikacja daty w przy logowaniu przeniesień i blokada jeśli data jest starsza od najnowszego przeniesienia? To kilka linijek kodu i szybkie rozwiązanie problemu z tego issue.
Co oczywiście nie załatwia problemu dziwnych znalezień. Choć z drugiej strony - czasami keszuje się w grupie, podejmuje wspólnie mobilniaka, przenosi i... jak to zalogować (to a'propos pomysłu Miklobita).

**Comment by kojoty** [comment]
ja tam nie wiem, ale pomysł "blokowanie" wydaje mi się błędną drogą - to będzie prowadziło do "zablokowania" kesza gdy jakiś user zapomni coś zalogować, a np. przekaże komuś kesz mobilny...

Mi się zdaje, że wystarczy brać jako kordy kesza wpis "przeniesienia" z najnowszą datą i tyle...
Zmiana będzie wtedy najmniejsza, nie będzie wymagać wprowadzania nowego stanu etc...

**Comment by miklobit** [comment]
Jedyne ( ale nie proste do implementacji  ) rozwiązanie dla grup to by było  stworzenie mechanizmu grup (  grupa userów ~ wirtualna lista userów z prawem wyłącznie do logowania w imieniu grupy )  i  logowanie na konto grupy.  
Ja bym zablokował logowanie wstecz i tyle  a jak ktoś ma problem to przecież log papierowy się liczy a w systemie można wpisać jako  komentarz. 
Najpierw chyba  trzeba ustalić zasady  bo nie da się dopasować programu do tej wolnej amerykanki ktora userzy robią....

**Comment by miklobit** [comment]
Jeżeli to ma być tylko korekta techniczna problemu to wystarczy ignorować koordynaty przeniesienia jeśli ma datę wcześniejsza niż ostatnie wpisane. Ale takie wpisy w oczywisty sposób wynikają z przekazywania z rak do rak i braku faktycznego stanu kesza w systemie (czyli niedostępny) w momencie kiedy został znaleziony/zabrany. Ludzi, którzy chcą szukać takich keszy ( a nie tylko zaliczać) najbardziej zniechęca, że aktualny stan i pozycja na mapie ma się nijak do faktycznego .

**Comment by deg-pl** [comment]
Myślę, że Rada Techniczna przy 144 otwartych issues, zmianach mysql_* i przenosinach serwera nie powinna teraz bawić się w Radę Policjantów tropiących kto przeniósł, a kto nie. Zapewnijmy poprawne działanie serwera po bezsensownym zalogowaniu przeniesienia, a ewentualną dalszą dyskusję przenieśmy na później. Teraz na prawdę mamy co robić.

**Comment by wloczynutka** [comment]
spróbuję kłikfiksnąć

**Comment by wloczynutka** [comment]
probelm załatany na krótko, ale droga do wprowadzenia rozwiązania opisanego przez @miklobit jest nadal otwarta.
