### ISSUE TITLE
No GC waypoints

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#512]
From FB:
czesc, dziś zauważyłem ze linki do skrzynek dwusystemowych zostały zlikwidowane (jeśli oczywiście podało się link do GC). Teraz jest w tym miejscu podane OP skrzynki.

**Comment by wloczynutka** [comment]
Nic nie zostało zlikwidowane. Wyświetlanie podlega pewnym ograniczeniom, ale od kilku lat nie było nic zmieniane w tym temacie.
![image](https://cloud.githubusercontent.com/assets/11460149/14474934/a95a5c3a-00ff-11e6-9766-5d5a2c94c10e.png)

**Comment by deg-pl** [comment]
No to muszę się przyznać, że przekleiłem zgłoszenie Art_noise'a nie sprawdzając nawet - gdzieś między wysłaniem testowego maila numer 87234 a 87235 z nowego serwera. Dzięki i przepraszam za zawracanie d* ;)

**Comment by wloczynutka** [comment]
być może przeglądał kesze niezalogowany, albo z czyjegoś konta.
