### ISSUE TITLE
Problem with c:geo and OAuth

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#513]
As of yesterday, c:geo has problems connecting to OCPL via OAuth.

I don't have time to debug this problem properly just right now, but here are some clues:

* According to @kojoty, c:geo might be using an invalid domain (with `www.` prefix) when connecting to OCPL. OKAPI documentation [requires](http://opencaching.pl/okapi/services/apisrv/installation.html) - the value of **okapi_base_url** to be used, which for OCPL equals `http://opencaching.pl/okapi/` (without the www prefix).

* It is probably also related to the change in #508. We should try to revert it and see if it fixes the problem.

* If reverting #508 fixes the problem, and the statement in the first paragraph is true, then why OKAPI allowed c:geo to access OAuth with the `www.` prefix in the first place? This could mean there's a bug in OKAPI.

**Comment by wrygiel** [comment]
#508 reverted. Please check if it fixes the problem.

**Comment by kojoty** [comment]
I confirm: Yes. It works now.

**Comment by andrixnet** [comment]
Could it be related with fact that previous configuration worked because in .htaccess redirection, the webserver config specified this?
```
ServerName opencaching.pl
ServerAlias www.opencaching.pl
```

And the redirection rewrite the URL with all components after HTTP_HOST, while full redirection redirects all calls to www.opencaching.pl to http://opencaching.pl/ 
And while modern desktop browsers will take you to the same URL on the new name, API http clients may not (and stop at the redirect to /) ?

**Comment by andrixnet** [comment]
On the other hand, does OAuth compare hostname with what is configured as  $absolute_server_URI, or other means?

**Comment by andrixnet** [comment]
This is indeed an unforseen side effect. :-(

**Comment by andrixnet** [comment]
Try to remove the rewrite rules in .htaccess and replace the hard redirect, with a RedirectMatch in VirtualHost such as this: 

```
<VirtualHost *:80>
    ServerName www.opencaching.pl
    RedirectMatch permanent ^/(.*)$ http://opencaching.pl/$1
</VirtualHost>
```

This may solve the problem at webserver config level, if API (in c:geo probably) stops at / after the redirect.

**Comment by deg-pl** [comment]
`RewriteEngine On
RewriteCond %{REQUEST_URI} !^/okapi/
RewriteRule (.*) http://opencaching.pl$1 [R=302,L]
`
But config for www.opencaching.pl should be normal config - similar to opencaching.pl.
**And don't use permanent (301) redirect for testing purposes!!!**

**Comment by andrixnet** [comment]
Ah, yes, HTTP code 302. Missed that one.

**Comment by wrygiel** [comment]
I'm back "alive" - I will have some (not much) time for OCPL for the next couple of days.

> On the other hand, does OAuth compare hostname with what is configured as $absolute_server_URI, or other means?

It should. That's why I'm so surprised accessing OKAPI with "www." works. I will try to find the cause of this in https://github.com/opencaching/okapi/issues/416.

**Comment by wrygiel** [comment]
OKAPI is fixed. It will now verify the URL before executing the request. Both www and no-www domains are supported for OCPL. As to the issue of fixing `.htaccess`, let's continue this in #105.
