### ISSUE TITLE
Strange effects around watchers counter

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#515]
Cache: http://opencaching.pl/viewcache.php?cacheid=49542

![image](https://cloud.githubusercontent.com/assets/2961448/14491181/9e4c53e8-0177-11e6-8ff1-607df52e1b87.png)

I click on "watch":
![image](https://cloud.githubusercontent.com/assets/2961448/14491193/b2387cf6-0177-11e6-8825-f705dc4f8174.png)

I click "unwatch":
![image](https://cloud.githubusercontent.com/assets/2961448/14491205/c5a5d0c2-0177-11e6-98ae-7ce4bf2d9a6c.png)

I checked another cache and... it works! With this cache something is wrong...

**..and BTW: if every viewcache refresh should increase the counter of visits?**

**Comment by deg-pl** [comment]
Maybe related with #336

**Comment by wloczynutka** [comment]
w bazie pole watcher dla tej skrzynki (i wszystkich nowszych) jest null.
Przypuszczam, że powinno być 0, ponieważ starsze skrzynki mają ustawione 0.
Jakiś skrypt ma problem z inkrementacją/dekrementacją nulla. w tabelce
cache_watchers rekordy dodają się i odejmują poprawnie. Był zbliżony issue
tydzień/dwa temu - podejrzewam, że tam tkwi bug. (newcache.php, zapis nowej
skrzynki do bazy)

2016-04-13 13:02 GMT+02:00 kojoty <notifications@github.com>:

> Cache: http://opencaching.pl/viewcache.php?cacheid=49542
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/2961448/14491181/9e4c53e8-0177-11e6-8ff1-607df52e1b87.png>
>
> I click on "watch":
> [image: image]
> <https://cloud.githubusercontent.com/assets/2961448/14491193/b2387cf6-0177-11e6-8825-f705dc4f8174.png>
>
> I click "unwatch":
> [image: image]
> <https://cloud.githubusercontent.com/assets/2961448/14491205/c5a5d0c2-0177-11e6-98ae-7ce4bf2d9a6c.png>
>
> I checked another cache and... it works! With this cache something is
> wrong...
>
> *..and BTW: if every viewcache refresh should increase the counter of
> visits?*
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencaching/opencaching-pl/issues/515>
>



-- 
__________________________________
*Andrzej 'Łza' Woźniak*

*(+48) 798 835 592*
skype praca: *andrzej.wozniak.traveltech*
skype dom: *wloczynutka*

**Comment by wloczynutka** [comment]
stawiam na to, że w newcache.php, linia 686, brakuje `watchers` = 0

**Comment by kojoty** [comment]
czy nie powinniśmy ustawić default w bazie?
`ALTER TABLE `caches` CHANGE `watcher` `watcher` INT(11) NULL DEFAULT '0';`
