### ISSUE TITLE
Logo na wybory

### ISSUE THREAD

**Issue by miklobit** [opencaching/opencaching-pl#521]
Prośba do mających dostęp do serwera o podmianę na czas wyborów w config.inc loga w nagłowku na wersję wyborczą /images/oc_logo_cog_anim.gif   ![Wybory COG](http://opencaching.pl/images/oc_logo_cog_anim.gif "Wybory COG")

**Comment by deg-pl** [comment]
Fajne ;)

**Comment by kojoty** [comment]
Logo wystawione. Po wyborach trzeba usunąć wpis:
```
// logo during COG 2016 voting
$config['headerLogo'] = 'oc_logo_pl_cog_voting.gif';
```
na końcu settings.inc.php

**Comment by tripper1971** [comment]
OK. Dzięki
