### ISSUE TITLE
GPX/other formats export

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#522]
There is a problem with export list of geocaches in GPX/other formats.
Both via viewcache.php and search.php. 
![search](https://cloud.githubusercontent.com/assets/13884863/14524853/c76bafd0-023a-11e6-8af2-7b26d896e1b1.png)

It is critical function of OC server

**Comment by deg-pl** [comment]
@kojoty #516 ?

**Comment by kojoty** [comment]
poprawione ?

problem leży w funkcji
PlConvert

która jest w wielu miejscach i niekiedy przez PL a niekedy przez Pl co
spowodowało nieścisłość...

popatrzę jeszcze na to...

p.

**Comment by kojoty** [comment]
OK, już powinno działać ze wszystkim formatami...

@wloczynutka, kurcze objawił się przy okazji problem konstrukcji typu:

```
$dbc->singleQuery(...);
while( $x = $dbc->fetchResults() ){
    $dbc->singleQuery(...);
}
```
i wtedy to zawołanie wewn. while'a niszczy stmt przechowywany wewnątrz obiektu...

Mam wrażenie, że dla "spokojności" powinniśmy w ogóle odejść od tej konstrukcji z ukrytym stmt w obiekcie bazy, bo tak to albo wiele obiektów / połączeń trzeba mieć albo takie bomby będą się objawiać...

**Comment by deg-pl** [comment]
Działa. Dzięki.

**Comment by deg-pl** [comment]
@kojoty można zamknąć tego issue, czy coś jeszcze będziesz grzebał?
