### ISSUE TITLE
GK not avaliable when log a cache

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#533]
When logging a cache as found and pressing the button "Log GeoKrety now" we see the message that there can not connected to geokrety.org.

When running the crontab command "wget -O - -q http://www.opencaching.nl/util.sec/geokrety/geokrety.new.php" it works fine. The website geokrety.org is also online.

Could it be a bug in the code that cannot connect to GK?
![selectie_161](https://cloud.githubusercontent.com/assets/1060518/14587174/52fd78b0-04ae-11e6-93e1-f401f07a29aa.png)

**Comment by wloczynutka** [comment]
@deg-pl removed part of geokrety api url in commit 7c96c56a51a9742f0f52087e6c6d2f26624bb863 (Is Accident or Intention?), @deg-pl please check. now urls are invalid. (file GeoKretyAPI.php).

**Comment by deg-pl** [comment]
Mea culpa. Fixed.
Could you check it now?

**Comment by harrieklomp** [comment]
Yes. It works again :-)

Thanks
