### ISSUE TITLE
Statistics: Number of finds 

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#536]
Z forum (Brasia):

> Statystyki: Liczba odkryć
> Jeśli zmienia się filtrowanie poza aktualny rok nie wyrzuca żadnych wyników. W roku 2016 mogę zmieniać przedział czasowy i działa.
> Przeglądarka FF 45.0.2

Realnie można się cofnąć do 10.2015. Września już nie wyświetla.

**Comment by deg-pl** [comment]
Poprawka - tylko września 2015 nie wyświetla. Pozostałe miesiące działają OK.

**Comment by deg-pl** [comment]
KTHM na Forum (jeszcze w grudniu'15):
> Zgłoszenie dotyczy: Statystyki Liczba odkryć.
> Błąd: generowanie statystyki dla września 2015 jest niemożliwe.
> Przyczyna: brak danych dla dwóch dat 15.09.2015 oraz 23.09.2015.

**Comment by deg-pl** [comment]
Brasia (forum):

> Tak strzelałem:
> 2014-04-04 - 2015-08-31 - nie działa
> 2014-04-04 - 2015-08-30 - działa
> 2015-04-04 - 2015-08-31 - działa
> 2008-03-01 - 2015-04-01 - nie działa
> 2008-03-01 - 2013-04-01 - nie działa
> 2008-03-01 - 2012-04-01 - działa
> czyli nie tylko wrzesień, patrząc na pierwsze powyższe 3 wyniki problem chyba nie tkwi w jakiejś konkretnej dacie.

**Comment by kojoty** [comment]
poprawka zaplikowana. Problem okazał sie dość banalny: np. 09.2015 rozwalał nam user: 5 KDH "Feniks" - bo miał w nazwie cudzysłowy, a kod statów sobie z tym nie radził... 

ech całe te staty to do poprawy...
