### ISSUE TITLE
Link on cachepage to same cachepage

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#537]
Perhaps a stupid question.

On a cachepage is see the waypoint number. This is very good :-) .
But why is this a link to the same cachepage? Is only text not better?

![selectie_163](https://cloud.githubusercontent.com/assets/1060518/14607155/b5eac63a-0580-11e6-9019-c80127b2530b.png)

**Comment by deg-pl** [comment]
I think we should remove both - the link and the text, because of the duplication of data. The waypoint is given above - next to the cache name

**Comment by andrixnet** [comment]
The original UI showed only the waypoint code.
I added the link as an option to have available the short form of the link to the cache page. 

Cache page in location bar uses internal cache_id (not useful to user). 
This link was made as http://www.opencaching.xx/OX1234 -> simple reference directly to cache code (useful info for the user). 

Alternately this type of link could be assigned to cache code in title ?

**Comment by harrieklomp** [comment]
This was mentioned a while ago. The links would be changed in OC code in a later stadium.
