### ISSUE TITLE
Notification mail from OC without logs

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#538]
I'm not sure but maybe related with @kojoty changes in utils directory (#518)

![image](https://cloud.githubusercontent.com/assets/13780868/14616430/af6e6706-05aa-11e6-8139-dc5176fe953e.png)

**Comment by wloczynutka** [comment]
a u mnie jeszcze inaczej to wyggląda:

![image](https://cloud.githubusercontent.com/assets/11460149/14616733/e7a8ea00-05ab-11e6-8cba-f6608941a961.png)

**Comment by wloczynutka** [comment]
rano miałem jeszcze normalne powiadomienia. jakiś ostatni commit musiał być zarobaczony.

**Comment by kojoty** [comment]
tak, dziś po południu wpuściłem commit ze zmianami w skryptach util.sec, pisałem, że nei ma jak tego przetestować na developerce skutecznie ...

już biorę się za poszukiwanie problemu...

p.

**Comment by mzylowski** [comment]
Próbowałem zarejestrować użytkownika user@ocdevel i wywołać na nim akcje ale bezskutecznie. Zgadzam się, że testowanie tego to spory problem.
Spoko :)

**Comment by kojoty** [comment]
ok, dogrzebałem się błędu - już powinno być OK
