### ISSUE TITLE
HTTP 500 when user is not loged in and want to see geopath description

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#554]
To reproduce:
Log Out from OC.pl
Try access to:
http://opencaching.pl/powerTrail.php?ptAction=showSerie&ptrail=178

I've got HTTP 500 error.

**Comment by kojoty** [comment]
może to to, bo mamy tego dużo w logu...
`[Thu Apr 21 20:53:23 2016] [error] [client 46.113.11.1] PHP Fatal error:  Call to a member function getIsAdmin() on a non-object in /var/www/ocpl/powerTrail.php on line 190`

`[Thu Apr 21 20:35:16 2016] [error] [client 68.180.230.25] PHP Fatal error:  Call to a member function getUserId() on a non-object in /var/www/ocpl/powerTrail.php on line 450`

**Comment by wloczynutka** [comment]
ano tak, wiem OCB, naprawię.
