### ISSUE TITLE
Problem with geopath description edit when html code was pasted in description textarea

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#559]
From RT mail, by Tomanek111
> Łeeeee matko. Kod w "Zamkach w Polsce", zamiast wkleić w okno kodu, wkleiłem w okno opisu. Rozsypało się wszystko i nie widzę przycisku do zmiany opisu.

I don't have time to reproduce it now, but we should look at this ;]

**Comment by kojoty** [comment]
sprawa jest b. prosta:
w okienko opisu można wkelić baaaardzo długie ciągi znaków, które przesuną przycisk "zmień opis" poza obszar widoczny w oknie przeglądarki, a nasza strona tak działa, że w tym momencie nie ma scrolla prawo-lewo...

ogranąć to jest łatwo - starczy wyłączyć opis w css z poziomu przeglądarki i przycisk się pojawia

rozwiązanie: trzeba by poprawić css strony z geościezkami, by nie pozwalać by teksty "wymykały się z okienka" - nie wiem jak to się tam w cssie nazywa, ale taka opcja jest i bedzie dobrze ...

**Comment by deg-pl** [comment]
Ja też mam taką geościeżkę, z którą nic nie mogę zrobić, bo po wklejeniu loga o dziwnej rozdzielczości - nie da się go usunąć ;) 
http://opencaching.pl/powerTrail.php?ptAction=showSerie&ptrail=361

**Comment by wloczynutka** [comment]
nie mam pojęcia jak wymusić rozmiar diva. width i max-width nie pomaga :-( trzeba by jakiegos front-endowca ktory zna sztuczki.

**Comment by wloczynutka** [comment]
Swoją drogą logotyp geościeżki jest ZAWSZE zmniejszany przy ładowaniu na serwer, W kodzie wygląda, że zawsze zmniejsza obrazek. (ajaximage.php) Jak Ci się udało taki plik przeforsować?

**Comment by kojoty** [comment]
mój prywatny fron-endowiec mówi, że jak masz ustawiony width to robisz _overflow:hidden_ i wtedy już nie wyskakuje za ramkę...

**Comment by wloczynutka** [comment]
Super, pomogło :+1:

**Comment by kojoty** [comment]
już od jakiegoś czasu namawiam mojego prywatnego front-endowca (aka makotka - bo ona robi UI zawodowo) żeby coś zrobiła dla nas ale ona woli COG...

**Comment by mzylowski** [comment]
https://img.buzzfeed.com/buzzfeed-static/static/2015-03/26/19/enhanced/webdr06/enhanced-25942-1427414324-7.jpg

**Comment by wloczynutka** [comment]
szkoda, bo front-end jest nie na moje nerwy, ale jak ktoś w tym siedzi cały czas, to wymiata ;) http://imgur.com/gallery/Q3cUg29

**Comment by deg-pl** [comment]
Buu... na moje logo nie pomogło :(

Logo załadowałem 11.2015. To był zwykły chyba PNG, tylko sporych rozmiarów. Miałem nadzieję, że na OC działa automatyczna konwersja wielkości więc załadowałem i... na tym historia ścieżki się zakończyła, bo wywaliło mi wielką czarną plamę. Więc mam wrażenie, że mechanizm konwersji ma jakieś słabe punkty.

**Comment by wloczynutka** [comment]
ciągnie ci css z kesza, wyczyść / przeładuj.


W dniu 2016-04-22 o 12:01, Grzegorz Deja - deg pisze:

**Comment by deg-pl** [comment]
Ja gupa baba jestem ;)
Nawet bez przeładowania - ponowne wejście na oc pomogło. Dzięki!
