### ISSUE TITLE
quote mark destroy 'my caches' and 'last logs'

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#561]
mail do RT:

> Chciałbym zgłosić błąd przy wyświetlaniu moich skrzynek ("Moje skrzynki"). Wygląda to tak:
> ![image](https://cloud.githubusercontent.com/assets/2961448/14737912/f3f1dd1e-087e-11e6-955c-294473e3ea9b.png)
> 
> 
> Może to być związane z tym, że w nazwie znalazcy skrzynki znajdują się cudzysłowy.
>

**Comment by mzylowski** [comment]
Some think similar we have on new oc server with 'last log'
![selection_030](https://cloud.githubusercontent.com/assets/13780868/15447517/5e47c1c4-1f45-11e6-9299-1edbe9672fd5.png)
