### ISSUE TITLE
New method for email addresses validation

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#566]
Related with #490

Hi all!

I want to talk about mail validation.
Now we have method is_valid_email_address in common.inc.php. I think we should remove this metod (it's obsolete, 3rdparty and we should keep common.inc.php as small as possible).

New interface for mail sending should be kojoty class from Utils\Email. There is isValidEmail method but it is not implemented yet.
My idea:
We can use PHP5 validate class - http://php.net/manual/en/filter.examples.validation.php
Actually this solution is used but is commented. @kojoty why?
Also i have an idea about blacklisted domains. For now we don't have this feature right?
I want to ask about best way to to perform blacklist domain in OC. Where keep this list? In DB? In configuration file? In normal file somewhere in project tree?
Somebody know about good blacklist file what we can use? 

Or maybe we have any idea/solution to deploy on OC server? Plugin for mail server or something else?

**Comment by kojoty** [comment]
Hi.  I think common.php should be removed in near future after redesign of code. 

Please note also that "my" email classes was a sidework of db refactoring and I implemented it with idea of further development. 

I agree email validation should be done with native php functions.

**Comment by andrixnet** [comment]
If any blacklists are to be implemented (email domain blacklists, source IPs / networks blacklists), I believe that whitelists should also be implemented.

Second, these blacklists should be implemented in the database, with a common dataset to start with and site UI for ADMIN users to manage these lists.
