### ISSUE TITLE
medale "wojewódzkie" - ilość poziomów i liczba skrzynek znalezionych / posadzonych

### ISSUE THREAD

**Issue by wloczynutka** [opencaching/opencaching-pl#567]
Dla medali wojewódzkich przewidziałem - podobnie jak "typo-skrzynkowych" - 10 poziomów:

```
            1 => array(
                'levelName' => _('paper'),
                'cacheCount' => array(
                    'found' => 1,
                    'placed' => 0,
                ),
            ),
            2 => array(
                'levelName' => _('wooden'),
                'cacheCount' => array(
                    'found' => 10,
                    'placed' => 0,
                ),
            ),
            3 => array(
                'levelName' => _('iron'),
                'cacheCount' => array(
                    'found' => 20,
                    'placed' => 0,
                ),
            ),
            4 => array(
                'levelName' => _('beril'),
                'cacheCount' => array(
                    'found' => 40,
                    'placed' => 1,
                ),
            ),
            5 => array(
                'levelName' => _('bronze'),
                'cacheCount' => array(
                    'found' => 80,
                    'placed' => 2,
                ),
            ),
            6 => array(
                'levelName' => _('silver'),
                'cacheCount' => array(
                    'found' => 160,
                    'placed' => 5,
                ),
            ),
            7 => array(
                'levelName' => _('gold'),
                'cacheCount' => array(
                    'found' => 320,
                    'placed' => 10,
                ),
            ),
            8 => array(
                'levelName' => _('platinum'),
                'cacheCount' => array(
                    'found' => 640,
                    'placed' => 25,
                ),
            ),
            9 => array(
                'levelName' => _('perl'),
                'cacheCount' => array(
                    'found' => 1000,
                    'placed' => 40,
                ),
            ),
            10 => array(
                'levelName' => _('crystal'),
                'cacheCount' => array(
                    'found' => 1300,
                    'placed' => 64,
                ),
            ),
```

Czy macie jakieś uwagi, alternatywne propozycje co do ilości poziomów i liczby skrzynek?

**Comment by tripper1971** [comment]
Ostatnio, w czasie pogaduch przy ognisku padła propozycja aby ograniczyć się 
z poziomami tylko do 5 góra 7 (a resztę zachować w rezerwie - zabawa się 
rozwija) i podwyższyć progi.
Przykładowo w woj Pomorskim na teraz aktywnych jest ponad 2 700 keszy, w 
śląskim ponad 2900, w zachodniopomorskim, blisko 2 700, w mazowieckim 3 400

Tak więc zgłaszam propozycję tylko 5 poziomów
1  =>  > 150
2 =>   > 300
3 =>  > 600
4 =>  > 1 200
5 =>  > 2 500

Co do posadzonych nie mam zdania.

Pozdrawiam
Jacek


-----Oryginalna wiadomość----- 
From: Łza z Włóczynutki
Sent: Sunday, April 24, 2016 6:11 PM
To: opencaching/opencaching-pl
Subject: [opencaching/opencaching-pl] medale "wojewódzkie" - ilość poziomów 
i liczba skrzynek znalezionych / posadzonych (#567)



Dla medali wojewódzkich przewidziałem - podobnie jak "typo-skrzynkowych" - 
10 poziomów:

1 => array( 'levelName' => _('paper'), 'cacheCount' => array( 'found' => 1, 
'placed' => 0, ), ), 2 => array( 'levelName' => _('wooden'), 'cacheCount' => 
array( 'found' => 10, 'placed' => 0, ), ), 3 => array( 'levelName' => 
_('iron'), 'cacheCount' => array( 'found' => 20, 'placed' => 0, ), ), 4 => 
array( 'levelName' => _('beril'), 'cacheCount' => array( 'found' => 40, 
'placed' => 1, ), ), 5 => array( 'levelName' => _('bronze'), 'cacheCount' => 
array( 'found' => 80, 'placed' => 2, ), ), 6 => array( 'levelName' => 
_('silver'), 'cacheCount' => array( 'found' => 160, 'placed' => 5, ), ), 7 
=> array( 'levelName' => _('gold'), 'cacheCount' => array( 'found' => 320, 
'placed' => 10, ), ), 8 => array( 'levelName' => _('platinum'), 'cacheCount' 
=> array( 'found' => 640, 'placed' => 25, ), ), 9 => array( 'levelName' => 
_('perl'), 'cacheCount' => array( 'found' => 1000, 'placed' => 40, ), ), 10 
=> array( 'levelName' => _('crystal'), 'cacheCount' => array( 'found' => 
1300, 'placed' => 64, ), ),

Czy macie jakieś uwagi, alternatywne propozycje co do ilości poziomów i 
liczby skrzynek?

**Comment by deg-pl** [comment]
Nie jestem zwolennikiem medali, więc pewnie mam skrzywione spojrzenie, ale ;)
Wrzucenie do jednego worka skrzynek znalezionych ze skrzynkami założonymi może spowodować patologię. Sam mam "trochę" skrzynek znalezionych i teraz żeby dostać medal - będę musiał na siłę tworzyć skrzynki w województwach, do których mam daleko. Powstanie morze skrzynek nieserwisowanych, byle jakich, założonych na siłę - tylko by mieć "order" w profilu.

To mniej więcej tak samo, jak odznaczenia "pisarskie" na GC. Powstają debilne logi zbiorcze opowiadające w każdej skrzynce to samo, jak autor rano umył zęby zanim pojechał na kesze.

Motywujmy ludzi do tego, co przysłuży się jakości geocachingu, a nie wręcz odwrotnie.

**Comment by miklobit** [comment]
Też jestem za rozdzieleniem medali za zakładanie i szukanie. To dwie osobne dyscypliny sportu i  nie powinny być łączone na siłę.

**Comment by mzylowski** [comment]
Z tego co wiem @tripper1971 zajmujesz się tematem medali. Jeśli to issue jest ciągle potrzebne - otwórz ponownie.
