### ISSUE TITLE
Add a uuid to the reports table

### ISSUE THREAD

**Issue by following5** [opencaching/opencaching-pl#569]
I would like to add the feature of reporting geocaches to OKAPI (https://github.com/opencaching/okapi/issues/411). It would be nice if users could also query the current status of their reports. The cleanest way to handle the reports would be a `uuid` column in the `reports` table.

Would this be ok for you?

If yes: How is the procedure for adding a database column to OCPL installations?

**Comment by kojoty** [comment]
@following5, are you still working on this issue? Do you need any support with it?

If you need to change anything in DB just call here maintainers of oc nodes servers:
- **deg-pl** (oc.pl/oc.uk), 
- **andrixnet** (oc.ro) 
- **harrieklomp** (oc.nl). 

Please also note that all 4 nodes has autoupdate to the current github code from branch master.

**Comment by following5** [comment]
Thanks for explanation. I am currently not workin on this issue, but still think that it would be an important OKAPI feature.

**Comment by kojoty** [comment]
Thanks for answer - so I close it for now - please reopen if necessary.
