### ISSUE TITLE
Improve password strength in registration and password change forms

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#588]
When I tested my new solution for activating account by link I noticed problem about password strength in OC web-service.
At this moment:
- my password have to be longer then **two** characters !
- I can't use any special characters in my password !!!

Now I can create account with those passwords:
- qaz
- 123
  etc.
  But I **can't** create account with password like:
- !qa
- 12^

So... We permit to use very very week passwords at oc service. For me it is very big issue in security.

What limitation should we use for passwords?
My proposition:
Password:
- must contain at least one digit
- must contains at least one lowercase characters
- must contains at least one uppercase characters
- must contain at least one special symbol
- be longer then 8 characters

Any suggestions ?

**Comment by kojoty** [comment]
my point of view: it's only a fun - if anyone get access to your account what so important can do with it?
in my opinion rule could be like this:
- must contain one digit OR spec. symbol
- be at least 6 char. long

**Comment by harrieklomp** [comment]
I do not think we can force people to use different type of characters like lowercase, uppercase and other things. For example, i do not use uppercase characters in my pass.
People do like to use special symbol/characters.
Perhaps add more (special) characters and use a minimum of characters?

**Comment by mzylowski** [comment]
I really like my opencaching account and I don't want to let somebody to access to it ;]

Maybe it is true - my idea was too much restricted..

**Comment by andrixnet** [comment]
I would suggest a minimum password length of 6 or 8 characters.
Recommend using a mix of lower and upper case letters, digits and symbols (%^@&*etc). 
Recommend not to use regional characters. 

Make a strength indicator (JS?) to enforce minimul length and show a colored strength indicator, as the user types the password. (red, too short, yellow acceptable length, green acceptable length plus a good mix of different characters)
