### ISSUE TITLE
Node cannot exclude cache size

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#600]
In the recent past when cache sizes where read via database a node could decide to exclude a cache size. This was done via settings.inc.php.

```
'forbiddenCacheSizes' => array(
    cache::SIZE_MICRO
),
```

Is it possible to make this work again?

**Comment by harrieklomp** [comment]
The first post is not correct!!!! 

When i remember correct i did add this myself as prework to exclude cachesizes. This was partly for OC.RO who liked to add a new cachesize "nano" and partly to prevent making caches like "nano" and "micro" caches on OC.NL. I do not have knowledge to implement this.
On the live site (oc.nl) i did edit /lib/cache.php to prevent selecting size micro. But somehow this was overwritten by github.

This means that i need to change my question.
Can a programmer make it work that we can exclude cachesizes?

**Comment by kojoty** [comment]
@harrieklomp,
I'm going to redesign configuration ( #290 ) and after that also move the configuration which was stored in db tables to config files. I'll try to resolve it then - then every node will be able to define its cache sizes.

**Comment by andrixnet** [comment]
> every node will be able to define its cache sizes.
Meaning a common, complete set of sizes defined project-wide and each node configures which items to have active (and in use) and which not (for new caches and edit caches)

**Comment by following5** [comment]
> Can a programmer make it work that we can exclude cachesizes?

On my develsite, the setting

`$config['forbiddenCacheSizes'] = [cache::SIZE_MICRO]`

works.

**Comment by harrieklomp** [comment]
This is solved now.
