### ISSUE TITLE
Visual problem around table in viewreport.php

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#604]
Reported by brasia by rt mail:

> Się rozjechało w zgłoszeniach, po prawej od "statusu" powinno być ostatnie zmiany czy coś takiego. Załączam screen. Na innych zgłoszeniach tez tak mam. Win7 + Firefox
> ![image](https://cloud.githubusercontent.com/assets/13780868/15058619/982df798-131d-11e6-8e63-6f46545e4ace.png)

I can't reproduce it on chrome or firefox on ubuntu 14.04. Even with 'Łza+Lenka..." in COG menu, my table is ok
![image](https://cloud.githubusercontent.com/assets/13780868/15058716/24867be8-131e-11e6-8d1d-86e62411e49e.png)

**Comment by wloczynutka** [comment]
IE znalazł godnego kontunuatora w postaci firefoxa: przy niektórych powiększeniach da się zreprodukować błąd - spróbuj powiększyć/pomniejszyć stronę kółkiem od myszki.

**Comment by deg-pl** [comment]
Our OC Team says, that viewreports table now is fine. Whetever I'll refactor most of OC-Team menu, among others viewreports. So I close this issue now.
