### ISSUE TITLE
DB on PL node is killed when somebody access to admin_cachenotfound.php (file refactoring required)

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#605]
Copy-paste from emails:

> Dotarły do mnie słuchy, że funkcja 'skrzynki nieznalezione' dostępna z menu COG nie działa/ładuje się mega wolno.
> 
> Hej ja próbowałam wejść tam w ciągu dnia parę razy. Nie udało się - muli mocno. 
> 
> oprócz uproszczenia zapytania do bazy i paginacji, warto wprowadzić podział na województwa. Mało kiedy COGowicza interesują nieznalezienia poza swoim województwem, a to już daje z kilkanaście razy mniej wyników zapytania.
> 
> być może warto przenieść to do jakiejś metody w lib\Controllers\LogEnteryController i wywołać z log.php, tylko gdy typ logu === 2. sprawdzić dla danej skrzynki to co zapytanie sprawdza w tej chwili i jeśli trzeba wpakować skrzynkę COG-owi do zgłoszonych.)
> albo dorobić jakiekolwiek keszowanie, np. na 24 godziny. (można użyć np. apc / apcu_ store / fetch lub w inny sposób)

Issue is confirmed and it is important function in COG menu, especially now - we have new COG's team in oc.pl

**Comment by kojoty** [comment]
I'll try to fix it ASAP but if anyone starts working on it before give me know please...

**Comment by kojoty** [comment]
Dorobiłem dziś na szybko w krytycznym zapytaniu:
- podział na województwa 
- chyba lekko skróciłem zapytanie względem tego co było na początku

niemniej chyba nadal jeszcze to nie pomogło albo coś się tam jeszcze innego dzieje bo tylko blokuje mysql-a... sprawa jest jeszcze w toku.

Do ostatecznego podejścia do województw potrzebny mi jest refaktoring klasy z GetRegions.php, ale to niebawem...

**Comment by kojoty** [comment]
BTW (chwilowo dodałem sobie "cog-admina" celem testowania zmian...

**Comment by kojoty** [comment]
OK, znalazłem problem: 
w naszej wersji bazy warunek w stylu:
`AND c.cache_id NOT IN ( SELECT r.cache_id FROM reports r WHERE r.status <> 2 )`
zabija bazę - ma masakrycznie zły performance...

Jak tylko usunie się taki warunek - zapytanie smiga aż miło - na nowym serwerze problem wydaje się nie występować :smile: 

Bardzo się ubawiłem!

Poprawki wkrótce!

**Comment by kojoty** [comment]
It seems not to be an issue anymore...
