### ISSUE TITLE
opencaching.eu contents

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#607]
Following this https://github.com/opencaching/okapi/pull/423#issuecomment-216766585 and this https://github.com/opencaching/okapi/pull/423#issuecomment-217141999 and this https://github.com/opencaching/okapi/pull/423#issuecomment-217300131 I suggest : 

www.opencaching.eu to host (among others, at least) the following:
- access portal to national opencaching sites (currently achived by home page)
- short intro about "opencaching"
- short presentation about the directly involved projects: OCDE, OCPL, OKAPI, including links to github
- documentation section for project developers and node admins and "registered number assignments" (_to bring a bit more order and consistency_):
- - node_id numbers. currently existing assignments; current nodes status; new node registration procedure.
- - cache_type (names and IDs). defined cache types (all available, even if not all are in use); new cache type registration procedure. (should also help consistency with OKAPI and third party apps)
- - cache_size (name and IDs).  defined cache sizes (all available, even if not all are in use); IMHO this could be a comprehensive list and not require new items. (should also help consistency with OKAPI and third party apps)
- - cache_attributes (name, IDs, category, description). defined attributes (all available, even if not all are in use, even if some are project specific); new attribute registration procedure. (should also help consistency with OKAPI and third party apps)
- - reference graphic resources for all the above, for project developers and for third party apps (even though each project/node has it's own theme)
- third party apps that can exchange information with opencaching sites (like c:geo, Flopp's Map, GeoKrety, etc)

There are ID overlaps (at least for cache types and attributes) between projects, and for OCPL based nodes, between nodes. IMO these should be resolved. See here https://github.com/opencaching/opencaching-pl/issues/462#issuecomment-215948171

**Comment by andrixnet** [comment]
@kojoty @deg-pl @wrygiel @following5 @harrieklomp

**Comment by andrixnet** [comment]
Also, all this info should be in english.

**Comment by kojoty** [comment]
I agree. I think we can prepare the separate wiki for this domain and then we all can create and update the content under this domain. OCPL is now during the migration to the new server - after that we can take a look at this...

**Comment by following5** [comment]
I think this is a good idea and would contribute to the wiki.

**Comment by andrixnet** [comment]
I would definitely like to contribute. 

Question: what platform : 
- a separate wiki instance. information edited as plain wiki articles. a bit more work to maintain tabular data. any request handled manually.
- a small dedicated website application, with article editing, a small database to contain and organize the items, IDs, etc, new item request form, contributor logins with github for github.com/opencaching/* project members?

**Comment by deg-pl** [comment]
Separate MediaWiki for opencachin.eu is ready, and today will be published

**Comment by deg-pl** [comment]
Ok. Wiki on Opencaching.eu is now published.
@following5 @andrixnet @andrixnet @mzylowski (and who else wants) - please create your accounts, because registration will be closed soon.

**Comment by following5** [comment]
Oh, please don't close ist! It's a Wiki, and it's _Open_ caching! Mediawiki delivers everything needed to control _open_ Wiki contents - change lists, watch lists, notifications, admin rights, page protection ...

If you are concerned of spam: There is a Mediawiki extension wich allows to secure the registration agains spambots. It's proved 100% effective at wiki.opencaching.de. We created an own list of questions, one of which must be answered on registration. The question always is like: "Who found the geocache OC-cache-code first?" No spambot can answer that. :-)

**Comment by andrixnet** [comment]
One observation, if I may: it is set to answer on both names (with and without www) rather then performing a redirect. This has the end-user side effect that one has to make separate logins, depending on host name. (ok, affects only editors, but still)

**Comment by andrixnet** [comment]
I've created a user. I presume editing rights will be granted later on.

**Comment by deg-pl** [comment]
@following5 - you're right. We had PL Wiki closed for years. Now it's time to open it! (and opencaching.eu should be open too)

@andrixnet - now you have full rights. Server has no redirection (only http -> https). MediaWiki redirects to opencaching.eu ($wgServer = "https://opencaching.eu";)

I enabled reCaptcha-nocaptcha - let's test it - maybe it is the best solutuion for international site?

I think we should now close this issue and... edit opencaching.eu Wiki instead ;)

**Comment by andrixnet** [comment]
Is it possible to add https://www.mediawiki.org/wiki/VisualEditor ?

**Comment by andrixnet** [comment]
A few clarifications, for content: 
under what license is the OPENCACHING logo? 
http://opencaching.pl/images/oc_logo.png ?

**Comment by andrixnet** [comment]
Please use as icon: https://opencaching.eu/images/6/6e/Opencaching_icon.png
https://www.mediawiki.org/wiki/Manual:$wgFavicon

**Comment by miklobit** [comment]
Licence  for user contributed content (cache listing, media) at opencaching.pl  is required to be CC-BY-SA ( https://wiki.opencaching.pl/index.php/Regulamin_u%C5%BCytkownika_OC_PL  ).   
I think this should be extended/unified across all opencaching.pl services (wiki,forum,blog)

**Comment by deg-pl** [comment]
> Please use as icon: https://opencaching.eu/images/6/6e/Opencaching_icon.png

Done

> Is it possible to add https://www.mediawiki.org/wiki/VisualEditor ?

Yes. But it is "a little" more work. Give me a few days because I have a lot of work.

**Comment by deg-pl** [comment]
Done ;)

**Comment by andrixnet** [comment]
Please configure the Wiki to allow also SVG uploads.

**Comment by following5** [comment]
There is a page http://wiki.opencaching.eu/ which shows some Polish error message. Could you redirect that to http://opencaching.eu/ (or move the wiki to wiki.opencaching.eu and redirect opencaching.eu to there)?

**Comment by mzylowski** [comment]
cc @deg-pl

**Comment by deg-pl** [comment]
@andrixnet Done (also installed ImageMagick)
@following5 done

**Comment by following5** [comment]
@deg-pl 
Thanks!

It looks like template programming is not working in the Wiki. Would be great if you can enable this somehow, and additionally install the "ParserFunctions" extension for advanced template programming. This allows to remove redundancy from articels by putting common building blocks into templates.

**Comment by deg-pl** [comment]
@following5 Done

**Comment by following5** [comment]
thx!
