### ISSUE TITLE
tinyMCE or editcache bug?

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#610]
![op6312](https://cloud.githubusercontent.com/assets/3382777/15114256/bb3d90f4-1601-11e6-97ba-f1ed54da8e16.png)

Take a look at this cache: http://opencaching.pl/viewcache.php?cacheid=25367 

See the "XX" in the description? 

I've seen the same side effect on OCRO when sometimes I edit a cache description.
A `<p>XX</p>` appears at the end of the description.
I am uncertain under what circumstances, as I was unable to consistently reproduce it. But now I see the effects of this bug on OCPL as well.

The "XX" (as I know it as bug) is not typed by the user, but appears.

**Comment by deg-pl** [comment]
I've upgraded TinyMCE (commit c6feedf862d062af7af2e6977238ec3816558246) and I hope that problem doesn't exist. In OC PL we have only 2 caches with <p>XX</p>, last edited 2-3 years ago.

If problem still persist - please reopen.
