### ISSUE TITLE
Remove events from 'cache found' count. Recalculate user stats.

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#611]
For me (and a lot of others opencaching users) including events into cache founds it's bad idea. 
Event isn't a cache.
We talk about it in #593, we receive e-mails like that:
`Cześć.
Czy te spotkania zawsze były doliczane? Spotkanie to nie skrzynka jej się nie szuka. Więc w statach spotkań niech pokazuje na ilu spotkaniach byłem  a w statach ogólnych tylko znalezione Kesze.
Pozdrawiam`

In this issue:
- we need changes in code
- run script for recalculate stats

**Comment by andrixnet** [comment]
Can events be counted separately and shown? 
or
Can "attended" count as a "found" on per node basis?
OCRO prefers it like this and I know OCNA would like to rejoin within the next year the current OPENCACHING-PL code, and this was one specific issue of theirs.

**Comment by harrieklomp** [comment]
For oc.nl it is logic that events are no caches, so should not be counted as found cache.
There are some parts in the code who does count them as found and some show them separate.

For example on http://www.opencaching.pl/viewprofile.php?userid=?? show only caches as found and events are shown separate.

**Comment by deg-pl** [comment]
We have a lot of users surprised counting events to "Number of found caches". Another mail today:

> mam pytanie odnośnie statystyk na OC.
> Wiem, że sporo działacie ostatnio ale wychwyciłem małą nieścisłość pomiędzy ilością znalezionych skrzynek z poziomu mojego profilu (4384 na chwile obecną) a ilością znalezionych skrzynek z poziomu ogólnych statystyk (4368 na chwile obecną). Różnica to 16. 
> Skąd to się bierze, ktoś już może coś takiego zgłaszał, itd? W wolnej chwili mógłbyś zerknąć czy pisać oficjalne pismo do RT? ;-)

**Comment by Opencachingna** [comment]
We use the old OCPL code at opencaching.us. This code did NOT count events as finds anywhere on the site. However, we had several requests over the years that they DO count as finds. So I went in to I'll bet about 15 files on the site, and changed the code so they do count. This must be a North American thing that people want them to count as finds. :-)

**Comment by harrieklomp** [comment]
@Opencachingna I think this is more a GC thing. Some things should not be the same as on GC, for example this count a event as found :-)

**Comment by Opencachingna** [comment]
@harrieklomp You're probably right, it's a GC thing for sure. I'm confused here anyways, does the new OCPL code count events as finds? Or only in some places on the site, and not all?

**Comment by harrieklomp** [comment]
@Opencachingna I will check this when i am home from work.

**Comment by harrieklomp** [comment]
I have checked several pages and find out the next data. Official i have found 256 caches (logs) and attended 5 events.
- Via search "Finder" on the right uppercorner i have found 261 caches (inclusive events). This search option is without any filter.
- On my profile page i did find 261 caches (inclusive events) when i click "show" i do not see the events in the list. Perhaps because they are archived? But i see normal caches who are archived. Strange????
- My banner shows 256 finds. This is without the events.
- Via statistics page http://www.opencaching.nl/articles.php?page=stat and fill in date from long way in the past i found 256 caches. This is without events.
- Via normal search page and finder at the bottom of that page the data is correct when de/select the event attribute.

**Comment by andrixnet** [comment]
After further study, I agree with @harrieklomp : events to be counted separately, not included in total # of finds. But the counts and statistics should be made consistent.

**Comment by Opencachingna** [comment]
@harrieklomp This is Mr.Yuck by the way. I should maybe create an account in my own name when I start doing some translation work for the OCPL code. I have an account on your site, I will check your profile and site so I can see some of these things for myself.

**Comment by mzylowski** [comment]
Also TODO:
- revert #672 
- unified translations around this issue
