### ISSUE TITLE
When log a GK always results in error

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#618]
When log a GK via a logpage i always see the message that there cannot be connected to the geokerty site. This is when i drop a GK in a cache and when i take a GK from a cache.
The GK site is online at this moment.

The next screenshot is in Dutch but the message is clear i hope.
![selectie_019](https://cloud.githubusercontent.com/assets/1060518/15276101/4092e3ea-1ade-11e6-92a5-d90d1571bebe.png)

**Comment by mzylowski** [comment]
@harrieklomp this is still an issue after #784 ? 
If no, please close this ;]

**Comment by harrieklomp** [comment]
I will check this next Sunday.
