### ISSUE TITLE
Cache new/edit - form submission via keyboard

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#621]
It is normal <FORM> behaviour to submit the form by pressing ENTER in a text field.
This can be modified (by Javascript) if and when it suits specific needs. 

The New cache and Edit cache page have however a strange behaviour: 
- if focus in cache_title and press ENTER --> "region from coordinates" action is performed.

Expected behaviour: 
- form is submitted as in cache new/edit is saved

Action "region from coordinates" has it's own button and is seldom needed as a special action, compared to normal workflow case : save changes.

**Comment by following5** [comment]
Duplicate of #119.
