### ISSUE TITLE
I just activate account created one month ago!

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#626]
We have in our string translations: 
`'useractivationmail6' => 'If you don\'t activate your account within the next 14 days, your account will be automatically deleted.',
`
Do we even have any code responding for remove out of dated account? I don't think so.

**Comment by kojoty** [comment]
@mzylowski 
why you think this is "high" - I think it could be a medium-level enchantment to implement cron-based mechanism which remove such inactivated accounts...

**Comment by andrixnet** [comment]
subscribe

**Comment by following5** [comment]
This has been duplicated by the broader issue #626. I am working on that.

Btw, the message meanwhile is that there are 48 hours for activation.

**Comment by following5** [comment]
oops... duplicated by #1290
