### ISSUE TITLE
Unused files?

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#627]
I am investigating unused files in the source tree.
- [x] images/cacheatr/ - apparently referenced only in /tpl/stdstyle/cache-atr.tpl.php (which seems to be unused)
- [x] images/cachemaps - apparently not referenced
- [x] util/google-earth/\* and images/ge - apparently not referenced
- [x] images/header/ and util.sec/make_logo.php - apparently not referenced
- [x] images/thumbs - apparently not referenced
- [x] images/amnesius\* 
- [x] images/*.swf
- [x] images/diff-*
- [x] images/terr-*
- [x] images/lightbox/\* seem to be a duplicate. It is referenced, but /tpl/stdstyle/images/lightbox is actually used
- [x] various files under /images (especially third party logos)
- [x] lib/tinymce (not 4) seems to be a remnant from a previous tinymce instance ?
- [x] various .js files are spread around lib/ rather then being under lib/js/
- [x] SVG and graphic resource files under logbook/ should be moved as templates under docs/ and the files actually used to be published by each node via wiki, based on these templates
- [x] util/ and Utils/ should be merged. (no reason to have many utilities directories)
- [x] there are at least 3 versions on jQuery under tpl/stdstyle/js/ ; These should be unified to a single deployment.
- [x] tpl/stdstyle/images/log/ and tpl/stdstyle/images/log2 ; These should be merged or cleaned up
- [x] tpl/stdstyle/images/profile 
- [x] tpl/stdstyle/images/progressbar
- [x] tpl/stdstyle/images/thumb - at least some are unused (images with german text)
- [x] tpl/stdstyle/images/toltipsImages - should be added to more pages that need such icons (and directory renamed)

These are the ones I was able to identify today. 
If any/some/all of these are not used anymore, I suggest removal, they only add clutter.

**Comment by kojoty** [comment]
I like removing files so I try to look at this in a meanwhile...

**Comment by mzylowski** [comment]
util/google-earth/* and images/ge - apparently not referenced
We have reference to it from our wiki.
It is plugin to google-earth. If it still works it shouldn't be removed.

**Comment by deg-pl** [comment]
@mzylowski I think we should move google-earth plugin to wiki OC PL and remove from github.

**Comment by andrixnet** [comment]
Even if google-earth plugin involves no specific PHP and or JS code, (ie only KML file), I disagree. 
Plugin probably would need editing to make it specific to a certain node.

I suggest moving it to another directory, like docs, as a template/sample plugin, with instructions how to configure it on each node and to publish the modified version via the node's own wiki.

**Comment by andrixnet** [comment]
Updated list with more files / directories. Some could be removed, some could be merged, some need partial cleanup, some need reuse / more usage.

**Comment by andrixnet** [comment]
Google Earth exporter now working much better and with improved graphics. 
See https://github.com/opencaching/opencaching-pl/pull/931

images/ge REMOVED.

**Comment by kojoty** [comment]
> images/cacheatr/ - apparently referenced only in /tpl/stdstyle/cache-atr.tpl.php (which seems to be unused) 

are still used by some caches at oc.pl nad can't be removed

**Comment by kojoty** [comment]
> various .js files are spread around lib/ rather then being under lib/js/

There are only js files used by cachemaps - I think it should stay as is.

**Comment by kojoty** [comment]
>  util/ and Utils/ should be merged. (no reason to have many utilities directories)

util/ contains two things: ping script + googleEarth plugin - I think it should stay as is.

**Comment by kojoty** [comment]
> there are at least 3 versions on jQuery under tpl/stdstyle/js/ ; These should be unified to a single deployment.

right, but we have separate sighting for it #927

**Comment by kojoty** [comment]
> tpl/stdstyle/images/thumb - at least some are unused (images with german text)

This is referenced by thumbs generator - I think it needs to stay till thumbs.php refactoring...

**Comment by kojoty** [comment]
> SVG and graphic resource files under logbook/ should be moved as templates under docs/ and the files actually used to be published by each node via wiki, based on these templates

there are not only templates but also logbook generator - it should be cleanup in different issue #655

**Comment by kojoty** [comment]
It seems I've checked/removed all listed files. If not please reopen.
