### ISSUE TITLE
Prevent cache adoption by users under verification. 

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#628]
message from ocpl COG:

> Cześć
> W imieniu COG (zmiana została przegłosowana) proszę o wprowadzenie mechanizmu zakazu adpocji skrzynek przez użytkowników, których skrzynki podlegają weryfikacji. 
> Od strony algorytmu widzę to jako dodanie warunku:
> po kliknięciu "zmień właściciela" jest sprawdzany warunek czy skrzynki użytkownika są weryfikowane, 
> jeśli tak to pojawia się komunikat na stronie "Ten użytkownik nie może adoptować skrzynek" 
> jeśli nie to działa tak jak w tej chwili.
> 
> Po wprowadzeniu zmiany proszę o powiadomienie mnie (nas) wtedy wystosuję odpowiedni komunikat na forum.
> 
> Obecnie jest to wykorzystywany (świadomie lub nie) sposób na obejście weryfikacji skrzynek. Ktoś zakłada trzy skrzynki, drugi je adoptuje i nawet nie mając znalezionej żadnej skrzynki może zakładać kolejne bez weryfikacji. 
> 
> Pozdrawiam i dziękuję 
> brasia / COG

**Comment by deg-pl** [comment]
Dodatkowo trzeba zrobić warunek, aby osoby z włączoną weryfikacją wszystkich skrzynek przez COG też nie mogły adoptować.

**Comment by andrixnet** [comment]
subscribe

**Comment by brasiaPL** [comment]
Deg, rozumiem, że sprawdzenie warunku, czy skrzynki są weryfikowane dotyczy przypadku ogólnego, weryfikacji, niezależnie od przyczyny tej weryfikacji.

**Comment by deg-pl** [comment]
Z punktu widzenia kodu OC to są dwa różne przypadki:
- weryfikacja pierwszych 3 skrzynek,
- nałożona stała weryfikacja przez COG
I obydwa warunki trzeba sprawdzić przy adopcji. Ale jest to oczywiście do zrobienia. Szukamy wolnych mocy przerobowych ;)

**Comment by mzylowski** [comment]
This should be done via user class.
We have to create method in User class, for example: cacheNeedBeVerified (renturned true/false) where we check all conditions.
This method should be called from adoption code. That's all :)

**Comment by harrieklomp** [comment]
Because my 2 month old laptop is defect i cannot do it via commit for the next 3 or 4 weeks. When this is committed i can add the translation online. 
Or if possible it also can be done via this commit.

'adopt_34' => 'Helaas kan deze gebruiker niet de nieuwe eigenaar worden van deze cache.',

**Comment by mzylowski** [comment]
Not an issue anymore? 
/cc @deg-pl @kojoty
