### ISSUE TITLE
search.php: query generates sql error

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#630]
source of the issue:

> 
> +++ PDO Error +++ 
> +++ Debug: Query: INSERT INTO `queries` (`user_id`, `options`, `uuid`, `last_queried`)
>                         VALUES (0, ?, UUID(), NOW())
> +++ Ex_Code: HY000
> +++ Ex_Msg: SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value
> +++ Ex_Trace:
> #0 /srv/ocpl/Utils/Database/XDb.php(117): PDOStatement->execute(Array)
> #1 /srv/ocpl/search.php(397): Utils\Database\XDb::xSql('INSERT INTO `qu...', 'a:37:{s:11:"f_u...')
> #2 {main}

It seems that this is buggy query or something changed meanwhile:
```
XDb::xSql(
                        'INSERT INTO `queries` (`user_id`, `options`, `uuid`, `last_queried`)
                        VALUES (0, ?, UUID(), NOW())',
                        serialize($options));
```

**Comment by kojoty** [comment]
It seems that this is an issue around [http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict] which is enabled since mysql 5.6 - what means at least that all every column needs to be defined in INSERT statement or has a DEFAULT value in table structure...

**Comment by andrixnet** [comment]
SQL MODE can also be set by admin according to this http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_sql_mode (thus not necesarily requiring changes in the code)

**Comment by kojoty** [comment]
> SQL MODE can also be set by admin according to this http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_sql_mode (thus not necesarily requiring changes in the code)

sure, I know but I think it a good idea to be "strict" in this matter and set defaults in sql queries or tables schema

**Comment by andrixnet** [comment]
See this as well: https://github.com/opencaching/okapi/issues/425
