### ISSUE TITLE
Admin should not be able to edit logs

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#643]
Currently an ADMIN user can both edit and delete any logs. 
- OK admin to delete log (ie. moderation)
- NOT OK admin to edit contents of another user's log. 

Editing a log by an admin is equivalent to censorship. In some countries, including RO, this is prohibited by law. 
If a log entry is problematic in ways that require admin intervention, that log should be deleted (ie. marked as deleted and hidden from view for normal users).

**Comment by deg-pl** [comment]
I think it makes sense! +1

**Comment by mzylowski** [comment]
We have regression here - now admin can't edit OC-Team comment.
When COG reviews cache all messages are posted as OC-Team Comment. After changes from this issue admins can't edit his logs with this type.
@deg-pl Can you fix it?

**Comment by mzylowski** [comment]
This was false alarm, sorry.
