### ISSUE TITLE
The number of caches needed to give a recommendation is not rounded (new PL server)

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#645]
From forum (Dezerterzy):

> (...) przy dodawaniu wpisu znaleziona, pokazuje mi "okrągłą" liczbę 8.9999999999998 wymaganych znalezień do nagrodzenia kolejnej skrzynki

I can't reproduce this error because I have to many "free" recommendations (about 100 ;) ).

**Comment by kojoty** [comment]
I hope I've fixed this...
