### ISSUE TITLE
Banned user still can add log into cache...

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#646]
![screen shot 05-23-16 at 09 18 pm](https://cloud.githubusercontent.com/assets/13780868/15481696/15565b4a-212c-11e6-81e7-e826300b5965.PNG)
![screen shot 05-23-16 at 09 19 pm](https://cloud.githubusercontent.com/assets/13780868/15481697/155d0f62-212c-11e6-9dc7-fe11c3767945.PNG)

**Comment by mzylowski** [comment]
Actually I'v checked a lot of ways to log a cache. I have no idea how to do it on opencaching.pl when user is banned...
But!
I authorized through OKAPI in c:geo and quick note (android app by wrygiel) and I send log through it.
Effect:
![screen shot 05-23-16 at 09 48 pm](https://cloud.githubusercontent.com/assets/13780868/15482479/3cbade00-2130-11e6-9c2b-4c121050df5a.PNG)
![screen shot 05-23-16 at 09 49 pm](https://cloud.githubusercontent.com/assets/13780868/15482480/3cd7167e-2130-11e6-9639-0bd35d11163a.PNG)
@opencaching/okapi-lead-programmers probably you are interested of this ;]

**Comment by following5** [comment]
I will try to fix it in OKAPI, should be the same problem also for Opencaching.de.

Can you please verify if those logs were created by OKAPI? There is a table `okapi_submitted_objects` which records all submitted logs and pictures. Look for `object_type` = 5 and `object_id` = ID of the log.

**Comment by mzylowski** [comment]
Confirmed.
There is a row for my log (Techniczny_Czarodziej) and 'the cheater' logs in `okapi_submitted_objects`.

**Comment by following5** [comment]
The users' OKAPI autzorizations are not revoked by the ban, therefore they have still OKAPI access.

The cleanest solution would be to add code [here](https://github.com/opencaching/opencaching-pl/blob/master/admin_users.php#L91) which calls some new OKAPI facade function to revoke the user's access. But for now, I will solve it via an OKAPI workaround.

**Comment by following5** [comment]
This is turned out to be an OC code issue, not OKAPI. When a user is banned, he must be logged out by the OC software. I guess that this means to delete the user's entry from the `sys_sessions` table.

@mzylowski 
Please reopen the issue.

**Comment by following5** [comment]
Well, one can argue if it's an OC oder OKAPI issue. I will try to diccuss again in OKAPI project.

**Comment by mzylowski** [comment]
Hi!
I'm quite sure user is logout automatically if is banned. (It happens somewhere else in the code).
I will check it in the evening.
