### ISSUE TITLE
Pagination in viewreports.php

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#647]
http://opencaching.pl/viewreports.php?archiwum=1
At this link for COG members is list of old, closed reports. At this moment it's really difficult to access to it - long loading, browser crashes etc.

I know, we have issue #409, but here we have important priority. Also it is COG request.

**Comment by deg-pl** [comment]
@kojoty Masz tu coś z tego zrobione? Zrobiłbym COGowi porządek m.in. z viewreports, ale nie chcę dublować Twojej pracy.

**Comment by kojoty** [comment]
@deg-pl - działaj śmiało.

**Comment by deg-pl** [comment]
New reports system has very good (kojoty's code) pagination. Old report system will be dropped in next few days.
