### ISSUE TITLE
Latest VM

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#661]
Because of a new computer at home i needed the latest build VM.
Where is this located? The links in the wiki do not work somehow.

**Comment by OCUK-Tim** [comment]
I'm also looking for this.

**Comment by mzylowski** [comment]
New VM image is available here: 
http://opencaching.pl/download/ocpl-devel-r7.7z
I will change link in documentation (after migration it is a new one).

cc @wrygiel

**Comment by wrygiel** [comment]
Oops. Sorry. I can see that I forgot to push the commit with the change, that's why the link was not working.
