### ISSUE TITLE
Hiding a virtual cache becomes type unknown

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#663]
When I try to hide a VirtualCache, I select it in the new cache page as such, but after submission, I see it as Unknown.

Tested on both OCRO and OCNL.

**Comment by harrieklomp** [comment]
After done some research i found some differences is use of "cache_sizes" and "cache_types"
When i look in the database in table "cache_type" i see two columns.  "ID" and "sort".
![database](https://cloud.githubusercontent.com/assets/1060518/15675127/ab6333c8-2740-11e6-8203-ab8c789adb13.png)

When i look in file "cache.php" it uses column "ID" like in the database.
![cache php](https://cloud.githubusercontent.com/assets/1060518/15675242/474deea4-2741-11e6-9cfe-de57b70ee4d3.png)

When i look in translation files (EN and PL) i see that other numbers (sort) are used.
![english translation](https://cloud.githubusercontent.com/assets/1060518/15675267/78d316a2-2741-11e6-84bd-b00d44128145.png)![polish translation](https://cloud.githubusercontent.com/assets/1060518/15675272/80f19908-2741-11e6-8f70-03f9165c872d.png)

We could make a standard with "cache types" and "cache sizes"
including TYPE_GEOPATHFINAL as new type (11) and restore "Podcast cache"
Add "nano" as new size 1

**Comment by andrixnet** [comment]
I would suggest following the recommendations here: https://wiki.opencaching.eu/index.php/Cache_types 
cache_type=11 would overlap OCUS "usb cache".
Anyway, such changes would need to be coordinated with database updates.

**Comment by andrixnet** [comment]
Still, it does not explain how a virtual becomes an unknown. It has ID=4 and SORT=8
Unknown has ID=1 and SORT=5 ...

**Comment by harrieklomp** [comment]
I found out that Webcam caches also becomes unknown caches.
Is this because Poland do not allow Webcam and Virtual caches?

**Comment by deg-pl** [comment]
Fixed
