### ISSUE TITLE
Region autocomplete

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#664]
Region autocomplete from newcache page does not work properly.
**Tested on OCNL.** 

While writing latitude, country and region got autocompleted to Spain and Valencia.
Afterwards, while writing longitude (obviously outside Spain), country and region did not change again.
Afterwards, while changing latitude, country and region did not change.

Both country and region, if they are to be autocompleted while user writes coordinates, should be updated onchange for both fields, for all modifications (I mean js events onchange, not onkeyup/onkeypress).

---

Pressing "Region from coordinates" opens a popup. 
Country and Region from opencaching.nl are detected properly, but only shown in this popup as information. They are not completed automatically, nor with a button press.
Region from Google Maps is empty.

**Comment by deg-pl** [comment]
System also should check region (and suggest right region) when user edit his cache and change coords.

**Comment by andrixnet** [comment]
Likely obsoleted by #2423 by now.
