### ISSUE TITLE
maps-api issue

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#665]
Google-maps-team sends us email where signals the issue:

> In particular, your application violates clause 10.4(d), which generally prohibits developers from using or displaying certain Google Content (as defined in the terms of service and in the Maps API Documentation, including but not limited to Street View images, Places data, and geocodes) with a non-Google map.

**Comment by kojoty** [comment]
I try to understand what we are doing wrong and for me it seems that we should hide google-street-button 
![image](https://cloud.githubusercontent.com/assets/2961448/15771288/fa58614e-2969-11e6-8706-91b912f7c800.png)


for non-google maps...
I'm going to implement hiding of this button for non-google-maps soon and then I'll contact google-team...

Can you see any other violations? Any comments?

**Comment by andrixnet** [comment]
I would contact google-team directly and ask them to be more specific such that we can fix the code properly.

**Comment by andrixnet** [comment]
Should also remove "Google" icon (bottom left) and "Google map terms of use" link (bottom right, next to map scale indicator) when viewing OSM

**Comment by andrixnet** [comment]
According to email received on June 13th, this issue URGENT.

> Dear developer,
> 
> We previously contacted you about your application, http://opencaching.pl/, on the basis that it violates the Google Maps APIs terms of service (https://developers.google.com/maps/terms).
> 
> This is a reminder that if you’re not able to bring your implementation into compliance with the terms, we will take action to restrict your access to the service.
> 
> Please let us know within the next 7 days that you have updated your implementation to comply with our terms of service. You can respond to this e-mail.
> 
> Thanks for your cooperation,
> Google Maps Team

**Comment by kojoty** [comment]
@andrixnet 
I'm aware of deadlines and I'm OK with it. Last days I have a lot of changes and work around it (I change a job, need to switch to another laptop and much more) so I don't have a time to work for OC. I will reply to google this week.

**Comment by harrieklomp** [comment]
Please also look at Geopath maps. Here are still Google contents on non Google maps.

**Comment by harrieklomp** [comment]
Google did find it also ;-)

**Comment by mzylowski** [comment]
Not yet :(

> We still see violation in Geopath maps.
> 
> Regards,
> 
> Google Maps Team

**Comment by kojoty** [comment]
@mzylowski a widzisz gdzie?

**Comment by kojoty** [comment]
moim zdaniem wszystko jest ok

**Comment by mzylowski** [comment]
Nie widzę.
Odesłali info, że jeszcze coś im nie pasuje to otworzyłem. Poczekajmy z tym issue, aż dadzą znać, że wszystko ok.
