### ISSUE TITLE
Mentor doesn't see his geopaths

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#668]
From Forum (Tomanek111 - https://forum.opencaching.pl/viewtopic.php?f=9&t=4801&start=1005#p134370):

> Witam!
> Po zalogowaniu się do serwisu i kliknięciu w menu w "geościeżki" rozwija nam się lista geościeżek. Na tej liście nie widzę geościeżek, w których jestem tzw. "mentorem". Wchodzę w "opcje wyświetlania" i w polu "ukryj" >>> "moje własne" nie ma zaznaczonego ptaszka, więc nie wiem dlaczego ukrywa "moje własne" geościeżki. Sprawdzane na kilku komputerach.

**Comment by deg-pl** [comment]
From mail (Maciek_B):

> Zauważyłem, że moja geościeżka Osiedle Przyjaźń nie wyświetla się liście ścieżek ani na mapie (również po kliknięciu na 'pokaż również mini-geościeżki') - nie wiem dlaczego tak się dzieje ? Ścieżka jest cały czas aktywna.

**Comment by mzylowski** [comment]
Related with my changes in #155. Sorry.
