### ISSUE TITLE
make m.opencaching.* international

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#68]
```
http://m.opencaching.ro/index.php

Page shows initially in polish. 
only 3 buttons for language at the bottom, though "de" and "ro" files are 
available. 

Does not seem to follow language settings from settings.inc.php

"PC version" button has hardcoded URL to opencaching.pl

http://m.opencaching.ro/find.php
waypoint is prefilled with OP, not the prefix set in settings.inc.php

Incomplete graphic styles for title and for lower box. See attach. 
```

Original issue reported on code.google.com by `andrixnet` on 28 Mar 2014 at 11:03

Attachments:
- [mobile.png](https://storage.googleapis.com/google-code-attachments/opencaching-pl/issue-68/comment-0/mobile.png)

**Comment by kojoty** [comment]
I think there isn't anyone which would like to maintain this code - I postulate to reject it and fix only security issues in mobile code. If anyone is against it - please reopen.
