### ISSUE TITLE
Autoarchiwizacja eventów / Auto-archive of events

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#682]
mail do rt:

> (https://forum.opencaching.pl/viewtopic.php?f=9&p=134547&sid=f7f62d32fbe42d7605012e5c5afdbf1a#p134547.com) pozwalam sobie przesłać je mailem (link widać). Rozumiem, że z jakichś powodów nie wszyscy kwapią się do wyjaśniania wszystkich problemów, jednak ten jest dla mnie ba tyle istotny, że oczekuję racjonalnej odpowiedzi.
> 
> Pzdr,
> Wojtek/ronja

link do kesza który znalazł się nie wiedziec czamu w stanie "zaarchiwizowany": [(http://opencaching.pl/viewcache.php?cacheid=47849]

**Comment by kojoty** [comment]
wydaje mi się, że warto by zbadać, czy faktycznie działał tu jakiś automat czy jak to się mogło stać...

**Comment by mzylowski** [comment]
Oh! There was an cronjob for that, somewhere. And still is because status of event is changing, but we didn't have a log information.

**Comment by andrixnet** [comment]
subscribe

**Comment by kojoty** [comment]
The problem is located in [https://github.com/opencaching/opencaching-pl/blob/master/util.sec/auto_arch.php#L196] (ArchEvent()).

There is only sql which changes a status of every event older than 2 months to archived.

Sending email + log comment should be implemented.
