### ISSUE TITLE
OC Team comments issue(s)

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#688]
- Somehow there are some changes in the code that prevents that OC Team comments do not show up on a cachepage anymore. I remember that this worked fine two or three months ago. The email is send correct with the nice logo :+1: 
- Is it possible to add a hard enter via the editor to write this OC Team comment? Now the e-mail is one long line without any enter when starting a new line in the editor.
![selectie_015](https://cloud.githubusercontent.com/assets/1060518/16192261/88266f08-36e8-11e6-98c6-9b4f5a08e257.png)

**Comment by mzylowski** [comment]
Do you have any error in php logs on server?

**Comment by harrieklomp** [comment]
I do not have any errors on this item.

On 31-05-2016 Andrixnet made a new (test)cache here the OC Team comment works correct. This was the latest new cache prior this issue.
![selectie_018](https://cloud.githubusercontent.com/assets/1060518/16205088/75f8e600-3722-11e6-98d7-abda0d3e5adf.png)

On the cache from the latest user when i started this issue i have manually added the text so this i cannot use anymore. but i found a strange new thing that i will explain in the next lines.

I have tried to reproduce this by making a new (test)cache as a user who has no caches on oc.nl. Now this new cache shows in DB table "cache_desc" in column "rr_comment" the text "NULL". When i add a OC Team comment via the cachepage as admin/octeam the mail does send correct but the text does not show on the cachepage because of this "NULL". Please check this on oc.pl. I did not change anything on oc.nl database in the last time.
![selectie_017](https://cloud.githubusercontent.com/assets/1060518/16205390/e7c8fa76-3723-11e6-83cb-89b54958df98.png)

**Comment by mzylowski** [comment]
On my devel it works fine - when I created a cache the rr_comment was empty:
![selection_053](https://cloud.githubusercontent.com/assets/13780868/16364658/dea8a23e-3bec-11e6-9200-fb1e26d8c0dd.png)
But I reproduced it on OC.pl node. (probably some differences between devel and ocpl configuration).
![selection_054](https://cloud.githubusercontent.com/assets/13780868/16364698/04735ed6-3bee-11e6-881e-d01debc5dffd.png)
After `SELECT * FROM `cache_desc` WHERE `rr_comment` IS NULL` I've got 790 caches, and the oldest is from 2016-05-20 23:55:50
@harrieklomp Check the same on your server.
Last commit for newcache.php is DB code refactoring around, but it is from April.
cc @deg-pl Do you have idea what happened on our server 2016-05-20 23:55:50? ;]
Maybe any update of MySQL or something else?
I will try to commit something to fix it, but I will need your (Harrie) help in debugging) ;]

**Comment by harrieklomp** [comment]
I did made these changes on the oc.nl server and now the field rr_commend stays empty when making a new cache.
And now the written comment will show on the cache page :+1:

**Comment by deg-pl** [comment]
@mzylowski - yes - mysql update probably changed this. But your fix should repair it.

**Comment by mzylowski** [comment]
@harrieklomp @andrixnet 
Is possible to fix cache_desc table by
`UPDATE cache_desc SET `rr_comment` = '' WHERE rr_comment IS NULL`
I run it on pl node.
Changes are merged to master. Please reopen if there is any other problem.
