### ISSUE TITLE
Cache owner can't change type of his logs

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#695]
From Forum (parlando - https://forum.opencaching.pl/viewtopic.php?p=134617#p134617):
> Z czego wynika brak możliwości zmiany komentarza na "wykonano serwis" lub inny typ wpisu?

![edit log](https://cloud.githubusercontent.com/assets/13884863/16398594/e1540b56-3ccb-11e6-9c32-08782754d7a5.png)

**Comment by andrixnet** [comment]
If type of log can be changed, then one of the following should happen: 
* if originally submitted log has associated actions (such as found it = increment found count, disable = change status of cache), there are two ways of handling this:
1) change type of log, undo associated actions for old log type, perform new associated actions for new log type, if any
2) allow changing of log type only for types that did not have associated actions. (allow changing a write note, but not a found it or disable)

**Comment by deg-pl** [comment]
This issue applies only when the owner has changed the type of entry to "Comment" on "Service made/Cache OK" or vice versa.
