### ISSUE TITLE
Don't leave note about log edit, when the edit was only few minutes ago

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#696]
By Brasia from opencaching.pl forum

> Dokonując wpisu do skrzynki, jeśli popełni się błąd (literówkę) to poprawa wpisu powoduje powstanie adnotacji o edycji wpisu. (O ile pamiętam adnotacja wzięła się stąd, że ktoś sobie „jechał” w logach, później je edytował i udawał, że nic się nie stało). Uważam, że dobrze byłoby, po dokonaniu wpisu powinno mieć się jeszcze kilka (np. 5) minut na kosmetyczną poprawę wpisu, adnotacja o edycji pojawiłaby się dopiero po przekroczeniu tego czasu.

**Comment by deg-pl** [comment]
@wrygiel please confirm that (in the context of https://github.com/opencaching/okapi/issues/383), we may don't change the value of cache_logs.edit_counts.

(Boję się, że moja "gramatyka angielska" może wprowadzać w błąd, więc piszę też po polsku - potwierdź mi proszę, że przy edycji logu można NIE zmieniać edit_counts i OKAPI się nie posypie. Moim zdaniem ważne jest odpowiednie ustawienie last_modified i okapi_syncbase (to akurat się samo ustawia), ale wolę mieć 100% pewność.)

**Comment by wrygiel** [comment]
OKAPI w ogóle nie używa, ani nie patrzy na kolumnę `edit_counts`, więc obojętnie co tam będzie wstawione, nie powinno się posypać.
