### ISSUE TITLE
extend opensprawdzacz coords to other Earth quartires

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#7]
```
Add N/S and W/E dropbox witch coordinate inputs

```

Original issue reported on code.google.com by `wloczynutka` on 11 Jan 2014 at 5:41

**Comment by deg-pl** [comment]
From OC UK staff:
The geochecker has a problem connected with east/west hemisphere. It prompts with Degrees E and Minutes E. But the solution is W001. I've managed to get it to work by entering a minus in front of BOTH the degrees AND minutes boxes, which is not intuitive for most people, and it then prints out that W -1 -5.xxx is correct, which is pretty ugly!

(I've also clean some comments with "test" only content)

**Comment by kojoty** [comment]
seems to work OK - if there is anything more to do - please reopen.

**Comment by deg-pl** [comment]
Thanks!!!

**Comment by Amberel** [comment]
Hi kojoty, very many thanks for sorting this out :-) When the checker is used and the person inputs the correct solution, it appears to be displaying an image quiz-s.png, but the image is not on our server, I guess this is a different issue? Also, very minor, the text "Save as you own coordinates ..." probably should be "Save as your own coordinates ..." 
Rgds, Andy

**Comment by Amberel** [comment]
Hi kojoty, very many thanks for sorting this out :-) When the checker is used and the person inputs the correct solution, it appears to be displaying an image quiz-s.png, but the image is not on our server, I guess this is a different issue? Also, very minor, the text "Save as you own coordinates ..." probably should be "Save as your own coordinates ..." 
Rgds, Andy

**Comment by kojoty** [comment]
@Amberel - should be done. Thanks.

**Comment by Amberel** [comment]
@kojoty - Just checked and it is excellent, thank you so much :-)
