### ISSUE TITLE
Error with honered cache

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#703]
Last night ocnl tried to make a cache of the month (ocpl has cache of the week). When running the cron for this it give the next error.

+++ PDO Error +++ 

+++ Debug: Query|Params: INSERT INTO cache_titled

        (cache_id, rate, ratio, rating, found, days, date_alg, log_id)

        VALUES (:1, :2, :3, :4, :5, :6, :7, :8) |  |  |  |  |  |  | 2016-07-01 | 

+++ Ex_Code: 23000

+++ Ex_Msg: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cache_id' cannot be null

+++ Ex_Trace:

#0 /var/www/www.opencaching.nl/Utils/Database/OcDb.php(278): PDOStatement->execute()

#1 /var/www/www.opencaching.nl/cache_titled_add.php(136): Utils\Database\OcDb->multiVariableQuery('INSERT INTO cac...', NULL, NULL, NULL, NULL, NULL, NULL, '2016-07-01', NULL)

#2 {main}

Can please some one take a look at this.
Thanks.

**Comment by tripper1971** [comment]
I'm in touch with Harrie

**Comment by harrieklomp** [comment]
Because oc.nl has not much logs the amount of $titled_cache_nr_found=5 was to high. Advice from tripper1972 was to change to $titled_cache_nr_found=2.  Now it works again :+1: 

Perhaps edit the code to get a warning to decrease the number of founds and not get a error?

**Comment by mzylowski** [comment]
Yes, we can add a information - for example by calling error_log method :)
