### ISSUE TITLE
User can't change cachetype to owncache

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#705]
From forum (https://forum.opencaching.pl/viewtopic.php?p=134743#p134743):

> Jedyny problem jest taki że mi wyrzuca owna - wraca notorycznie do nietypowej.
> 
> Potwierdzam, że jest jakiś problem - próbowałem zmienić losową skrzynkę na own i się nie da. Możliwe, że to jest związane z aktualnymi obostrzeniami tego typu

**Comment by harrieklomp** [comment]
This kind of change is also not possible from "Own cache" type to another type of cache. If cache type is "own cache" the user get a empty dropdown menu when selecting the cachetype. This is only for user. When login as admin the dropdown menu does work correct and the cachetype can be changed.

**Comment by deg-pl** [comment]
I think this has already been resolved earlier. Now you can change (as user) any cache type to own cache and back.
