### ISSUE TITLE
My voivodeship / Moje województwo

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#722]
OCPL COG is a group of people and every of them is responsible for one polish administrative province called "województwo" (eng. voivodeship).
Currently every OC user can set a "my neighbourhood" circle by define the center + range and be informed about oc activity inside this range. Every COG member need the same information but not from "circle" but from his/her voivodeship.

The plan is to present the same similar information as "my neighborhood" but for voivodeship defined by user. At first stage it will be accessible only for selected number of user (admins-COG members) but further we decide if it can be accessible for all OC users.

This feature will be disabled by default in config, so nodes which not enable it will not be affected by this.

Any comments are welcome.

**Comment by harrieklomp** [comment]
It could be interesting for other nodes if the Polish provinces are not hardcoded in the software like in http://www.opencaching.nl/articles.php?page=s7 or http://www.opencaching.nl/articles.php?page=s8 . There should be a system that nodes can use their own provinces.

**Comment by kojoty** [comment]
@harrieklomp, don't worry - It will not be a oc.pl-centric feature - I see that oc.nl has defined province for every cache so I believe it would work for you as well as for oc.pl...

I agree statistics you mentioned are broken in this matter... I made a new issue #723 to fix it as well...

**Comment by harrieklomp** [comment]
:+1:

**Comment by kojoty** [comment]
after myNbh refactoring it seems this is experiment no longer needed 
i'll remove the code from repo
