### ISSUE TITLE
Hardcoded provinces in statistics

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#723]
from @harrieklomp message:

> It could be interesting for other nodes if the Polish provinces are not hardcoded in the software like in http://www.opencaching.nl/articles.php?page=s7 or http://www.opencaching.nl/articles.php?page=s8 . There should be a system that nodes can use their own provinces.

It should be fixed as well...

**Comment by harrieklomp** [comment]
:+1:

**Comment by deg-pl** [comment]
Fixed by commit f5aee81da300f3dee63d0d8ab8248dc634379550 . Thanks @following5
