### ISSUE TITLE
Strange behavior when look at other user map

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#724]
I found something weird when looking on other users map. This could be a small bug in the code.

This is for all registered users, no matter if they have ever logged in or filled in a home coordinate.
Just go to http://www.opencaching.pl/searchuser.php and fill in a existing username who has not logged in in the last month. I did select a user who has never logged in.
![selectie_006](https://cloud.githubusercontent.com/assets/1060518/17470710/c00d2890-5d3e-11e6-912a-efa536615d01.png)
Now press on the right site the button "Show user's map". After the map page is loaded go back a page in your browser and refresh the (user profile)page.
![selectie_007](https://cloud.githubusercontent.com/assets/1060518/17470780/6271d342-5d3f-11e6-8abd-ad6b37b596fc.png)
This page shows if this user was recently online but in real he was never online. This is only triggered when showing the map of that user.

The function at the bottom of the site who does show the online users do not show the searched user if he was online in the past 10 minutes. It looks that this is a small local problem in "Show user's map" or "User profile".

**Comment by harrieklomp** [comment]
BTW. The database does also show that this user was online at the moment i pressed ""Show user's map". In real he was never online.
![selectie_008](https://cloud.githubusercontent.com/assets/1060518/17471140/4355012a-5d42-11e6-8cc5-f2926ee3eff3.png)

**Comment by kojoty** [comment]
I can confirm - it happens.
Last_login column is in this case updated by OKAPI when user map is requested - I think it is okapi issue. I created new issue on OKAPI (reference above)

**Comment by harrieklomp** [comment]
It looks that this is solved with https://github.com/opencaching/okapi/issues/439
