### ISSUE TITLE
[Security] Vulnerability by $_COOKIE through unzerialize()

### ISSUE THREAD

**Issue by Rotzbua** [opencaching/opencaching-pl#730]
same as: https://github.com/opencaching/okapi/issues/438
- Object Injection
- https://www.owasp.org/index.php/PHP_Object_Injection
- affects all OC versions
- replace serialize by json_decode/encode -> then also usable by javascript

Found at:
lib/cookie.class.php
mobile/lib/cookie.class.php
`$this->values = @unserialize($decoded);`

**Comment by wrygiel** [comment]
Alternative: I've done some reading and I believe that in PHP 7 you can also call `unserialize($decoded, array('allowed_classes' => false))`.

**Comment by deg-pl** [comment]
We have also similar issue #1020

**Comment by kojoty** [comment]
@wrygiel, it seems to be a real problem. What do you think should be done here - I think we should fix ASAP.

**Comment by wrygiel** [comment]
1. Easy, but a bit less secure - copy the [solution from OKAPI](https://github.com/opencaching/okapi/commit/d148501e24eeacdb115235a455d35219e0c446fb).
2. A bit more difficult, but more secure - copy the [solution from OCDE](https://github.com/OpencachingDeutschland/oc-server3/pull/364/files).

**Comment by kojoty** [comment]
everything seems to work OK, so I guess we can close it.
