### ISSUE TITLE
Add new column in viewpendings (last update + its author)

### ISSUE THREAD

**Issue by DorotkaMakotka** [opencaching/opencaching-pl#732]
During the verification process of the new cache COG member is waiting for owner's response. It would be really helpful to see last comments of verified caches on pendings list, without having to enter each cache page.

**Comment by kojoty** [comment]
I assign to me but makotka will work on this issue and prepare the change and deliver it as a pull request.

**Comment by kojoty** [comment]
this is fixed by commit 0ac140e
