### ISSUE TITLE
Invalid sign of numeric score for "Below average" rating

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#737]
From forum (https://forum.opencaching.pl/viewtopic.php?p=135280#p135280):

> Problem z punktacją oceny skrzynek.
> Przy "poniżej przeciętnej" zamiast (minus) - 0,5 liczy najprawdopodobniej wartość dodatnią

We should:
- fix function new2oldscore($score) in common.inc.php
- alter table scores to fix "score" field
- recalculate caches.score fields (util.sec/repair_cache_scores.php)

**Comment by deg-pl** [comment]
@andrixnet and @harrieklomp - please do sqlAlters/2016-08-24_fix_invalid_cache_log_scores
and next run util.sec/repair_cache_scores.php

**Comment by harrieklomp** [comment]
Done on oc.nl.
