### ISSUE TITLE
More watched areas in "My neighbourhood"/ "Moja okolica"

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#744]
From email:

> Andrzej Zieliński
> Brakuje nam funkcjonalności (..) dowolnej liczby obserwowanych obszarów. Sporo ludzi przebywa w więcej niż jednym miejscu i moja okolica pomimo tego że jest świetnym narzędziem (...) to jednak obejmuje tylko jedną okolicę.

**Comment by deg-pl** [comment]
Czy przy założeniu, że będzie "moje województwo" z możliwością wyboru województwa (np. jako <select>), czyli w "moim województwie" będzie można przełączać województwo na inne - czy ten issue nadal ma sens? Może zamiast komplikować Moją okolicę i rozciągać ją na wiele obszarów, dać userom dodatkowo Moje województwo z możliwością szybkiego przełączenia województwa.
Choć z drugiej strony - nie rozwiązuje to problemu powiadomień o nowych keszach...
