### ISSUE TITLE
myn_ftf.php doesn't work

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#750]
From Forum (https://forum.opencaching.pl/viewtopic.php?p=135388#p135388):
> Chyba coś się popsuło z pełną listą FTF w Mojej okolicy
> http://opencaching.pl/myn_ftf.php

From error.log:
```
PHP Warning:  Classpath can't find: Gis in /srv/ocpl/lib/ClassPathDictionary.php on line 76
PHP Fatal error:  Class 'Gis' not found in /srv/ocpl/myn_ftf.php on line 56
```

**Comment by kojoty** [comment]
It was my fault - Now it should be fixed.
