### ISSUE TITLE
Mail generated by "Report problem" should show be differentiated

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#755]
Currently, when you report a problem to the Cache Owner or OC Team is generated the same email. Cache Owner does not know whether the problem was reported to him or to the OC Team. In addition, in both cases, the sender of the email is the OC Team (cog@opencaching.pl).

**Comment by mzylowski** [comment]
Related with emails - can be on me.

**Comment by deg-pl** [comment]
@mzylowski Działasz coś w tym temacie, czy mogę przejąć issue?

**Comment by deg-pl** [comment]
New idea: User who report caches to cache owner shoud decide to show (or not) his e-mail address in report (like in message sending).

**Comment by deg-pl** [comment]
Done:
- Mails has different, clear subjects ant different content
- Checkbox - report submitter may now show his e-mail with cache owner.
