### ISSUE TITLE
mailto.php allow "save" message without destination user

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#759]
There is improper input param handling and for example if user_id param is not set message is saved in DB but destination user id = 0! (without any user notice!)

Such messages are never sent and stays in DB forever and server tries to send it at every user emails sending session... what generates log messages:

_sendmail: fatal: www-data(33): No recipient addresses found in message header_

**Comment by kojoty** [comment]
@mzylowski, masz już jakieś zmiany w obrębie tego pliku? Mogę to poprawić czy ty chcesz to zrobić w ramach Twoich prac nad mailami?

Pozdrowienia!

**Comment by mzylowski** [comment]
In september I have a lot of work to do with my studies/university things, so fell free to fix this.

**Comment by kojoty** [comment]
should be fixed now.
