### ISSUE TITLE
Look&Feel improvements

### ISSUE THREAD

**Issue by DorotkaMakotka** [opencaching/opencaching-pl#764]

**Comment by DorotkaMakotka** [comment]
![buttonsforviewpendings](https://cloud.githubusercontent.com/assets/19299162/18608646/6d680bc0-7cef-11e6-94f3-79a6e36fa5a2.PNG)

**Comment by DorotkaMakotka** [comment]
![newcache](https://cloud.githubusercontent.com/assets/19299162/18610636/5dcc23ae-7d21-11e6-8b28-85a3e90c3669.PNG)

**Comment by DorotkaMakotka** [comment]
![formbuttons](https://cloud.githubusercontent.com/assets/19299162/18616620/7c8cecee-7dbf-11e6-8f03-cc1c68b3a4d4.PNG)

**Comment by harrieklomp** [comment]
Looks very nice.
Great work :+1:

**Comment by DorotkaMakotka** [comment]
Inputs changing in progress:
![Uploading inputs.PNG…]()
![inputs2](https://cloud.githubusercontent.com/assets/19299162/18619742/ae45cac2-7e04-11e6-8075-4f2f99428928.PNG)

**Comment by DorotkaMakotka** [comment]
I added some new buttons to help users find a way to change their profile (there are links in the side panel  but not really intuitive and many people failed to notice) 
![changeprofile](https://cloud.githubusercontent.com/assets/19299162/18619774/39311e02-7e05-11e6-86d8-6530785df578.PNG)

**Comment by DorotkaMakotka** [comment]
New select elements + further forms improvements
![forms-selects](https://cloud.githubusercontent.com/assets/19299162/18648949/42898634-7ebd-11e6-9dff-4efe0fbd74c4.PNG)
![checker](https://cloud.githubusercontent.com/assets/19299162/18648959/4a8fde82-7ebd-11e6-994e-f91b706d2110.PNG)
![map search](https://cloud.githubusercontent.com/assets/19299162/18648968/508983f6-7ebd-11e6-875c-2ed1ea9468df.PNG)

**Comment by DorotkaMakotka** [comment]
Colors - some tiny changes.
![main](https://cloud.githubusercontent.com/assets/19299162/18648990/68bcd54a-7ebd-11e6-9886-4d33d07f6367.PNG)

**Comment by DorotkaMakotka** [comment]
New form styles have been applied for further forms e.g.
* search 
![search2](https://cloud.githubusercontent.com/assets/19299162/18692562/740e7668-7f9b-11e6-93f0-45e1a7d4dae4.PNG)
![search](https://cloud.githubusercontent.com/assets/19299162/18692570/79a81d4a-7f9b-11e6-90e2-fc9a330185da.PNG)
* routes
![addroute](https://cloud.githubusercontent.com/assets/19299162/18692615/d7635de6-7f9b-11e6-963b-5b28d825527f.PNG)
![route](https://cloud.githubusercontent.com/assets/19299162/18692617/db4a4122-7f9b-11e6-9837-9cb9b98540b1.PNG)
* cache logs 
![log](https://cloud.githubusercontent.com/assets/19299162/18692650/2c87e0d0-7f9c-11e6-833e-e100437d3c10.PNG)
* and others
![coordinates](https://cloud.githubusercontent.com/assets/19299162/18692653/367daf20-7f9c-11e6-8916-93a4ebb651d3.PNG)
![news](https://cloud.githubusercontent.com/assets/19299162/18692655/3adb40d2-7f9c-11e6-8b32-ddcf9f752821.PNG)

**Comment by andrixnet** [comment]
:+1:

**Comment by DorotkaMakotka** [comment]
* buttons group intro
![buttongroup](https://cloud.githubusercontent.com/assets/19299162/18718168/c36b6996-8022-11e6-8a6b-5df45f62e068.PNG)

* menu smoothing
![menu](https://cloud.githubusercontent.com/assets/19299162/18718176/cacbaed0-8022-11e6-93c7-cea8c526281a.PNG)

* list of caches chunk modifications 
![chunklistofcaches](https://cloud.githubusercontent.com/assets/19299162/18718214/e36c02c8-8022-11e6-9ba6-a27b7cf970c6.PNG)

**Comment by DorotkaMakotka** [comment]
* search results - buttons etc
![searchresults](https://cloud.githubusercontent.com/assets/19299162/18731035/c0d8a2ac-8059-11e6-8dce-757254298d6e.PNG)
![savesearchresults](https://cloud.githubusercontent.com/assets/19299162/18731038/c53a6268-8059-11e6-99f5-1d242953c2e1.PNG)

**Comment by andrixnet** [comment]
Note about search results: 
1. IMO the 2 top buttons with icons are much less visible without the icons.
2. the column, with date and icons: there should be a space between the left side icon and the text
3. there should be a small spacing between the 2 pagination buttons (below the list of results)

**Comment by DorotkaMakotka** [comment]
Hi @andrixnet, thanks for your input.

First, let me explain what am I doing here :) 
I plan to improve the appearance of our site a little bit. 
The are many things to be unified, some things to be added, some other to be removed (things that looked fancy at the beginning of the internet but now they don't). 

The truth is that many of the views require complete refactoring. I don't have time for it so I won't do it in the nearest future. I decided to improve the look (or remove ugliness) step by step. It will be kind of evolution, definitely not the revolution. Of course some things will be not consistent for some time but there was no consistency before my changes so I don't think it is a big problem.

In recent days I've introduced new styles for buttons and inputs. I'm gradually removing old styling and applying new one.  **I'm not changing the whole views**. 
I am also preparing styles for kojoty's chunk - list of caches. As soon it's ready I think that @kojoty will be replacing existing lists one by one with his 'chunk', but it will be also rather slow process. 

So, time to answer to your points:

> IMO the 2 top buttons with icons are much less visible without the icons.

As for icons themselves - in gerenal - I feel that on our site there are too many icons (what's worse - old fashioned ones). Many of the icons don't provide really useful information but are generating chaos. We don't need the icon next to each action, each title, each header and so on...

As for this particular case: 
Button styles are based on bootstrap buttons (of course we can customize them and adjust to our needs but right now I focus on applyng new styles to all buttons, so that in future changing all buttons will require only one change in one place - css file).

How it looks like now: 
![buttons](https://cloud.githubusercontent.com/assets/19299162/18743931/b988f62a-80bb-11e6-8042-6999808a541a.PNG)
We can increase visibility of buttons mentioned by you by changing style from default  to primary or sth like that. What do you think?  

>  the column, with date and icons: there should be a space between the left side icon and the text

As I wrote above, I won't touch it now, but it will be fixed some day (when the time for refactoring this view will come). 


> there should be a small spacing between the 2 pagination buttons (below the list of results)

The same as for point 2.  Plus: I can show you some teaser of pagination styles I've prepared :)
![pagination](https://cloud.githubusercontent.com/assets/19299162/18744522/afde3ccc-80be-11e6-92a3-d4b722c7ceee.png)

As kojoty will gradually refactor tables/lists he will also use new pagination chunk with these styles.


-----
For next few days I plan to prepare coordinates modification widget. What will be next - I don't know yet, but feel free to suggest what is important to you, I'll take your opinion into account.  

Greetings,
makotka

**Comment by wrygiel** [comment]
> As for icons themselves - in gerenal - I feel that on our site there are too many icons (what's worse - old fashioned ones).

I agree. It's better to have no icons than to have ugly ones.

Still, we might consider using single, predefined iconset. For example, [Font Awesome](http://fontawesome.io/examples/). I haven't used it in any large projects yet (only simple pages, like [this one](http://developers.erasmuswithoutpaper.eu/)), but it makes a good impression. It's reusable and easy to include in any place. It's default iconset is limited, but I think it should cover our usecases.

> We can increase visibility of buttons mentioned by you by changing style from default to primary or sth like that. What do you think?

It's indeed easy to miss the default ones.

**Comment by DorotkaMakotka** [comment]
* file upload buttons improved
![fileupload1](https://cloud.githubusercontent.com/assets/19299162/18852855/a98ea370-8442-11e6-8039-7985ee2e47cc.PNG)

**Comment by andrixnet** [comment]
@DorotkaMakotka thank you for your efforts, great job. 

I agree that in some places there are too many icons, too many icon+text combo or some places with icons that have too litle visual meaning. 

Some icons should dissapear, some icons should stay (cache listing, header), some icons could use visual improvements.

There are some situations where either by icon or by button style, the importance / significance should be emphasized.

**Comment by andrixnet** [comment]
See also about icons: https://github.com/opencaching/opencaching-pl/issues/779

**Comment by kojoty** [comment]
I think we can close this general thread. We can reopen it in future if needed. Works at UI are endless :)
