### ISSUE TITLE
Google Analytics key should be read form config and GA should be load for all pages

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#769]
We used GA in many scripts right now but pages from all running versions of the GA code are counted a oc.pl visits in GA.

GA key should be set in config to allow OC node administrator enable it for its nodes.

**Comment by kojoty** [comment]
GA for main site is fixed - we still need changes for "mobile" version of OC ...

**Comment by andrixnet** [comment]
After reading on the mailing list, I was on my way to investigate and report it as an issue.
Good job, @kojoty !

This solves https://github.com/opencaching/opencaching-pl/issues/300

GA for mobile version is opened here: https://github.com/opencaching/opencaching-pl/issues/239

**Comment by deg-pl** [comment]
Can we close this issue?
