### ISSUE TITLE
Cache visits counter

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#782]
from mail to RT:

> kieruję do Was prośbę w imieniu COG, dotyczącą zmian w funkcjonowaniu licznika odwiedzin na stronie kesza.
> 1. Licznik ma być informacją dla autora, do ilu osób dotarła skrzynka. Wnioskujemy o następującą zmianę -  wizyty na stronie kesza powinny być zliczane dopiero od momentu publikacji skrzynki. Aby licznik spełniał swoją rolę prosimy również w miarę możliwości o ograniczenie nabijania licznika do minimum - tak, aby zliczał możliwie unikalne wizyty (teraz nabija się np po każdym refreshu). 
> 2. Chcemy oczywiście zachować informacje o wejściach na skrzynkę przed publikacją i wyświetlić ją w postaci listy nicków w polu widocznym dla COG.

**Comment by andrixnet** [comment]
Does this work also affect the print view?

**Comment by kojoty** [comment]
viewcache.php has two views (templates): viewcache.tpl.php and viewcache_print.tpl.php 
I complete redesigned viewcache.php code so it touches both templates, but changes are almost invisible for end users.

Probably I should tell you more about changes in visit counter - this is a case we discussed offline a little  and that's the new "vision" of this counters (in fact it has a minor impact, but I try to describe what I prepare), so:

- till now cache-visit-counter was increased by every viewcache.php call - so refresh of the page gets +1 to views - in my opinion it damaged the current stats values, which lost its sense - I assume that we reset visit counters values

- polish COG(admin team) has also another issue: there were accusations that admin-team members cheats and looked at cache pages before publication - some of them need to do that because of verification but others not, and we would like to allow for cache-owner and rest of admin team to view the list of usernames which accessed the cache page before the publication date - this is the one of the purpose of this change - it will be implemented similar to the list of the users which recommended the cache

- the new visits counter will show _unique-visits_ at the cache page, where such _unique-visit_ is discovered if the user display cache page after at least one week after his last _unique-visit_, so this counter will show real interest in the cache

**Comment by kojoty** [comment]
it should be fixed after #885.
