### ISSUE TITLE
Coś nie tak z emailami z forum

### ISSUE THREAD

**Issue by wrygiel** [opencaching/opencaching-pl#783]
Dostałem powiadomienie o wiadomości:

![image](https://cloud.githubusercontent.com/assets/2168535/19233112/c8c8b8e2-8ee3-11e6-9970-627ef329ae0a.png)

której nie mam uprawnień przeczytać:

![image](https://cloud.githubusercontent.com/assets/2168535/19233122/d993727a-8ee3-11e6-9bed-22926644f080.png)

Chyba jakiś bug. O tyle istotny, że spamuje użytkowników.

**Comment by deg-pl** [comment]
@wrygiel wyślij mi proszę PM na forum - dla testu

**Comment by wrygiel** [comment]
wysłałem

**Comment by wrygiel** [comment]
Chyba wiem - właśnie widzę, że mimo wysłania, nadal mogę tę wiadomość usunąć. Wtedy pewnie dostaniesz powiadomienie, a nie będziesz mógł wiadomości przeczytać. Właśnie to zrobiłem.

**Comment by wrygiel** [comment]
Czyli pewnie to jest "ficzer". ;)

**Comment by deg-pl** [comment]
Napisało mi, że nie mogę czytać, bo wiadomość usunąłeś.

**Comment by wrygiel** [comment]
Hmm, czyli jednak coś innego napisało, niż mi? Dziwne dziwne. Wysłałem jeszcze jedną i tym razem nie usuwam jej.

**Comment by deg-pl** [comment]
Komunikat miałem trochę inny niż Ty - że wiadomość jest usunięta.
Co do nowego testu, to wygląda na to, że wszystko działa poprawnie - gdy jestem zalogowany na Forum (domyślnie), to link przekierowuje mnie bezpośrednio do PW od Ciebie. Jeśli nie jestem zalogowany, link przekierowuje do strony z logowaniem, a po zalogowaniu jest redirect do PW od Ciebie. Więc.... "u mnie działa" :)
Napiszę Ci też PW, to sprawdzisz, czy u Ciebie też działa.

**Comment by wrygiel** [comment]
Twoją wiadomość mogę otworzyć. Ale tej poprzedniej nadal nie mogę. W powiadomieniach ją nadal widać:

![image](https://cloud.githubusercontent.com/assets/2168535/19251043/b5db1554-8f3d-11e6-8b6f-6cec257cabb4.png)

Ale po jej kliknięciu dostaję ten błąd z brakiem uprawnień co wyżej.

**Comment by deg-pl** [comment]
Myślę, że możemy zamknąć to issue. Nie jest powiązane z kodem OC PL, tylko z forum PL, a w dodatku - nie jesteśmy w stanie odtworzyć tego błędu.
