### ISSUE TITLE
Current database structure

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#788]
@opencaching/opencaching-pl-lead-programmers : 

I am comparing OCRO and OCNL database structures and I can already see slight differences.
**I want to request a current OCPL database structure export so that I can compare, discuss and update, so that in the end each site has a consistent and identical database.**

Each site started at a different point in time, from a (presumably up to date, yet not so sure) given DB structure and applied changes as they came into being (sqlAlters/*.sql).
However, there are differences, and assuming OCPL is the master, I would like to request a schema dump (without data) from official OCPL.

For the sake of consistency, I recommend using:

`mysqldump --no-data --routines --triggers --add-drop-database --flush-logs --lock-all-tables --opt --default-character-set=utf8 --database DATABASE_NAME -u root -p > OCPL_schema.sql`

This has to be done with MySQL root user or a user that has sufficient server privileges.
It will contain tables, triggers, stored procedures.
It will NOT contain data.

Of course, if anyone can/would recommend a better and more complete way of generating the schema dump, please show the command together with the dump.

**Comment by wloczynutka** [comment]
There is tool for comparing oc dbstructures.
https://github.com/opencaching/opencaching-pl/wiki/vm_installation_and_usage => setup

**Comment by wloczynutka** [comment]
There is tool for comparing oc dbstructures.
https://github.com/opencaching/opencaching-pl/wiki/vm_installation_and_usage 
=> setup

**Comment by andrixnet** [comment]
Specifically this : `http://local.opencaching.pl/okapi/devel/dbstruct?compare_to=http://opencaching.pl/okapi/devel/dbstruct` to generate a diff between local and OCPL database. 

Noting it here for completeness.

**Comment by andrixnet** [comment]
However I have discovered 2 things which are not good: 

1. both OCNL and OCRO differ from OCPL in quite a few places
2. I cannot compare OCNL and OCRO this way because of a script error.
3. OCPL database is missing some columns vital for OCRO (mainly related to strings still in database) e.g.:
```
ALTER TABLE `cache_size` DROP `ro`;
ALTER TABLE `cache_status` DROP `ro`;
ALTER TABLE `cache_type` DROP `ro`;
```
_And these are only a few of them._
Next I will take each difference for both OCRO and OCNL and try to analyze it in detail, also with changes published in /sqlAlters

**Comment by andrixnet** [comment]
Closing as duplicate of #1164
