### ISSUE TITLE
website sometimes unaccessible

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#79]
```
I was running one of the cron jobs in a console and it seemed to take a lot of 
time, and while it was running, the website was no accessible to users. 

Website displays: waiting ... 

On the server, CPU load is insignificat, both httpd and mysqld do not show 
excessive CPU usage. 

I interrupted the command. In this case do-wget-url   
util.sec/cron/modules/cache_npa_areas.class.php
Website access did not resume. 

No noticable errors in error.log

I had to restart the httpd to get the website usable again. 


```

Original issue reported on code.google.com by `andrixnet` on 29 Mar 2014 at 11:28
- Blocking: #176

**Comment by andrixnet** [comment]
I've changed internet hosting early this year. 
I totally missed util.sec/.htaccess problem ( https://github.com/opencaching/opencaching-pl/issues/350 ) and for a while I experienced improved performance of the website. 

Of course, with the drawback that some scripts did not run.

I recently corrected this ( https://github.com/opencaching/opencaching-pl/pull/969 ) and again I started to experience website slugishness (less outages because the new hosting has more RAM). 

However the hosting virtualization manager has shown a periodical sawtooth pattern in memory usage. Memory usage increases almost constantly, until another cronjob runs that does a graceful restart of Apache ( I put it in place to handle this issue https://github.com/opencaching/opencaching-pl/issues/79 )

Obviously it is one of the cron jobs, which I have yet to identify.

**Comment by kojoty** [comment]
@andrixnet, have you identified which script is a source of the current issues?

**Comment by kojoty** [comment]
@andrixnet, I'm closing this issue - please reopen if the problem still exists.

**Comment by deg-pl** [comment]
Problem still exists on OC RO. This is server speciffic problem, not in OC code, but this thread may be helpfull for debugging process.

@andrixnet - you have enabled mpm_event. Do you use mod_php or php-fpm?

**Comment by andrixnet** [comment]
From RT mailing list 

> Hi Deg,
> 
> Even though I upgraded my VPS from 1GB RAM to 2GB RAM last year, I am still experiencing some sort of memory leak problems.
> Partially described here: https://github.com/opencaching/opencaching-pl/issues/79 , the problem is somewhat held under control by periodic graceful restart of apache (cron job).
> If I deactivate OC site and OC cron jobs, the problem goes away, so it is definitely related.
> I haven't had the time to investigate further, that is why I haven't reopened #79.
> 
> My system's default configuration used mpm_event, which I left untouched. Recently, when I was investigating some problems, switching from mpm_event to mpm_prefork reduced Apache's startup memory usage to almost half. No changes to the default settings.
> When handling this, I read several articles on the net, some were saying about mismatches between mpm_event and PHP's threading model (though not citing versions other then Apache-2.4).
> For the time being, the current mpm_prefork configuration seems to hold the memory usage down. See below my system's settings (incidentally, they are the distro default)
> 
> Even with all my reading so far, I am not sure how to tweak the mpm_event to reduce memory usage.
> 
> # prefork MPM
> # StartServers: number of server processes to start
> # MinSpareServers: minimum number of server processes which are kept spare
> # MaxSpareServers: maximum number of server processes which are kept spare
> # MaxRequestWorkers: maximum number of server processes allowed to start
> # MaxConnectionsPerChild: maximum number of connections a server process serves
> #                         before terminating
> <IfModule mpm_prefork_module>
>     StartServers             5
>     MinSpareServers          5
>     MaxSpareServers         10
>     MaxRequestWorkers      250
>     MaxConnectionsPerChild   1000
> </IfModule>
> 
> # worker MPM
> # StartServers: initial number of server processes to start
> # MinSpareThreads: minimum number of worker threads which are kept spare
> # MaxSpareThreads: maximum number of worker threads which are kept spare
> # ThreadsPerChild: constant number of worker threads in each server process
> # MaxRequestWorkers: maximum number of worker threads
> # MaxConnectionsPerChild: maximum number of connections a server process serves
> #                         before terminating
> <IfModule mpm_worker_module>
>     StartServers             3
>     MinSpareThreads         75
>     MaxSpareThreads        250
>     ThreadsPerChild         25
>     MaxRequestWorkers      400
>     MaxConnectionsPerChild   0
> </IfModule>
> 
> # event MPM
> # StartServers: initial number of server processes to start
> # MinSpareThreads: minimum number of worker threads which are kept spare
> # MaxSpareThreads: maximum number of worker threads which are kept spare
> # ThreadsPerChild: constant number of worker threads in each server process
> # MaxRequestWorkers: maximum number of worker threads
> # MaxConnectionsPerChild: maximum number of connections a server process serves
> #                         before terminating
> <IfModule mpm_event_module>
>     StartServers             3
>     MinSpareThreads         75
>     MaxSpareThreads        250
>     ThreadsPerChild         25
>     MaxRequestWorkers      400
>     MaxConnectionsPerChild   0
> </IfModule>
> 
> 
> On the other hand, HTTPS is on the TODO list. Not sure if letsencrypt or a paid certificate provider yet, there are other (non-technical) considerations to be addressed first.
> 
> IMO it can be a benefit that the site can work well over HTTP/2, however I believe, even for the future, this should not become a strict requirement.
> 
> I also believe it would be highly useful for node admins to have sample webserver configuration documented, for example here:
> https://github.com/opencaching/opencaching-pl/tree/master/docs/system
> The suggested caching and expires optimization could also go there.
> 
> You can find OCRO based sample configuration here: https://github.com/andrixnet/opencaching-pl/tree/INSTALL/docs/system
> which is a rather explicit configuration with more details then the basic configuration on some linux distros I've seen, but I prefer it to be this way.
> Feel free to improve on it.
> Note: the SSL configuration gets grade A from SSLLabs, while allowing for some wider cipher compatibility.
> 
> Updating to PHP-7.1 is on the TODO list as well for this year. I have to consider other technical details regarding the distro and other services running on the same machine as well. This is a subject I've discussed with kojoty as well.
> 
> Programming question: how does the current code fare on PHP-7.2 compared to 7.1?
> My question is in part also based on http://php.net/supported-versions.php

**Comment by andrixnet** [comment]
Follow-up:

> Hi!
> 
> 1) Problems with your server
> 
> Our (default) mpm_event config has much lower limits than yours:
> 
> <IfModule mpm_event_module>
>         StartServers                     2
>         MinSpareThreads          25
>         MaxSpareThreads          75
>         ThreadLimit                      64
>         ThreadsPerChild          25
>         MaxRequestWorkers         150
>         MaxConnectionsPerChild   0
> </IfModule>
> 
> OC UK (and my devel machine) works on ArubaCloud (1 core, 1 GB RAM, 20 GB storage) without any problems and memory leaks. But both of these servers run on newest versions of software (Ubuntu, Apache, MariaDB, PHP). OC UK has bigger DB than OC RO, so problem is somewhere in your server config. Verify that you're using php-fpm, not mod_php. Let's continue this thread not here, but in #79 or/and on Facebook.
> 
> 2) https / SSL
> 
> We use Letsencrypt, not paid certificate, because Letsencrypt is free and has no domain limit. Now we use SSL on many domains (opencaching.pl, akq.opencaching.pl, forum.opencaching.pl, wiki.opencaching.pl, wybory.opencaching.pl and opencaching.eu), so we would need two wildcard certificates - this is very expensive!
> 
> 3) HTTP/2 & docs
> 
> Main adventages of HTTP/2 are push technology and multiplexing of request and responces over single TCP connection - THIS SAVES SERVER RESOURCES. Multiplexing doesn't require any changes in code. Push technology require some changes in .htaccess files, but these changes should be transparent to HTTP 1.1.
> 
> Whatever - both HTTP/2 and newest PHP7.x requres less resources (i.a. server memory!) than HTTP 1.1 and PHP 5.x
> I've created new doc about Apache2 caching config. See /docs/system/2.README.server.md
> 
> 4) PHP 7.x
> 
> I've changed PHP version to 7.1, because I tested this version on my devel machine and next on OC UK for couple of months. Then PHP 7.2 was not stabile version. Now I started test of PHP 7.2, but we have some incompatibilities in the code (see #1376)

**Comment by andrixnet** [comment]
1. So those parameters for mpm_event are the ones that come with your distro by default, or are they optimized for that memory situation and the site(s) hosted?

At this time I am using mod_php.

2. It's a TODO and will let you know when we implement it. 
AFAIK the site should respond both http and https for some apps that call OKAPI, right?

3. Thanks. I'll look them over.

4. upgrading PHP is on our TODO list for 2018.

**Comment by kojoty** [comment]
@andrixnet, please reopen it if this is still an issue, Thanks.
