### ISSUE TITLE
Adaptation OC PL code to Opencaching UK

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#790]
This is a technical issue - joining all commits related to new OC UK node.

**Comment by andrixnet** [comment]
Please take this https://wiki.opencaching.eu/index.php/Cache_types into consideration if there are any adaptations needed for cache_types. AFAIK OCUK had "educache" type. If so, please make the adaptation such that "educache" gets type 17 as suggested.

**Comment by deg-pl** [comment]
@andrixnet OC UK team decided to convert educache to virtual cache.

**Comment by deg-pl** [comment]
@wrygiel please add https://opencache.uk/post-commit.php to post commit server list on Github

**Comment by andrixnet** [comment]
@deg-pl there is a problem (I don't remember if I got to report it) : someone published virtual cache (as alternative to earthcache on gc.com) and it got transformed into unkown after submission. 
http://www.opencaching.ro/viewcache.php?wp=OR0172
http://www.opencaching.ro/viewcache.php?wp=OR0170

I checked just now: I can't hide a virtual. While filling the form I forgot some fields, and even the error taking me back to the form already transforms virtual into unknown. 

You have my settings file, according to it, virtual cache type is allowed.

**Comment by andrixnet** [comment]
Note: translation of geopath (and others is a work in progress. should be done by the end of the weekend)

**Comment by wrygiel** [comment]
> @wrygiel please add https://opencache.uk/post-commit.php to post commit server list on Github

Done!

**Comment by andrixnet** [comment]
see https://github.com/opencaching/opencaching-pl/issues/663

**Comment by andrixnet** [comment]
opencache.uk back on wiki.opencaching.eu main page.

**Comment by andrixnet** [comment]
Links page needs updating : https://opencache.uk/articles.php?page=links

On homepage, static map is empty. 

On cache page, static map is empty.
Popup map loads for a moment, then shows the error like on the geopath pages.

On geopath pages : map does not load.
> This page didn't load Google Maps correctly. 

Same for Map v3

**Comment by andrixnet** [comment]
@deg-pl could you please add the UK attribute images to the opencaching-pl tree so that other nodes may also use them?

**Comment by andrixnet** [comment]
wiki.opencache.uk ERROR while uploading file : 

> Exception encountered, of type "LocalFileLockError"

**Comment by andrixnet** [comment]
Translation help, please (both for wiki and strings): what would you say is the best term for findind all caches in a GeoPath? 

1. gained (current version, sounds bad)
2. found (applies to caches, doesn't fit well for geopath)
3. acquired (google translate from polish to english)
4. completed (my recommendation)

**Comment by harrieklomp** [comment]
You have completed this GeoPath.
I recommend also "completed"

**Comment by deg-pl** [comment]
@andrixnet - could you check Wiki UK once again? 
I think "compleded" sounds good!
Please - don't announce OC UK. This site is still under developing and testing. So I'll update links page, but not now.

**Comment by andrixnet** [comment]
GeoPath wiki page in english - first complete draft: https://wiki.opencache.uk/index.php/GeoPath 
OCPL team: please verify that the functionalities are described properly.
OCUK team: please proof read for proper english.

**Comment by andrixnet** [comment]
I have used the 500 finds limit as is on OCPL. Considering the lower number of users and caches on OCUK, the brithis team should decide on a limit. (even 0 like OCNL). This is the only dependency I left (not knowing what will it be) but it can be easily changed.

**Comment by andrixnet** [comment]
@wloczynutka do you have a SVG source for the geopath type icons?

**Comment by andrixnet** [comment]
OpenChecker wiki page in english - first complete draft: https://wiki.opencache.uk/index.php/OpenChecker

Note: I used the brief help on the OpenChecker page to create this wiki page. Perhaps that help can now be replaced with a link to the wiki. 

OCUK team: please proof read for proper english.
OCPL team: I could not find any page on PL wiki about openchecker or OpenSprawdzacz. Perhaps you can reverse translate this wiki page into your wiki.

**Comment by andrixnet** [comment]
See https://github.com/opencaching/opencaching-pl/issues/796

**Comment by andrixnet** [comment]
@deg-pl notify c:geo developers about new OCUK site when it is up and production ready.
@wrygiel does OKAPI need some changes, now that OCUK has switched to OCPL-current?

**Comment by deg-pl** [comment]
@andrixnet @wrygiel Just a moment. OKAPI at OC UK is not ready yet!

**Comment by andrixnet** [comment]
No rush. I'm just pointing out various details and dependencies, in case one of them gets forgotten. :-)

**Comment by wloczynutka** [comment]
geopath map issue on ocuk is conected with google restrictions for new sites. Now they require key.  ocpl, ocnl and ocro are old sites, and google do not require key. ocuk is new site and they require the key.

https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

maybe other map issues have the same problem.

@andrixnet geopath icons, Nope. Why?

**Comment by wrygiel** [comment]
> does OKAPI need some changes, now that OCUK has switched to OCPL-current?

I think not, it only needs the upgrade script to run once. (BTW, I will be offline between November 4th and December 1st.)

**Comment by deg-pl** [comment]
@wrygiel We MUST change okapi/okapi/services/attrs/attribute-definitions.xml !
Also functions get_normalized_site_name(), get_allowed_base_urls()
and okapi/etc/installations.xml

**Comment by andrixnet** [comment]
OCUK has different attribute set?

**Comment by andrixnet** [comment]
About API keys: at OCRO I created an API key (at the time) and it is configured in settings.inc.php.
Does it require a different key, or the same kind? If so, someone at OCUK should get such a key.

@wloczynutka actually I am interested in all available SVG sources for all icons in the OC site, both for documentation purposes and for better results on printed materials. 
being on topic with geopaths, I asked specifically for those. 
Perhaps in the future we may identify identical or very similar graphics files in SVG format, that we can then transform to become the theme source.

**Comment by deg-pl** [comment]
First of all - OC UK has no A-mapping.

Google API Key in OC PL code is not used for some API scripts :(

**Comment by wrygiel** [comment]
> get_normalized_site_name(), get_allowed_base_urls()

You mean changing the functions' bodies? Upgrading `okapi_settings.php` should be enough, I think?

**Comment by deg-pl** [comment]
No. Because OC UK has another domain - opencache.uk not opencaching.something

**Comment by wrygiel** [comment]
Ah, yes. Forgot about the domain change...

**Comment by wrygiel** [comment]
BTW, have you tried contacting the registrant of the `opencaching.uk` domain? (opencaching.org.uk, but without the org)

**Comment by andrixnet** [comment]
I wanted to edit attribute-definitions.xml (OKAPI) but without knowing the contents of the cache_attrib table I cannot be sure that my edits are 100% correct, only that they would correspond to the best known superset of OCPL, OCNL, OCRO so far. Please advise.

**Comment by deg-pl** [comment]
Oh great!
Here is list of attributes at OC UK:
[cache_attrib.zip](https://github.com/opencaching/opencaching-pl/files/564392/cache_attrib.zip)

**Comment by wrygiel** [comment]
This also can be useful:

http://opencache.uk/okapi/devel/attrlist

On Tue, Nov 1, 2016 at 4:42 PM, Grzegorz Deja - deg
<notifications@github.com> wrote:
> Oh great!
> Here is list of attributes at OC UK:
> cache_attrib.zip
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Like I said before, I never repeat myself.
http://rygielski.net/

**Comment by andrixnet** [comment]
Solved OKAPI attribute definitions here: https://github.com/opencaching/okapi/pull/444

**Comment by andrixnet** [comment]
More attribute ID overlaps must be solved according to https://github.com/opencaching/opencaching-pl/issues/806

This is not a complete list, but the ones required for now, some critical.

**Comment by andrixnet** [comment]
Please add shortcut-icon for wiki.opencache.uk

**Comment by andrixnet** [comment]
Attributes solved in https://github.com/opencaching/okapi/pull/444

**Comment by andrixnet** [comment]
More OKAPI definitions sovled in https://github.com/opencaching/okapi/pull/447

**Comment by deg-pl** [comment]
For now I think code is ready, so I close this issue.
Thanks for help!
