### ISSUE TITLE
My routes always uses Poland map

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#796]
When I open the "My routes" page and click on "Set a new route", I am shown the Google Map of Poland. This is regardless of the map center coordinates for homepage static map or for map v3 page.

Verified on OCRO, OCNL, OCUK

See:
http://www.opencaching.ro/myroutes_add_map2.php
http://www.opencaching.nl/myroutes_add_map2.php
http://www.opencache.uk/myroutes_add_map2.php
![my_routes_map](https://cloud.githubusercontent.com/assets/3382777/19835666/c4a72bd4-9e9e-11e6-82be-e938ea43427e.png)

Note: please add "Component_My_routes" to issue Lables on github.

**Comment by kojoty** [comment]
it seems it is fixed now. If not please reopen. Before please check if vars:

$main_page_map_center_lat = 52.13;
$main_page_map_center_lon = 19.20;
$main_page_map_zoom = 5;

are set to your coords. THX.
