### ISSUE TITLE
User object defect

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#809]
Viewing profile of non-existent user (i.e. https://opencaching.pl/viewprofile.php/?userid=10000000) generates blank page and error:

> PHP Catchable fatal error:  Argument 1 passed to lib\\Objects\\User\\User::setUserFieldsByUsedDbRow() must be of the type array, boolean given, called in /srv/ocpl/lib/Objects/User/User.php on line 97 and defined in /srv/ocpl/lib/Objects/User/User.php on line 205

**Comment by kojoty** [comment]
seems to be fixed now...

**Comment by deg-pl** [comment]
@kojoty I've checked https://opencaching.pl/viewprofile.php/?userid=10000000 and this page looks 'a little bit different' ;). Please - check it.
But you're right - now php doesn't generate error.

**Comment by kojoty** [comment]
@deg-pl, 
the problem is in "/" in url:
https://opencaching.pl/viewprofile.php/?userid=10000000
check this
https://opencaching.pl/viewprofile.php?userid=10000000
and this
https://opencaching.pl/index.php/
