### ISSUE TITLE
Support for touch screen devices

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#818]
From forum (https://forum.opencaching.pl/viewtopic.php?p=135579#p135579):

> Mam laptopa z dotykowym ekranem i w przypadku map google, osm, jakdojade.pl itp. mogę mapę przesuwać palcem po ekranie oraz przybliżać/oddalać dwoma palcami. Jest to, jak dla mnie, bardzo dobre rozwiązanie, działa przy otworzeniu mapy na telefonie, niestety na laptopie nie działa. Czy jest możliwość wprowadzenia takiej funkcji?
> Edit:
> O dziwo w przeglądarce Edge to działa, na Chrome już nie.

**Comment by kojoty** [comment]
it seems to not be an issue anymore - if anyone disagree please reopen
