### ISSUE TITLE
Charts in statistics don't work

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#822]
Pages Statistics -> Number of finds and Statistics -> Maintenance of caches have buttons "Line" and "Bar" - probably to generate charts. But both of them don't work.

**Comment by harrieklomp** [comment]
I believe this happened after updating jgraph.

**Comment by deg-pl** [comment]
I don't think so. There's no action related with there buttons - see  opencaching-pl/tpl/stdstyle/articles/mypositionandcharts.php

**Comment by deg-pl** [comment]
I've upgraded jQuery and jQueryUI and now it works.
