### ISSUE TITLE
Some problems with new MySQL

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#823]
I very much appreciate the help i get from you all, but after the MySQL upgrade i get some errors and hope we can solve this somehow with your help.

Send a mail to user via profile page results in the next error/message.
+++ PDO Error +++ 

+++ Debug: Query: INSERT INTO `email_user`

                              SET `ipaddress`=? , `date_generated`=NOW(), `date_sent`='0',

                                  `from_user_id`= ? , `from_email`=?, `to_user_id`=?,

                                  `to_email`=?, `mail_subject`=?, `mail_text`=?, `send_emailaddress`=?

+++ Ex_Code: 22007

+++ Ex_Msg: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0' for column 'date_sent' at row 1

+++ Ex_Trace:

#0 /var/www/www.opencaching.nl/Utils/Database/XDb.php(117): PDOStatement->execute(Array)

#1 /var/www/www.opencaching.nl/mailto.php(90): Utils\Database\XDb::xSql('INSERT INTO `em...', '84.195.36.55', 298, 'grenspalen_nl-d...', '3', 'harrie@harriekl...', '[opencaching] E...', 'Hallo harrieklo...', '1')

#2 {main}

Another error message is when someone (when i read the message) edit his log.
+++ PDO Error +++ 

+++ Debug: Query: UPDATE `caches` SET `last_found`=?, `founds`=?, `notfounds`=?, `notes`=? WHERE `cache_id`=?

+++ Ex_Code: 22007

+++ Ex_Msg: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'NULL' for column 'last_found' at row 1

+++ Ex_Trace:

#0 /var/www/www.opencaching.nl/Utils/Database/XDb.php(117): PDOStatement->execute(Array)

#1 /var/www/www.opencaching.nl/editlog.php(381): Utils\Database\XDb::xSql('UPDATE `caches`...', 'NULL', '0', '1', '0', '5580')

#2 {main}

**Comment by harrieklomp** [comment]
Looks like we also can not welcome new users.

+++ PDO Error +++ 

+++ Debug: Query: INSERT INTO `user` ( `user_id`, `username`, `password`, `email`, `latitude`,

                                          `longitude`, `last_modified`, `login_faults`, `login_id`, `is_active_flag`,

                                          `was_loggedin`, `country`, `date_created`,

                                          `uuid`, `activation_code`, `node`, `rules_confirmed` )

                    VALUES ('', ?, ?, ?, NULL, NULL, NOW(), '0', '0', '0', '0', ?, NOW(), ?, ?, ?, ?)

+++ Ex_Code: 22007

+++ Ex_Msg: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'last_login' at row 1

+++ Ex_Trace:

#0 /var/www/www.opencaching.nl/Utils/Database/XDb.php(117): PDOStatement->execute(Array)

#1 /var/www/www.opencaching.nl/register.php(107): Utils\Database\XDb::xSql('INSERT INTO `us...', 'Joyddee', '682a3851dfe4eab...', 'jorritbonnema@l...', 'NL', '0A623219-9E74-1...', 'F0066C9E8A019', 14, 1)

#2 {main}

**Comment by harrieklomp** [comment]
Pictures cannot be place somehow.

+++ PDO Error +++ 

+++ Debug: Query: INSERT INTO pictures

                                (`uuid`, `url`, `last_modified`, `title`, `description`, `desc_html`,

                                 `date_created`, `last_url_check`, `object_id`, `object_type`, `user_id`,

                                 `local`,`spoiler`,`display`,`node`,`seq`)

                            VALUES (?, ?, NOW(), ?, '', 0, NOW(), NOW(),?, ?,

                                    ?, 1, ?, ?, ?, ?)

+++ Ex_Code: 22007

+++ Ex_Msg: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'thumb_last_generated' at row 1

+++ Ex_Trace:

#0 /var/www/www.opencaching.nl/Utils/Database/XDb.php(117): PDOStatement->execute(Array)

#1 /var/www/www.opencaching.nl/newpic.php(191): Utils\Database\XDb::xSql('INSERT INTO pic...', 'D8596B64-1968-5...', 'http://www.open...', 'Grenspaal 228_0...', '4446', '1', 4271, '0', '1', 14, '1')

#2 {main}

**Comment by deg-pl** [comment]
Look at /etc/mysql/* (with subdirectories)
Search sql-mode="(...)S,NO_ZERO_IN_DATE,NO_ZERO_DATE,(...)"
remove NO_ZERO_IN_DATE,NO_ZERO_DATE and restart MySQL.

**Comment by deg-pl** [comment]
At OC PL we have /etc/mysql/mysql.conf.d/mysqld_set_modes.cnf :

> [mysqld]
> sql-mode=""

DISABLE/REMOVE ALSO "ONLY_FULL_GROUP_BY"!!!

**Comment by andrixnet** [comment]
will handle it shortly

**Comment by harrieklomp** [comment]
Yesss. that works :+1: 
Thanks @deg-pl and @andrixnet

**Comment by andrixnet** [comment]
By the time I managed to squeeze a bit of time @ work to look into it, @harrieklomp managed to correct the problem. :-) Bravo! 

Note: MySQL has traditionally behaved in a more relaxed way (compared to strict SQL standards), allowing more leeway in the use of the language, values, conversions, etc.

Since MySQL has been taken over by Oracle Corp., they changed the direction in which development goes and some of the changes in 5.6 or 5.7 are default global settings that disable various traditional MySQL behaviours. This makes it more strict and more similar to OracleDB or MSSQL behaviour. 

MariaDB is a fork of MySQL created by some of the original developers of MySQL, mostly because they feared how Oracle will handle the future of MySQL as an open source project. Oracle's track record in past involvements in open-source isn't good. One example is how they killed OpenSolaris.
I haven't followed MariaDB evolution enough to know how they changed defaults across major versions, @deg-pl do you know more? How is the `sql-mode` on OCUK compared to the default?

**Comment by deg-pl** [comment]
@andrixnet These facts were the reason why I chose a MariaDB on OC UK. More information you can easily find on MariaDB pages.

On OC UK I also set sql-mode to "".

**Comment by andrixnet** [comment]
https://mariadb.com/kb/en/mariadb/sql_mode/ :-)
