### ISSUE TITLE
Volunteer requirements = configurable

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#824]
Make volunteer cacher criteria as configuration variables instead of hardcoded parameters.

**Comment by kojoty** [comment]
@andrixnet - is that what you wanted to get?
See /Config/guides file.

Please reopen if there is anythings more to do.

**Comment by harrieklomp** [comment]
Sorry that i reopen this issue.

Should translation files not show the the "set value"?
Now it is hard coded "20" in all translations.

**Comment by kojoty** [comment]
I hope now it can be marked as done
