### ISSUE TITLE
Dynamic loading of logs depends on scrollbar

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#825]
On very large screens (and at least some OCUK members have such), the cache page does not load any logs because there is no vertical scrollbar.

How to reproduce on regular screens: 
- look for a cache that has small description
- use browser zoom in/out controls to zoom out as much as possible.
- open that cache page again. 

If you can manage to have it displayed 100% in the browser window, then no logs are loaded. 
Since there is no scroll bar and no scrolling event, dynamic loading of logs is not triggered. 
Page shows no logs.

**Comment by deg-pl** [comment]
See https://youtu.be/WqSi8qDhC4w

**Comment by mzylowski** [comment]
Hmmm, I tried to reproduce this today but without success. 
Is this still an issue?

**Comment by rapotek** [comment]
It shouldn't be an issue any more, I home. I tried to fix it in PR #1601, but forgot to mention this issue in PR.

**Comment by mzylowski** [comment]
So fixed via #1601.
@andrixnet please reopen if problem persists.
