### ISSUE TITLE
GPX files

### ISSUE THREAD

**Issue by Amberel** [opencaching/opencaching-pl#826]
The cache pages contained in GPX files (GPX and GPX_GC downloads) are very different to the pages online. They have lost the formatting, links to images etc. They used to work OK on the very old version of the web site that was running on OCUK until recently, but not on the current version.

**Comment by Amberel** [comment]
I see this has no other comments. I'm happy to try to help on this. I am a programmer, and have some small knowledge of GPX file structure. But I have no experience of PHP (my languages are C and Pascal), or of working in a collaborative environment, so would need some guidance in order to not cause more problems than I solve.

**Comment by andrixnet** [comment]
@Amberel please take a look at https://github.com/opencaching/opencaching-pl/pull/931
After it is merged, please retest your problem.

**Comment by andrixnet** [comment]
@Amberel note that the OCUK attribute overhaul is not yet implemented. I will tend to it next week.

**Comment by kojoty** [comment]
is it still an issue? If yes please reopen.

**Comment by andrixnet** [comment]
Will repopen later, as I get to it. It needs more work.
