### ISSUE TITLE
About and History pages hardcoded in Polish

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#827]
Some informational pages, with mostly static content, are hardcoded in polish, regardless of the display language. 
- [ ] About page /articles.php?page=impressum
- [ ] History OC page /articles.php?page=history

Definitely related to https://github.com/opencaching/opencaching-pl/issues/299
Until #299 is implemented, perhaps a quick fix can be implemented.

**Comment by harrieklomp** [comment]
There should be two pages.
A common (impressum) page about opencaching itself. Translated in different languages.
A page about the node itself. (history)

**Comment by deg-pl** [comment]
This issue is a duplicate of #196
