### ISSUE TITLE
OC PL exceeded Google Maps API Limit

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#830]
New Google pricing plan (https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update) has strict rules - we have 25 000 Google StaticMap API for free. Every 1000 requests are charged for 0,50 USD (or is dislplayed JS error). Yesterday we exceeded this limit (c.a. 27 000 request) and Google for about two hours disabled maps to OC PL.

My idea to resolve this problem is change all default maps to OpenStreetMap - especially on viewcache.php and main page. There are plenty small maps, which now use our Google Maps API limit. Google Map should be avaible only via Mapv3.

@kojoty has also another idea.

Problem is critical because our users can't use OC PL in certain hours.

**Comment by kojoty** [comment]
@deg-pl can you describe the idea how to use OSM as a static map provider? I afraid I don't know free service like that with higher quota than Google. Alternatively we can generate our own static maps based on OSM tiles but I afraid it needs significant work to make it run...

**Comment by miklobit** [comment]
Consider this simple script : https://github.com/dfacts/staticmaplite : osm based static map, with markers, and caching

**Comment by kojoty** [comment]
> Consider this simple script : https://github.com/dfacts/staticmaplite : osm based static map, with markers, and caching

it seems it would be a good solution...

**Comment by andrixnet** [comment]
Does it allow caching of map image? 
(I believe Google didn't allow it). 

AFAIK
- Home page static map doesn't change much, if any, it is fixed in settings.inc.php
- cache static map changes only with coordinate change

**Comment by miklobit** [comment]
As first step - static map on viewcache.php  changed to local script.  I think we should also consider changing  zoom (8->9, with   param $config['maps']['cache_page_map']['zoom'] in lib/settings.inc.php ) because at zoom 8  OSM  has not enough labels to be readable.

**Comment by kojoty** [comment]
@miklobit: is OSM logo necessary because of some licence requirement?

**Comment by miklobit** [comment]
Logo or even better  "(c) openstreetmap contributors" text  ( according to guidelines: http://www.openstreetmap.org/copyright ).

**Comment by deg-pl** [comment]
With $config['maps']['cache_page_map']['zoom'] = 9; maps look very good.
Changed on OC PL and OC UK nodes.
Thanks @miklobit

**Comment by miklobit** [comment]
@deg-pl   prev.  used parameter  $config['maps']['cache_page_map']['layer'] make sense only for google so  please add new $config['maps']['cache_page_map']['source'] = 'mapnik' to  current settings.inc.php and then i will make script parameter 'maptype' variable . We can try another osm render styles then.

**Comment by andrixnet** [comment]
![ocpl-cache-map](https://cloud.githubusercontent.com/assets/3382777/20134691/0acc66c8-a675-11e6-9b72-713480271911.png)
The "Openstreetmap" text renders oddly and partially overlaps the magnifier icon.
Seen on OCPL and OCUK

**Comment by miklobit** [comment]
This logo comes with oryginal script. I will change this to small text at the bottom right corner.

**Comment by andrixnet** [comment]
I've changed $config['maps']['cache_page_map']['zoom'] on OCRO in settings.inc.php, ranges 6 to 14, I see no difference in cache static map (tested with new cache each time, to generate a different static map)

**Comment by miklobit** [comment]
@andrixnet  please check url generated in html source of  viewcache.php for certain cache.  Is zoom parameter set to desired value ? If so  copy url and test  staticmap.php alone with this url. It should lokks like f.e : http://opencaching.pl/lib/staticmap.php?center=50.821333,19.112583&zoom=9&size=170x170&maptype=mapnik&markers=50.821333,19.112583,mark-small-blue

**Comment by miklobit** [comment]
Changes to static map: 
1. OSM logo replaced with attribution text.
2. Added $config['maps']['cache_page_map']['source'] parameter to customize osm static map.
Available sources (default =  'mapnik'): 
  'mapnik' ( example: http://opencaching.pl/lib/staticmap.php?center=50.097850,18.548517&zoom=9&size=170x170&maptype=mapnik&markers=50.097850,18.548517,mark-small-blue )
 'sterrain' (  example: http://opencaching.pl/lib/staticmap.php?center=50.097850,18.548517&zoom=8&size=170x170&maptype=sterrain&markers=50.097850,18.548517,mark-small-blue )
 'stoner' (  example: http://opencaching.pl/lib/staticmap.php?center=50.097850,18.548517&zoom=8&size=170x170&maptype=stoner&markers=50.097850,18.548517,mark-small-blue )
 'cycle' (  example: http://opencaching.pl/lib/staticmap.php?center=50.097850,18.548517&zoom=8&size=170x170&maptype=cycle&markers=50.097850,18.548517,mark-small-blue )

Stamen terrain style at zoom 8 looks very good.  This tiles  are served for free and if you will select it, please consider donation https://stamen.com/opensource/#donate

**Comment by deg-pl** [comment]
OC PL generates now 17-22 000+ Google Static Map API request per day. It is better (was up to 27k), but we are still dangerously close to 25k request / day limit.

**Comment by miklobit** [comment]
It seems the majority of staticapi workload comes from myneighborhood.php and index.php. As i see  , both pages generates multiply api request (with the same url each !) for each page request. If google ticks counter for each such request even if url and referer are the same , we have  the obvious guilty...  BTW main page requires only ONE static image per country. I will try to implement OSM static map for both pages.

**Comment by deg-pl** [comment]
Our users are very satisfied with map changes!
See https://forum.opencaching.pl/viewtopic.php?p=135630#p135630 and next

**Comment by deg-pl** [comment]
@miklobit Jak tam postępy? Warto byłoby to zrobić przed wiosennym boomem. Użytkownicy bardzo dobrze ocenili zmianę z Googla na OSM i sami zaproponowali, by pozostałe mapy też były OSM.

**Comment by miklobit** [comment]
OK. W tym tygodniu będę miał chwilę to siądę do tego :-)

**Comment by deg-pl** [comment]
We still have a BIG problem...
![tmp](https://cloud.githubusercontent.com/assets/13884863/24922845/fe36c86a-1eef-11e7-9ce7-dbbe5a4270a1.png)
Now is april... not a high season.

**Comment by deg-pl** [comment]
@miklobit jesteś w stanie jeszcze coś podziałać? Mamy koniec kwietnia i wykorzystanie GoogleAPI dochodzące do 24k (wczoraj). Dałbyś radę coś z tego ugryźć:
- Moja okolica - 1,5k odsłon dziennie
- Cachemap v3 - tu chyba wyświetlają się mapy google domyślnie, póki tego nie zmienimy. Wszyscy nowi userzy korzystają z google, dopóki nie wpadną, że mogą zmienić. Może trzeba byłoby przestawić default na OSM? Zaryzykowałbym nawet i wszystkim userom zmienił mapę na OSM. Jeśli komuś to będzie przeszkadzało, to jednym kliknięciem zmieni, jeśli nie - zyskujemy. Mapa v3 ma ok 1k odsłon dziennie.
- Cachemap v2 - może to najwyższy czas wywalić tego starocia? W każdym razie jest dobry powód (w długi weekend pewnie mapy siądą i powód będzie jeszcze lepszy ;) ). Mało, bo ok. 60-70 odsłon dziennie, ale powody do likwidacji są liczne ;)
- Geościeżki - tam są tylko mapy Google. Około 200 odsłon dziennie głównej strony GŚ + odsłony na poszczególnych GŚ

Przy takim wykorzystaniu API nie mamy szans przeżyć sezonu :(

**Comment by miklobit** [comment]
Na której w/w wartości jest błąd ? Limit dla Web API to 25k/dzień a napisałeś, że moja okolica + mapa v3 + pozostałe to w sumie ~3k/dzień. ?

**Comment by deg-pl** [comment]
@miklobit Gdy mi podrzucisz swój e-mail dodam Cię do konsoli Google API (i Google Analytics jeśli jeszcze nie masz) - pooglądasz sobie. Ja teraz niestety mam zawodowe urwanie głowy i ten stan jeszcze trochę potrwa.

**Comment by kojoty** [comment]
@deg, @miklobit, 

Chłopaki, tak BTW (apropos apeli o używanie OSM itp): jesteście pewni, że przełączanie mapyv3 na OSM coś daje? Mnie się zdaje, że oni nie kasują nas "za kafelek mapy google" ale za "używanie API", a API używamy niezależnie jakie kafelki tam wyświetlamy. 

Twierdzę tak na podstawie dwóch faktów:
A/ https://developers.google.com/maps/faq#usage_mapload - ja to rozumiem tak, że dla JS API liczy się pojedyncze użycie API, a później można sobie skrolować, przełączać mapę (źródło kafelków), i co tam kto lubi 

B/ na moim dev-setupie mam własny, prywatny klucz do map i mapę ustawioną na OSM i... każde wyświetlenie strony z mapą generuje mi "+1" w tej ichniej konsoli od podglądania zużycia free-quoty!

(oczywiście to nie dotyczy static-maps - tu nasze odejście od używana Google API jest w pełni zdaje się skuteczne - mówię  jedynie o "mapiev3")

Wnioski (niezbyt radosne): nic z tym nie zrobimy i trzeba bedzie albo płacić, albo zaimplementować inne maps-api na stronie (na szczęście są "jakieś" alternatywy np. http://leafletjs.com/).

Co uważacie?

**Comment by deg-pl** [comment]
@kojoty - po przeczytaniu tekstu z linka który podesłałeś mam wrażenie, że cachemapv3 kasuje nas jako JS API (myślałem, że zarówno JS API jak i Static Map API). JS API mamy na niskim poziomie (około 2000/dobę). To gdzie generujemy tyle Static Mam API? Na stronach keszy też odpalają się kontrolki Google, więc powinno zliczać do limitu JS API. Podobnie w Geościeżkach. Zostaje... Moja okolica. Ale przecież 1500 odsłon mojej okolicy nie może generować 25000 Static Map API!

PS: U nas stosunek JS API / Static Map API wynosi 12%, podczas gdy na OC UK wynosi 60%! Dziwne. API Key jest zabezpieczony tak, że obsługuje tylko ruch z refererem opencaching.pl

**Comment by deg-pl** [comment]
Wykonałem test - wyłączyłem sobie na devie Google Static Map API i po przeklikaniu gdzie tylko się dało - przestała działać chyba wyłącznie Moja okolica. Reszta map tak  @kojoty pisały - ciągnie z JS API. Pozostaje otwarte pytanie - co w takim razie zżera nam Static Map API? 1200-1500 odsłon dziennie Mojej okolicy??

Gdyby ten problem rozwiązać, to być może żadnego innego nie trzeba ;)
(@kojoty - jeśli przeczytałeś mój poprzedni komentarz tylko w mailu, to przeczytaj go na githubie, bo wprowadziłem spore edycje po jego pierwszym wysłaniu)

**Comment by kojoty** [comment]
@deg, już wiem odpowiedź brzmi: **moja okolica**

każde wyswietlenie (a moja okolica cieszy się sporą popularnością, bo ma ponad 1k wyswietleń dziennie wg GA) generuje coś koło kilkunastu mapek statycznych :) bo kazde podswietlenie balonika to osobna mapka :) - nie zauważyłem tego wcześniej - i to jest nasz "ruch".

Zmiana w "mojej okolicy" np. nie podswietlanie balonika da nam zejscie do poziomu 2-3 tysiecy wyswietlen mapy statycznej...

Powiem tak, uff, jesteśmy uratowani (po raz kolejny i na razie).

**Comment by deg-pl** [comment]
O balonikach nie miałem pojęcia. A gdyby w to miejsce dać OSM, nawet bez bajeru z balonikami - wtedy dotyczy nas tylko JS API, a tu mamy BARDZO daleko do limitu.

Jeśli bajer z balonikami jest tak zasobożerny, to może nie robić go nawet na OSM?

**Comment by kojoty** [comment]
mam wrażenie, że wyłączenie tej "balonikozy" załatwia nam sprawę - nawet nie trzeba przechodzić na OSM - jak my generujemy OSM - tam nie ma jakichś limitów?

**Comment by kojoty** [comment]
It seems that situation is under control and we can close this issue, am I right? If no reopen.
