### ISSUE TITLE
Some of log types have double "Delete" link (for OC Team)

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#831]
![tmp](https://cloud.githubusercontent.com/assets/13884863/20081853/69c7ea0e-a552-11e6-82d7-34aec59fd726.png)

**Comment by andrixnet** [comment]
I have encountered a similar bug when I helped OCNA after their migration of old OCPL code (same as OCUK generation) to a new server, earlier this year. 

There is faulty logic in that menu creation, regarding being own log or not, being admin or not, etc.
