### ISSUE TITLE
Link to CC license

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#835]
All OC content is published under Creative Commons license. Every node may use different license - for example:
OC PL - CC-BY-SA 3.0
OC NL - CC-BY-NC-SA 3.0
OC DE - CC-BY-NC-ND 3.0 DE
OC US - CC-BY-NC-SA 2.5
But... we don't inform our users and Internet society which license we use. Yes - often we have this info in "Terms" on Wiki, but we should have it on every OC page (for example - in footer).
More information about CC licenses: https://creativecommons.org/
Which license to chose? HTML generator: https://creativecommons.org/choose/

(see also at OC PL OC-Team forum - https://forum.opencaching.pl/viewtopic.php?f=71&t=8666)

**Comment by deg-pl** [comment]
@andrixnet @harrieklomp if you want to use this feature, please add $config['license_html'] to your settings.inc.php file. For example:

```
$config['license_html'] = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a>';
```

**Comment by harrieklomp** [comment]
Added this license in footer of OCNL
