### ISSUE TITLE
Change Normal -> Regular size and Quiz -> Puzzle cache type

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#853]
OC UK proposed to change EN translations of "Normal size" to "Regular size" and "Quiz cache" to "Puzzle cache".
What do you think about it?

**Comment by harrieklomp** [comment]
Should be okay.

**Comment by Amberel** [comment]
I think it would be better, and even more important to be consistent. I was involved in the translation, but I was doing it with no context for what I was translating, which made it rather awkward.

**Comment by harrieklomp** [comment]
Please keep in mind that translations/changes also has to be done in the database. Some parts of the code are still collecting data from database.

**Comment by harrieklomp** [comment]
For example on the search page. (this i have changed in DB of oc.nl)
![selectie_071](https://cloud.githubusercontent.com/assets/1060518/21959178/a52d1e00-dabf-11e6-98c3-645893108946.png)

**Comment by harrieklomp** [comment]
@Amberel Can you do it yourself or do i have to change it? This can be done in English translation file.

**Comment by deg-pl** [comment]
@harrieklomp - not only in translation file, but also we should change some data in database

**Comment by harrieklomp** [comment]
@Amberel @deg-pl  Changes are done in English translation file. Now each node has to change it in DB too (if they want ;-) )

**Comment by Amberel** [comment]
Sorry for the delay Harry, been away the last couple of days, will take a look at the database today

**Comment by deg-pl** [comment]
@harrieklomp could you prepare sql alter file?

**Comment by harrieklomp** [comment]
UPDATE `cache_size` SET `en` = 'Regular' WHERE `cache_size`.`id` = 4;

**Comment by deg-pl** [comment]
OC PL and OC UK already has "Regular", so it is not necessary to change DB.

BUT we should also change Quiz -> Puzzle in cache_type table (@harrieklomp)

**Comment by Amberel** [comment]
I checked ours this evening, and they were all already correct, i.e.

Micro, Small, Regular, Large, Very Large, No container

Unknown type, Traditional, Multicache, Virtual, Webcam, Event, Puzzle, Moving, Podcast cache, Own cache

Rgds, Andy

**Comment by harrieklomp** [comment]
UPDATE `cache_type` SET `en` = 'Puzzle cache' WHERE `cache_type`.`id` = 7;

**Comment by deg-pl** [comment]
@andrixnet Did you change cache_size and cache_type? Can we close this issue?
(OC PL and OC UK is ready)

**Comment by Amberel** [comment]
I have asked the person who initially raised this matter if they can check it again now. The problem wasn't just that the words used were not ideal, it was that different words were used in different places, indicating that the code uses different sources of data in different places.

**Comment by andrixnet** [comment]
OC RO updated.
Thank you.
