### ISSUE TITLE
Ignore find 3 caches before you can hide one policy (Requested by OCNA)

### ISSUE THREAD

**Issue by Mr-Yuck** [opencaching/opencaching-pl#866]
I stumbled on this with my Opencaching.uk account. We will let anyone hide a cache! :-) Before you get offended, our experience is that only long time, highly experienced Geocachers are interested in "alternative" Geocaching websites such as ourselves or Terracaching.com. We have found zero evidence of completely clueless newbies trying to hide a cache on our site. It just doesn't happen over here.

**Comment by andrixnet** [comment]
This is easily handled by a configuration directive: 
```
    //block register new cache before first find xx nuber caches value -1 off this feature
    //$NEED_FIND_LIMIT=10;
```
Just set this variable to -1

Also: 
```
    // Number of forst caches will be send to approve , disable 0, all caches max 999999999
    //$NEED_APPROVE_LIMIT = 3;
```
Set this to the maximum value to force all caches to be approved first.
