### ISSUE TITLE
Remove Openchecker when changing to traditional

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#873]
> Cześć
> Zastanawialiście się kiedyś czy można umieścić opensprawdzacz w skrzynce np. tradycyjnej?
> Odpowiedź brzmi tak: https://opencaching.pl/viewcache.php?cacheid=10356
> Skrzynka zarchiwizowana, ale nie chciałem robić bałaganu w tych na mapie. Można to zrobić w każdym typie skrzynki. Jeśli nie wiecie jak, mogę podesłać instrukcję na prv osobie, która się tym zajmie.
> Pozdrawiam Paweł

> pewnie był quiz, dodano opensprawdzacza, a później ktoś zmienił typ skrzynki.

Changing cache type of a multi/puzzle cache with Openchecker to traditional leaves the Openchecker active, though it makes no sense in the new scope.

**Comment by kojoty** [comment]
I hide openchecker at viewcache view for inappropriate cache types as part of my current works around viewcache.php - I've made complete refactoring of viewcache.php and I deliver it this week.

**Comment by kojoty** [comment]
Now openchecker is presented at viewcache page only if
$this->cacheType == self::TYPE_MOVING || self::TYPE_QUIZ || self::TYPE_OTHERTYPE;
what resolves this issue in my opinion.

**Comment by andrixnet** [comment]
Why not allow checker for multi ?

**Comment by kojoty** [comment]
Openchecker for multicache is also allowed :) now.
