### ISSUE TITLE
Make location of ocpl-update.sh configurable

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#874]
post-commit.php contains a hardcoded reference to /var/www/ocpl-update.sh as the update script for the site. 

This works fine when the site is hoted on a Linux server where root access is available to the OC admin.
Unfortunately the webhosting of OCNA is through a hosting company. Client user does not have permissions to write in /var/www

Also, in principle, having such a hardcoded reference is bad practice.

**Comment by andrixnet** [comment]
Fixed in https://github.com/opencaching/opencaching-pl/pull/1192

**Comment by mzylowski** [comment]
@andrixnet Issue will be closed automatically if you prepare right commit message (see: https://help.github.com/articles/closing-issues-using-keywords/).
If you want closing issues manually, please do it after merging fix to master, not when PR is submitting ;]
