### ISSUE TITLE
cache_size data definition and properties

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#876]
Cache size defines the size of the container for a cache. Each cache size is identified by a unique ID.

Properties:
- ID
- name (for referencing translations)
- base image icon
- actual (represents an actual size; eg false = no container, not specified)

**Comment by andrixnet** [comment]
Initial corrections done here: https://github.com/opencaching/opencaching-pl/projects/2
NANO and NOT_SPECIFIED cache sizes that already existed in the code as non-working and incomplete are now fully functional.

**Comment by andrixnet** [comment]
DOcumented at https://wiki.opencaching.eu/index.php/Cache_sizes

**Comment by andrixnet** [comment]
Documented at https://wiki.opencaching.eu/index.php/Cache_sizes
@kojoty plese take a look at the above link.

**Comment by andrixnet** [comment]
@harrieklomp @kojoty @deg-pl I have an important functional question (might have been partially discussed elsewhere, but needs clarifing here): 

there are several cache sizes. 
size_A is forbidden. 

The question is what to do in the following scenarios:
- new caches of size_A are NOT ALLOWED _(this is clear)_

- existing caches of size_A, when edited, what to do?
1. size_A is not allowed, automatically reassign the size upon submission of cache edit form (to whatever the first option is in the dropdown. (assume user does not change it, is unaware of it))
2. all caches of size_A, once it is forbidden, may be allowed to stay as such, when editing, other caches may not set size_A.
3. admin changes database and reassigns all caches of size_A to the closest available size. (assume site rules define the allowed sizes, conversion and give the admin this power)

if size_A is forbidden, but there are older caches of size_A, allow the following:
- search for caches with size_A ? (general search)
- search caches in my routes with size_A ? 

There is also the consideration expressed by some, that allowing users to see a searchable cache size, that is not allowed for new caches, creates discussions, raises questions and requests to allow that cache size to exist for new hides (even though OC rules do not allow it and it is deemed undesirable).

**Comment by kojoty** [comment]
My vision is simple and the same for sizes/types/etc.

A/ There is a wide super-set of some entries across the code common for all nodes
B/ Node define in settings subset of allowed-entries (entries which can be found at this node) 
C/ Node define in settings subset of forbidden-for-new-caches entries (entries are present, but can't be set for new caches)

Then everywhere (except new cache dialog) are presented entries form subset B and additionally on cache edit there is a check which prevent change any entry from subset B to any from subset C.

I hope this is clear.

**Comment by andrixnet** [comment]
Thank you. 
#
Then by this logic, if at some point in the past a cache could be set to sizeX, but today sizeX is no longer allowed for new caches, the following can be performed:
- search for caches of sizeX
- edit cache of sizeX retaining it's size
#
The following are NOT allowed:
- edit cache of any other size to sizeX
- create new cache of sizeX

So far I've implemented A/ and C/ for newcache. See https://github.com/andrixnet/opencaching-pl/tree/well_defined (geocache common, newcache, newcache.tpl). 

I do have some difficulty with the JS code. it works, but I am not entirely satisfied with the solution.

**Comment by following5** [comment]
This was implemented by #1837  and by earlier changes to editcache. Everything works new as proposed by @andrixnet and @kojoty.
