### ISSUE TITLE
Incorrect "ó" translation while export to ggz

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#892]
From Forum (https://forum.opencaching.pl/viewtopic.php?p=136758#p136758)

> Próbowałem wrzucić zestaw skrzynek w formacie GGZ do Garmina Montany 610.
> Ogólnie działa ale jest jeden mankament. Mianowicie litera "ó" jest zapisana jako ciąg "&amp;oacute;" i tak też niepoprawnie wyświetla się w odbiorniku. Są skrzynki, w których jest poprawnie, ale w dużej części jest problem z tą jedną literką.
> Podmiana znaków w wyeksportowanych plikach (a biorę np. całe województwo) to nie problem, ale potem trzeba chyba poprawić plik indeksowy, bo się te skrzynki nie pokazują w odbiorniku.
> Nie wiem jak jest wyświetlaniem tych kodów w innych odbiornikach ale w Montanie na najnowszym sofcie jest źle.
> Można liczyć na poprawkę eksportu?

**Comment by miklobit** [comment]
redirected to https://github.com/opencaching/okapi/issues/169

**Comment by wrygiel** [comment]
Coś mi się wydaje, że to bug w odbiorniku związany z brakującą obsługą encji. Oczywiście możemy ten bug spróbować poprawić po stronie serwera, dekodując encje do znaków unicode, ale jeśli chcemy tak robić, to funkcja `xmlescape` na pewno nie jest dobrym miejscem na to, no i przydałoby się dekodować wszystkie encje, a nie tylko jedną wybraną (są biblioteki do tego).

**Comment by wrygiel** [comment]
Z tego co widzę, w PHP jest do tego gotowa funkcja - [`html_entity_decode`](http://php.net/manual/en/function.html-entity-decode.php). Jeśli dobrze rozumiem problem, to należałoby przed zapisaniem HTMLa do bazy przelecieć go tą funkcją?

Można to robić również dynamicznie w miejscach gdzie pobieramy z bazy, ale to by było trochę nieoptymalne. Bo wtedy zamiast wywołać raz, wywoływać będziemy za każdym razem.

**Comment by miklobit** [comment]
Funkcja dekodowania html entity na znaki unicode  jest w tej chwili na pewno   poprawnie wywoływana w edytorze opisu bo  opis  kesza (który takie entity zawiera w bazie) po ponownym zapisaniu z powrotem jest już prawidłowo eksportowany.  Nie wiem natomiast ile keszy ma jeszcze w opisach znaki zapisane w taki sposób (mógłbym to sprawdzić gdybym miał dostęp do bazy produkcyjnej albo jej kopii). I ilu jeszcze innych znaków to dotyczy  - a wszytkie te entity będą taka samo błędnie  po raz drugi escape'wane przez okapi.  Więc oczywiście poprawka usuwa tylko skutek a nie przyczynę  (i to tylko dla jednego znaku).  Problem może być nie tylko w bazie OCPL więc ja bym zostawił to po stronie okapi rozszerzając to na wszystkie znaki.

**Comment by wrygiel** [comment]
Sorry, trochę za szybko odpowiedziałem. Faktycznie `html_entity_decode` się nie nadaje, bo umożliwi ataki XSS. Wprawdzie kod OC jest [mega dziurawy](http://opencaching.pl/viewcache.php?cacheid=10492) jeśli chodzi o XSS (jak zjedziesz na dół strony, to wykona się kod javascript, który kiedyś dodałem w komentarzu), ale i tak, nie ma co nowych dziur dodawać.

> wszytkie te entity będą taka samo błędnie po raz drugi escape'wane przez okapi

Ale to przecież nie jest błędne... OKAPI escapuje encje XMLowe, bo zamierza wpuścić HTML do pliku XML. Problem leży po stronie odbiorcy, który niby obsługuje HTML, ale jednak niektórych encji HTML nie zna. Prawdopodobnie ten sam plik importowany np. do c:geo wyświetla się poprawnie, prawda?

Czyli nie mówimy o problemie w OKAPI, a jedynie o pomocy dla odbiorników Garmina, które nie potrafią wyświetlić encji `&oacute;`. Jeśli faktycznie problem występuje tylko z tą jedną encją, to najłatwiej byłoby przelecieć wszystkie opisy skrzynek i zastąpić ją literą "ó" - jedno zapytanie SQL do bazy. Bo z tego co piszesz rozumiem, że nowy kod zapisujący do bazy drugi raz już `&oacute;` nie wstawi, tak?

**Comment by miklobit** [comment]
Zgadzam się że w Okapi ani w (bieżącej wersji) kodu OC nie ma problemu. Problem jest w garminie (do sprawdzenia których jeszcze encje nie potrafi poprawnie zamienić)  i w zawartości bazy OC.  Ustalimy co się jeszcze garminowi nie podoba i  podmienimy to w bazie OC
