### ISSUE TITLE
Files with execute bit ?

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#909]
There are many .php and other files with execute bit set, which, are not meant to be executables, nor are they shell scripts. 

Is this by design or a mishap?

**Comment by mzylowski** [comment]
Why it is related with OKAPI?

**Comment by andrixnet** [comment]
https://github.com/opencaching/okapi/issues/454

**Comment by mzylowski** [comment]
I still don't know why files related with opencaching-pl code affects OKAPI.

**Comment by andrixnet** [comment]
It's the other way around. oepncaching-pl contains OKAPI. 
While there are OKAPI files with exec bit, there are opencaching-pl files with exec bit.

**Comment by andrixnet** [comment]
Fixed in OKAPI https://github.com/opencaching/okapi/issues/454#event-998108005
Will proceed myself to fix the rest in opencaching-pl.

**Comment by andrixnet** [comment]
Solved in https://github.com/opencaching/opencaching-pl/pull/914
