### ISSUE TITLE
prepare new error_pages (403, 404 etc.) must be translatable.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/opencaching-pl#91]
```
Files in /error_pages are plain .html files hardcoded in polish. 


```

Original issue reported on code.google.com by `andrixnet` on 2 Apr 2014 at 1:01

**Comment by deg-pl** [comment]
@kojoty can we safetly remove error_pages directory?

**Comment by kojoty** [comment]
yes we can!

currently this is not used probably anywhere, our simpleRouter has its own error-page and it should be seen for 4** http codes, I think we should prepare something for 5** situations - another TODO...

**Comment by kojoty** [comment]
I'm going to remove error_pages dir and its content soon - and then I close this issue.
