### ISSUE TITLE
GPX: XML Parsing Error: not well-formed

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#917]
Please visit here: http://www.opencaching.ro/search.php?queryid=1465&startat=0 and export GPX file for all results. 

Try loading the GPX file into an XML parser. 
I tried in Firefox (plain parser), GSAK, GPSBABEL. 
Each give the following error: 
`XML Parsing Error: not well-formed`

Firefox shows this error: 
```
XML Parsing Error: not well-formed
Location: file:///E:/download/OC.gpx
Line Number 15, Column 47:                <desc>[LALEA] Baraj lacul Gole￿ti de la andrixnet, Traditional Cache (2/2)</desc>
----------------------------------------------^
```

A closer look at the generated file shows the header being properly generated : 
`<urlname>Opencaching.ro - Geocaching ├«n Rom├ónia</urlname> ` 
_(this is by an ASCII viewer)_

` ├«n ` = 20 **C3 AE** 6E 20
Properly shown as UTF-8 character  = **în**
This is the correct testcase.

=================================
`<groundspeak:name>[LALEA] Baraj lacul Gole┼ti</groundspeak:name>`
`e┼t` = 65 **C5** 74
Proper UTF-8 character would be = **eşt**
Correct byte sequence would be : 65 **C5 9F** 74 
Thus it is apparently an incomplete byte sequence. 

The problem goes on for the rest of the file.

**Comment by kojoty** [comment]
Hi @andrixnet,

few ideas at first sight:
- there wasn't any significant change in source code around gpx production so it not a bug in a code (probably)
- it seems that something is wrong with encoding of texts from DB - non-ascii chars are in different encoding
- it also seems that this is specific to ro node - I can't reproduce similar issue with my local dev-node
- I assume it works before - right?
so:
1. have you check if you have any warnings in apache error log - maybe we find some clue there - can you send me your error.log from today?
2. what is a encoding in your DB? - can you send me a dump with structure of table cache and cache-desc?
3. can you identify when it worked last time - maybe you upgraded software on server or something?

**Comment by andrixnet** [comment]
We've done a lot of content translation and proper localization in the recent past, so, let's say this time last year, we had a lot less such characters. 

Nothing in the error log. 
Only one thing appears for KML:  `PHP Notice:  Undefined variable: kmlDetailHead in lib/search.kml.inc.php on line 165` but it's not even GPX related.

Database is: ```CREATE DATABASE `oc_ro` /*!40100 DEFAULT CHARACTER SET utf8 */;```

Caches table (which contains the title, here at fault): 
```
DROP TABLE IF EXISTS `oc_ro`.`caches`;
CREATE TABLE `caches` (
  `cache_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `last_modified` datetime DEFAULT NULL,
  `okapi_syncbase` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `date_created` datetime DEFAULT NULL,
  `type` int(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `country` char(2) DEFAULT NULL,
  `date_hidden` datetime DEFAULT NULL,
  `founds` int(11) DEFAULT NULL,
  `notfounds` int(11) DEFAULT NULL,
  `notes` int(11) DEFAULT NULL,
  `images` int(11) DEFAULT NULL,
  `last_found` datetime DEFAULT NULL,
  `desc_languages` varchar(60) DEFAULT NULL,
  `size` int(11) DEFAULT NULL,
  `difficulty` int(11) DEFAULT NULL,
  `terrain` int(11) DEFAULT NULL,
  `uuid` varchar(36) DEFAULT NULL,
  `watcher` int(11) DEFAULT '0',
  `logpw` varchar(20) DEFAULT NULL,
  `picturescount` int(11) NOT NULL DEFAULT '0',
  `mp3count` int(11) NOT NULL DEFAULT '0',
  `search_time` double DEFAULT NULL,
  `way_length` double DEFAULT NULL,
  `wp_gc` varchar(7) DEFAULT NULL COMMENT 'Geocaching.com',
  `wp_nc` varchar(6) DEFAULT NULL COMMENT 'Navicache.com',
  `wp_ge` varchar(7) DEFAULT NULL COMMENT 'GPSGames.org',
  `wp_tc` varchar(7) DEFAULT NULL COMMENT 'TerraCaching.com',
  `wp_qc` varchar(10) DEFAULT NULL COMMENT 'QualityCaching.com',
  `wp_oc` varchar(7) DEFAULT NULL COMMENT 'OpenCaching',
  `default_desclang` char(2) NOT NULL,
  `date_activate` datetime DEFAULT NULL,
  `topratings` int(11) NOT NULL DEFAULT '0',
  `ignorer_count` int(11) DEFAULT NULL,
  `node` tinyint(4) NOT NULL DEFAULT '0',
  `votes` int(11) NOT NULL DEFAULT '0',
  `score` float(2,1) NOT NULL DEFAULT '0.0',
  `need_npa_recalc` tinyint(1) NOT NULL DEFAULT '1',
  `org_user_id` int(11) DEFAULT NULL COMMENT 'Origianl user_id, who created the geocache',
  PRIMARY KEY (`cache_id`),
  UNIQUE KEY `wp_oc` (`wp_oc`),
  KEY `date_created` (`date_created`),
  KEY `latitude` (`latitude`),
  KEY `country` (`country`),
  KEY `status` (`status`,`date_activate`),
  KEY `last_modified` (`last_modified`),
  KEY `score` (`score`),
  KEY `type` (`type`),
  KEY `size` (`size`),
  KEY `difficulty` (`difficulty`),
  KEY `terrain` (`terrain`),
  KEY `name` (`name`),
  KEY `votes` (`votes`),
  KEY `picturescount` (`picturescount`),
  KEY `user_id` (`user_id`),
  KEY `need_npa_recalc` (`need_npa_recalc`),
  KEY `okapi_syncbase` (`okapi_syncbase`),
  KEY `longitude` (`longitude`),
  KEY `caches_org_user_id` (`org_user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=421 DEFAULT CHARSET=utf8;
```

Server configuration has : `default-character-set = utf8` and
```
character_set_server = utf8
collation_server = utf8_general_ci
```

Server version: Apache/2.4.25
MySQL: 5.5.54-MariaDB
PHP 5.6.30

I only applied security updates against distro packages. So no major change at server level. I know for sure in 2015 worked, because I generated some GPX files then and they had such characters, though fewer. 

```'[LALEA2] Socoteala de la Piaţă',
'5B4C414C4541325D20536F636F7465616C61206465206C6120506961C5A3C483'
```
This is the contents of the name field for cache this cache http://www.opencaching.ro/viewcache.php?cacheid=61 which results in a bad GPX. I'll mail the GPX file separately, github won't take it.

The GPX contains at the end of the title 0xC5A3C4 followed by 0x20 [space] (0x83 is missing) in this example.

**Comment by andrixnet** [comment]
File export modules have changed at least in early 2016 due to this: 
https://github.com/opencaching/opencaching-pl/issues/359 
See also history of https://github.com/opencaching/opencaching-pl/commits/master/lib/search.wpt.inc.php which was broken until point 5 in #359 was solved.

Could this be related? 
https://github.com/opencaching/opencaching-pl/commit/5e5834a1259c69c834a85965ce303966f0161155

or this ?
https://github.com/opencaching/opencaching-pl/commit/8d35ccd429dd865be413ed77b0da8c86bf0c7d48

**Comment by kojoty** [comment]
Hi Andrei
Everything you wrote looks good - I still don't have any idea why it fails. Changes you mentioned are not a real change - this is only refactoring of the code - I moved function from one file to another.

Let's try to do one more experiment: 
- in gpx creation process temporary table is created and it seems that there is no charset settings. Can you try to set manually temporary table and check what is its collation and charset? Maybe we get something different than utf8.

**Comment by andrixnet** [comment]
I changed the create table statement and removed temporary (for testing). 

This is the create definition that was applied. 

```
DROP TABLE IF EXISTS `oc_ro`.`gpxcontent`;
CREATE TABLE `gpxcontent` (
  `distance` double DEFAULT NULL,
  `cache_id` int(11) NOT NULL DEFAULT '0',
  `cache_wp` varchar(7) DEFAULT NULL COMMENT 'OpenCaching',
  `status` int(11) DEFAULT NULL,
  `type` int(11) DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `cache_mod_cords_id` bigint(11) NOT NULL DEFAULT '0',
  `user_id` int(11) DEFAULT NULL,
  `votes` int(11) NOT NULL DEFAULT '0',
  `score` float(2,1) NOT NULL DEFAULT '0.0',
  `topratings` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

I looked at the table definition and at data content and cache name does not exist in this table. This is the only temporary table table I could find (in search.gpxgc.inc.php).

**Comment by kojoty** [comment]
@andrixnet,
you're right - it's not a temp. table - I replied from smartphone and I didn't realize that this temp table doesn't contain cache details like cache-name, but it could be replacement! 

search.gpx.inc.php code contains many str_replace function which is not safe for mulitbyte strings - maybe this is side effect of it.

Try to change str_replace [here](https://github.com/opencaching/opencaching-pl/blob/master/lib/search.gpx.inc.php#L414) to mb_ereg_replace and check if it helps...

**Comment by andrixnet** [comment]
After extensive trial and error, I found this in cleanuptext():
https://github.com/opencaching/opencaching-pl/blob/master/lib/search.gpxgc.inc.php#L830
`$str = preg_replace('/[[:cntrl:]]/', '', $str);`
str_replace seems to work with UTF-8, but preg_replace won't. 

If I comment it out, the title part goes through ok. 
But I still get errors in the attribute fields, when in romanian. 

A similar line in function xmlentities():
https://github.com/opencaching/opencaching-pl/blob/master/lib/search.gpxgc.inc.php#L797

**Comment by andrixnet** [comment]
I've put together xmlentities, plconvert and cleanup_text functions into common.inc.php, since they are used in several places.
One question: I've never used "my routes". The cleanup_text there is more elaborate but does not change regional characters. Should be the same (seems to generate a GPX as well), or should it stay different then the GPX exporting search page?

**Comment by andrixnet** [comment]
ocxm11.php seem to reimplement these same functions, but slightly different. I left it as is, isolated.

**Comment by andrixnet** [comment]
Most formats are now ready and consistent. 

Still to go: 
- KML
- GPX

(for these I will move the common sections into a different file, because more then the search.*.inc.php use them, plus GC common attributes need to be defined in GPX, etc)

**Comment by andrixnet** [comment]
FIXED in https://github.com/opencaching/opencaching-pl/pull/931
