### ISSUE TITLE
Cachetype "own cache" not default ON in the search page.

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#920]
When people start the searchpage at search.php there are standard settings like picture below.
![selectie_020](https://cloud.githubusercontent.com/assets/1060518/24134247/4fa5b6a0-0e03-11e7-90ef-97d674c89342.jpg)
This standard setting does not include the cachetype "Own cache" when performing a search. Should it be possible to include this cachetype when opening this page?

**Comment by deg-pl** [comment]
I think that current setting is OK.
Users use search page to generate GPX for GPS. When you go caching you usually don't want to search owncaches, because it is only cache type which you can find only after contact with cache owner.

**Comment by andrixnet** [comment]
@harrieklomp : what deg-pl says sounds logical. Think about it. Do you still want it set as default?
