### ISSUE TITLE
Cannot change cache type to virtual

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#921]
There was a problem creating virtual caches ( https://github.com/opencaching/opencaching-pl/issues/663 ) which was fixed. At that time I was able to edit a cache and change type to virtual. 

Now, as I am preparing some caches, I have several listings that I want to transform into virtuals. 
However, it does not work. I select virtual, I press save, cache type remains unchanged.

**Comment by harrieklomp** [comment]
It looks that only admin can change this.

**Comment by mzylowski** [comment]
It is not an issue for PL node. In opencaching.pl creating new virtual caches is blocked.
This should be considered if any fix for this issue will be proposed. Also if any refactoring for editcache.php will be prepared, there is a place for creating better cache-ban-node mechanism.

cc @kojoty

**Comment by andrixnet** [comment]
@mzylowski : is creating of new virtual blocked via ForbiddenCacheTypes or by other means? 

I understand the need to take this into account for OCPL, but I want to clarify: are there special rules in place (either code or by "Terms and conditions") for OCPL regarding virtual, or just a not permitted new cache type? 

See my project https://github.com/opencaching/opencaching-pl/projects/2 
A cache type if it is not allowed for a certain node, the following should apply (_please correct if necessary_):
1. cache type not available for selection for new caches
2. cache type for existing caches : 
- do not allow changing type (select disabled) for all users
- allow user to change to any other type (type disabled in select), but this means the first edit on the cache will also automatically change type. 
- allow user to change to any other type (but do not allow user to change other caches into forbidden type), prevents automatic type change when editing.
- allow only admin to change type (allow forbidden to change to non-forbidden, but do not allow the reverse)
_Each of these working variants under 2. must be discussed as some of them may be per node rule._

**IMO there are the following strategies to consider:** 
1. prevent owner to edit anything for a forbidden type. 
_IMO not a very good idea. Cache is frozen and requires admin for anything, like an attribute change (which does not significantly affect the listing). Also prevents archiving and requires admin intervention.
This complicates maintenance and site usage procedures._
2. coupled with 1. allow admin to edit a forbidden type.
3. allow owner to edit existing forbidden type, allow change type or retain type. 
4. prevent owner/admin to change any other cache into forbidden type.

From what I know so far of OC, it allows in principle the most [reasonable] control over a cache to it's owner. 
IMO variant 3+4 is optimal.

**Comment by deg-pl** [comment]
I think this issue was solved already.
On my devel server I can change any type of cache to virtual and from virtual to any other type.

If do you still has problem with this - please reopen.
