### ISSUE TITLE
Proper use of "Select one" in drop down lists

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#923]
Some time ago @harrieklomp asked of me to fix this: 
![17012364_1512014465493991_1667778073_n](https://cloud.githubusercontent.com/assets/3382777/24225217/f640e696-0f67-11e7-940c-9140d283d383.png)
By default, the "select one" is also selectable as a valid option. This is incorrect.

Here's another view for difficulty / terrain drop-down boxes: 
![select](https://cloud.githubusercontent.com/assets/3382777/24225251/20f2dc96-0f68-11e7-863c-278df514b7ae.png)

Affected pages and drop-down menus:
- [x] newcache page
- [x] cache type
- [x] cache size
- [x] region
- [x] difficulty
- [x] terrain

- [x] newwp page
- [x] waypoint type

**Comment by andrixnet** [comment]
waypoint type drop-down fixed in https://github.com/opencaching/opencaching-pl/pull/922

**Comment by andrixnet** [comment]
@kojoty please help me with region drop-down. This is generated by AJAX and is beyond me.

**Comment by kojoty** [comment]
@andrixnet, if you want to disable option "select smth" check the file: [ajaxGetRegionsByCountryCode.php](https://github.com/opencaching/opencaching-pl/blob/master/ajaxGetRegionsByCountryCode.php#L17) and a lines below - I don't have a time this week to make a deeper research around it - in my opinion new/edit cache is a next (after geopaths) module for complete refactoring.

**Comment by andrixnet** [comment]
Fixed in https://github.com/opencaching/opencaching-pl/pull/922
