### ISSUE TITLE
Hardcoded strings in myroutes_search.php

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#929]
There are several hardcoded strings in myroutes_search.php

**Comment by harrieklomp** [comment]
Do you mean that generated GPX file has hardcoded links and/or text? I can compare this with other GPX generators and add some changes.
There are many GPX generators in the code and all have different code. Perhaps there should be one example (GPX generator) for use with other GPX generators.

**Comment by harrieklomp** [comment]
In the past i have modified "search.gpx.inc.php" with correct links and added attributes for use in GSAK. This file is not perfect but can be used as example how other generators should be written. Perhaps a programmer can optimize this file and use this as example to other GPX generators.

**Comment by harrieklomp** [comment]
To show what i mean i can show a example.
In file search.gps.inc.php there are lines as:
            if ($r['votes'] > 3) {

                $score = cleanup_text(GeoCacheCommons::ScoreNameTranslation($r['score']));
                $thisextra .= "\n" . tr('search_gpxgc_05') . ": " . $score . "\n";
            }
            if ($r['topratings'] > 0) {
                $thisextra .= "" . tr('search_gpxgc_06') . ": " . $r['topratings'] . "\n";
            }
And in file myroutes_search.php is the same but in other words:
                    if ($r['votes'] > 3) {
                        $score = cleanup_text(GeoCacheCommons::ScoreNameTranslation($r['score']));
                        $thislogs .= "\nOcena skrzynki: " . $score . "\n";
                    }

                    if ($r['topratings'] > 0) {
                        $thislogs .= "Rekomendacje: " . $r['topratings'] . "\n";
                    }
In one file there is "thisextra" and in the other file is "thislogs" is used.

For a non programmer like me it is hard to understand this. I like to help with this but there should be some kind of system that i can work with.

**Comment by andrixnet** [comment]
At least lines: 1034-1037, 1047, 1059, 1095, 1358, 1362, maybe 1373,

**Comment by andrixnet** [comment]
@harrieklomp Please take a look at https://github.com/opencaching/opencaching-pl/pull/931 if I missed any

**Comment by kojoty** [comment]
@harrieklomp, I close this issue - please reopen if there is anything to do.
