### ISSUE TITLE
Table in mycaches.php (appearance)

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#937]
Table in My Caches section looks really better on on pl in English translation.

Oc pl in english version:
![selection_605](https://cloud.githubusercontent.com/assets/13780868/24447787/69a0dcea-1472-11e7-8114-8c5fd2f92d7b.png)

Oc pl in polish version:
![selection_606](https://cloud.githubusercontent.com/assets/13780868/24447875/af320c84-1472-11e7-8d32-88ed22f12fd2.png)

@DorotkaMakotka maybe you want check this?

**Comment by andrixnet** [comment]
I use Large fonts. On Firefox, all languages show tall rows.
On Opera, using english, it seems ok. Using romanian, rows are tall. And there seems to be an additional space between the images that does not appear in english (?) 
See files. 
![my_caches1](https://cloud.githubusercontent.com/assets/3382777/24525770/47ae2efc-15a4-11e7-8652-8c239eddcc6d.png)
![my_caches2](https://cloud.githubusercontent.com/assets/3382777/24525772/49e62b02-15a4-11e7-85e6-00133f588cab.png)

**Comment by mzylowski** [comment]
@andrixnet you are right.. it's so trivial..
