### ISSUE TITLE
images link in c:geo

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#942]
@wrygiel, @deg-pl 
I'm not sure if this is an issue in oc-code or in okapi or c:geo - I don't have a time to investigate now, but c:geo can't properly display links to images from cache after changes from around 2017-02-23

We have in DB links with protocol like:
https://opencaching.pl/images/uploads/2FF53E69-1E57-10A7-CFCE-3D47742C1652.jpg

and without proto like:
//opencaching.pl/images/uploads/64A8CAB4-89EE-E88B...

if okapi returns url without proto. image is not displayed (at least in c:geo).

**Comment by wrygiel** [comment]
How such URLs ended up in the database? Does OCPL allow them there?

Apps expect absolute URLs. Relative URLs (like the one starting with `//`) are valid only in context of another webpage, not an app.

**Comment by deg-pl** [comment]
There was a incorrect config of OCPL. Corrected in config and database.
