### ISSUE TITLE
No own caches in userprofile on OC.UK

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#952]
When i look at a userprofile on OC.UK the own caches are not shown. This is the case with newer made caches. Older users do have own caches in their profile but recent new caches are not shown.

For example look at user [Bearded Zombie](https://opencache.uk/viewprofile.php?userid=8127). He has made some caches but his profile shows no own caches.

**Comment by deg-pl** [comment]
Fixed
