### ISSUE TITLE
Localize per node opencaching.kml

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#955]
util/google-earth/opencaching.kml seems to be set specifically for Poland. 
In it's current form it is unusable for other nodes.

Plus, added feature : center at user's home location, if exists.

**Comment by harrieklomp** [comment]
How and where are these files used? I cannot find it on the site.

**Comment by andrixnet** [comment]
It's a KML similar to one geocaching.com offers, to have a live view in Google Earth with caches loaded live from the website. 

Download www.opencaching.nl/util/google-earth/opencaching.kml and open in it Google Earth, see what you get.

**Comment by harrieklomp** [comment]
I see what you mean.

**Comment by andrixnet** [comment]
FIXED in https://github.com/opencaching/opencaching-pl/pull/931
