### ISSUE TITLE
$nodeDetect strategy is wrong

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#958]
```
// sitename and slogan iternational handling
$nodeDetect = substr($absolute_server_URI, - 3, 2);

```

This is based on the website URL, and tries to obtain the site language. 
This will fail for any TLD suffix that is not a 2 letter language code

**Comment by deg-pl** [comment]
It is related with #1137

I think site language should be stored in config, not readed from URI

**Comment by kojoty** [comment]
It seems this is not an issue now - am I wrong? If yes - please reopen.
