### ISSUE TITLE
Script to sync language files (for translators)

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#960]
Language files are not 100% in sync (contain the same string definitions, in same order, in same place) for ease of maintenance. 

I am planning on writing a script to compare 2 language files and do the following:
- [ ] compare based only on key, not on value and show differences
- [ ] reorder the second to match the first (including value)
- [ ] add keys and empty values where they are missing in second file
- [ ] comment keys in second file if missing in first

Suggestions welcome.

**Comment by following5** [comment]
This has been fixed recently. The files are synchronized by Crowdin and the OCPL-crowdin-robot.
