### ISSUE TITLE
Let's remove some tiggers

### ISSUE THREAD

**Issue by deg-pl** [opencaching/opencaching-pl#967]
Why we use tiggers:
cacheDescBeforeInsert
```
BEGIN
      SET NEW.`date_created`=NOW();
    END
```

cacheLocationBeforeInsert
```
BEGIN
      SET NEW.`last_modified`=NOW();
    END
```

cacheLocationBeforeUpdate
```
BEGIN
      SET NEW.`last_modified`=NOW();
    END
```

if we can modify DB:
```
ALTER TABLE `cache_desc` CHANGE `date_created` `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `cache_location` CHANGE `last_modified` `last_modified` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
```

**Comment by andrixnet** [comment]
Each node must check database version if it supports this. 
I rememeber there were some problems in this area with a recent (this year) SQL change.

**Comment by andrixnet** [comment]
OCRO running  mysql  Ver 15.1 Distrib 5.5.54-MariaDB
OCNL running mysql  Ver 14.14 Distrib 5.7.16

**Comment by deg-pl** [comment]
I think all modern version of MySQL and MariaDB support it.

OCUK running MariaDB 10.1.22
OCPL - MySQL 5.7.17

**Comment by andrixnet** [comment]
I have verified on OCRO and it is supported. 
AFAIK the problem earlier was with a column DATETIME default CURRENT_TIMESTAMP, which was not supported. 
TIMESTAMP data type is ok. 

Green light from us. Thank you.

**Comment by andrixnet** [comment]
Administrative notice: under certain server configuration one can get this error running the SQL file as regular mysql user (not root or highly privileged user).
`You do not have the SUPER privilege and binary logging is enabled`

The offending query is `DROP TRIGGER`.

Running the SQL file with mysq `root` user solves it.

**Comment by deg-pl** [comment]
@andrixnet MariaDB from version 10.0.1 allow default CURRENT_TIMESTAMP for DATATIME type.

**Comment by andrixnet** [comment]
Thank you. Since it works for TIMESTAMP type, which essentially does much the same, I don't think it is critical. 
On the other hand, I will see about upgrading the distro version (I prefer to keep things very "stable")

**Comment by andrixnet** [comment]
For now it stays at MariaDB Distrib 5.5.54
