### ISSUE TITLE
Mapv3 filter enhancement

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#974]
from forum.oc.pl:

> areckis » środa, 12 kwietnia 2017, 07:39
> Mapa skrzynek v3. "Ukryj skrzynki". W tej chwili włączenie opcji "znalezione" oraz "jeszcze nie znalezione" ukrywa wszystkie skrzynki wraz z własnymi, które i tak mają własny przycisk ukrycia. Może by odizolować ukrywanie znalezionych/nieznalezionych od własnych (bez względu na to czy były znalezione, czy nie)?

**Comment by deg-pl** [comment]
I think now is OK - logical. We have few filters which are ADDED (operation AND) together. This proposition will complicate filters (filters become less logical)

**Comment by kojoty** [comment]
I agree with deg-pl - set "not-founds" contains "owns" in logic we used. 
I added new issue: **map of my own caches** #1303 and now close this one.
