### ISSUE TITLE
Add "trailhead" as extra waypoint

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#976]
There are a few additional wayoints in the code:
- Physical point
- Virtual point
- Final location
- Interesting place
- Parking area

Should it be interesting to add a new additional waypoint to it like:
- Trailhead

This Trailhead should also be selectable in a traditional cache. With this waypoint a user can show where a trail is to prevent damaging the nature.

**Comment by deg-pl** [comment]
Good idea!

**Comment by harrieklomp** [comment]
This extra waypoint should also be added to database.
@deg-pl . How should "Trailhead" be translated to Polish?
@andrixnet . How should "Trailhead" be translated to Romanian?

**Comment by mzylowski** [comment]
maybe "Początek ścieżki"

**Comment by harrieklomp** [comment]
:+1:

**Comment by harrieklomp** [comment]
When i look at different .png files of these extra waypoint there are some different. Some have a shadow at the bottom and others not.
![wp_question](https://cloud.githubusercontent.com/assets/1060518/25075051/5e2f0aba-230b-11e7-8023-ba9709451c1d.png)![wp_final](https://cloud.githubusercontent.com/assets/1060518/25075056/8dcc2186-230b-11e7-8fed-8744beea874d.png)
I would like some suggestions to redraw these icons.

**Comment by andrixnet** [comment]
@harrieklomp : if you draw a new icon, use the non-shadow as template. AFAIK those are currently in use. 

Second, except parking, IMO current waypoint icons do not have good visual meaning. 
If you plan to redraw all the icons, may I suggest the following
1. choose more meaningful symbols
2. choose an icon template (for all) to contain the symbols
3. if possible, use SVG drawings, then convert them to PNG (but upload both and conversion script).

Third, romanian for "trailhead" : there is no easy translation, let's try this: `Început de traseu` (I've used the same for GC equivalent in c:geo).

**Comment by harrieklomp** [comment]
We can start with adding the new waypoint to database. It does not show on the site this way.

INSERT INTO `waypoint_type` (`id`, `pl`, `en`, `nl`, `de`, `ro`, `icon`) VALUES (NULL, 'Początek ścieżki', 'Trailhead', 'Begin wandelpad', 'Anfang wanderpfad', 'Început de traseu', 'images/waypoints/wp_trailhead.png')

**Comment by deg-pl** [comment]
@harrieklomp make official sqlAlter please.

**Comment by harrieklomp** [comment]
Does anyone like this?
![wp_trailhead](https://cloud.githubusercontent.com/assets/1060518/25131705/0acd3dd2-2447-11e7-95f7-5d5dd4757940.png)

**Comment by andrixnet** [comment]
yes. (btw, same as OCDE waypoint_path)

**Comment by andrixnet** [comment]
See how I documented waypoints (almost complete) https://wiki.opencaching.eu/index.php/Waypoint_types

**Comment by harrieklomp** [comment]
Is correct. I redraw it and our is without the shadow on the bottom.

**Comment by andrixnet** [comment]
Well then, next week I'll see what other changes in the code may be necessary.

**Comment by harrieklomp** [comment]
What should be changed in the code i have figured out and it works on my local machine. First i need to find out how PR works without messing up Github ;-)

**Comment by following5** [comment]
> yes. (btw, same as OCDE waypoint_path)

This _originally is_ the OCDE waypoint type "path", I created it from two other icons. ;)

On of those original icons is CC-BY 3.0, (c) Yusuke Kamiyamane. You need to note that somewhere to avoid copyright violation. (see https://github.com/OpencachingDeutschland/oc-server3/blob/development/LICENSE.md, Icons section, No 4).

**Comment by following5** [comment]
http://www.softicons.com/toolbar-icons/fugue-16px-additional-icons-2-by-yusuke-kamiyamane/footprint-icon
