### ISSUE TITLE
Date of mail sending is wrong in database

### ISSUE THREAD

**Issue by mzylowski** [opencaching/opencaching-pl#983]
Date of mail sending in table 'email_user' is always 0000-00-00 00:00:00.
Now it's difficult to check mail history by dates.

Probably related with #918 so @kojoty can you check? ;]

**Comment by mzylowski** [comment]
Oh.. but we have also date_generated field. And value here is set fine.

**Comment by kojoty** [comment]
mail_sent is now unused and removed.
