### ISSUE TITLE
Cachepage shows differend corrected coordinates

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#987]
When on a cachepage the coordinate is corrected by a user the coordinates in the field where you can fill the coordinates are not correct. The corrected coordinates on top of the page are correct.
![selectie_038](https://cloud.githubusercontent.com/assets/1060518/25437633/4c45213e-2a97-11e7-98bb-74ef13bf74a0.jpg)
![selectie_039](https://cloud.githubusercontent.com/assets/1060518/25437639/51e65b94-2a97-11e7-9e9a-d0e982c5144e.jpg)

**Comment by kojoty** [comment]
I'll try to fix it soon - probably one more regression after my changes...

**Comment by harrieklomp** [comment]
:+1:

**Comment by kojoty** [comment]
@harrieklomp, can you confirm that now it is OK - if yes - please close the issue.

**Comment by harrieklomp** [comment]
Now it is correct. Thank you :+1:
