### ISSUE TITLE
improper size listed

### ISSUE THREAD

**Issue by kojoty** [opencaching/opencaching-pl#995]
from mail to RT:

> Paweł Brasia OC to rt, Opencaching.pl 
> Są planowane jakieś zmiany?
> Skąd to "nano"?
> 
![image](https://cloud.githubusercontent.com/assets/2961448/25519757/69ea82f2-2bf9-11e7-8a9c-387aed7fe8a8.png)
> (wyszukiwanie myroute)

**Comment by andrixnet** [comment]
Got it. It was part of the GPX rework (and myroutes.php generates GPX file). 
Probably I have added hooks for `nano` size in the template, but missed out the code part that enables it according to settings. (if exists). 

I can deal with it this saturday. (if @kojoty hasn't)

**Comment by kojoty** [comment]
it's up to you @andrixnet, this is not a big bug - so if you want to deal with it soon it's OK for me

**Comment by andrixnet** [comment]
Fixed by a quick comment. 

Code will have to be redesigned under project well_defined https://github.com/opencaching/opencaching-pl/projects/2 to display only the relevant checkboxes.
