### ISSUE TITLE
Opencaching Monitor

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#996]
Because sometimes a node can be offline it would be nice if users can check this. I know there is one far outdated site where there this is monitored. This is on https://filipspl.github.io/status/. For this you need to install some software on your server to show your site.

Now i have started a private project on https://stats.uptimerobot.com/z6BQRFOgD to monitor OC sites. It should be more interesting to change private to more common. Because my personal emailaddress (also login name) is used, i would like to change it to something with "monitor(at) opencaching.eu". I do not know if there is a mail server on oc.eu. If not, perhaps a gmail or other mail address can be made and used.

My idea is to share login between OC site admins so they can change/add the way each node receive alerts. Each node can receive alerts from their own OC site and if interested from other OC sites.

Any suggestion is welcome.

**Comment by andrixnet** [comment]
Is it the rain (here, tonight, in Bucharest) or the uptime robot itself is down (?) :-)

Anyway, great work and a very useful tool. 
Thank you.

**Suggestions:** 
- Each OC node should have at least one email set up for notifications. (I believe this is already taken care of)

- a system / a protocol / a mutual agreement should be reached with all OC node admins to share access credentials to this monitor for the sake of future updates.

**Comment by harrieklomp** [comment]
They are back again :-)

**Comment by harrieklomp** [comment]
Most nodes are listed now.
Now there are mail alerts for:
- OC.DE
- OC.RO
- OC.NL

Other sites can contact me for adding their mail address.

**Comment by andrixnet** [comment]
Nice updates

**Comment by andrixnet** [comment]
BTW, info about this tracker / monitor should be added to the overall site/project docs.

**Comment by harrieklomp** [comment]
It seems that others are not interested, so i close this.
