### ISSUE TITLE
Wrong signaling on adoption page

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#998]
The signaling boxes (red and green) after performing an operation on the adoption page are wrong.

- adoption procedure started - shows red. should be green.
- destination user not found - shows green. should be red. 
- acceptance message - shows red. should be green
- refusal message - shows red. THIS IS CORRECT.

**Comment by kojoty** [comment]
@andrixnet, Could you check if it is OK now and then close the issue please? Thanks!
